### ISSUE TITLE
Update permission of an existing resource

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#1015]
In recent v2 create resource API, I've seen that we can set the permission on the fly 👍 , but can we hope to update it later ?

This could be **particularly** useful for us in the following (common) use case in our app:
```
Bibliography -- hasNote --> Note
```
Any project member can create and add a Note to a Bibliography, then during the lifetime of the Note, the user can modify the access of this Note:
- visible/editable only by project members
- visible/editable only by users of a group list
- visible to any users

From permissions Knora point of view, it is just playing with the permission property of a Resource, isn't it ?

thanks.

**Comment by benjamingeer** [comment]
Currently when you create or update a value in v2, you can change its permissions. We could add a route **just** for changing permissions (without changing the rest of the value).

As for resource permissions, we could also make a separate route for changing them.

**Comment by gfoo** [comment]
you're right, I didn't think about the permissions of the `hasNote` property...
I've got two ways:
- from the Angular app (UI point of view), I make a gravsearch query, so changing the permission of `hasNote`  is sufficient to filter the retrieved Notes
- from Salsah (data management point of view), any user could get the Notes, so I need to change permissions of Note resource too.

If I only change the Note perms and not the hasNote perms, we get the hasNote properties but related to `ForbiddenResource`, is that right ?

So:
- "add a route just for changing permissions (without changing the rest of the value)." : don't know if I really need that right now ...
- "As for resource permissions, we could also make a separate route for changing them." : as I said, really useful for us

@mrivoal any remarks ?

**Comment by benjamingeer** [comment]
If you don’t have permission to see a resource, or you don’t have permission to see a value that matched your search criteria, you get `ForbiddenResource`, if I’m not mistaken. @tobiasschweizer is the expert on how this works.

**Comment by tobiasschweizer** [comment]
> If you don’t have permission to see a resource, or you don’t have permission to see a value that matched your search criteria, you get ForbiddenResource

Yes. We have to do it in Scala after we got the results from the triplestore. In it only in Scala that we know if the user has sufficient permissions.
