### ISSUE TITLE
Export of GUI Attributes from SALSAH to Knora

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#102]
In GUI attributes, restrictions to resource classes have to be removed when exporting them from SALSAH because the restrictions are now expressed via the `knora-base:objectClassConstraint`. Also, keeping the old ids makes no sense because the IRIs change.

Example from `incunabula-onto.ttl`:

```turtle
### ###########################################
### incunabula:hasRightSideband

:hasRightSideband rdf:type owl:ObjectProperty ;

                  rdfs:subPropertyOf knora-base:hasLinkTo ;

                  rdfs:label "Randleistentyp rechts"@de ;

                  rdfs:comment """Verweis auf einen Randleistentyp"""@de ;

                  knora-base:subjectClassConstraint :page ;

                  knora-base:objectClassConstraint :Sideband ;

                  salsah-gui:guiOrder "11"^^xsd:integer ;

                  salsah-gui:guiElement salsah-gui:Searchbox ;

                  salsah-gui:guiAttribute "restypeid=53" ,
                                          "numprops=1" ;

                  knora-base:hasDefaultViewPermission knora-base:KnownUser ;

                  knora-base:hasDefaultModifyPermission knora-base:ProjectMember ;

                  knora-base:hasDefaultDeletePermission knora-base:Owner .

```

`restypeid=53` has to be removed, i.d. the export script should not put it in the ttl-files.

Resources responder and ontology responder will be changed so that they add the resource class defined by `knora-base:objectClassConstraint` in the attributes. All the other attributes like `numprops` can remain.

**Comment by benjamingeer** [comment]
Fixed in the SALSAH export script:

http://git.iml.unibas.ch/salsah-suite/salsah/commit/5b88db424f5af6e6648ac6282878bfa02e7df53c
