### ISSUE TITLE
Create default permissions for BEOL resources

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#1022]
For BEOL, we should add default permissions, so that image files have view permissions for unknown users. 

Currently unknown users only have restricted view permissions.

**Comment by SepidehAlassi** [comment]
@tobiasschweizer yes, I have noticed the problem.

**Comment by tobiasschweizer** [comment]
As for the beolids, I would suggest that we show them to everyone (`UnknownUser`), but do not display them in the beol templates for the public. We could make template for editors where it is shown. 

Example: exchange the part of the route `/person/` with `/resource/` and then the GUI uses another template.

**Comment by SepidehAlassi** [comment]
@tobiasschweizer I believe it would be better to make template for editors and show BEOL-IDs there.
