### ISSUE TITLE
Digital vs. non-digital representation

### ISSUE THREAD

**Issue by musicEnfanthen** [dhlab-basel/Knora#1046]
When it comes to the (quite often-used) distinction of non-digital vs. digital representations In the documentation, it is not quite clear what is meant at all. Finally I found some explanation about Representations (without attribute) in

"/Knora Onotologies/The Knora Base Ontology/Resources/Representations" 

what can only be found by incident or full text search.

**Comment by benjamingeer** [comment]
In the Knora documentation, representation means "file", i.e. something that is stored outside the triplestore by Sipi. It's explained here:

https://docs.knora.org/paradox/02-knora-ontologies/knora-base.html#representations

All representations are digital, and I suppose the word "digital" is redundant here.

Please let us know how we could make this clearer.

**Comment by benjamingeer** [comment]
Actually, to be more precise, a representation is a collection of one or more files that represent the same thing.

**Comment by benjamingeer** [comment]
Thanks, I will revise the text following your suggestions.

> How is the FileValue generated? Automatically with upload of a file to SIPI? Has it to be provided manually by the user?

This depends on which version of the Knora API you use. In API v1, the procedure is described here:

https://docs.knora.org/paradox/03-apis/api-v1/adding-resources.html#adding-resources-with-a-digital-representation

In API v2, creation of file values is currently being implemented, and will be somewhat different.

> The distinction between digital vs. non-digital is made up here in the text

I'm sorry, I don't see what you mean. I can't find anything in the text about non-digital representations. The text describes "Adding Resources Without a Digital Representation" and "Adding Resources with a Digital Representation". Here were are talking about two different kinds of resources, not two different kinds of representations.

**Comment by benjamingeer** [comment]
Maybe we could change it to "Adding resources with/without an attached file".

**Comment by musicEnfanthen** [comment]
Thanks.

> I'm sorry, I don't see what you mean. I can't find anything in the text about non-digital representations. The text describes "Adding Resources Without a Digital Representation" and "Adding Resources with a Digital Representation". Here were are talking about two different kinds of resources, not two different kinds of representations.

I understand now where my misunderstanding comes from. Just read it as "Adding Resources without a **Digital** Representation" instead of "Adding Resources **Without** a digital Representation". Maybe renaming it could indeed solve this point of confusion, e.g. "Adding resources with/without attached files (digital representations)" including a link from the section to the representations section.
