### ISSUE TITLE
Explain how to adjust application.conf when adding an ontology in the Knora documentation

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#105]
Explain how `application.conf` has to be adjusted when adding a new project ontology:

```
 project-named-graphs =
        [
            {
                project = "http://data.knora.org/projects/knora-base"
                ontology = "http://www.knora.org/ontology/knora-base"
                data = "knora-base"
                visibleInGUI = true // TODO: this has to be included in the future
                name = "Knora-Base"
            }
]
```

**Comment by subotic** [comment]
I'm actually redesigning this at the moment as part of #54. This information will be part of the project and stored in the admin named graph, e.g., ``http://www.knora.org/data/admin``:

```
<http://data.knora.org/projects/[UUID]>
        rdf:type knora-base:knoraProject ;
        knora-base:projectBasepath "/imldata/SALSAH-TEST-01/images" ;
        knora-base:projectShortname "images" ;
        knora-base:projectLongname "Images Collection Demo" ;
        knora-base:projectOntolgyGraph "http://www.knora.org/ontology/images" ;
        knora-base:projectDataGraph "http://www.knora.org/data/images" ;
        knora-base:isActiveProject "true"^^xsd:boolean ;
        knora-base:hasSelfAssignmentEnabled "false"^^xsd:boolean ;
        knora-base:hasProjectAdmin <User-IRI> .
```

The problem with ``application.conf`` is that it is read-only. For any changes to be visible, we would be required to reboot the knora server (the actor system).

**Comment by tobiasschweizer** [comment]
When you add a project to `application.conf`, but do not add its data to the triplestore, this can lead to problems.

The available named graphs are queried from `application.conf` (this is a just a static entry), but when you query all the resource types of a named graph (vocabulary) whose data have not been loaded, nothing is found.

Whenever a new project is added to `application.conf`, we have to make sure that its data is added to the loading script in `webapi/scripts` as well as in the tests.

**Comment by subotic** [comment]
This is nor relevant anymore as projects are not part of `application.conf` anymore.
