### ISSUE TITLE
Do we need both fileValueAsUrl and stillImageFileValueHasIIIFBaseUrl?

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#1058]
Seems redundant.

**Comment by tobiasschweizer** [comment]
My idea was that the GUI could create IIIF Urls for different quality levels: 
https://github.com/dhlab-basel/Knora-ui/blob/6b749cf94b9618e8c5afd8a4f571e77f42a337cc/projects/knora/core/src/lib/declarations/api/v2/properties/read-property-item.ts#L284

Another use case would be rotation.

**Comment by benjamingeer** [comment]
OK but in that case, why do we need `fileValueAsUrl `? Wouldn't `stillImageFileValueHasIIIFBaseUrl` be enough?

**Comment by benjamingeer** [comment]
I guess it's redundant for image values, but not for other kinds of files (that don't have IIIF URLs)?

**Comment by tobiasschweizer** [comment]
Probably in simple use cases you just want to display an image, without knowing the IIIF syntax. And in more complex use cases you don‘t want to parse the URL first.

**Comment by benjamingeer** [comment]
OK, got it, thanks.
