### ISSUE TITLE
Get XML Schemas in Bulk Import API v1 

### ISSUE THREAD

**Issue by ezbinden** [dhlab-basel/Knora#1061]
Hi
I am trying the bulk import v1 as documented in  https://docs.knora.org/paradox/03-apis/api-v1/adding-resources. I try to get the XML Schemas and interpret the 

HTTP GET to http://host/v1/resources/xmlimportschemas/ontologyIRI as follows:

http://localhost:3333/v1/resources/xmlimportschemas/0802/biblio

With this I get a 404 Error. What is wrong with the link? Thanks for your help.

**Comment by benjamingeer** [comment]
Your ontology IRI needs to be a complete IRI and needs to be URL-encoded.

In this case, your ontology IRI is http://www.knora.org/ontology/0802/biblio

You can URL-encode it with a tool like this: https://meyerweb.com/eric/tools/dencoder/

The URL-encoded ontology IRI is then:

http%3A%2F%2Fwww.knora.org%2Fontology%2F0802%2Fbiblio

Assuming that Knora is running on the default port of 3333, your complete Knora API request URL is:

http://localhost:3333/v1/resources/xmlimportschemas/http%3A%2F%2Fwww.knora.org%2Fontology%2F0802%2Fbiblio

I guess we need to make it clearer in the documentation that IRIs in URLs need to be URL-encoded.

**Comment by gfoo** [comment]
[an another tool, this one completely hackable :)](https://beta.observablehq.com/@gfoo/de-en-codeuri-component?input=http://www.knora.org/ontology/0802/biblio)
