### ISSUE TITLE
Search for Subclasses of a given Resource Class in Extended Search

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#108]
Enable to find a subclasses of a given resource class in extended search.

`searchExtended.scala.txt`

```
@restypeIriOption match {
        case Some(restypeIri) => {

            # filter by restypeIri
            ?resource a <@restypeIri> .
        }

        case None => {}
    }
```

This should be

```
@restypeIriOption match {
        case Some(restypeIri) => {

            # filter by restypeIri
            ?resource a ?resClass .
           <@restypeIri> rdfs:subClassOf* ?resClass .
        }

        case None => {}
    }

```

Write a test for this.

When searching for the class `knora-base:Resource`, all resources should be found.

DO the equivalent thing for properties (e.g. dc:title).

**Comment by benjamingeer** [comment]
We also need to be able to search for subproperties.

**Comment by tobiasschweizer** [comment]
https://github.com/dhlab-basel/Knora/commit/5af0a8caaf0951c0ce8a1b45b0793865c03f956d

**Comment by tobiasschweizer** [comment]
https://github.com/dhlab-basel/Knora/issues/242

**Comment by tobiasschweizer** [comment]
Also search for subclasses in `getResourceSearchResult.scala.txt`:

```
@if(resourceTypeIri.nonEmpty) {
        FILTER(?resourceClass = <@resourceTypeIri>)
    }
```

I tried the same thing I did for extended search:

```
@restypeIriOption match {
        case Some(restypeIri) => {

            # filter by restypeIri
            ?resClass rdfs:subClassOf* <@restypeIri> .
            ?resource a ?resClass .
        }

        case None => {}
    }
```
But it was very slow.

**Comment by tobiasschweizer** [comment]
https://github.com/dhlab-basel/Knora/commit/fbea57930fdee05f01f9831ebd27b262267ee159

**Comment by tobiasschweizer** [comment]
We implemented his already for v1 for resource classes. V2 simple Knora-api will provide mechanisms to use properties like dcterms:title etc.
