### ISSUE TITLE
Bulk import error after a webapi docker restart

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#1081]
(Using docker compose dev)

When I update an ontology, I relaunch the bootstrap script `./graphdb-se-docker-init-knora-test.sh` and then restart the webapi container `docker-compose restart  webapi`.

Then I have this error when I launch the first bulk import:
`{"status":11,"error":"org.knora.webapi.BadRequestException: An error occurred when requesting mapping http://rdfh.ch/standoff/mappings/StandardMapping: Failed to connect to triplestore"}`

then everything works fine for the next bulk imports.

**Comment by subotic** [comment]
Thanks for the report. Could you maybe try the same thing with the current `develop`? Now the Knora stack is started from SBT with `$ sbt dockerComposeUp`. Also, SBT needs to be run from the repository's root directory.

**Comment by subotic** [comment]
I think there is a problem with accessing GraphDB, where the first call to a freshly reloaded repository takes too long and thus `webapi` times out.

**Comment by gfoo** [comment]
Yes, I have the same error. You probably right about the graphdb synchro, but it is also related, as suggested by the error, to data having a xml richtext property related to a `StandardMapping`.
I cannot reproduce the error with a simple bulk import without richtext, but I didn't dig a lot, just an assumption.

n.b. : This time, I restarted all the stack using `sbt dockerComposeRestart` (didn't find the way to just restart a container)

**Comment by gfoo** [comment]
I think the error is mainly related to the **first** (as I mentioned) bulk import **but** with a data linked to `StandardMapping`, because I can reproduce the error after having successfully launched simple bulk import before.
