### ISSUE TITLE
Update internal modification date of a resource

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#1088]
If it is possible to change the modification date of a resource, I'm interested to have an API entry point to manage a common use case in our app due to what we call a _composite resource_, for example :
```
Person -- hasNote -- Note
```
Each time a User modify a Note I would like to update the modification date of the related `Person`(s). I have of course many other ways to implement this function, the fatest way being obviously to manage myself a lastModification date property in `Person`.

Thanks.

**Comment by benjamingeer** [comment]
I'll try to do this soon.

**Comment by benjamingeer** [comment]
Do you need to set the last modification date to a specific timestamp, or would it be OK for you just to tell Knora to set it to the current time?

**Comment by subotic** [comment]
If I may, I would suggest either both or if only one, then to a specified date.

**Comment by benjamingeer** [comment]
> If I may, I would suggest either both or if only one, then to a specified date.

OK, will do.

**Comment by benjamingeer** [comment]
Both, I mean. :)

**Comment by subotic** [comment]
If he needs to update more than one ressource to the same timestamp, then he would probably need to supply one himself.

**Comment by subotic** [comment]
great 😀

**Comment by gfoo** [comment]
I need to set the date myself, in my example, set the `Note`'s  modif date to `Person`.
thanks
