### ISSUE TITLE
Set internal creation/modification date of a resource on bulk import

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#1089]
Few months ago (I cannot find the issue) we have talked about to set the creation and last modification date of resource during the bulk import, is that possible ? 

Use case: keep useful dates of data migrated from a database into Knora

(maybe related to #1088)

**Comment by benjamingeer** [comment]
I'll try to do all this at the same time, along with changing the resource's label.

**Comment by gfoo** [comment]
👍  and if I may, add this one  #1015
Super thx !

**Comment by benjamingeer** [comment]
Yes, definitely, thanks for reminding me. Hope to do all this in January.
