### ISSUE TITLE
webapi dockerfile error

### ISSUE THREAD

**Issue by janCstoffregen** [dhlab-basel/Knora#1090]
Dear DHLab,
when I run 

```
docker build -t knora .
```

in the webapi - folder, I get the message

```
Getting Scala 2.12.6 (for sbt)...
:: retrieving :: org.scala-sbt#boot-scala
	confs: [default]
	5 artifacts copied, 0 already retrieved (19632kB/74ms)
[warn] No sbt.version set in project/build.properties, base directory: /src
[info] Set current project to src (in build file:/src/)
[error] Not a valid command: stage (similar: last-grep, set, last)
[error] Not a valid project ID: stage
[error] Expected ':'
[error] Not a valid key: stage (similar: state, target, tags)
[error] stage
[error]      ^
The command '/bin/sh -c sbt stage' returned a non-zero code: 1
```

on step 

```
Step 7/15 : RUN sbt stage
```

It starts fine and downloads lots of repositories, but then it fails.

Thank you for your response and best regards,
Jan

**Comment by subotic** [comment]
Which version of Knora? The build structure changed since `v3.0.0`. There is now one central `KnoraBuild.sbt` for building the different subprojects, i.e. `docs`, `salsah1` and `webapi`. You need to run SBT from the repositories root directory.

**Comment by subotic** [comment]
Also, there are no `Dockerfiles` as such anymore. The building of Docker images is now done from SBT:

```
$ sbt webapi/docker:stage
$ sbt webapi/docker:publishLocal
```

**Comment by subotic** [comment]
Just curious, what is your use case that makes it necessary to build your own images, instead of using the published ones?

**Comment by janCstoffregen** [comment]
ok, that explains it, sorry, I didn't know...

**Comment by janCstoffregen** [comment]
is there a public knora image?

**Comment by janCstoffregen** [comment]
on dockerhub?

**Comment by janCstoffregen** [comment]
I just thought there is the webapi base..

**Comment by janCstoffregen** [comment]
it used to be the case that:
 - Knora, Salsah and Sipi only worked in certain versions with one another. 
 - Our ontologies only worked with a certain version of Knora

So we tried everything locally and then built docker images for the versions of Salsah, Knora, Sipi and our ontologies so that the whole stack worked well together.

But I saw the webapi image on dockerhub now.. I just built it myself to see the file structure and changes since I mount some conf files outside of the docker image to adjust it to our docker compose..

**Comment by janCstoffregen** [comment]
ok, I'm able to use the dockerhub image

sometimes we built an own image after a bugfix to include it in our stack.
