### ISSUE TITLE
Double declaration of variables in the application.conf

### ISSUE THREAD

**Issue by janCstoffregen** [dhlab-basel/Knora#1093]
Dear DHLab - Team,

in the new application.conf, variables are declared twice:

New:
```
dbtype = "graphdb-se"
dbtype = ${?KNORA_WEBAPI_TRIPLESTORE_DBTYPE}
```

Old:
```
dbtype = "graphdb-se"
```

Especially when I choose graphdb-free, should I leave the other declaration? Does the sequence play a role?

**Comment by janCstoffregen** [comment]
I did see this: https://docs.knora.org/paradox/04-deployment/configuration.html

but don't know what to do when switching the variables..

**Comment by subotic** [comment]
You can either change `dbtype = "graphdb-se"` to something like `dbtype = "graphdb-free"`, or you can start the `webapi` docker container with the system variable `KNORA_WEBAPI_TRIPLESTORE_DBTYPE` set to `graphdb-free`.

Here is an example: https://github.com/dhlab-basel/Knora/blob/bff34ab09edc0cb6392dd3b4c6344f0120f2d79a/docker-compose.yml#L51-L53

**Comment by janCstoffregen** [comment]
That's a very nice enhancement, thank you! It works now! Thank you very much!
