### ISSUE TITLE
Change knora-admin.ttl to http://www.knora.org/ontology/knora-admin

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#1106]
- Change `knora-admin.ttl` to `http://www.knora.org/ontology/knora-admin`
- Add `KnoraAdmin` object to `OntologyConstants` and move all relevant properties
- Make necessary changes to source-code so that OntologyConstants work again.
- Make necessary changes to test data
- Change groups inside permission strings from `knora-base:GroupName` to `knora-admin:GroupName` in all test data.

Related to #777

**Comment by benjamingeer** [comment]
I'm working on this now, because I think it actually has to be done for #1259.
