### ISSUE TITLE
Selenium Browser Test

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#111]
Could the browser GUI-tests be moved to a different test root so they would not be run automatically with the other tests?

The GUI tests assume that the salsah app and Knora are both running which is normally is not the case when I run the tests.

**Comment by benjamingeer** [comment]
What do you mean by a different test root? A different directory? I don't think that would stop them from being run automatically. Ivan knows more about this than I do.

**Comment by tobiasschweizer** [comment]
I guess we need names

@subotic Do you know how ti defined names for tests?

**Comment by subotic** [comment]
Where are the Selenium tests now?

**Comment by subotic** [comment]
I can enable 'integration tests' in SBT. This will provide us with another directory ``it`` in which we can have tests. The tests inside this directory can then be started by calling  ``it:testOnly``.

Also, all Selenium tests could be moved to the ``salsah`` directory (if they are now in ``webapi``). Also there (in ``salsah``) I would suggest to have ``test`` and ``it``.

**Comment by benjamingeer** [comment]
There's just one Selenium test so far, it's in `test/scala/org/knora/webapi/e2e/browser`. Moving it to `salsah` sounds like a good idea.

**Comment by tobiasschweizer** [comment]
done https://github.com/dhlab-basel/Knora/commit/df8a458f14527da5362a42df59349f60cd50c4fc

**Comment by subotic** [comment]
Please reference the pull request containing the commit and not the commit itself.
