### ISSUE TITLE
Improve bulk import and separate from API v1

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#1110]
Wish list:

- Files get uploaded to Sipi before sending the bulk import data to Knora #963
- Limit the size of bulk import #1177
- Import is done in batch mode (submit, then get a notification later when it's done)
- If Knora is restarted during processing, it can resume from where it left off
- https://github.com/dhlab-basel/Knora/issues/1110#issuecomment-458995411

Needs #1210.

**Comment by SepidehAlassi** [comment]
I like the last two items in the list 👍

**Comment by benjamingeer** [comment]
> We should try.

So here you have two problems:

1. Find an algorithm that can analyse the dependencies between resources in the import, and try to separate the date into subgraphs that could be imported separately.
2. Make sure that in each subgraph, all cardinalities for required links are respected.

For (2), you might want to change the ontologies to make the required links optional, then import the data, then change the ontologies back. Of course, if you make the links optional, you lose Knora's ability to check the cardinalities.

> In the current form, It can be to easily used (on purpose or by mistake) to bring the whole server down.

Probably not on purpose, because you have to be a project administrator or a system administrator to do a bulk import.

**Comment by subotic** [comment]
Then we should maybe limit the number of resources per bulk-import step. The user should do the work and make smaller bundles. The XML is probably anyway generated, so they could create as many as needed and upload them at the same time. The bulk-importer can then process one after the other.

Currently, the bulk-import of Lukas is taking over 15 minutes. It uses the resources as follows. For a few seconds, the `webapi` CPU usage spiked to 100%. After that GraphDB spikes to 100% for the whole duration.

This is not something that I feel comfortable with allowing on our production deployment. But then we need to think about the whole workflow. If they can only import their data locally, how is the data going to be moved to the production server?

**Comment by benjamingeer** [comment]
> Then we should maybe limit the number of resources per bulk-import step. The user should do the work and make smaller bundles.

OK.

> For a few seconds, the `webapi` CPU usage spiked to 100%. After that GraphDB spikes to 100% for the whole duration.

We can make the bulk import code in `webapi` run more slowly, so it uses less CPU (maybe just with `Thread.sleep`), but I don't know if there's anything we can do about GraphDB.

> If they can only import their data locally, how is the data going to be moved to the production server?

Would it help to have two GraphDB servers, one for updates and one for read queries?

**Comment by subotic** [comment]
> Would it help to have two GraphDB servers, one for updates and one for read queries?

Of course. But then we need to deal with synchronization of the triplestores, which brings a whole other set of problems, like eventual consistency. I wanted to wait with separating the read and write side until we had event logging. But also then. If a bulk-import takes over all the resources on the write side for 15 minutes, then we will still run into issues if other users want to write at the same time.

I think that if we limit the number of resources per bulk-import step, that it should be fine. It is probably by far the simplest to implement.

**Comment by subotic** [comment]
As far as I can tell, only GraphDB is the bottleneck. `webapi` is more than capable to cope with the load.

**Comment by subotic** [comment]
I think we talked about only having one bulk-import route. e.g., /bulk-import because there is no need to support different versions.

**Comment by subotic** [comment]
another one: #963

**Comment by subotic** [comment]
another one: #964

**Comment by gfoo** [comment]
The main features of the `bulk import` for me are:
1. easy resource's links by internal xml ids
2. single transaction, no cleanup on fails

So if we cannot import huge amount of data by this way... well probably it is no more so interesting:( Will probably prefer to use directly API to deal with IRI just created to possibly link to next resource.

**Comment by loicjaouen** [comment]
for now, in Lausanne, we have two servers, one for prod, the second is pre-prod and we use it for the imports. Then we move the graph from one server to the other.

**Comment by gfoo** [comment]
> for now, in Lausanne, we have two servers, one for prod, the second is pre-prod and we use it for the imports. Then we move the graph from one server to the other.

yes, great for point 2.

**Comment by subotic** [comment]
FEATURE: allow to use internal IDs inside the different XML parts. The server will then exchange those internal IDs for the IRIs after a resource is created.

BONUS: now that the `bulkimporter` has a list of all created resources, it should be possible to undo the import after an error. This could also allow using the `bulkimporter` for projects with existing data, as the clean-up after an error could be done by the server.

**Comment by SepidehAlassi** [comment]
@subotic the feature you mention is already possible with bulk import. The user can link the XML elements by the internal ids inside the different XML parts. This can be easily done by the attribute link_type=ref

**Comment by loicjaouen** [comment]
i am lost with the definition of *xml parts*?

I understand it as:
- I have a big import to do, with one big xml file
- but the bulk import limits the number of entry per import
- so I break up my big xml file in smaller different *xml parts*

And I see questions of two kinds:
- data integrity:
  - in my second import, I do I link to data from my first import?
  - if one of the imports fail, how do I clean-up knora? how do I clean-up sipi?
- organization: how do I schedule the imports

It has been proposed earlier in this thread that at the end of an import, a mail could be sent, maybe this mail could attach a dictionary mapping of the IDs used in the xml at import and the IRI created for them by knora. These dictionary could be added as argument to subsequent bulk import?

**Comment by loicjaouen** [comment]
thanks @subotic, I was a bit lost and that clears my understanding

**Comment by gfoo** [comment]
Why don't you split  into xml parts yourself instead of asking us? What is the missing information for you?

**Comment by benjamingeer** [comment]
@gfoo See https://github.com/dhlab-basel/Knora/issues/1110#issuecomment-455550488

**Comment by gfoo** [comment]
oups, read too quickly, so we are the algorithm :)

**Comment by benjamingeer** [comment]
> so we are the algorithm :)

Exactly. :)

**Comment by lrosenth** [comment]
Let me add my 2 cents of opinion:
It is really bad that we cannot do one transaction for all. But from a technical point of view it is obvious that one gigantic transaction will overwhelm the GraphDB server.
So I think the only "solution" is to split up the import into smaller, self-consistent parts. Unfortunately this brings some burden to the programmer of the bulk import. He has to isolate self-consistent parts of the data. It is really helpful if resources of **previous** parts can be referenced by an "internal" id and not the real IRI.

I'm not happy with it but given the technological constraints its probably the only solution...

Just one method came to mind – but this would be a" real bad hack": we could make a dedicated GraphDB which is only used for import – then export as turtle to the live system. But this would require the duplication of the whole infrastructure (may be without SIPI data) – and we would have to ensure that the 2 GraphDB's are always in sync before an import. 

Therefore I personally prefer the first method even if it imposes considerable burden on the bulk-import-scripter...

Comments welcome!!!

**Comment by sacha-alex** [comment]
Just a comment from the outside:

As a customer I would find it irritating to be 'the algorithm' when a machine would handle this work better and faster than I do. Of course, I should know my data, but in general it is easier and faster for all involved parties when the machine will do the work.
From a technical point of view, I would suggest for example to apply a topological sorting on the
(data-)graph(s). This would divide the data into its separate independent parts (graphs). These smaller parts than can be handled independently within the import (e.g. as suggested, as part of an overall batch job).
Of course, this wouldn't reduce the overall time/resources, but it would allow the system to control the import, and therefore the usage of the resources, more precisely.

Concerning the import process itself, I would be fine with a batch mode, where I can upload my data and get a notification when it is done. And of course the import itself should follow the ACID properties (Atomicity, Consistency, Isolation, Durability).

**Comment by benjamingeer** [comment]
> As a customer I would find it irritating to be 'the algorithm' when a machine would handle this work better and faster than I do.

The question is how much time we would need to implement this, and whether it's worth spending the time on it in the short term.

> From a technical point of view, I would suggest for example to apply a topological sorting on the
> (data-)graph(s). This would divide the data into its separate independent parts (graphs).

What if there are no parts that are completely independent? I think that in a lot of large data sets, it would be common for almost every resource to be (directly or indirectly) connected to every other. But there might still be parts that are *relatively* independent. The algorithm would have to measure the relative independence of different possible subgraphs.

> And of course the import itself should follow the ACID properties (Atomicity, Consistency, Isolation, Durability).

There is no way in SPARQL to have a transaction that lasts for more than one SPARQL request. So if we split a bulk import into parts, there will be a transaction for each part.

**Comment by SepidehAlassi** [comment]
@benjamingeer I believe if we use xi:include implementing of this will be easier. The user has to break the xmls in small pieces like "a.xml", "b.xml" and then merge them in the "main.xml" file using xi:include. Then main.xml will be like:
`
<knoraXmlImport:resources ...">`
`<xi:include xmlns:xi="http://www.w3.org/2001/XInclude"  href="a.xml"/>`
`<xi:include xmlns:xi="http://www.w3.org/2001/XInclude"  href="b.xml"/>`
`</knoraXmlImport:resources>`

Then the main.xml has to be posted to bulk-xml import route. There the sub xml files will be imported in the order mentioned in "main.xml" . During the import of "a.xml" a hashmap of the ids of its elements are created which helps with resolving the ids referred in "b.xml", and so on. 
This will not need much effort with implementation as we will not be changing anything in bulk import, we need to just change the route. Importing the sub-xmls one by one should not overload the GraphDB, and user can refer to elements with id instead of IRI. What do you think? 
But with this, we need to also change the xsd generations as well.

**Comment by benjamingeer** [comment]
> I believe if we use xi:include implementing of this will be easier.

Yes, that sounds good to me.

**Comment by benjamingeer** [comment]
After some discussion with @lrosenth and @subotic, we have what we think is a better approach:

The goal here is to minimise the load on the triplestore. The ideal would therefore be to just create one resource at a time, with a pause between each resource. The only problem is dependencies (required links) between resources. We can solve this problem by creating dummy resources to serve as the targets of required links. In the case where resource class A has a required link to B which has a required link to C, we will have to create dummy instances of B and C. This way, it does not matter in what order the real resources are created. At the end of the import, we will replace all the links to dummy resources with links to real resources, and delete the dummy resources.

We think that the client can still submit an XML file containing the whole import, as with the current approach. But this file will be broken up into tasks (one task per resource) and executed as a batch job (see #1210).

**Comment by benjamingeer** [comment]
This is being implemented in [knora-py](https://github.com/dhlab-basel/knora-py) instead of in Knora.
