### ISSUE TITLE
org.knora.webapi.InconsistentTriplestoreDataException (properties and subclasses)

### ISSUE THREAD

**Issue by sacha-alex** [dhlab-basel/Knora#1117]
Dear DHLab-Team,

 I'm facing a problem with the latest release, concerning our ontologies and the inheritance.
After the update of our admin-data.ttl file, the import itself runs very smoothly, so there are
no problems there. But when I restart Knora afterwards, I am getting the message:

> ================================================================
> Knora API Server started at http://0.0.0.0:3333
> ----------------------------------------------------------------
> DB-Name: knora-test
> DB-Type: graphdb-free
> DB Server: graphdb, DB Port: 7200
> ================================================================
> 2018-12-07T10:40:56.425782124Z 
> [2018-12-07 10:41:32,960] INFO  - KnoraService(akka://webapi) - KnoraService - Shutting down.
> [YourKit Java Profiler 2018.04-b87] Log file: /root/.yjp/log/Main-1.log
> [2018-12-07 10:41:41,608] INFO  - KnoraService(akka://webapi) - KnoraService - applicationStateActorReady
> [2018-12-07 10:41:45,289] INFO  - KnoraService(akka://webapi) - KnoraService - Startup State: StartingUp
> [2018-12-07 10:41:46,058] INFO  - KnoraService(akka://webapi) - KnoraService - Startup State: RepositoryReady
> [2018-12-07 10:41:49,529] INFO  - KnoraService(akka://webapi) - KnoraService - Startup State: CachesReady
> [2018-12-07 10:41:56,238] ERROR - Dispatcher - Class http://www.knora.org/ontology/0059/text#DiaryExpression has a cardinality on property http://www.knora.org/ontology/0056/publishing#hasPublication and on its subproperty http://www.knora.org/ontology/0056/publishing#hasUnauthorizedPublication
> org.knora.webapi.InconsistentTriplestoreDataException
[document_and_text_ontos.zip](https://github.com/dhlab-basel/Knora/files/2657440/document_and_text_ontos.zip)
: Class http://www.knora.org/ontology/0059/text#DiaryExpression has a cardinality on property http://www.knora.org/ontology/0056/publishing#hasPublication and on its subproperty http://www.knora.org/ontology/0056/publishing#hasUnauthorizedPublication
> at org.knora.webapi.responders.v2.OntologyResponderV2.$anonfun$makeReadClassInfos$1(OntologyResponderV2.scala:724)
> at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
> at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:231)
> at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:462)
> at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:462)
> at scala.collection.TraversableLike.map(TraversableLike.scala:234)
> at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
> at scala.collection.AbstractTraversable.map(Traversable.scala:104)
> ....

which I don't understand. 

The structur of the classes and there inheritance/dependencies are more or less like this:

                text:DiaryExpression
                          ^
                          |
                text:IndividualExpression
                  ^                  ^
                  |                  |
            text:Expression     document:IndividualExpression
            ^                     ^                                      ^
            |                      |                                      |
document:Expression  text:Text         document:Expression
            ^                               ^                            ^
            |                                |                            |
document:Document        ...                           ...
            ^
            |
           ...

document:Expression is the only place that is using the properties publish:hasPublication and its derived property publish:hasUnauthorizedPublication.
Both times with a minCardinality of "0" (which is the default minCardinalty for all our Properties)

So in my understanding the message means that the class text#DiaryExpression has a cardinality on both properties, because it is a sub-sub-subclass of document:Expression,
but both times the minCardinality is defined as 0 and never changed to another value.
It would be nice, if you can take a look at the problem and give me hint, what i am missing.

Thank you very, very much in advance,

Best,
Sascha

**Comment by benjamingeer** [comment]
> So in my understanding the message means that the class text#DiaryExpression has a cardinality on both properties, because it is a sub-sub-subclass of document:Expression,
but both times the minCardinality is defined as 0 and never changed to another value.

The resolution of your issue #978 was PR #982: Don't allow class with cardinalities on P and on a subproperty of P.

It doesn't matter which cardinality you choose; you can't have a class with cardinalities on P and on a subproperty of P.

**Comment by benjamingeer** [comment]
This is documented here:

https://docs.knora.org/paradox/02-knora-ontologies/knora-base.html#restrictions-on-classes

**Comment by sacha-alex** [comment]
Thanks you very much for your fast response. This info helps me a lot!
