### ISSUE TITLE
Make responders not be actors

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#1139]
Since there's just one instance of each responder, and they do all their work in futures, they don't need to be actors.

A theoretically easy way to do this:

* Make `Responder` not extend `Actor`.
* Make `ResponderManager` a singleton, not an actor, containing one instance of each responder.
* Give `ResponderManager` a `?` method that takes a Knora request message as argument, and has the same return type as Akka's `?`.
* Have that `?` method call `receive` directly on the relevant responder instance and return the result.
* Write an alternative to `future2Message` that takes care of error-handling in this new context, and use it in responders instead of the existing `future2Message`.

**Comment by subotic** [comment]
Sounds good to me. Would you like to give it a try, or should I?
