### ISSUE TITLE
Update an existing link

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#114]
I am trying to update the partOf prop of a page with this test in `ValuesResponderSpecV1`:

```scala
            // A test UserDataV1.
            val userData = UserDataV1(
                email = Some("test@test.ch"),
                lastname = Some("Test"),
                firstname = Some("User"),
                username = Some("testuser"),
                token = None,
                user_id = Some("http://data.knora.org/users/91e19f1e01"),
                lang = "de"
            )

            // A test UserProfileV1.
            val userProfile = UserProfileV1(
                projects = Vector("http://data.knora.org/projects/77275339"),
                groups = Nil,
                userData = userData
            )


            val linkTargetIri = "http://data.knora.org/e41ab5695c"
            val linkValueIri = "http://data.knora.org/8a0b1e75/values/3a7b5130-22c2-4400-a794-062b7a3e3436"

            val changeValueRequest = ChangeValueRequestV1(
                value = LinkUpdateV1(
                    targetResourceIri = linkTargetIri
                ),
                userProfile = userProfile,
                valueIri = linkValueIri,
                apiRequestID = UUID.randomUUID
            )

            actorUnderTest ! changeValueRequest

            expectMsgPF(timeout) {
                case ChangeValueResponseV1(linkValue: LinkV1, _, newLinkValueIri: IRI, _, _) =>
                    linkValue.targetResourceIri should ===(linkTargetIri)
            }

```

However, I get this error msg:

>The update to link value http://data.knora.org/8a0b1e75/values/1bsbipU4S_-dS1ddb9XOUQ with source IRI http://data.knora.org/8a0b1e75, link property http://www.knora.org/ontology/incunabula#partOf, and target http://data.knora.org/e41ab5695c was not performed. Please report this as a possible bug.
org.knora.webapi.UpdateNotPerformedException: The update to link value http://data.knora.org/8a0b1e75/values/1bsbipU4S_-dS1ddb9XOUQ with source IRI http://data.knora.org/8a0b1e75, link property http://www.knora.org/ontology/incunabula#partOf, and target http://data.knora.org/e41ab5695c was not performed. Please report this as a possible bug.

The value Iri in this case would be the Iri of the reification node, right?

**Comment by tobiasschweizer** [comment]
problem can be reproduced with this script:

Please note that you have to add link_value to the messages. We forgot that.



```python
import requests, json

params = {
	'project_id': 'http://data.knora.org/projects/77275339',
	'link_value': 'http://data.knora.org/5e77e98d2603'
}

r = requests.put("http://localhost:3333/v1/values/http%3A%2F%2Fdata.knora.org%2Ffcac0fe61801%2Fvalues%2F292db688-d37d-4c54-b920-e4248f3e357b", 
data=json.dumps(params), 
auth=("root", "test"),
headers={'content-type': 'application/json; charset=utf8'}
)

print(r.text)
```

response:

>{"status":27,"error":"org.knora.webapi.UpdateNotPerformedException: The update to link value http://data.knora.org/fcac0fe61801/values/y2Rlp1KZT2eKXszRjXYQ1A with source IRI http://data.knora.org/fcac0fe61801, link property http://www.knora.org/ontology/incunabula#partOf, and target http://data.knora.org/5e77e98d2603 was not performed. Please report this as a possible bug."}

**Comment by tobiasschweizer** [comment]
Probably I do something fundamentally wrong because the already existing tests pass. Please enlighten me :-)

**Comment by benjamingeer** [comment]
> > The update to link value http://data.knora.org/8a0b1e75/values/1bsbipU4S_-dS1ddb9XOUQ
>
> The value Iri in this case would be the Iri of the reification node, right?

Yes, that's why the error message says `link value`. :)

I'll look at this tomorrow.

**Comment by tobiasschweizer** [comment]
Great!

**Comment by benjamingeer** [comment]
This is because the link value you're trying to change has no `valueHasOrder`. If I remember correctly, `valueHasOrder` is optional, though. I'm changing the SPARQL accordingly.

**Comment by tobiasschweizer** [comment]
If you need me to change something in the test data, just tell me.

**Comment by benjamingeer** [comment]
I need some more time with this.

**Comment by benjamingeer** [comment]
Fixed:

https://github.com/dhlab-basel/Knora/commit/90e9c8ed4f041e4f6a317243e2ef0350d4b2ee72

I had to comment out a consistency rule to make this work (because the consistency rules can't yet take deleted values into account), so you'll need to run `graphdb-se-ci-prepare.sh` again (and restart Tomcat).

**Comment by tobiasschweizer** [comment]
Sometimes (not always) I encounter this error now:

> status":4,"error":"org.knora.webapi.SparqlGenerationException: linkUpdateForNewLink.directLinkExists must be false in this SPARQL

**Comment by benjamingeer** [comment]
Is there a stack trace for that error on the console?

**Comment by tobiasschweizer** [comment]
> webapi 2016-04-15 16:24:27,447 - ERROR - akka.dispatch.Dispatcher - webapi-akka.actor.default-dispatcher-9 - akka.dispatch.Dispatcher - linkUpdateForNewLink.directLinkExists must be false in this SPARQL template
webapi org.knora.webapi.SparqlGenerationException: linkUpdateForNewLink.directLinkExists must be false in this SPARQL template
webapi 	at queries.sparql.v1.txt.changeLink_Scope0$changeLink.apply(changeLink.template.scala:172) ~[classes/:na]
webapi 	at org.knora.webapi.responders.v1.ValuesResponderV1$$anonfun$org$knora$webapi$responders$v1$ValuesResponderV1$$changeLinkValueV1AfterChecks$1$$anonfun$apply$68.apply(ValuesResponderV1.scala:1770) ~[classes/:na]
webapi 	at org.knora.webapi.responders.v1.ValuesResponderV1$$anonfun$org$knora$webapi$responders$v1$ValuesResponderV1$$changeLinkValueV1AfterChecks$1$$anonfun$apply$68.apply(ValuesResponderV1.scala:1761) ~[classes/:na]
webapi 	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237) ~[na:na]
webapi 	at scala.util.Try$.apply(Try.scala:192) ~[na:na]
webapi 	at scala.util.Success.map(Try.scala:237) ~[na:na]
webapi 	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[na:na]
webapi 	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[na:na]
webapi 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) ~[na:na]
webapi 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) ~[akka-actor_2.11-2.4.0.jar:na]
webapi 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91) ~[akka-actor_2.11-2.4.0.jar:na]
webapi 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) ~[akka-actor_2.11-2.4.0.jar:na]
webapi 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) ~[akka-actor_2.11-2.4.0.jar:na]
webapi 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) ~[na:na]
webapi 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90) ~[akka-actor_2.11-2.4.0.jar:na]
webapi 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39) ~[akka-actor_2.11-2.4.0.jar:na]
webapi 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:399) ~[akka-actor_2.11-2.4.0.jar:na]
webapi 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
webapi 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
webapi 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
webapi 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]

**Comment by benjamingeer** [comment]
I probably won't be able to look at this till Monday.

**Comment by benjamingeer** [comment]
I just ran your Python script 5 times, reloading the test data after each run (using `graphdb-se-load-test-data.sh`), and was unable to reproduce this bug. I only get this:

```
ben@bayes:scripts$ ./bugtest.py 
{"userdata":{"email":"test@test.ch","username":"root","firstname":"Administrator","projects_info":[{"basepath":null,"shortname":"incunabula","description":null,"logo":"incunabula_logo.png","id":"http://data.knora.org/projects/77275339","keywords":null,"rights":null,"longname":"Bilderfolgen Basler Frühdrucke"},{"basepath":null,"shortname":"images","description":null,"logo":null,"id":"http://data.knora.org/projects/images","keywords":null,"rights":null,"longname":"Images Collection Demo"}],"user_id":"http://data.knora.org/users/91e19f1e01","activeProject":null,"lastname":"Admin","token":null,"projects":["http://data.knora.org/projects/77275339","http://data.knora.org/projects/images"],"lang":"de","password":null},"id":"http://data.knora.org/fcac0fe61801/values/HhwdZ-_sRLWAH2RhDVlu0w","status":0,"comment":null,"rights":8,"value":"http://data.knora.org/5e77e98d2603"}
```

**Comment by benjamingeer** [comment]
What are you doing exactly? If you can write a script that reproduces this problem reliably, I can look at it next week.

**Comment by tobiasschweizer** [comment]
Ok, I will try toprovide you with a script that reproduces the problem. Perhaps I resubmitted the same tragetIri which would be a duplicate. I will keep you posted.

**Comment by tobiasschweizer** [comment]
it occurs when you try to change a link and submit the already existing traget Iri again:

```python
import requests, json, urllib

def changeLink(valueIri, params):
    r = requests.put("http://localhost:3333/v1/values/" + urllib.parse.quote_plus(valueIri),
    data=json.dumps(params),
    auth=("root", "test"),
    headers={'content-type': 'application/json; charset=utf8'}
    )
    return r

#########

valueIri = "http://data.knora.org/fcac0fe61801/values/292db688-d37d-4c54-b920-e4248f3e357b"

params = {
    'project_id': 'http://data.knora.org/projects/77275339',
    'link_value': 'http://data.knora.org/5e77e98d2603'
}

res1 = changeLink(valueIri, params)

print("*********")
print(res1.text)

valueIri2 = res1.json()['id']

params2 = {
    'project_id': 'http://data.knora.org/projects/77275339',
    'link_value': 'http://data.knora.org/5e77e98d2603'
}

res2 = changeLink(valueIri2, params2)

print("*********")
print(res2.text)
```

> ```json
{"status":4,"error":"org.knora.webapi.SparqlGenerationException: linkUpdateForNewLink.directLinkExists must be false in this SPARQL template"}
```

An error message is absolutely find, but it should be a of type duplicate I think

**Comment by tobiasschweizer** [comment]
change one of the submitted target Iris to `http://data.knora.org/e41ab5695c`  (so they are different) and it works

**Comment by benjamingeer** [comment]
Good catch! You could fix that by adding one line to the values responder, I guess you don't need me for that. :)

**Comment by tobiasschweizer** [comment]
Ok, I will check if the submitted Iri equals the existing one and throw a DuplicateException if so

**Comment by tobiasschweizer** [comment]
```scala
case class LinkUpdateV1(targetResourceIri: IRI) extends UpdateValueV1 { ...

 override def isDuplicateOfOtherValue(other: ApiValueV1): Boolean = {

        other match {
            case linkV1: LinkV1 => targetResourceIri == linkV1.targetResourceIri
            case _ => false
        }
    }
```

because it is a LinkValueV1 in our case:

```
other match {
            case linkV1: LinkV1 => targetResourceIri == linkV1.targetResourceIri
            case linkValueV1: LinkValueV1 => targetResourceIri == linkValueV1.objectIri
            case _ => false
        }
```

**Comment by tobiasschweizer** [comment]
so not the direct link, but the reification node is compared

**Comment by benjamingeer** [comment]
Makes sense!

**Comment by tobiasschweizer** [comment]
https://github.com/dhlab-basel/Knora/commit/6fea7603812db126b7679d54a012020d07fee0b8

**Comment by tobiasschweizer** [comment]
Do we need a test for this?

**Comment by benjamingeer** [comment]
Yes please. :)

**Comment by tobiasschweizer** [comment]
in which case would `isDuplicateOfOtherValue` deal with a `LinkV1`?

**Comment by tobiasschweizer** [comment]
and why are we dealing with this on a Friday night? I guess we are no nerds with too few human links :-)

**Comment by benjamingeer** [comment]
In the trait `UpdateValueV1`, the signature of `isDuplicateOfOtherValue` takes an `ApiValueV1`, so logically you have to handle anything that could be considered a duplicate, including a `LinkV1`. I don't know whether there's actually a case where you would get a `LinkV1`. One of the problems with API v1 is that we have both `LinkV1` and `LinkValueV1` for representing links in different contexts.

I'm going to sleep now. :)

**Comment by tobiasschweizer** [comment]
I have just discovered that I after doing the update of a link value I do have two reification nodes partOfValue

**Comment by benjamingeer** [comment]
You should have two reification nodes, but one of them should be marked as deleted and should not be returned in API query responses.

**Comment by tobiasschweizer** [comment]
You are right! One is marked as deleted! 

I will add the test on Monday.

**Comment by benjamingeer** [comment]
Now that I've slept, I think I remember that when you create a new link (rather than changing an existing link), the values responder receives `LinkV1` objects from the resources responder and uses them to check for duplicates.

**Comment by tobiasschweizer** [comment]
Ok, that means now both cases are covered. 

But why do we have a default to false? `case _ => false`

That was the cause of the problem: if it returned true, we would have got a duplicate exception for each attempt to change a link, regardless of it IRI

**Comment by benjamingeer** [comment]
Because the method takes an `ApiValueV1`. If you pass it a `TextValueV1`, it should return `false`.

**Comment by tobiasschweizer** [comment]
but it is overriding this method, no?

```scala
case class LinkUpdateV1(targetResourceIri: IRI) extends UpdateValueV1 {
    def valueTypeIri = OntologyConstants.KnoraBase.LinkValue

    /**
      * It doesn't make sense to add a link to a resource when we already have a link to the same resource.
      *
      * @param other another [[ApiValueV1]].
      * @return `true` if `other` is a duplicate of `this`.
      */
    override def isDuplicateOfOtherValue(other: ApiValueV1): Boolean = {

        other match {
            case linkV1: LinkV1 => targetResourceIri == linkV1.targetResourceIri
            case linkValueV1: LinkValueV1 => targetResourceIri == linkValueV1.objectIri
            case _ => false
        }
    }

    override def toString = {
        targetResourceIri
    }

    /**
      * A link isn't really changed if the new version points to the same resource as the old version.
      *
      * @param currentVersion the current version of the value.
      * @return `true` if this [[UpdateValueV1]] is redundant given `currentVersion`.
      */
    override def isRedundant(currentVersion: ApiValueV1): Boolean = isDuplicateOfOtherValue(currentVersion)
}

```

This is the specific implementation for `LinkUpdateV1 `. `LinkV1` is probably wrong here.

**Comment by benjamingeer** [comment]
`LinkUpdateV1` extends `UpdateValueV1`, which provides a default definition for the method. The definition in `LinkUpdateV1` overrides the default definition in `UpdateValueV1`. The idea is that any `UpdateValueV1` can be compared to any `ApiValueV1` to see if it's a duplicate. There are two classes that extend `ApiValueV1` and represent links: `LinkV1` and `LinkValueV1`. An instance of either of these classes could be a duplicate of a `LinkUpdateV1`. An instance of any other type of `ApiValueV1` could not be a duplicate of a `LinkUpdateV1`. So I think the code is correct as you have it now.

**Comment by benjamingeer** [comment]
Maybe what's confusing you is that the method doesn't compare an `UpdateValueV1` to another `UpdateValueV1`, it compares it to an `ApiValueV1`.

**Comment by tobiasschweizer** [comment]
https://github.com/dhlab-basel/Knora/commit/4fe7de8bbace4e6850ca8150715582927dfe52e3
