### ISSUE TITLE
New Error on Bulk Import with Images

### ISSUE THREAD

**Issue by ezbinden** [dhlab-basel/Knora#1140]
I am working with KNORA v2.1.0 and Sipi v1.4.2-Snapshot on Ubuntu 18.4 LTS

First I had errors on a image bulkimport together with my data according to the prescription of v1 Bulkimport of image data on docs.knora.org. To make sure it is not an error in my ontology I tested also the script of gfoo (https://github.com/LaDHUL/BulkImageImportTest) with the anything ontology.

Same error. I do: 

./checkImageFolder.sh /home/ez/Dokumente/DaSCH/img_data /home/ez/Dokumente/DaSCH/Sipi/test/_test_data/img_data

which results in KNORA telling me:

### ERROR /home/ez/Dokumente/DaSCH/img_data/3MFER-02-single.jpg
    {"status":4,"error":"org.knora.webapi.SipiException: JSON error response returned by Sipi is invalid, it cannot be turned into a SipiErrorConversionResponse"}

Sipi simply accepts the connection from localhost.

Is it the versions not working together (simple) or is it something else? Help would be appreciated. Thanks!

PS I use v2.1.0 of Knora to view the data in Salsah2 generic interface.

**Comment by benjamingeer** [comment]
To test this myself, I will need the image file.

**Comment by benjamingeer** [comment]
I can't reproduce this using the current `develop` branches of Knora and Sipi with `BulkImageImportTest` and the images you provided. For me, the script runs without errors.

**Comment by ezbinden** [comment]
With new versions and the right configuration of sipi ( sipi.knora-local-config.lua ) inside of Knora it works also for me.
