### ISSUE TITLE
Use HTTP POST to mark a value as deleted

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#1149]
Marking as deleted is really an update, not a deletion, and this would allow the request to have a JSON-LD body, which would be simpler and more consistent with the rest of the API.

**Comment by gfoo** [comment]
not necessary related, but I didn't find in the doc a `DELETE v2/resources` entry point.

**Comment by benjamingeer** [comment]
@gfoo You're right, thanks, I'll add it. :)
