### ISSUE TITLE
Changes in the folder structure / build process

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#115]
I would propose the following changes, which would give us a more modular structure, allowing easier testing / deployment.

Relevant for #3.

1. Get rid of SBT in the root folder. Only ``webapi`` is using scala/sbt and by moving it to here, allows us  to have everything that is needed for running it in production or testing in one place. Also makes it easier to create a docker image containing just the ``webapi`` content.

2. Move ``/webapi/_fuseki`` to ``/triplestores/fuseki``. Hopefully, sometime soon, we can add ``graphdb-free`` (still waiting on the approval from Ontotext) to the repository, and then it would live in ``/triplestores/graphdb-free``. This change will also allow us to isolate only the files that are needed for the docker image.

@benjamingeer @tobiasschweizer

**Comment by benjamingeer** [comment]
I think we can't do (1) because `salsah` is using Scala and SBT for the Selenium tests, as per #111. But (2) seems OK to me.

**Comment by subotic** [comment]
For ``salsah`` I would then propose a two step approach. As a first step, I would create a small ``sbt``-based build, so that we can still use scala/sbt. Later as a second step, I would change it to a ``nodejs/npm`` based build and rewrite the selenium test, since these are the tools that are already used for ``angular2`` development, and there I also need to write selenium tests. I don't see a good reason to force a web developer working with javascript/angular/etc to use scala for writing their tests. There is also a nice web-server running in ``nodejs`` (that is recommended when doing angular2 development) that can be used instead of the current spray web-server, which is the initial reason for using  ``sbt`` in ``salsah``. I simply didn't know better at that time ;-).

**Comment by subotic** [comment]
Ongoing work in [wip/subotic-folder-build-restructuring](/https://github.com/dhlab-basel/Knora/tree/wip/subotic-folder-build-restructuring) branch.

**Comment by benjamingeer** [comment]
I've written Selenium tests in both JavaScript and Scala, and writing them in Scala is much more pleasant. Writing them in JavaScript was really a pain, because debugging JavaScript is a pain. When the test didn't work because of a bug in the JavaScript code, it was much harder to find the problem, because there was no compiler to check the code. And there were race conditions that I never managed to solve. Selenium is written in Java, so you need Java for it anyway, and I suspect that putting a JavaScript layer on top of it introduces problems.

**Comment by benjamingeer** [comment]
Plus, rewriting Scala code in JavaScript would be a lot of work.

**Comment by subotic** [comment]
I don't know. Never written any test so far in javascript. Angular2 is using typescript, which is then transpiled to javascript. Maybe this makes it easier. I will report back on this topic as soon as I have more information. Anyway, if it makes our life easier, then we can leave it at step 1, i.e. use ```scala/sbt```.

**Comment by benjamingeer** [comment]
Could we support both Scala and JavaScript for Selenium tests? We could just have one Scala spec that runs `npm` on the command line to run any tests written in JavaScript.

**Comment by subotic** [comment]
> Plus, rewriting Scala code in JavaScript would be a lot of work.

I don't really know the extent of the selenium tests. Also bear in mind, that the current salsah application is not really written with testability in mind. When changing over to angular2, testing should be much easier.

> Could we support both Scala and JavaScript for Selenium tests? We could just have one Scala spec that runs npm on the command line to run any tests written in JavaScript.

Yes, sure. I just wanted to simplify things in the sense that we don't require using scala/sbt for html/javascript/angular development, since this 'community' has already its own widely used tools.

**Comment by benjamingeer** [comment]
> I don't really know the extent of the selenium tests. Also bear in mind, that the current salsah application is not really written with testability in mind.

Tobias has been working for weeks to get the SALSAH GUI working with the Knora API server. He's writing Selenium tests in Scala as he goes along, so that when he fixes something in the GUI, he can check that it stays fixed and isn't broken again by subsequent fixes. This saves him a lot of time because he doesn't have to keep testing the same things manually again and again. Also, without tests, we'll have no way to be sure that the GUI actually works with Knora.

**Comment by subotic** [comment]
I just looked at the tests. Looks great. I absolutely agree, that we need tests for the current salsah version. What I meant is, that it should get easier to write them with angular2 in the future and that maybe then we can move away from scala/sbt ;-).

We can keep writing them now in scala/sbt, but at the same time also evaluate how to write them in the future with angular2.

**Comment by benjamingeer** [comment]
OK!

**Comment by subotic** [comment]
So, then I would suggest to remove sbt from the root folder, and move the respective parts to the ``webapi`` and ``salsah`` folder.

**Comment by benjamingeer** [comment]
Sounds fine to me.

**Comment by subotic** [comment]
resolves #111
