### ISSUE TITLE
OntologyCache empty after startup

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#1154]
When I start webapi and access the route `/v2/ontologies/metadata` I get:

> {
"error": "org.knora.webapi.ApplicationCacheException: The Knora API server has not loaded any ontologies, perhaps because of an invalid ontology"
}

When I start webapi, it is up immediately. Before it took a couple of seconds.

> webapi [2019-01-10 16:06:31,539] INFO  - ApplicationStateActor - appStateChanged - to state: StartingUp
webapi [2019-01-10 16:06:31,539] INFO  - ApplicationStateActor - appStateChanged - to state: WaitingForRepository
webapi [2019-01-10 16:06:31,595] INFO  - ApplicationStateActor - appStateChanged - to state: RepositoryReady
webapi [2019-01-10 16:06:31,595] INFO  - ApplicationStateActor - appStateChanged - to state: CreatingCaches
webapi [2019-01-10 16:06:31,738] INFO  - ApplicationStateActor - appStateChanged - to state: CachesReady
webapi [2019-01-10 16:06:31,738] INFO  - ApplicationStateActor - appStateChanged - to state: LoadingOntologies
webapi [2019-01-10 16:06:31,739] INFO  - ApplicationStateActor - appStateChanged - to state: OntologiesReady
webapi [2019-01-10 16:06:31,739] INFO  - ApplicationStateActor - appStateChanged - to state: Running
webapi [2019-01-10 16:06:31,739] INFO  - ApplicationStateActor - 
webapi ================================================================
webapi Knora API Server started at http://0.0.0.0:3333
webapi ----------------------------------------------------------------
webapi DB-Name: knora-test
webapi DB-Type: graphdb-se
webapi DB Server: localhost, DB Port: 7200
webapi ================================================================
webapi

**Comment by tobiasschweizer** [comment]
I have check out 0ee9b20f064279a9b871c558bab99b8c002a81dd and everything works as expect

**Comment by subotic** [comment]
If you could maybe review it. It's just one line of code that changed.

**Comment by benjamingeer** [comment]
How did the tests pass on Travis if the ontologies were never loaded?

**Comment by subotic** [comment]
Because we start Knora differently in the tests, which is on my to-do list to change. During our testing, we don't start Knora by calling `main`, we call directly `KnoraService.start()`. The parameter to `KnoraService.start()` was the culprit.

**Comment by subotic** [comment]
For the tests, the ontologies were always loaded.
