### ISSUE TITLE
All calls to Sipi should go through the SipiResponder

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#1156]
There are some cases where Sipi is contacted directly from inside a responder. Shouldn't in those cases the call go through the SipiResponder (or the SipiManager in the future)?

**Comment by benjamingeer** [comment]
Yes, they should. I didn't know about those cases, where are they?

**Comment by benjamingeer** [comment]
Or maybe I knew and I forgot... 🙂

**Comment by subotic** [comment]
- https://github.com/dhlab-basel/Knora/blob/14e17df9d0c0768fe2237a4846398c00b922b7e3/webapi/src/main/scala/org/knora/webapi/responders/v2/StandoffResponderV2.scala#L133

- https://github.com/dhlab-basel/Knora/blob/05664eeaaa91f96f9d9b9db2f5248d4e29cbf73a/webapi/src/main/scala/org/knora/webapi/responders/v2/ResourcesResponderV2.scala#L998

**Comment by subotic** [comment]
I only found them because I removed the `ActorMaterializer` in those classes and then the compiler complained :-)

**Comment by tobiasschweizer** [comment]
So I have to add a message and and a method to the `SipiResponder` that handles these http calls? When do you need it?

**Comment by subotic** [comment]
I can do it. I just wanted to know if it needs to be done. You can do the review ;-)

**Comment by tobiasschweizer** [comment]
@subotic Great! I have written integration tests for both cases:

- `org/knora/webapi/e2e/v1/KnoraSipiIntegrationV1ITSpec.scala`: "create a TextRepresentation of type XSLTransformation and refer to it in a mapping"
- `org/knora/webapi/e2e/v1/KnoraSipiIntegrationV1ITSpec.scala`: "create a mapping for standoff conversion to TEI referring to an XSLT and also create a Gravsearch template and an XSLT for transforming TEI header data"

In one case, Knora requests an XSLT file from Sipi. In the other case it requests a Gravsearch template.
