### ISSUE TITLE
Investigate Lukas‘s GraphDB OOM error during mass-import

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#1157]

**Comment by subotic** [comment]
Thank you very much for the detailed instructions :-)

**Comment by subotic** [comment]
@lrosenth I'm running into some error.

The first command runs successfully, or at least without any errors.

The second command throws the following error:
```
$ python3 create_data_terlag.py lager.csv -P "0808" -O "terlag" -x data.xml                                                                                                                                                                                                                                                   master  ✭ ✱
Traceback (most recent call last):
  File "create_data_terlag.py", line 72, in <module>
    with open(args.tabfile) as tsv:
FileNotFoundError: [Errno 2] No such file or directory: 'lager.csv'
```

**Comment by subotic** [comment]
Creating `data.csv` by hand fixed it. Now `data.xml` gets generated, but not much inside:

```
<?xml version='1.0' encoding='utf-8'?>
<knoraXmlImport:resources xmlns:knoraXmlImport="http://api.knora.org/ontology/knoraXmlImport/v1#" xmlns:p0808-terlag="http://api.knora.org/ontology/0808/terlag/xml-import/v1#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://api.knora.org/ontology/0808/terlag/xml-import/v1#"/>
```

**Comment by subotic** [comment]
Also, `lager.csv` is empty.

**Comment by lrosenth** [comment]
Shit – forgot these data files. You could directely use data.xml for upload to knora...

[TEstData.zip](https://github.com/dhlab-basel/Knora/files/2756089/TEstData.zip)

**Comment by subotic** [comment]
Thanks. Now I can reproduce the error.

**Comment by subotic** [comment]
I've fixed the error, by raising the memory for GraphDB to 3GB.

Now I'm running into another error:
```
{"status":4,"error":"akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://webapi/user/storeManager#353594245]] after [180000 ms]. Message of type [org.knora.webapi.messages.store.triplestoremessages.SparqlUpdateRequest]. A typical reason for `AskTimeoutException` is that the recipient actor didn't send a reply."}
```

@benjamingeer what should the default max response time for bulk-import be? Are 15 minutes ok? There is a setting `update-timeout = 15 minutes` but that doesn't seem to be used.

Also, we have defined in the route for bulk-import 1 hour, but no way that this can work. I would like to make them uniform to some sane value.

**Comment by benjamingeer** [comment]
> There is a setting `update-timeout = 15 minutes` but that doesn't seem to be used.

It's used in `HttpTriplestoreConnector` when making the connection to the triplestore:

https://github.com/dhlab-basel/Knora/blob/develop/webapi/src/main/scala/org/knora/webapi/store/triplestore/http/HttpTriplestoreConnector.scala#L96

But it should also be used in `ResourcesResponderV1`, where the message is sent to `HttpTriplestoreConnector` to do the update:

https://github.com/dhlab-basel/Knora/blob/develop/webapi/src/main/scala/org/knora/webapi/responders/v1/ResourcesResponderV1.scala#L1465

**Comment by subotic** [comment]
I've raised GRaphDB's memory limit and the timeout limit to 30 minutes. The operation now finishes with an inconsitency error. There is probably a problem with the data:

```
{"status":4,"error":"org.knora.webapi.TriplestoreResponseException: Triplestore responded with HTTP code 500: org.eclipse.rdf4j.repository.RepositoryException: org.eclipse.rdf4j.sail.SailException: com.ontotext.trree.consistency.ConsistencyException: Consistency check object_class_constraint_1 failed:\n
http://rdfh.ch/0808/bQPlWELXSF2Rt_hhUj-QKQ/values/vriO06N7Q9a2kBtLaYyXaw http://www.knora.org/ontology/knora-base#valueHasListNode http://rdfh.ch/lists/0808/X6bb-JerQyu5ULruCGEO0w\n
http://www.knora.org/ontology/knora-base#valueHasListNode http://www.knora.org/ontology/knora-base#objectClassConstraint http://www.knora.org/ontology/knora-base#ListNode\n
-----------------------------------\n
http://rdfh.ch/lists/0808/X6bb-JerQyu5ULruCGEO0w http://www.w3.org/1999/02/22-rdf-syntax-ns#type http://www.knora.org/ontology/knora-base#ListNode\n"}
```

**Comment by subotic** [comment]
@lrosenth I would suggest, that you break the import into smaller XML files and then upload them one by one.

**Comment by benjamingeer** [comment]
The consistency error probably means that the list node `<http://rdfh.ch/lists/0808/X6bb-JerQyu5ULruCGEO0w>` doesn't exist.
