### ISSUE TITLE
Bulk import AskTimeoutException exception

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#1163]
Using Knora `develop` branch I get new errors with our `reforme-geneve` project.
New version of images : https://drive.switch.ch/index.php/s/Jgr085ZQvOG12Yx

Using the [BulkImageImportTest](https://github.com/LaDHUL/BulkImageImportTest) tool, all images seems to be ok for `sipi` but at the end for the last full import I get this error: `{"status":4,"error":"org.knora.webapi.SipiException: Failed to connect to Sipi"}`

After the 106 single image imports, my laptop started to freeze (docker over loaded etc.) so I presume the last full import error is not necessarily representative.

Then I launched only the full import which failed: (data file: [allbulk-1547547960.zip](https://github.com/dhlab-basel/Knora/files/2759362/allbulk-1547547960.zip))
`curl -k -s -u root@example.com:test -X POST -d @/tmp/allbulk-1547547960 http://localhost:3333/v1/resources/xmlimport/http%3A%2F%2Frdfh.ch%2Fprojects%2F0001`

And I get this error:
```json
{"status":4,"error":"akka.pattern.AskTimeoutException: Ask timed out on [ActorSelection[Anchor(akka://webapi/), Path(/user/responderManager)]] after [180000 ms]. Message of type [org.knora.webapi.messages.v1.responder.sipimessages.SipiResponderConversionPathRequestV1] was sent by [Actor[akka://webapi/user/responderManager/resourcesV1#-804700161]]. A typical reason for `AskTimeoutException` is that the recipient actor didn't send a reply."}
```
Do you reproduce this error?  (don't forget to fix image paths in the `allbulk-1547547960.` file)

thx

**Comment by benjamingeer** [comment]
I've just tried the full import and it completed without errors. I ran GraphDB SE, Knora, and Sipi on the command line (not using Docker at all) on an iMac with a 3.4 GHz 8-core Intel i7 processor and 32 GB of RAM.

**Comment by benjamingeer** [comment]
If it works without Docker but fails with Docker, this is a deployment issue. @subotic any ideas?

**Comment by subotic** [comment]
Sipi is probably running slower inside Docker, because Docker on Mac is running in a separate virtual machine.

We can always raise the timeout value, but that doesn't feel right.

It should run slower, but not throw timeout exceptions. I have an idea, but that would require a bit of redesigning of the SipiResponder (or SipiConnector how it will be called in the future).

**Comment by benjamingeer** [comment]
@subotic I believe that @gfoo needs this to work in the next few weeks, could you possibly help him work out at least a temporary solution?

**Comment by gfoo** [comment]
doesn't matter if it doesn't work on my personal computer, but it also fails on a prod server.

@loicjaouen could give us the prod server hardware and/or docker configs where the `reforme-geneve` project import failed yesterday? 

It is maybe just a docker tuning.

**Comment by subotic** [comment]
I'm trying to run the bulkimport on my machine.

A few questions:

 1. I need to download the allbulk-1547547960.zip and the images, and then run the:
```
curl -k -s -u root@example.com:test -X POST -d @/tmp/allbulk-1547547960 http://localhost:3333/v1/resources/xmlimport/http%3A%2F%2Frdfh.ch%2Fprojects%2F0001
```

 2. Where do you put the images and how did you tell docker where to find them? Did you change `docker-compose.yml`?

**Comment by gfoo** [comment]
1. yes

2. the bulk file contains those kind of file locations: `<knoraXmlImport:file path="/sipi_import/reforme-geneve/AEG_Ms_hist_22b.tiff"`, so, you're right I modify the compose file:
```json
  sipi:
[...]
      - ${HOME}/work/sipi_import:/sipi_import
```
I copied all images into the `${HOME}/work/sipi_import/reforme-geneve` folder.

If you don't want to modify your compose file you could copy images into `/tmp/reforme-geneve` and query/replace `/sipi_import/reforme-geneve/` into `/tmp/reforme-geneve/` of bulk file.

**Comment by subotic** [comment]
Got it working, but it works on my machine.

**Comment by subotic** [comment]
![screenshot 2019-01-16 at 11 56 46](https://user-images.githubusercontent.com/400790/51244611-cea86d00-1985-11e9-831b-22bb07f57466.png)

**Comment by subotic** [comment]
I used the latest `develop` with the refactored `SipiResponders`. Maybe you could try the latest `develop`

**Comment by gfoo** [comment]
I have the same config but how many real CPUs/cores do you have on your machine? (me, just 1 with 4 cores so 6 CPUs is a kind of emulation, don't know really how it wors behind the scene especially on Mac OS)

Ok, I will test that this afternoon, thanks for the tests.

**Comment by gfoo** [comment]
Ok, now it works on my machine 👍 ... but after having restarted the stack, not sure that you can do the same import several times without restarting the stack.

Is the next [release](https://github.com/dhlab-basel/Knora/milestone/17) is still scheduled for the end of January?

**Comment by gfoo** [comment]
Anyway we will try a workaround to upload our data to a 4.0.0 deployment, just by exporting a data turtle file from my machine and upload it to our `graphdb` prod and copy sipi image folders into our `sipi` prod.
I let you close the issue if it's fine for you, thanks for the help.

**Comment by gfoo** [comment]
If you want more perf test, my real test is with all the data into the project:

[ref-gen-test.zip](https://github.com/dhlab-basel/Knora/files/2764380/ref-gen-test.zip)

```shell
# require console.sh in the PATH
./load-onto.expect  http://localhost:7200
# restart stack
sed -e 's,/tmp,/sipi_import,g' reforme-geneve-test-data-knora-nv.xml |curl -u reforme1@unil.ch:test -X POST -d @- -H "content-type: text/xml" http://localhost:3333/v1/resources/xmlimport/http%3A%2F%2Frdfh.ch%2Fprojects%2F0111
```

**Comment by subotic** [comment]
Thanks, I will try it out.
