### ISSUE TITLE
Error Message concerning 'knoraXmlImport:Representation_linkValueType' during bulk-import in V1

### ISSUE THREAD

**Issue by sacha-alex** [dhlab-basel/Knora#1168]
Dear Knora team,

  during the import of an xml-file (attached), which looks fine for me, I got the following error from Knora (build "a61ad3a664bc7dd5772567563445542b3efa35b1" from the 10th of January):

Post: 
    http://localhost:3333/v1/resources/xmlimport/http%3A%2F%2Frdfh.ch%2Fprojects%2F004D

Result:
  {"status":11,"error":"org.knora.webapi.BadRequestException: XML import did not pass XML schema validation: org.xml.sax.SAXParseException; lineNumber: 1091; columnNumber: 166; src-resolve: Cannot resolve the name 'knoraXmlImport:Representation_linkValueType' to a(n) 'type definition' component."}

Could you give me a hint please? I don't understand this error(-message), since the data I am currently using doesn't contain any properties related to (knora-base:has)Representation.

Many, many thanks in advance.
Best,
Sascha

[import_data.xml.zip](https://github.com/dhlab-basel/Knora/files/2765046/import_data.xml.zip)

**Comment by benjamingeer** [comment]
I'm pretty sure this is a bug. I tried to reproduce it with your ontologies, but they can't be loaded because of an inconsistency:

```
org.knora.webapi.InconsistentTriplestoreDataException: Class
http://www.knora.org/ontology/0000/text-structure#Dialogue has a cardinality on property
http://www.knora.org/ontology/0000/document#hasTextReference and on its subproperty
http://www.knora.org/ontology/0000/document#hasEndnoteReference
```

I'll try to make my own test case, but please fix your ontologies.

**Comment by sacha-alex** [comment]
Thanks a lot for the fix! Tried it and the problem is gone.
Many thanks.

**Comment by benjamingeer** [comment]
Thanks for the bug report!
