### ISSUE TITLE
what sipi docker-hub image should we use?

### ISSUE THREAD

**Issue by loicjaouen** [dhlab-basel/Knora#1173]
the latest stable image for `dhlabbasel/webapi` is:
```
"name": "4.0.0", "last_updated": "2018-12-12T20:19:28.887844Z"
```

the latest for sipi is:
```
"name": "knora-v3.0.0", "last_updated": "2018-11-30T12:45:43.939255Z"
```

shouldn't the latest official sipi for knora image at docker-hub be v4.0.0 ?

**Comment by subotic** [comment]
see https://github.com/dhlab-basel/Knora/blob/develop/project/Dependencies.scala

currently it is `v1.4.2-SNAPSHOT`

**Comment by loicjaouen** [comment]
thanks! I missed to look at your sbt docker-compose too yet, doing so now
