### ISSUE TITLE
Sipi reports: Unauthorized access

### ISSUE THREAD

**Issue by ezbinden** [dhlab-basel/Knora#1174]
I try to load images from two different points (salsah1 in docker, knora-ui page). In the Browser Konsole I see the stillImageFileValues 
(e.g. http://localhost:1024/knora/LKryHE3Ar1S-FCdFoxwEQIr.jpx/full/834,750/0/default.jpg ) 

but neither via the webpages nor with direct access to Sipi (path above) I can access the image. Sipi reports Unahthorized access, although I am logged in as root.

Any ideas?

**Comment by subotic** [comment]
Which client are you using? `Salsah1` or `Salsah2`.

When used locally, you need to access over `0.0.0.0` instead of `localhost`.

**Comment by gfoo** [comment]
On Mac OS, it works only if I use `localhost` as Sipi URL **and** configure in compose `SIPI_WEBAPI_HOSTNAME=webapi` else I get this Sipi error (container log):
`sipi_1     | Sipi: Server.http() failed: Error #1368: HTTP GET request to http://0.0.0.0:3333/v1/files/BzNRKJ2Kq0z-Fx5K8x3omT2.jpx failed: Failed to connect to 0.0.0.0 port 3333: Connection refused`

**Comment by gfoo** [comment]
#1130

**Comment by subotic** [comment]
@gfoo In #1170 we set `0.0.0.0` as the default. Are you using the latest `develop`?

**Comment by gfoo** [comment]
yes, I changed my docker compose file, not found any ohter solution.

**Comment by gfoo** [comment]
Well, it is a little bit more complicated, since I login to Knora with `http://0.0.0.0:3333`, It seems to work with Sipi URL : `http://0.0.0.0:1024` (The Sipi url is provided by Knora in its json response: `knora-api:stillImageFileValueHasIIIFBaseUrl`)

**Comment by subotic** [comment]
Sorry about that. I changed it in December (https://github.com/dhlab-basel/Knora/pull/1125). I will change it back to `webapi`.

**Comment by subotic** [comment]
> Well, it is a little bit more complicated, since I login to Knora with http://0.0.0.0:3333, It seems to work with Sipi URL : http://0.0.0.0:1024 (The Sipi url is provided by Knora in its json response: knora-api:stillImageFileValueHasIIIFBaseUrl)

Yes, locally, access to `webapi` and `sipi` from the browser should always go to `0.0.0.0`. The change introduced in #1179 makes `sipi` again talk to `webapi` over the internal network. This actually never needs to be changed. We have it like this configured in production.

The reason for changing things around from `localhost` to `0.0.0.0` is so that the stack works when deployed inside and outside of docker.
