### ISSUE TITLE
confusion about 'shared' and '0000' when shared ontologies working with shared ontologies?

### ISSUE THREAD

**Issue by sacha-alex** [dhlab-basel/Knora#1175]
Dear Knora-Team,

  I run into some trouble, that occurs, when a shared ontology is using a property that is defined within another shared ontology. As an example you fill find attached two example ontologies, where the 'ibox' is using a property that is defined in 'box'. I can create an instance of a box, as expected. In case I won't create an instance of iBox, Knora's xml parser works fine, but I'm getting the following error

{"status":9,"error":"org.knora.webapi.NotFoundException: Property not found: http://www.knora.org/ontology/0000/example-box#hasName"}

which is right, because it is declared in the .ttl-file as http://www.knora.org/ontology/shared/example-box#hasName, that is accepted by the xml-parser.
So there might be a little confusion within Knora about or when to use 'shared' or '0000' as project code for shared ontologies. Or is my assumption wrong and I interpret the error message in a wrong way?

Many thanks in advance for your support.

Best,
Sascha
[example.zip](https://github.com/dhlab-basel/Knora/files/2772926/example.zip)

**Comment by benjamingeer** [comment]
According to https://docs.knora.org/paradox/03-apis/api-v2/knora-iris.html#shared-ontology-iris, `shared` is required, but the default shared project code, `0000`, is optional. So this looks like a bug.

**Comment by benjamingeer** [comment]
Which API operation causes the error?

**Comment by sacha-alex** [comment]
Sorry, if forgot.
It is the v1 bulk import. In/with the example I used

http://localhost:3333/v1/resources/xmlimport/http%3A%2F%2Frdfh.ch%2Fprojects%2F004D

**Comment by benjamingeer** [comment]
Fixed in #1182.

**Comment by sacha-alex** [comment]
super, thanks a lot!
