### ISSUE TITLE
set SALSAH.userdata correctly after login or refresh with an active session

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#118]
SALSAH.userdata only contains the userdata when you do a login, not when you refresh the page with an active session

Also, the user's active project is not set

we need the user's active project when creating a resource

**Comment by subotic** [comment]
As far as I can remember (maybe I'm wrong), the whole ``userdata`` stuff is a product of removing sessions at one point in time (``userdata`` contains information that was previously stored in the session cookie). After the sessions where reintroduced (1-2 weeks later), the ``userdata`` was not removed.

Currently in Knora, the ``userdata`` contains information coming from the triplestore (user profile). If you want the active project, then this needs to be either stored in the users profile in the triplestore (every time the user changes his selection in the GUI), which can then be returned in ``userdata``, or store it somewhere locally in the client (which I would personally prefer).

**Comment by tobiasschweizer** [comment]
Also, the actual user's name is not displayed in the GUI. It says `undefined`.

**Comment by tobiasschweizer** [comment]
make project selection work again, because we need the user's active project

**Comment by tobiasschweizer** [comment]
in `jquery.resadd.js` and `jquery.valcomment.js` the project IRI has to be submitted when creating a new resource or comment. At the moment, I use a workaround by just taking the user's first project.

`jquery.resadd.js`: 

```
SALSAH.ApiPost('resources', {
								restype_id: rtinfo.name,
								properties: propvals,
								project_id: SALSAH.userdata.projects[0], // TODO: take the user's active project here:
								file: file,
								label: "test" // TODO: add the first property's value here
							}
```

`jquery.valcomment.js`:

```
SALSAH.ApiPut('values/' + encodeURIComponent(localdata.settings.value_id),
							{
								project_id: SALSAH.userdata.projects[0], // TODO: how to get this information in a correct way? 
								comment: localdata.settings.comment
							},
```
