### ISSUE TITLE
Token expiration

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#1181]
As mentioned in your [doc](https://docs.knora.org/paradox/03-apis/api-v2/authentication.html#login-and-logout), the token provided is a *JSON Web Tokens*, can we consider that this token contains an `expiration date` as recommended in the [doc](https://jwt.io/introduction/) (Payload > Registered claims) ?

I would like to use this expiration date (example [there](https://github.com/auth0/angular2-jwt)) test everywhere in my Http Interceptor to avoid an Http call to `GET v2/auth`.

Of course I still use `GET v2/auth` to check private route access (Angular `AuthGuard` pattern which less frequent)

**Comment by subotic** [comment]
Yes and the token longevity is also configurable: https://github.com/dhlab-basel/Knora/blob/2b92c7d2a4bf72522e43747e3a77ebf7e2f59194/webapi/src/main/resources/application.conf#L237

**Comment by subotic** [comment]
Interesting [library](url
https://github.com/auth0/angular2-jwt). This is something for @kilchenmann.

**Comment by gfoo** [comment]
ok thanks
