### ISSUE TITLE
API returns user data without authentication

### ISSUE THREAD

**Issue by andreas-aeschlimann** [dhlab-basel/Knora#1207]
A GET https://api.01.unibas.dasch.swiss/admin/users returns all user data, which could be easily abused to gather e-mails and names of users.

I suggest that the API should return a 403 FORBIDDEN in case no auth data is given in the request. Other endpoints may have to be checked as well whether they return data without authentication.

**Comment by subotic** [comment]
duplicate of #961

**Comment by subotic** [comment]
But thanks for reminding me.

**Comment by andreas-aeschlimann** [comment]
Ah, didn't see it. Great!
