### ISSUE TITLE
Implement a scheduler for batch jobs

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#1210]
To limit the load on the triplestore, we need to be able to break a large batch job into small tasks to be executed at scheduled intervals. This applies to:

- Bulk import #1110
- Exporting data in tabular format #919

I think this means we need to be able to:

- Store jobs on disk, so they can be resumed if Knora restarts
- Have a single task queue, so that only one task is run at a time
- Provide an API for administering and monitoring jobs
- Be able to cancel a job

The implementation could use a cron-like scheduler actor based on [Akka timers](https://doc.akka.io/docs/akka/2.5/actors.html#actors-timers). There would be a single instance of this actor. It would receive jobs to be queued, and would store each job in a directory and each task in a file. So there could be a directory structure like this:

```
jobs
  - bulk_import_2394293
      - status.json
      - tasks
        - bulk_import_task_00000001.json
        - bulk_import_task_00000002.json
        - bulk_import_task_00000003.json
        - bulk_import_task_00000004.json
      - output
  - csv_export_70234982
      - status.json
      - tasks
        - csv_export_task_00000001.json
        - csv_export_task_00000002.json
        - csv_export_task_00000003.json
        - csv_export_task_00000004.json
      - output
        - csv_export_task_00000001_output.txt
        - csv_export_task_00000002_output.txt
```

The scheduler would wake up, say, every two seconds, run one task, then go back to sleep.
A simple queuing strategy would be to finish each job before starting the next one. Alternatively, the scheduler could run a task from job 1, then a task from job 2, etc., in round-robin fashion. Or jobs could be given priorities. In any case, the scheduler would need to maintain a small file to remind itself what it should do the next time it wakes up.

Tasks could be implemented in Scala as objects that could read and write themselves in JSON, and have a `run()` method that would carry out the task (e.g. by sending messages to other actors). The scheduler would have to block waiting for the task to complete. After each task completes, its file could be deleted. To cancel a job, the job's directory would be deleted.

Each task would be able to save some output to a file. In the case of a CSV export, the output would be a few lines of CSV data. When a job completed, it would also be able to store output, e.g. the complete CSV file or a report on the completed bulk import, and send an email to the user. The email would contain a link to download the output. There would have to be a route for this, which would also have to check whether the user has permission to download the file.

There would be an API route for administering and monitoring jobs. The scheduler would therefore need to maintain a `status.json` file for each job.

@subotic How does this sound to you?

**Comment by benjamingeer** [comment]
It might even be possible to allow a job to recover after a failure. In the case of the bulk import, this could mean deleting all the resources that were created by the import job before it failed.

**Comment by subotic** [comment]
Great, as we discussed offline, I will try to implement something along those lines, but by using an `event store`. Could be a good opportunity to introduce `event sourcing` for an isolated feature.

**Comment by benjamingeer** [comment]
* Bulk import is being implemented in [knora-py](https://github.com/dhlab-basel/knora-py) instead of in Knora.
* CSV export could be implemented in [knora-py](https://github.com/dhlab-basel/knora-py) and/or in [knora-api-js-lib](https://github.com/dhlab-basel/knora-api-js-lib).

Therefore, we're going to implement batch job scheduling in Knora for now.
