### ISSUE TITLE
Retrieve turtle version of a mapping

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#1212]
Hello,
I use the `HTTP POST http://host/v2/mapping` API to create my mapping, but for installation reasons, a turtle file is more praticable to initialize a project.
Is there a way to retrieve the turtle version of a xml mapping?
I've started a sparql adventure, but, well I don't really know how to correctly achieve that:

```sparql
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX knora-base: <http://www.knora.org/ontology/knora-base#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT {
    ?s ?p ?o .
}
FROM <http://www.knora.org/data/0113/lumieres-lausanne>
WHERE { 
#        BIND(<http://rdfh.ch/projects/0113/mappings/LLStandoffMapping> AS ?resource)
    ?s ?p ?o .
    ?s rdf:type ?type .
    FILTER(?type IN (knora-base:XMLToStandoffMapping, knora-base:MappingElement))
}
```

*More general question*: I have the same problem with the list data, all triplets are located in graph `http://www.knora.org/data/0113/lumieres-lausanne`, could I use different graphs or is there Knora constraints?:
- list -> `http://www.knora.org/list/0113/lumieres-lausanne`
- mappings -> `http://www.knora.org/standoff/0113/lumieres-lausanne` 

Another way, could be to provide `Accept: text/turtle` for list end point:
`HTTP GET http://host/admin/lists?projectIri=xxxx`
And have the same endpoint for mapping:
`HTTP GET http://host/admin/mapping?mappingIri=xxxx`

The main point is that when we have to migrate data from one repository to another, the only praticable way today is the turtle file.

**Comment by tobiasschweizer** [comment]
I think this should return an RDF representation of a mapping (from the GraphBD web console, several serialization formats can be chosen for download):

```sparql
PREFIX knora-base: <http://www.knora.org/ontology/knora-base#>

Construct {
    ?mapping ?p ?o .
    
    ?mapping knora-base:hasMappingElement ?mEle .
    ?mEle ?pp ?oo .
    ?oo ?ppp ?ooo .
}
FROM <http://www.knora.org/data/0801/beol>
Where { 
    BIND(<http://rdfh.ch/projects/yTerZGyxjZVqFMNNKXCDPF/mappings/BEOLMeditationesLayer3> as ?mapping) 
    ?mapping ?p ?o .
    
    OPTIONAL {
        ?mapping knora-base:hasMappingElement ?mEle .
        ?mEle ?pp ?oo .
        
        ?oo ?ppp ?ooo .
    }
}
```

The mapping is included in the project data. When we transfer data, we just copy the Turtle file:

`curl -X GET -H "Accept:application/x-turtle" "http://localhost:7200/repositories/knora-test/rdf-graphs/service?graph=http://www.knora.org/data/0801/beol" > beol-data.ttl`

If your mapping has a default XSL transformation, do not forget to copy the file from Sipi's server dir.

We do the same with lists.

**Comment by tobiasschweizer** [comment]
Actually, I use dumps as snapshots when I have an import job consisting of different parts.

**Comment by gfoo** [comment]
Ok, thanks for the query, I'm going to test that.

**Comment by gfoo** [comment]
OK, it works with a @loicjaouen's fix (missing `OPTIONAL`):
```sparql
PREFIX knora-base: <http://www.knora.org/ontology/knora-base#>
Construct {
    ?mapping ?p ?o .
    ?mapping knora-base:hasMappingElement ?mEle .
    ?mEle ?pp ?oo .
    ?oo ?ppp ?ooo .
}
FROM <http://www.knora.org/data/0113/lumieres-lausanne>
Where {
    BIND(<http://rdfh.ch/projects/0113/mappings/manuscript-mapping> as ?mapping)
    ?mapping ?p ?o .

    OPTIONAL {
        ?mapping knora-base:hasMappingElement ?mEle .
    	OPTIONAL {
        	?mEle ?pp ?oo .
    		OPTIONAL {
        		?oo ?ppp ?ooo .
            }
        }
    }
}
```
Thanks.
