### ISSUE TITLE
Should we add knora-base:createdBy?

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#1216]
A resource currently records its owner, `knora-base:attachedToUser`, but I guess we'll want to make it possible to change the owner of a resource. That would mean that we would no longer have any record of who created the resource. That information could be useful when querying version history. Should we add `knora-base:createdBy`?

**Comment by loicjaouen** [comment]
and won't we want to change `knora-base:createdBy`?

**Comment by loicjaouen** [comment]
isn't `knora-base:attachedToUser` versioned like any other property?

Then the creator is the first owner. Only at creation time, one might want to specify a `User` that it not himself (like an import script of a project that already has information about resources and their creators).

**Comment by benjamingeer** [comment]
> isn't `knora-base:attachedToUser` versioned like any other property?

No, only Knora values (instances of `knora-base:Value`) are versioned. The metadata on the resource (`rdfs:label`, `knora-base:hasPermissions`, `knora-base:attachedToUser`, etc.) is not versioned. Properties that point to Knora values are subproperties of `knora-base:hasValue`.

**Comment by benjamingeer** [comment]
> and won't we want to change `knora-base:createdBy`?

The idea would be that you can't change it.

**Comment by loicjaouen** [comment]
thanks for explanations!

**Comment by subotic** [comment]
Isn’t the semantic of `kb:attachedToUser` the creator? We just never renamed it. So I wouldn’t mind to add `kb:createdBy` and phase out `kb:attachedToUser`.

**Comment by subotic** [comment]
maybe we need additionally `kb:owner`?

**Comment by benjamingeer** [comment]
@subotic you’re right, I had forgotten, we made `attachedToUser` the creator. So there actually is no concept of owner, and I guess it should not be possible to change `attachedToUser`?

**Comment by benjamingeer** [comment]
And in that case I think we should definitely rename it.

**Comment by subotic** [comment]
I agree, or we are going to have the same discussion in two years 😉
