### ISSUE TITLE
Forbid conflicting cardinalities

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#1228]
This shouldn't be allowed:

- property hasName
- property hasTitle subPropertyOf hasName
- property hasSubtitle subPropertyOf hasName
- class NamedThing
  - hasName maxCardinality 1
- class Text subClassOf NamedThing
  - hasTitle maxCardinality 1
  - hasSubtitle maxCardinality 1

It would result in an error if you tried to create a Text with a title and a subtitle, because that would violate hasName maxCardinality 1.

**Comment by musicEnfanthen** [comment]
So `NamedThing`'s `hasName` should then have a cardinality of 2 (i.e. 1-n)?

**Comment by benjamingeer** [comment]
Yes, then it would be OK.
