### ISSUE TITLE
Add global project filter

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#1235]
I would like to be able to set a global project filter, e.g., in the HTTP request header, and then the API should behave as if this project is the only one on the server:

- `GET /admin/users` - should only return members of the project
- `GET /v2/ontologies/metadata` - should only return the system and project ontologies
- `GET /v2/resources` - should return all the resources in the project (currently GET is not allowed on this endpoint)

These are just some queries from the top of my mind. In the case of `/v2/resources` I don't think that it should be necessary to use Gravsearch just to get some project relevant data out of Knora. It should be possible to add `GET /v2/resources` which under the hood would then run the appropriate Gravsearch query.

Use Case: project-specific GUI.

**Comment by subotic** [comment]
As further motivation, the current BEOL GUI has advanced search, which would become rather unusable with tens of projects on the same server. How should anybody know (besides @tobiasschweizer ) which ontologies belong to BEOL?

**Comment by benjamingeer** [comment]
> GET /v2/ontologies/metadata - should only return the system and project ontologies

`/v2/ontologies/metadata/PROJECT_IRI` already returns the ontologies for a project.

> It should be possible to add GET /v2/resources which under the hood would then run the appropriate Gravsearch query.

If you know which resource you want, you can already use `/v2/resources` to get it, with no need for Gravsearch. Or maybe I don't understand what you mean. Do you want `/v2/resources` to return all the resources in the project? That could be a huge amount of data. What would be the use case for that? If you wanted to export all the project's data, I think you would have to use a batch job (#1210).

> How should anybody know (besides @tobiasschweizer ) which ontologies belong to BEOL?

I think this is a user-interface issue. The GUI could display the project's ontologies separately from the others. But I think it will also be common to use shared ontologies in searches.

**Comment by benjamingeer** [comment]
It's also going to be important to search for links between data in different projects. The BEOL and Newton projects could be an example.

**Comment by benjamingeer** [comment]
I would expect the advanced search widget to group ontologies by project. The user could also have a setting in their user preferences, where they could select which projects' ontologies (and which shared ontologies) they want to use in the advanced search.

**Comment by subotic** [comment]
>> GET /v2/ontologies/metadata - should only return the system and project ontologies
>
> /v2/ontologies/metadata/PROJECT_IRI already returns the ontologies for a project.

So yes, I guess I could run two queries:

- `GET /v2/ontologies/metadata/http%3A%2F%2Frdfh.ch%2Fprojects%2FyTerZGyxjZVqFMNNKXCDPF`
- `GET /v2/ontologies/metadata/http%3A%2F%2Fwww.knora.org%2Fontology%2Fknora-base%23SystemProject`

And then merge those two together. Still, it would be nice, if I could only run one query.

> Do you want `/v2/resources` to return all the resources in the project?

Yes. Since there could be potentially a few thousand resources, this route could return only the IRIs. I guess some kind of paging would also be necessary/helpfull. The client can then fetch the data as it needs to be displayed.

**Comment by subotic** [comment]
While the multiproject linking features can be interessting in the future for some projects, I don't know of any project currently in the pipeline to be added to the DaSCH which would require it.

Let me be optimistic, and say that 99% of the projects we need to get into the DaSCH are standalone, and only care about their own data. As such, the API should make the life of those projects easier and allow easy access to their data so that it can be presented in a project specific GUI.

Probably only the Salsah/Kuirl/SUID GUI is going to be multi-project enabled. All others are going to be oriented towards a single-project.

**Comment by benjamingeer** [comment]
> Still, it would be nice, if I could only run one query.

I could add an option to include the system ontologies, `?includeSystem=true`.

> While the multi-project linking features can be interesting in the future for some projects, I don't know of any project currently in the pipeline to be added to the DaSCH which would require it.

Data reuse is the core mission of the DaSCH, and data reuse **requires** links between projects.

> Let me be optimistic, and say that 99% of the projects we need to get into the DaSCH are standalone projects, and only care about their own data.

If that's true, the DaSCH has no reason to exist. There is no reason to put all those projects in one repository unless they're going to be linked together. They could all be kept in separate silos instead.

> Since there could be potentially a few thousand resources, this route could return only the IRIs. 

There could be hundreds of thousands or millions of resources in a project. I just don't see why anyone would ever want to do this. Have any users requested this feature? How would it help anyone in their research?

**Comment by benjamingeer** [comment]
The weirdest thing about requesting "all the resources in a project" is that they would be returned in an arbitrary order. Why would anyone want to scroll through hundreds of pages of random resources? I don't see how this would be useful.

**Comment by benjamingeer** [comment]
Let's talk about this more on Monday in Basel.

**Comment by tobiasschweizer** [comment]
> I think this is a user-interface issue. The GUI could display the project's ontologies separately from the others. 

Yes, we intend to do this for the BEOL GUI in the extended search widget.

**Comment by benjamingeer** [comment]
After discussion with @subotic:

* The use case is a spreadsheet-like GUI that allows data entry into a table, with one table per resource class.
* In addition to the project IRI HTTP header, the `/v2/resources` route should take `resourceClass` and `orderBy` parameters and run a Gravsearch query that gets all the resources of that class, ordered by the value of the specified property.
