### ISSUE TITLE
healthy end point message typo

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#1243]
is there a prize for one letter fix? 🤡 
https://github.com/dhlab-basel/Knora/blob/4fcda61f6dc667f5950b15bb7a6536bd503a9565/webapi/src/main/scala/org/knora/webapi/routing/HealthRoute.scala#L103

**Comment by benjamingeer** [comment]
I think we have a winner!😄

**Comment by gfoo** [comment]
I think the price could be a t-shirt, but it's better to do it ourselves, right?
To make sure that Knora is written correctly at least :) https://www.amazon.fr/Teeburon-love-Nora-T-Shirt-Femme/dp/B076X6YJ64

**Comment by tobiasschweizer** [comment]
Heathy?

**Comment by gfoo** [comment]
Hea**l**thy

**Comment by benjamingeer** [comment]
> better to do it ourselves, right?

OK, I'll put it on my TODO list. 👕

**Comment by tobiasschweizer** [comment]
Haha, now I got it ;-) I was confused about the typo in the health route and did not get that this issue was just about it.
