### ISSUE TITLE
New IRI for ForbiddenResource

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#1249]
Is that normal to get `http://rdfh.ch/0000/forbiddenResource` as IRI for a `ForbiddenResource`?
I didn't find any mentions in the doc and/or release notes but I was used to have the IRI `http://rdfh.ch/permissions/forbiddenResource`.
And also is there a migration to do?

Related to #1185

**Comment by benjamingeer** [comment]
Yes, resource IRIs must be in that format (they must have a project code). That's why the IRI of `forbiddenResource` was changed in https://github.com/dhlab-basel/Knora/pull/1185/files#diff-c74dd69a9fe43c85558a51a76a2669e2L51. You need to reload `system-data.ttl` if you haven't done so since then.

**Comment by gfoo** [comment]
ok, thanks. With @loicjaouen we will test that tomorrow, we probably have to fix our v6 prod server by reloading `system-data.ttl`

**Comment by gfoo** [comment]
Log of `GET https://knora-nv.unil.ch/v1/search/?searchtype=extended&show_nrows=25&start_at=0`
```json
{"status":4,"error":"org.knora.webapi.InconsistentTriplestoreDataException: Invalid resource IRI: http://rdfh.ch/permissions/forbiddenResource"}
```

**Comment by benjamingeer** [comment]
Sorry for not mentioning it in the release notes. Now we have a system for updating production data, updates should be easier from now on:

https://github.com/dhlab-basel/Knora/tree/develop/upgrade

**Comment by loicjaouen** [comment]
sorry @gfoo , I didn't realize what it was about... without reloading `system-data.ttl` (meaning bringing down the server, making backup, etc) we can add the RDF:
```sql
<http://rdfh.ch/0000/forbiddenResource> a knora-base:ForbiddenResource ;

                      rdfs:label "This resource is a proxy for a resource you are not allowed to see (may depend on the context: query path)" ;

                      knora-base:isDeleted false ;

                      knora-base:attachedToUser <http://rdfh.ch/users/root> ;

                      knora-base:attachedToProject knora-base:SystemProject ;

                      knora-base:creationDate "2017-10-06T11:05:37Z"^^xsd:dateTimeStamp ;

knora-base:hasPermissions "CR knora-base:Creator|M knora-base:ProjectMember|V knora-base:KnownUser|V knora-base:UnknownUser" .
```

**Comment by loicjaouen** [comment]
but we will test first of course

**Comment by benjamingeer** [comment]
> we can add the RDF

Yes, that should work, too.

**Comment by gfoo** [comment]
The `xsd:dateTimeStamp` is not correct?
@loicjaouen not sure you have the last version: https://github.com/dhlab-basel/Knora/blob/develop/webapi/_test_data/all_data/system-data.ttl

**Comment by loicjaouen** [comment]
@gfoo  thanks, you are right

**Comment by gfoo** [comment]
Friday housekeeping.
