### ISSUE TITLE
gRPC the new old kid on the block

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#1250]
Maybe something to think about. API endpoints are described in a strongly typed IDL and then  compiled into 10+ languages for server and client side code. Basically client libraries for free and allways documented APIs.

-  https://grpc.io/
- https://developer.lightbend.com/docs/akka-grpc/current/overview.html

**Comment by gfoo** [comment]
Even if I personally prefer a ready-to-use client library, a go between could be GraphQL? 
My first question was "finally, what is the difference between GraphQL and SPARQL?" and I found this [post](https://stackoverflow.com/questions/50063202/what-is-the-difference-between-graphql-and-sparql).

**Comment by loicjaouen** [comment]
graphql was mentionned in #533

protobuf requires an additional build step: from IDL description of the service, protobuf's compiler builds the serializer/deserializer libraries that you can use in your application. It is efficient for well structured data where serializing is key (in a previous life, I used it for time series, a timestamp, a string, four floats). I am not sure the complex nature of our data gain much from it. And it used to not play well with JS, but I see they changed that.

**Comment by subotic** [comment]
I don't think that we are going to implement GraphQL now that we have Gravsearch. We could try to implement GraphQL by using Gravsearch, but I don't know how much would be gained. @benjamingeer and @tobiasschweizer are more knowledgable regarding this topic.

The main advantage I see with gRPC would be the generated client libraries. We have started building a generic client library for [JS](https://github.com/dhlab-basel/knora-api-js-lib). It will take some time tough and will need to be maintained. Additionally, with [knora-py](https://github.com/dhlab-basel/knora-py) we have the same problem, where we need to implement a good portion of the client side in Python.

Implementing and maintaining client libraries is not so fun and takes a lot of work. And what about native client libraries for iOS and Android?

The architecture of Knora would allow to easily add gRPC since the current REST endpoints represent only a thin layer. We will have to see. I still need to actually try to implement something, and see how it goes.

Also, maybe this is not a question about REST or gRPC, maybe we can have both, and depending on the use case, the one or the other can be used?

I also don't think, that someone who uses our client libraries will care if the communication protocol underneath is HTTP + JSON-LD (REST) or gRPC.

At the end of the day, we have to see what is less work for us in the long run, while providing the highest benefit to clients (other computers).

**Comment by benjamingeer** [comment]
> I don't think that we are going to implement GraphQL now that we have Gravsearch.

That's right. We made Gravsearch because GraphQL didn't meet our needs.

> Implementing and maintaining client libraries is not so fun and takes a lot of work.

Having a tool that generates client libraries would be great. As long as using the tool is actually less work than writing the libraries ourselves. 😉

**Comment by tobiasschweizer** [comment]
I think some day we could use HyperGraphQL to generate Gravsearch queries. We could offer a [configuration](https://www.hypergraphql.org/documentation/) for BEOL to give it a try.

**Comment by benjamingeer** [comment]
Possible alternative: #1256
