### ISSUE TITLE
Add GraphDB distribution files to repository and integrate into CI

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#127]
We got the approval to add the GraphDB files to the repository. What I would like to do is add GraphDB-Free and GraphDB-SE WAR files to the repository, and integrate them into the build process executed on Travis-CI, so that all our tests are run against all three triplestores.

**Comment by subotic** [comment]
Ongoing work is on the [wip/graphdb-ci](https://github.com/dhlab-basel/Knora/tree/wip/graphdb-ci) branch

**Comment by benjamingeer** [comment]
Cool!

**Comment by subotic** [comment]
When this is done, the next step would be to integrate sipi, so that we can run tests on the whole infrastructure :)

**Comment by subotic** [comment]
The GraphDB distribution files are a bit to large for Github. Fortunately there is a solution in the form of [GIT-LFS](https://git-lfs.github.com), which is an open source Git extension for versioning large files, and ist supported by Github.

**Comment by subotic** [comment]
This is implemented.
