### ISSUE TITLE
Set attachedToUser on resource creation 

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#1280]
It will be very helpful for us to set the attached user IRI on resource creation (like creation/modif dates etc.).

The only solution I see is to login with the concerned user, create resource, logout. In a database migration scenario it is no really efficient.

Related to #1217

**Comment by gfoo** [comment]
Related to #1216

**Comment by gfoo** [comment]
Really need that to correctly set the permissions, if you can plan that feature for the next release, it will be great.

**Comment by benjamingeer** [comment]
OK, I will do it soon.

**Comment by gfoo** [comment]
Thanks

**Comment by benjamingeer** [comment]
Where exactly do you need this?

* In API v1 when creating a single resource?
* In API v1 in the bulk import?
* In API v2 when creating a single resource?

**Comment by gfoo** [comment]
>     * In API v2 when creating a single resource?
please

**Comment by benjamingeer** [comment]
> In API v2 when creating a single resource

OK, that's the easiest place to do it. :)

**Comment by benjamingeer** [comment]
Would it be OK to say that only the project admin or system admin can create a resource as another user? I'm a little concerned about the security implications of allowing anyone to create a resource as anyone else.

**Comment by benjamingeer** [comment]
@subotic What do you think about this:

> Would it be OK to say that only the project admin or system admin can create a resource as another user? I'm a little concerned about the security implications of allowing anyone to create a resource as anyone else.

**Comment by benjamingeer** [comment]
Talked to @subotic, we decided it will be a bit like `sudo`, with these restrictions:

* Only a project admin or system admin can create a resource as another user.
* The user chosen as the resource creator must be in the project and have permission to create resources in that project.

**Comment by gfoo** [comment]
LGTM

`have permission to create resources`: this is mainly why I want to set the user, because I have special permissions for `Creator`.

We could even say `have permission to create resource of this class`

**Comment by benjamingeer** [comment]
@gfoo OK good, I'll do it like that.
