### ISSUE TITLE
BulkImport maybe allows creation of data breaking cardinalities

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#1283]
I'm not really sure what is happening. I create the data on my computer with BulkImport and when @flavens tries to import the exported graphs, she gets errors like this:

<img width="1624" alt="55144054-4fcb6f80-5140-11e9-87df-da8cca29fbcd" src="https://user-images.githubusercontent.com/400790/55160349-68994c80-5163-11e9-8c12-aa358c30a54c.png">
<img width="2032" alt="55154788-fc641c00-5155-11e9-8467-48f2f37ab305" src="https://user-images.githubusercontent.com/400790/55160351-68994c80-5163-11e9-8ab0-2d2ae7b2cf81.png">

Maybe I'm also doing something wrong. I'm circumventing the errors by changing all cardinalities from `1` to `0-1`. When I'm to so under pressure, I will try to supply you with some data.

**Comment by subotic** [comment]
silly me, I have already a dropbox link to the data: https://www.dropbox.com/s/u6ovd2tsa0mkdh3/mls.trig-2019-03-28_001.zip?dl=1

**Comment by benjamingeer** [comment]
If the cardinalities were broken in your repository, GraphDB wouldn't have allowed the bulk import. You would have got the same error when you tried to do the bulk import on your computer.

Is it possible that you're not exporting all of the data?

**Comment by benjamingeer** [comment]
I imported your `mls.trig` file into GraphDB 8.5 without errors:

![Screen Shot 2019-03-28 at 15 15 43](https://user-images.githubusercontent.com/558389/55164702-6c7d9c80-516c-11e9-8aee-b465682cea31.png)

**Comment by flavens** [comment]
me too but now, I have other problems!

**Comment by subotic** [comment]
> I imported your `mls.trig` file into GraphDB 8.5 without errors:
> 

Then it was probably a local issue. Sorry for the noise.
