### ISSUE TITLE
Making updated ontologies human readable ? About #1263

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Knora#1288]
I have a question regarding (#1263).

Your script updates the `.ttl` for data and ontologies within GraphDB? Meaning that, if you want to modify an ontology later (which is very common from an on-going project support point of view: adding a new property to a resource class, adding a new resource class, etc.), you cannot rely anymore on the .ttl you uploaded in GraphDb in the first place.

And if you want to export the updated ontology from GraphDB, you will have a `.ttl` that can't be directly read by a human. And the same human cannot make any change to this ontology (outside GraphDB and SPARQL queries).

**From a projet-support point of view, projects (human-readable) ontologies are the corner stone of project monitoring**. The same apply to lists in .ttl in the absence of a proper admin interface. It is very difficult for me to think of a process that would not rely on a readable .ttl ontologies.

Besides, at some point, are we not also not supposed to dereference an ontology? And shouldn't that ontology be at least readable by a human? 
I also thought that human readable ontologies would be the way DaSCH documents data models (as long as we use an RDF-based infrastructure), providing a lasting documentation on research data (isn't it the point of #1253)?.

Is it possible to think of a serialization that would allow human interpretation after the ontologies have been updated?

**Comment by benjamingeer** [comment]
> And if you want to export the updated ontology from GraphDB, you will have a .ttl that can't be directly read by a human. 

You can reformat it to make it easier to read. It is just a matter of running it through a pretty-printer. There are a lot of RDF libraries that can do this. We could provide a very small script to help with this, if you like.

Knora's ontology API is also supposed to make it unnecessary to edit Turtle files by hand. Once we have an ontology editor GUI based on Knora-ui, this will be the more convenient option.

> Besides, at some point, are we not also not supposed to dereference an ontology? And shouldn't that ontology be at least readable by a human?

That functionality is [already in Knora](https://docs.knora.org/paradox/03-apis/api-v2/ontology-information.html#querying-an-ontology) (and has been there for a while).

But when Knora serves an ontology, it serves it in an [external schema](https://docs.knora.org/paradox/03-apis/api-v2/ontology-information.html#differences-between-internal-and-external-ontologies). It never serves the internal form of the ontology that's used in the triplestore (the Turtle file that you're talking about). This is a feature: you should not need to know the internal form of the ontology. Knora can serve ontologies in JSON-LD, (pretty-printed) Turtle, or RDF/XML.

Turtle is not meant to be a human-readable format for non-technical users. I don't think many users are going to want to read Turtle files, even if they're pretty-printed. To document ontologies, it would be better to present them in a user-friendly HTML format. Such documentation would be easy to generate from the JSON-LD representation of an ontology in its external form. I hope that Knora-ui will eventually provide this functionality.

**Comment by mrivoal** [comment]
Thanks for your answer.

>You can reformat it to make it easier to read. It is just a matter of running it through a pretty-printer. There are a lot of RDF libraries that can do this. 

 Could you point me one that you think/know is good? 

>We could provide a very small script to help with this, if you like.

I don't think a script will be necessary. @loicjaouen just managed to provide a rather readable turtle from a JSON-LD ontology using the complex schema. It will be fine, then. 

> Turtle is not meant to be a human-readable format for non-technical users. 

I guess I have come to be an above average human reader of Turtle :)

> To document ontologies, it would be better to present them in a user-friendly HTML format.

Right.

**Comment by benjamingeer** [comment]
> Could you point me one that you think/know is good?

I've used these:

- [rdflib](https://rdflib.readthedocs.io/en/stable/index.html) in Python
- [RDF4J Rio](http://docs.rdf4j.org/programming/#_parsing_and_writing_rdf_with_rio) in Java, also works well with Scala

They can both produce pretty-printed Turtle output.

> @loicjaouen just managed to provide a rather readable turtle from a JSON-LD ontology using the complex schema. It will be fine, then.

If you include the HTTP header `Accept: text/turtle` in your request to Knora, it will serve the ontology in Turtle format instead of JSON-LD.

> I guess I have come to be an above average human reader of Turtle :)

You have suffered so that future generations won't have to. :)

**Comment by mrivoal** [comment]
Thanks, I will have a look at the pretty-printers.
