### ISSUE TITLE
Give the admin ontology an external schema

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#1289]
For #1256, it would help to give `knora-admin` an external schema, like `knora-base` has, so that some entities that are in `knora-admin` in the triplestore can be excluded from the admin API, and other entities can be added to the API even though they're not in the triplestore.

**Comment by kilchenmann** [comment]
So, we have to change this in knora-ui as well... because the admin interface in Kuirl didn't work anymore

**Comment by benjamingeer** [comment]
This PR didn’t change the admin API in any visible way. It was only an internal refactoring. If you’re having trouble with the admin API, it’s probably not because of this PR.

**Comment by kilchenmann** [comment]
No it didn‘t change the api but the key values changed in user‘s permissions.

**Comment by benjamingeer** [comment]
The key values in permissions changed in PR #1263. Sorry, I didn’t know you were using them already.
