### ISSUE TITLE
Allow loading of test data for salsah tests over HTTP

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#129]
For tests in `webapi`, we load the test data before executing the automated tests:

```scala
private val storeManager = system.actorOf(Props(new StoreManager with LiveActorMaker), name = STORE_MANAGER_ACTOR_NAME)

    val rdfDataObjects = List(
        RdfDataObject(path = "../knora-ontologies/knora-base.ttl", name = "http://www.knora.org/ontology/knora-base"),
        RdfDataObject(path = "../knora-ontologies/knora-dc.ttl", name = "http://www.knora.org/ontology/dc"),
        RdfDataObject(path = "../knora-ontologies/salsah-gui.ttl", name = "http://www.knora.org/ontology/salsah-gui"),
        RdfDataObject(path = "_test_data/ontologies/incunabula-onto.ttl", name = "http://www.knora.org/ontology/incunabula"),
        RdfDataObject(path = "_test_data/all_data/incunabula-data.ttl", name = "http://www.knora.org/data/incunabula"),
        RdfDataObject(path = "_test_data/ontologies/images-demo-onto.ttl", name = "http://www.knora.org/ontology/images"),
        RdfDataObject(path = "_test_data/demo_data/images-demo-data.ttl", name = "http://www.knora.org/data/images")
    )

...

"Load test data" in {
        storeManager ! ResetTriplestoreContent(rdfDataObjects)
        expectMsg(300.seconds, ResetTriplestoreContentACK())
    }

```

How could we do the same for the tests in Knora `salsah`? One of the problems is that `org.knora.webapi` is not accessible from the project `salsah`.

I just want to load the test data before running the Selenium tests defined in `salsah` because some of them will modify data.

**Comment by subotic** [comment]
I propose to add a route to ```webapi```, which can receive a list of ttl files to load. Should behave much like the code we use in our tests:

```
"Load test data " in {
        storeManager ! ResetTriplestoreContent(rdfDataObjects)
        expectMsg(300.seconds, ResetTriplestoreContentACK())
    }
```

Basically to allow sending ```ResetTripleStoreContent(rdfObjects)``` to the ```StoreManager``` over http.

I would also propose to add a flag, that will need to be set when starting the ```webapi``` server, since this is a destructive operation, which should not be activated per default.

**Comment by tobiasschweizer** [comment]
The proposal with the route sounds good.

Would you like to add this route?

**Comment by subotic** [comment]
Jup, I will do it as soon as I can :)

**Comment by subotic** [comment]
Work in progress branch: https://github.com/dhlab-basel/Knora/tree/wip/ibs_data_reload_over_http

**Comment by tobiasschweizer** [comment]
Great!
