### ISSUE TITLE
Richtext and line feed in bulk-import

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#1294]
I have some text with new line (`\n`) in it. Here is how it looks like in the bulk-import XML:

```
<p0807-mls:hasArticleText knoraType="richtext_value">Zwick, Johannes

geboren um 1496 Konstanz,gestorben 23.10.1542 Bischofszell, aus Konstanz. Sohn des Konrad, Ratsherrn, und der Margreth (Nachname unbekannt). ∞ 1522 Anna (Nachname unsicher). Stud. in Freiburg i.Br. bei Ulrich Zasius und in Bologna, 1518 Priesterweihe, 1520 Dr. iur., 1521-22 Prof. der Rechtswissenschaft an der Univ. Basel, 1522 Pfarrer in Riedlingen (Oberschwaben). Nach seiner Absetzung 1525 wandte sich Z. nach Konstanz, wo er mit Ambrosius und Thomas Blarer und in engem Kontakt mit den schweiz. Theologen die reformator. Errungenschaften konsolidierte und die Stadt zu einem Zentrum der oberdt.-schweiz. Reformation machte. Z. profilierte sich dabei insbesondere als Verfasser von Katechismen, Gebets- und Gesangsbüchern sowie Trost- und Erbauungsschriften.


Literatur
– B. Moeller, Johannes Z. und die Reformation in Konstanz, 1961

Autorin/Autor: Christian Moser</p0807-mls:hasArticleText>
```

Question, do I need to convert the `\n` characters to `</br>` or should this happen through Knora?

**Comment by benjamingeer** [comment]
I believe that all the whitespace in the XML document is preserved in the string that we store in the triplestore.

**Comment by subotic** [comment]
> I believe that all the whitespace in the XML document is preserved in the string that we store in the triplestore.

What about new line `\n` characters? It looks like they are only escaped.

How do we define "richtext" exactly? Is it text with HTML tags? The documentation is not very clear on this point.

It would be very helpful to know what Knora expects so that we know which value-type to use for which types of data and if conversion needs to happen before the data is imported.

**Comment by benjamingeer** [comment]
> What about new line `\n` characters? It looks like they are only escaped.

Oops, that's a bug, introduced by me here:

https://github.com/dhlab-basel/Knora/pull/1276/files#diff-4fcd2a24123e105dc65d5b7c68264d26R830

Fixed in #1296.

> How do we define "richtext" exactly? Is it text with HTML tags?

Rich text means text with optional standoff markup. In the old SALSAH, there were separate value types for plain text (without markup) and rich text (with markup). In Knora, all text values support standoff markup, and API v1 uses the same terminology as the old SALSAH API, so all text values in API v1 are called "richtext".

**Comment by subotic** [comment]
So, newlines are stored as newlines and everything else, e.g., bold, italic, etc. can be optionally added as standoff?

What about the different "newline" variants on the different platforms. Is there some harmonization applied?

Here is a list of what is used by which OS [(SO)](https://stackoverflow.com/questions/3720612/what-is-the-universal-newline-for-all-operating-systems-lf-and-cr):
- For Windows, it is CRLF
- For UNIX, it is LF
- For MAC (up through version 9) it was CR
- For MAC OS X, it is LF

Just to be sure that I understand it correctly, for a richtext value to be rendered correctly in the browser, the GUI needs to replace the newlines with `</br>`?

**Comment by subotic** [comment]
Talked to @tobiasschweizer. Now it is more clear. I need to create a standoff mapping for LF so that the Web GUI will receive HTML.

**Comment by benjamingeer** [comment]
Knora doesn't consider newlines to be markup. They're just whitespace, which is just represented as Unicode characters in the string contents of the a `TextValue` in the triplestore. We don't allow CR, only LF.
