### ISSUE TITLE
Get AdministrativePermission informations

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#1295]
Is there a way with the Knora API to get the `AdministrativePermission` of a class? 
(don't know if the doc is up to date? https://docs.knora.org/paradox/03-apis/api-admin/permissions.html) 

My use case is for a connected user, how to know if it can create a resource of a particular class?  (basically show or not a create button)

(Of course I can hardcode that in the app knowing the permissions.ttl of the project's ontology)

**Comment by subotic** [comment]
This information should be part of the user information:

```
"permissions": {
        "groupsPerProject": {},
        "administrativePermissionsPerProject": {}
      }
```

but is always returned empty. It probably makes sense, to return it for the logged in user.

Currently, there is no route for accessing `AdministrativePermissions` but it will come. But even then, it won't do you any good, as this route will probably require `ProjectAdmin` permissions, which a normal user does not have. The GUI can only access the API as the currently logged in user.

**Comment by gfoo** [comment]
I think you can close this issue now, `administrativePermissionsPerProject` is filled.

**Comment by subotic** [comment]
thanks for the feedback.
