### ISSUE TITLE
Userdata includes the user's password hash

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#13]
When `authenticator.getUserProfileV1` returns a `UserProfileV1`, that object includes a `UserDataV1` containing a hash of the user's password. This hash can easily end up being returned to the client in an API response. Can we remove it from `UserDataV1`?

**Comment by subotic** [comment]
In 0e900a2eddf6974beb0c9d41e861fc67431ebbb4 I have changed the Authenticator trait so that the UserProfileV1 returned to the responders does not contain any sensitive information (token, password).
