### ISSUE TITLE
Issue when loading BEOL data

### ISSUE THREAD

**Issue by flavens** [dhlab-basel/Knora#1300]
Get a malformed document when loading webern data that blocks the update of the Lucene index:

<img width="1029" alt="Screen Shot 2019-04-11 at 10 39 32" src="https://user-images.githubusercontent.com/29532462/55946783-94313200-5c4d-11e9-8fb4-ea5702cf5bbd.png">

**Comment by benjamingeer** [comment]
The error in the screenshot occurs on loading the BEOL data, but I can't reproduce it.

**Comment by benjamingeer** [comment]
Using the Knora `develop` branch:

![Screen Shot 2019-04-11 at 11 58 51](https://user-images.githubusercontent.com/558389/55948637-3f8fb600-5c51-11e9-82f5-cec6294d4909.png)

**Comment by flavens** [comment]
back to normal with the new BEOL data
@benjamingeer thanks for helping

**Comment by benjamingeer** [comment]
No problem!
