### ISSUE TITLE
Gravsearch query error (TriplestoreConnectionException)

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#1309]
I get this errror `"org.knora.webapi.TriplestoreConnectionException: Failed to connect to triplestore"` with this following query:
```sparql

PREFIX knora-api: <http://api.knora.org/ontology/knora-api/simple/v2#>
PREFIX onto: <http://0.0.0.0:3333/ontology/0113/lumieres-lausanne/simple/v2#>

CONSTRUCT {
  ?Person knora-api:isMainResource true .
  ?Person onto:hasOldId ?hasOldId .
?Person onto:hasNote ?hasNote .
?hasNote onto:hasDiffusionType ?hasDiffusionType_hasNote .
?Person onto:isInCollection ?isInCollection .

?Person onto:isInProject ?isInProject .

?Person onto:isApproximateBeginDate ?isApproximateBeginDate .
?Person onto:isApproximateEndDate ?isApproximateEndDate .
?Person onto:hasName ?hasName .
?Person onto:noticeIsValid ?noticeIsValid .
?Person onto:isModern ?isModern .
?Person onto:mayHaveBiography ?mayHaveBiography .
?Person onto:noticeIsCreated ?noticeIsCreated .
?Person onto:personHasDate ?personHasDate .
?Person onto:hasPlaceBirth ?hasPlaceBirth .
?Person onto:hasPlaceDeath ?hasPlaceDeath .
?Person onto:hasReligion ?hasReligion .
?Person onto:hasPlaceOrigin ?hasPlaceOrigin .
?Person onto:hasNationality ?hasNationality .
?Person onto:hasCivilStatus ?hasCivilStatus .
?Person onto:hasBiography ?hasBiography .
?Person onto:hasCommentWork ?hasCommentWork .
?Person onto:hasPosition ?hasPosition .
?Person onto:isInSociety ?isInSociety .

?Person onto:hasRelationship ?hasRelationship .

?isRelationshipTarget_incoming onto:isRelationshipTarget ?Person .

?Person onto:isInArchive ?isInArchive .
  
} WHERE {
  
  ?Person a knora-api:Resource .
  ?Person a onto:Person .
  
  OPTIONAL {
?Person onto:hasOldId ?hasOldId .
onto:hasOldId knora-api:objectType xsd:string .
?hasOldId a xsd:string .

}
OPTIONAL {
?Person onto:hasNote ?hasNote .
onto:hasNote knora-api:objectType knora-api:Resource .
?hasNote a knora-api:Resource .
?hasNote a onto:Note .
?hasNote onto:hasDiffusionType ?hasDiffusionType_hasNote .
onto:hasDiffusionType knora-api:objectType xsd:boolean .
?hasDiffusionType_hasNote a xsd:boolean .

}
OPTIONAL {
?Person onto:isInCollection ?isInCollection .
onto:isInCollection knora-api:objectType knora-api:Resource .
?isInCollection a knora-api:Resource .
?isInCollection a onto:Collection .

}
OPTIONAL {
?Person onto:isInProject ?isInProject .
onto:isInProject knora-api:objectType knora-api:Resource .
?isInProject a knora-api:Resource .
?isInProject a onto:Project .

}
OPTIONAL {
?Person onto:isApproximateBeginDate ?isApproximateBeginDate .
onto:isApproximateBeginDate knora-api:objectType xsd:boolean .
?isApproximateBeginDate a xsd:boolean .

}
OPTIONAL {
?Person onto:isApproximateEndDate ?isApproximateEndDate .
onto:isApproximateEndDate knora-api:objectType xsd:boolean .
?isApproximateEndDate a xsd:boolean .

}
?Person onto:hasName ?hasName .
onto:hasName knora-api:objectType xsd:string .
?hasName a xsd:string .

?Person onto:noticeIsValid ?noticeIsValid .
onto:noticeIsValid knora-api:objectType xsd:boolean .
?noticeIsValid a xsd:boolean .

?Person onto:isModern ?isModern .
onto:isModern knora-api:objectType xsd:boolean .
?isModern a xsd:boolean .
FILTER(?isModern = "false"^^xsd:boolean)
?Person onto:mayHaveBiography ?mayHaveBiography .
onto:mayHaveBiography knora-api:objectType xsd:boolean .
?mayHaveBiography a xsd:boolean .
FILTER(?mayHaveBiography = "true"^^xsd:boolean)
?Person onto:noticeIsCreated ?noticeIsCreated .
onto:noticeIsCreated knora-api:objectType xsd:boolean .
?noticeIsCreated a xsd:boolean .
FILTER(?noticeIsCreated = "true"^^xsd:boolean)
OPTIONAL {
?Person onto:personHasDate ?personHasDate .
onto:personHasDate knora-api:objectType knora-api:Date .
?personHasDate a knora-api:Date .

}
OPTIONAL {
?Person onto:hasPlaceBirth ?hasPlaceBirth .
onto:hasPlaceBirth knora-api:objectType xsd:string .
?hasPlaceBirth a xsd:string .

}
OPTIONAL {
?Person onto:hasPlaceDeath ?hasPlaceDeath .
onto:hasPlaceDeath knora-api:objectType xsd:string .
?hasPlaceDeath a xsd:string .

}
OPTIONAL {
?Person onto:hasReligion ?hasReligion .
onto:hasReligion knora-api:objectType xsd:string .
?hasReligion a xsd:string .

}
OPTIONAL {
?Person onto:hasPlaceOrigin ?hasPlaceOrigin .
onto:hasPlaceOrigin knora-api:objectType xsd:string .
?hasPlaceOrigin a xsd:string .

}
OPTIONAL {
?Person onto:hasNationality ?hasNationality .
onto:hasNationality knora-api:objectType xsd:string .
?hasNationality a xsd:string .

}
OPTIONAL {
?Person onto:hasCivilStatus ?hasCivilStatus .
onto:hasCivilStatus knora-api:objectType xsd:string .
?hasCivilStatus a xsd:string .

}
OPTIONAL {
?Person onto:hasBiography ?hasBiography .
onto:hasBiography knora-api:objectType xsd:string .
?hasBiography a xsd:string .

}
OPTIONAL {
?Person onto:hasCommentWork ?hasCommentWork .
onto:hasCommentWork knora-api:objectType xsd:string .
?hasCommentWork a xsd:string .

}
OPTIONAL {
?Person onto:hasPosition ?hasPosition .
onto:hasPosition knora-api:objectType knora-api:Resource .
?hasPosition a knora-api:Resource .
?hasPosition a onto:Position .

}
OPTIONAL {
?Person onto:isInSociety ?isInSociety .
onto:isInSociety knora-api:objectType knora-api:Resource .
?isInSociety a knora-api:Resource .
?isInSociety a onto:SocietyMembership .

}
OPTIONAL {
?Person onto:hasRelationship ?hasRelationship .
onto:hasRelationship knora-api:objectType knora-api:Resource .
?hasRelationship a knora-api:Resource .
?hasRelationship a onto:Relationship .

}
OPTIONAL {
?isRelationshipTarget_incoming onto:isRelationshipTarget ?Person .
onto:isRelationshipTarget knora-api:objectType knora-api:Resource .
?isRelationshipTarget_incoming a knora-api:Resource .
?isRelationshipTarget_incoming a onto:Relationship .

}

OPTIONAL {
?Person onto:isInArchive ?isInArchive .
onto:isInArchive knora-api:objectType xsd:string .
?isInArchive a xsd:string .

}
  

}
ORDER BY ASC(?hasName)
 OFFSET 0
```

1/ by monitoring graphdb, I catched the corresponding sparql query to replay it and it works (took 13s to get results)

2/ it works if I remove just one property constraint from the `WHERE` part of the query, for example: `isRelationshipTarget_incoming` (link) or `isInArchive` (richtext) or `hasPosition` (link) but not with `hasCommentWork`  (richtext) or many others string constraints, very weird! 

Is there any special configurations in Knora or in graphdb? (similar to #1293)

Difficult to reproduce, it really depends of the repository content/size. I could maybe provide to you the full dump of my repos?

**Comment by benjamingeer** [comment]
If I‘m not mistaken, the error happens simply because your query takes too long, and Knora‘s timeout is exceeded. You could always increase the timeout, but will your users really be happy to wait 13 seconds to get the result?

In general, SPARQL queries with a lot of `OPTIONAL` blocks can be slow.

It looks like you are trying to get a complete list of all the `Person` resources in the triplestore, and display the entire contents of every resource, as well as the contents of other resources that each `Person` may be connected to. Why do you want to do that? Do you really need to retrieve all this data all at once? Could you get less data at first, and then get more if the user is really interested?

For example, do you want to display a list of `Person` resources so that the user can choose one and do something with it? If so, why just get each the name and birthdate of each `Person`, and then let the user click on the one they‘re interested in if they want more details?

See also my answer to your question in #1303:

https://github.com/dhlab-basel/Knora/issues/1303#issuecomment-482515047 

By the way, I you shouldn’t need type annotations like this:

```
onto:hasNote knora-api:objectType knora-api:Resource .
?hasNote a knora-api:Resource .
?hasNote a onto:Note .
```

Gravsearch should infer the type of `?hasNote` from the definition of the property `onto:hasNote`, which it gets from your ontology.

**Comment by gfoo** [comment]
> If I‘m not mistaken, the error happens simply because your query takes too long, and Knora‘s timeout is exceeded. You could always increase the timeout, but will your users really be happy to wait 13 seconds to get the result?
> 

Of course not :) But if I ignore that data are in a triplestore, just taking to an API, I'm *just* asking for 25 Persons (a page) with many properties, mainly strings, it is not so complicated ;-) But anyway I agree with you, see below. (I'm still making to much analogies in my mind with SQL...)

> In general, SPARQL queries with a lot of `OPTIONAL` blocks can be slow.

didn't find other solution for cardinalities `min === 0` or `max === 1` etc.
(I will probably move to `v2/resources/IRI` to let Knora manage that effeciently...)

> 
> It looks like you are trying to get a complete list of all the `Person` resources in the triplestore, and display the entire contents of every resource, as well as the contents of other resources that each `Person` may be connected to. Why do you want to do that? Do you really need to retrieve all this data all at once? Could you get less data at first, and then get more if the user is really interested?
> 

In this case, I don't need all the properties, this a list, I just print out the name, birth dates...

> For example, do you want to display a list of `Person` resources so that the user can choose one and do something with it? If so, why just get each the name and birthdate of each `Person`, and then let the user click on the one they‘re interested in if they want more details?
> 
> See also my answer to your question in #1303:
> 
> [#1303 (comment)](https://github.com/dhlab-basel/Knora/issues/1303#issuecomment-482515047)
> 

Yep, my mistake is to not have different queries for different pages talking about the same type of resource, I would not maintain too much different queries... I will rework that.
And I should also use `v2/resources/IRI` instead of gravsearch to finally get all data of a resource when I need it.

> By the way, you shouldn’t need type annotations like this:
> 
> ```
> onto:hasNote knora-api:objectType knora-api:Resource .
> ?hasNote a knora-api:Resource .
> ?hasNote a onto:Note .
> ```
> 

yep, I know, never took time to cleanup my queries created before the inference implem!

> Gravsearch should infer the type of `?hasNote` from the definition of the property `onto:hasNote`, which it gets from your ontology.

Thanks for the help.

**Comment by benjamingeer** [comment]
> (I'm still making to much analogies in my mind with SQL...)

The way I imagine it is that a triplestore has only one table, with three columns: Subject, Predicate, and Object. So it doesn’t actually store a resource as a thing with properties; it only stores separate triples that happen to have the same subject. This means that the triplestore often has to do more work (e.g. a JOIN) than you might expect. In general, having fewer criteria in your WHERE clause makes less work for the triplestore.

> didn't find other solution for cardinalities min === 0 or max === 1 etc.
> (I will probably move to v2/resources/IRI to let Knora manage that effeciently...)

That should be more efficient.

> Yep, my mistake is to not have different queries for different pages talking about the same type of resource, I would not maintain too much different queries... I will rework that.

One possibility would be to generate the queries from a template, using template parameters to specify which properties you want.
