### ISSUE TITLE
Handle Image Upload from the Salsah GUI

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#131]
- resource add
- change the representation of an existing resource

**Comment by tobiasschweizer** [comment]
When changing a file value, the following response is sent back:

```
{"changedFilesValues": [{

"value": {
                                    "originalFilename": "geer.jpg",
                                    "dimX": 128,
                                    "internalMimeType": "image / jpeg ","
                                    qualityName ":null,"
                                    qualityLevel ":10,"
                                    dimY ":128,"
                                    internalFilename ":"
                                    F9FCBPwgku1 - CcULIJmnRoZ.jpg ",
                                    "originalMimeType": null,
                                    "isPreview": true
                                }
```

This is a StillImageResprentation, but this should be converted to a LocationV1 so the SIPI URL can be updated in the GUI be

**Comment by benjamingeer** [comment]
Fixed: https://github.com/dhlab-basel/Knora/commit/6b0ad8c18def35243d2477d21ed9ccc007b65d7a

**Comment by tobiasschweizer** [comment]
this is my boy

great

welcome to JavaScript, har har har

**Comment by benjamingeer** [comment]
You're going to have so much fun writing the SPARQL for standoff. :)

**Comment by tobiasschweizer** [comment]
SPARQL - I used to eat a lot of it when I was a child. SPARQL with sirup.
