### ISSUE TITLE
Return list node label using the list responder

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#1317]
Use the list responder to query list node labels (only for the simple schema), do not return the list node labels in the complex schema (requires a change in Knora-ui).

https://github.com/dhlab-basel/Knora-ui/pull/233 changes Knora-ui so it queries Knora's list route and caches a list.

**Comment by tobiasschweizer** [comment]
relates to #763

**Comment by tobiasschweizer** [comment]
Implementing this involves:
- remove getting list node label from `webapi/src/main/twirl/queries/sparql/v2/getResourcePropertiesAndValuesGraphDB.scala.txt`
- remove getting list node label from main query in Gravsearch
- adapt logic in `org/knora/webapi/util/ConstructResponseUtilV2.scala`: make the node label optional and request it from the list responder if information is requested in the simple schema

**Comment by tobiasschweizer** [comment]
@benjamingeer does this (https://github.com/dhlab-basel/Knora/issues/1317#issuecomment-491224981) look good to you?

**Comment by benjamingeer** [comment]
Yes, this looks OK to me. Could we also cache the lists in Knora?

**Comment by tobiasschweizer** [comment]
> Could we also cache the lists in Knora?

I implemented caching in Knora-ui core so the same list is only requested once by the GUI. If this proves not to be good enough (too much load on the triplestore), we could cache lists as well in Knora, yes.

**Comment by subotic** [comment]
> Could we also cache the lists in Knora?

yes, I don‘t see why we should not be able to.
