### ISSUE TITLE
Delete a resource

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#132]
In the SALSAH GUI, the user can click on a trash can button to delete a resource.

But we have not defined this method in the resources route yet:

```
Request URL:http://localhost:3333/v1/resources/http%3A%2F%2Fdata.knora.org%2Ffcac0fe61801
Request Method:DELETE
Status Code:405 Method Not Allowed
Remote Address:127.0.0.1:3333
```

Can we just add this method to the route and mark the resource in question as deleted (sufficient permissions provided)?

**Comment by benjamingeer** [comment]
Yes, except for the word 'just'. :)

When a resource is marked as deleted, should all of its values also be marked as deleted?

If so, and if one of those values is a text value containing standoff, should the standoff be marked as deleted? In the new standoff design, standoff tags are resources containing values, so when we mark standoff resources as deleted, we'll have to mark those values as deleted, too.

We also need to do cardinality checks before marking things as deleted (from #53).

If we have to mark multiple resources and/or values as deleted in one API operation, we may need to do so in a single triplestore transaction to ensure that we don't violate consistency constraints.

So this all needs a bit of design.

**Comment by tobiasschweizer** [comment]
I see :-)

**Comment by benjamingeer** [comment]
If someone has annotated a standoff resource by linking to its IRI, we would have to worry about the cardinality constraints on the annotation. We could eliminate this problem if we allowed annotations on standoff only using UUIDs, which are not involved in constraint checking. Possibly this could be done using constraints in `knora-base`.

**Comment by benjamingeer** [comment]
Use case: a standoff tag indicates that some text is a transcription of a region in an image. Therefore the standoff tag points to the region resource. What happens if the region resource is deleted? Will this violate the consistency constraint on the standoff tag?

Similarly: a standoff tag says that some text is derived from some other text value in some other resource, e.g. it's a critical text based on a transcription. What happens if the transcription is deleted? Will this violate the consistency constraint on the standoff tag?

Solution: if a resource class has a constraint requiring a property pointing to an X, and it points to an X that's marked as deleted, that's OK.

**Comment by benjamingeer** [comment]
This will be easier now because standoff tags are not going to be resources.

When a resource is marked as deleted, @lrosenth says there's no need to mark all its values as deleted.

**Comment by benjamingeer** [comment]
Currently when we mark a value as deleted, we make a new version of the value. This introduces some redundancy, and I believe the reason for it was to make the code simpler. After looking at the code again, I don't think it actually makes a big difference, so I'd rather change it to mark the existing version of the value as deleted. So we have three cases:

* Delete a link
    * Already handled by `deleteLink.scala.txt`
* Delete a text value
    * Add `isDeleted true` and `deleteDate` to the existing value
    * Update links for resource references
* Delete any other value
    * Just add `isDeleted true` and `deleteDate` to the existing value

Work in progress is on `wip/delete-value`.

**Comment by benjamingeer** [comment]
Work in progress is on `wip/delete-value`.
