### ISSUE TITLE
Gravsearch list node constraint

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#1323]
With the dev Knora version, this query does not work anymore (it still works with 7.0.0) :
```sparql
PREFIX knora-api: <http://api.knora.org/ontology/knora-api/simple/v2#>
PREFIX ll: <http://0.0.0.0:3333/ontology/0113/lumieres-lausanne/simple/v2#>

CONSTRUCT {
  ?BibliographicNotice knora-api:isMainResource true .
} WHERE {
  
  ?BibliographicNotice a knora-api:Resource .
  ?BibliographicNotice a ll:BibliographicNotice .
  
  ?BibliographicNotice ll:hasDocumentType ?hasDocumentType .
  FILTER(?hasDocumentType = "http://rdfh.ch/lists/0113/hasDocumentType-manuscrit")

}
```
```json
{
    "knora-api:error": "org.knora.webapi.GravsearchException: One or more entities have inconsistent types: <http://0.0.0.0:3333/ontology/0113/lumieres-lausanne/simple/v2#hasDocumentType> knora-api:objectType <http://api.knora.org/ontology/knora-api/simple/v2#ListNode> ; knora-api:objectType <http://www.w3.org/2001/XMLSchema#string> . ?hasDocumentType rdf:type <http://www.w3.org/2001/XMLSchema#string> ; rdf:type <http://api.knora.org/ontology/knora-api/simple/v2#ListNode> .",
    "@context": {
        "knora-api": "http://api.knora.org/ontology/knora-api/v2#"
    }
}
```
Is that due to #1314? To fix it, do I have to wait for #1318?
Or do I have to move all my queries to the complex shcema to filter list nodes on their IRIs as mentioned in the [documentation](https://github.com/dhlab-basel/Knora/blob/develop/docs/src/paradox/03-apis/api-v2/query-language.md#searching-for-a-list-value-referring-to-a-particular-list-node)?

**Comment by tobiasschweizer** [comment]
The literal has to be of type `ListNode`, see `org/knora/webapi/e2e/v2/SearchRouteV2R2RSpec.scala`:

```
               """sparql
                  |PREFIX knora-api: <http://api.knora.org/ontology/knora-api/simple/v2#>
                  |PREFIX anything: <http://0.0.0.0:3333/ontology/0001/anything/simple/v2#>
                  |
                  |CONSTRUCT {
                  |
                  |?mainRes knora-api:isMainResource true .
                  |
                  |?mainRes anything:hasListItem ?propVal0 .
                  |
                  |} WHERE {
                  |
                  |?mainRes anything:hasListItem ?propVal0 .
                  |
                  |FILTER(?propVal0 = "Tree list node 02"^^knora-api:ListNode)
                  |
                  |}
                  |
                  |OFFSET 0
```

**Comment by tobiasschweizer** [comment]
@gfoo If it works for you, could you close the issue? Thanks!

**Comment by gfoo** [comment]
did you implement the `!=`operator? I have this error for `FILTER(?hasDocumentType != "http://rdfh.ch/lists/0113/hasDocumentType-manuscrit"^^knora-api:ListNode)`:

```json
{
    "knora-api:error": "org.knora.webapi.GravsearchException: Invalid operator '!=' in expression (allowed operators in this context are '=')",
    "@context": {
        "knora-api": "http://api.knora.org/ontology/knora-api/v2#"
    }
}
```

**Comment by gfoo** [comment]
And anyway I'm not sure that we are talking about the same thing?
`Tree list node 02` is the label value, I would like to filter on IRI value, is that possible in simple schema?

**Comment by tobiasschweizer** [comment]
> I would like to filter on IRI value, is that possible in simple schema?

In order to do that, you have to use the complex schema. There you can also use `FILTER NOT EXISTS`.

> did you implement the != operator?

No, this is not implemented in the simple schema because we cannot handle the languages correctly yet, see #1318

**Comment by gfoo** [comment]
So either:
- I continue to use simple schema but with `FILTER` on *node labels* (assuming they are unique)
- or I migrate my queries to the complex schema, that is, change all my `FILTER` and so on ([doc](https://github.com/dhlab-basel/Knora/blob/develop/docs/src/paradox/03-apis/api-v2/query-language.md#filtering-on-values-in-the-complex-schema))

**Comment by gfoo** [comment]
But I cannot use `!=` with FILTER on node labels ... so I have no choice, I must use complex schema :-|

**Comment by benjamingeer** [comment]
The simple schema is really for Linked Open Data, for clients that want to know as a little as possible about Knora. But you're a Knora power user. :)

**Comment by tobiasschweizer** [comment]
Please note that there will be soon a new version of Knora-ui search that allows users to select a node from a list.

**Comment by gfoo** [comment]
is there a difference between these two ways to refer a list node?
```sparql
  ?hasLiteratureType knora-api:valueAsString ?hasLiteratureType_Value .
  FILTER(?hasLiteratureType_Value = "http://rdfh.ch/lists/0113/hasLiteratureType-primary")
    
  ?hasLiteratureType knora-api:listValueAsListNode <http://rdfh.ch/lists/0113/hasLiteratureType-primary>

```

**Comment by benjamingeer** [comment]
It's always bothered me that we store IRIs in `valueHasString`. Someday I would like to deprecate that. I would recommend using `listValueAsListNode` instead, it makes more sense.

**Comment by tobiasschweizer** [comment]
> It's always bothered me that we store IRIs in valueHasString

true, it's not ideal

**Comment by gfoo** [comment]
is the correct way to reverse the previous constraint on list node?

```sparql
FILTER NOT EXISTS {
  ?hasLiteratureType knora-api:listValueAsListNode <http://rdfh.ch/lists/0113/hasLiteratureType-primary>
}
```

**Comment by benjamingeer** [comment]
> is the correct way to reverse the previous constraint on list node?

That should work.

**Comment by gfoo** [comment]
I want all resources not related to the node (or its childs) `http://rdfh.ch/lists/0113/hasLiteratureType-primary`.
And it seems to work, but as you know, I'm not very comfortable with the [SPARQL doc](https://www.w3.org/TR/sparql11-query/#neg-notexists-minus) and the subtilities with `MINUS` and append `FILTER` or not...

**Comment by benjamingeer** [comment]
Yes, this is one of the more annoying parts of the SPARQL spec. I personally find `FILTER NOT EXISTS` more intuitive than `MINUS`, and in my experience it's often faster.

**Comment by gfoo** [comment]
And to keep trace for other users:
- constraint on several nodes: 
```sparql
{ ?hasLanguage knora-api:listValueAsListNode <http://rdfh.ch/lists/0113/hasLanguage-allemand> . } 
UNION  
{ ?hasLanguage knora-api:listValueAsListNode <http://rdfh.ch/lists/0113/hasLanguage-italien> . }
```
- reverse : 
```sparql
FILTER NOT EXISTS { ?hasLanguage knora-api:listValueAsListNode <http://rdfh.ch/lists/0113/hasLanguage-allemand> . } 
FILTER NOT EXISTS { ?hasLanguage knora-api:listValueAsListNode <http://rdfh.ch/lists/0113/hasLanguage-italien> . }
```

**Comment by gfoo** [comment]
successfully migrated to complex schema, thanks for your help.

**Comment by benjamingeer** [comment]
You're welcome!
