### ISSUE TITLE
Connection to Sipi fails when using vpn

### ISSUE THREAD

**Issue by SepidehAlassi** [dhlab-basel/Knora#1330]
Here are the steps to generate this issue:

1. use vpn to connect to some network (Ex. Cisco to connect to uni)
2. run sipi through knora,
`May 24 10:49:46  Sipi[36195] <Info>: Added route /test_knora_session_cookie with script ./scripts/test_knora_session_cookie.lua`
`May 24 10:49:46  Sipi[36195] <Info>: Server listening on port 1024
`
3. serve a file to sipi through knora. (Ex. import of xslt)
at this point, you will get an error "a failure to connect to Sipi" although sipi is running!
Knora Error message:
`webapi Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 0.0.0.0:1024 [/0.0.0.0] failed: Operation timed out
webapi 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
webapi 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
webapi 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
webapi 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
webapi 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
webapi 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
webapi 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
webapi 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
webapi 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
webapi 	at org.knora.webapi.store.iiif.SipiConnector.$anonfun$callSipiConvertRoute$3(SipiConnector.scala:132)
webapi 	at scala.util.Try$.apply(Try.scala:209)
webapi 	at org.knora.webapi.store.iiif.SipiConnector.callSipiConvertRoute(SipiConnector.scala:128)
webapi 	... 12 common frames omitted
webapi Caused by: java.net.ConnectException: Operation timed out
webapi 	at java.net.PlainSocketImpl.socketConnect(Native Method)
webapi 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
webapi 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:204)
webapi 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
webapi 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
webapi 	at java.net.Socket.connect(Socket.java:589)
webapi 	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
webapi 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
webapi 	... 23 common frames omitted
`
Import failure message:
`{'status': 4, 'error': 'org.knora.webapi.SipiException: Failed to connect to Sipi'}`

4. Now, disconnect the vpn, without restarting the knora or sipi, try the import again. -> all will work!

this seems like a bug to me. Although it can be something I don't understand about sipi. Can you please guide?

**Comment by subotic** [comment]
sorry, as far as I understand it, it is not a bug but a feature of VPN: https://blog.lan-tech.ca/2013/02/21/access-local-and-vpn-network-simultaneously/

**Comment by SepidehAlassi** [comment]
@subotic Achso, didn't know about this security feature. Thanks!

**Comment by loicjaouen** [comment]
I am just curious about this, and it doesn't make sense to me ;)

connecting to `0.0.0.0:1024` should work wether a vpn is used or not! `0.0.0.0` is localhost and should be kept out of reach of a vpn .

for me it is a cisco bug :)

Now port 1024 is not a random port, it is the first of the [registered ports](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers#Registered_ports), many applications scan them and use the first unused one. VPN tasks is to mess with ports and they do well, so if they grab one, it is hard to detect. 

So my guess is that, if you make sure that the vpn process is killed, you first start sipi and then start the vpn, everything will be fine.

**Comment by SepidehAlassi** [comment]
@loicjaouen no, even if you first start sipi, and then start vpn, the same happens.

**Comment by SepidehAlassi** [comment]
@subotic if I understand this blog post and your argument correctly, then none of the localhosts should work simultaneously to VPN network, right? However, with vpn connected, I do not have any problems with localhosts on other ports, such as 4200 or 3333.  It seems to me that this is special to port 1024. Also considering comments of @loicjaouen about this port.
I will try changing the port of sipi to see if my suspicion is right!
