### ISSUE TITLE
Allow Sipi to get permissions from Knora for a past file version

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#1331]
If you request a past version of a file value from Knora, and then request the file from Sipi, Sipi asks Knora for the file permissions. Currently, Knora won't find the file value, because it's not the current version.

**Comment by loicjaouen** [comment]
unfolding issues, thanks for taking care of it :)

**Comment by benjamingeer** [comment]
It's nice when people actually use the software so we find out where the bugs are. :)
