### ISSUE TITLE
Weird use case on resource creation with permissions

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#1334]
Let say we have a group `Test` with `AdministrativePermission - ProjectResourceCreateRestrictedPermission` on resource `Person`.

Let say we have `DefaultObjectAccessPermission` `forGroup` `Test` = `D Creator`.

By this way we want to specify that users of group `Test` can *create* and *delete* a `Person` but cannot change the permissions.

The funny fact is when a user can *create* a resource with the v2 API, he can set the permissions he wants, so bypass the default `D Creator` rules!

Is that normal?

**Comment by subotic** [comment]
@benjamingeer You implemented resource creation in V2 with the possibility to provide the permissions. Do you check beforehand to see what the permission would be, based on the defined `DefaultObjectAccessPermission`? Probably the user-supplied permission would need to be ignored if it would give the user higher permissions then set through the `DefaultObjectAccessPermission`

**Comment by benjamingeer** [comment]
> Do you check beforehand to see what the permission would be, based on the defined `DefaultObjectAccessPermission`?

The code currently gets the default permission, but doesn't use it if the user specified a custom permission:

https://github.com/dhlab-basel/Knora/blob/develop/webapi/src/main/scala/org/knora/webapi/responders/v2/ResourcesResponderV2.scala#L508

> Probably the user-supplied permission would need to be ignored if it would give the user higher permissions then set through the `DefaultObjectAccessPermission`

OK, I can do this.

**Comment by subotic** [comment]
> OK, I can do this.

Great, thanks.
