### ISSUE TITLE
Upgrade scripts

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#1336]
The upgrade scripts are named after PRs and by what they are doing.

Both informations don't tell me which one I need to run when I'm running version `x.y.z`.

For each release, it would be nice to have a list of upgrade scripts that need to be 

Alternatively, I would very much prefer, if it would be possible to only have one script that needs to be run. This script could then figure out by itself based on a version string in knora-base which of those upgrades need to be run and then do it.

I would also need to be able to package it inside a docker container and run it this way on the server.

**Comment by benjamingeer** [comment]
> For each release, it would be nice to have a list of upgrade scripts that need to be

When we make a PR, there is no way to predict which release it will be included in. This is why the names of the scripts refer to PRs, not to releases.

When we had handwritten release notes, each PR would add something to the release notes of the “next” release (which could actually be any future release, depending on when the PR was merged and when the releases were done). The result was that the release notes did list the upgrade scripts that had to be run. For example:

https://github.com/dhlab-basel/Knora/releases/tag/v6.0.0

I have been hoping that we would get a similar result with automatically generated release notes. If each PR‘s merge commit comment says which upgrade script you have to run, and the automatically generated release notes contain those comments, then the release notes should contain what you’re asking for.

> I would very much prefer, if it would be possible to only have one script that needs to be run.

I agree that this would be better, and it wouldn’t be that hard. Let me think about it a bit.

**Comment by benjamingeer** [comment]
It could work like this:

* `knora-base` has a PR number attached to it, which is the number of the last PR that included an update for Knora built-in ontologies or for changes to data.
* The upgrade directory contains a main update script, which:
  * Checks what PR number `knora-base` contains in your repository.
  * Runs all the PR-specific update scripts whose numbers are higher than that one, in ascending order.
* Each PR-specific update script updates the PR number in `knora-base` in your repository.

Each PR-specific update script would:

* Have the same name, and take the same command-line arguments.
* Be in a subdirectory whose name was just the PR number.

**Comment by subotic** [comment]
Great, sounds good to me.

So, this is how I would see it running in production:

 1. stop `api` docker container
 2. spin up and run update scripts container with optional parameter limiting the max PR number
 3. create `api` container with newer version

I can create the Dockerfile for the container, and add a test to Travis, where we basically do the following:
 - spin up GraphDB
 - load some data
 - run the update-script container
 - check somehow if it worked.

**Comment by benjamingeer** [comment]
> check somehow if it worked.

This is the question I don't have an answer for yet. How do we check the data in your repository, if we don't know what data you're supposed to have?

Maybe we would need to have some test data that everyone would have to store in their repository, which we would only use for checking if the update scripts worked properly.

**Comment by benjamingeer** [comment]
Of course, the GraphDB consistency checks would detect some problems, but there could be errors that they wouldn't notice.

**Comment by subotic** [comment]
At least for Travis, we know what data was there before and what should be there after the upgrade.

As for data in production environments, the update script could check if something needs to be done, then creates a list of what needs to be changed, and afterward checks this list if the change was performed correctly.

**Comment by benjamingeer** [comment]
> As for data in production environments, the update script could check if something needs to be done, then creates a list of what needs to be changed, and afterward checks this list if the change was performed correctly.

OK, I'll think about how to do this.

**Comment by benjamingeer** [comment]
* Refactor existing repository transformation code into a library
* Try to get rdflib to preserve Turtle prefixes

**Comment by benjamingeer** [comment]
> the update script could check if something needs to be done, then creates a list of what needs to be changed, and afterward checks this list if the change was performed correctly.

A problem with this:

Each update can change millions of statements. It would be very slow to check them in SPARQL, so they would have to be checked outside the triplestore. But since the update itself is done outside the triplestore, this wouldn't be a useful check. The transformation calculates a set of triples to be added, and saves them in a file. We could read the file back to see if it contains those triples, but this test would always succeed. What really needs to be tested is the algorithm that determines which triples should be added: did it really identify the right triples to add? That's where the bugs are most likely to be. In other words, what needs to be tested is the code that "creates a list of what needs to be changed".

**Comment by benjamingeer** [comment]
Maybe each transformation should just have some test data of its own. Then the update script could have a test mode, which would just update the test data and compare it to a known correct result.

**Comment by benjamingeer** [comment]
Actually, comparing updated test data to a known result would also be tricky, because the updated data could contain unpredictable things like randomly generated UUID.
