### ISSUE TITLE
Gravsearch ignores silently construct properties not in the where clause

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#1343]
If in the `CONSTRUCT` I ask for the `Person`'s `hasName` property but don't declare it in the `WHERE` clause, the value is removed from the result without any warning:
```sparql

PREFIX knora-api: <http://api.knora.org/ontology/knora-api/simple/v2#>
PREFIX ll: <http://0.0.0.0:3333/ontology/0113/lumieres-lausanne/simple/v2#>
CONSTRUCT {
  ?Person knora-api:isMainResource true .
  ?Person ll:hasName ?hasName .
} WHERE {
 { BIND(<http://rdfh.ch/0113/A5nRGhSNSHqtDMDSFDC2sw> AS ?Person) }
  ?Person a knora-api:Resource .
  ?Person a ll:Person .
# ?Person ll:hasName ?hasName .
}
```

**Comment by benjamingeer** [comment]
In this respect it is like SPARQL:

"If any such instantiation produces a triple containing an unbound variable or an illegal RDF construct, such as a literal in subject or predicate position, then that triple is not included in the output RDF graph."

https://www.w3.org/TR/sparql11-query/#construct

We could introduce a check for this to make it more user-friendly.

**Comment by gfoo** [comment]
oups ! didn't know that, I couldn't anyway, I never read the SPARQL specs :)
Just found that example by exploring an issue that I'm preparing. Can be closed for me.
