### ISSUE TITLE
Richtext/HTML in page anchor link

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#1346]
By considering that the standard mapping is thought as a HTML mapping, a missing feature is the management of _in page anchor_ (#something) or  `URL fragment` (see `<a>`  [specs](https://developer.mozilla.org/fr/docs/Web/HTML/Element/a)).

My use case is to import HTML data containing footnotes:
```html
<p>Texte 1<a id="ref_1_note_1" href="#note_1">[1]</a></p> 
...
<p>Texte 2<a id="ref_2_note_1" href="#note_1">[1]</a></p> 
...
<p>Texte 3<a id="ref_1_note_2" href="#note_2">[2]</a></p> 
...
<p id="note_1">1. <a href="#ref_1_note_1">a</a>, <a href="#ref_2_note_1">b</a> La note 1</p>
<p id="note_2">2. <a href="#ref_1_note_2">^</a> La note 2</p>
```

One way is to create my own standoff mapping, but then, users cannot edit anymore their HTML in Salsah (because footnotes won’t be managed by the default CKEditor and because of #908)

An other way is to:

1. Enhanced standard mapping to import these new tags:
     -  `<a id="xxxx" href="#yyyyy">` 
     -  `<p id="yyyy">` 

2. Add footnote edition tools to Salsah by adding this plugin for example: https://ckeditor.com/cke4/addon/footnotes

**To reduce devs** we could limit the footnote to a simple link between two anchors (so you couldn’t add several refs to the same note):
```html
<p>Texte 1<a id="ref_note_1" href="#note_1">[1]</a></p> 
...
<p>Texte 2<a id="ref_note_2" href="#note_2">[2]</a></p> 
...
<p>Texte 3<a id="ref_note_3" href="#note_3">[3]</a></p> 
...
<a id="note_1" href="#ref_note_1">1.</a><p>La note 1</p>
<a id="note_2" href="#ref_note_2">2.</a><p>Voir note <a href="#note_1">1</a></p>
<a id="note_3" href="#ref_note_3">3.</a><p>La note 3</p>
```

1. Enhanced standard mapping to import this new anchor tag:  `<a id="xxxx" href="#yyyyy">` 

2. Enhance `link` button to add an `id` field edition

Some feedback?

**Comment by mrivoal** [comment]
Hi @tobiasschweizer. Do you think we could discuss this issue next week with you ?

**Comment by tobiasschweizer** [comment]
We already support internal references, see https://docs.knora.org/paradox/03-apis/api-v1/xml-to-standoff-mapping.html#internal-references-in-an-xml-document

Maybe it is just missing from the standard mapping, so it would need to be added.

**Comment by gfoo** [comment]
> We already support internal references, see https://docs.knora.org/paradox/03-apis/api-v1/xml-to-standoff-mapping.html#internal-references-in-an-xml-document
> 
> Maybe it is just missing from the standard mapping, so it would need to be added.

great, I didn't know that we could add an `id` into tag elements independently of the mapping.

The default anchor mapping in Knora requires the `StandoffUriTag` type for `href` which does not support `#` links, so we could add to the standard mapping a new anchor definition (imitating salsah link anchor) :
```xml
<mappingElement>
        <tag>
            <name>a</name>
            <class>internal-link</class>
            <namespace>noNamespace</namespace>
            <separatesWords>false</separatesWords>
        </tag>
        <standoffClass>
      <classIri>http://www.knora.org/ontology/knora base#StandoffInternalReferenceTag</classIri>
        <datatype>
            <type>http://www.knora.org/ontology/knora-base#StandoffInternalReferenceTag</type>
            <attributeName>href</attributeName>
        </datatype>
        </standoffClass>
</mappingElement>
```
And I could have this kind of html to manage internal refs:
```html
<p>Texte 1<a class="internal-link" id="ref_note_1" href="#note_1">[1]</a></p> 
...
<p>Texte 2<a class="internal-link" id="ref_note_2" href="#note_2">[2]</a></p> 
...
<p>Texte 3<a class="internal-link" id="ref_note_3" href="#note_3">[3]</a></p> 
...
<a class="internal-link" id="note_1" href="#ref_note_1">1.</a><p>La note 1</p>
<a class="internal-link" id="note_2" href="#ref_note_2">2.</a><p>Voir note <a href="#note_1">1</a></p>
<a class="internal-link" id="note_3" href="#ref_note_3">3.</a><p>La note 3</p>
```

The `class="internal-link"` is a little bit annoying for me because I have to import existing standard html data like that: `<a id="ref_note_1" href="#note_1">`  into `<a class="internal-link" id="ref_note_1" href="#note_1">` which willl require a dedicated editor.

So, we still have the problem of how to add an internal-anchor with its `id` attribute in our current Salsah 1.5 version that we are using in production.

n.b. : Maybe a quick way could be to restore the source button? :)

**Comment by tobiasschweizer** [comment]
> The class="internal-link" is a little bit annoying for me because I have to import existing standard html data like that: <a id="ref_note_1" href="#note_1"> into <a class="internal-link" id="ref_note_1" href="#note_1"> which willl require a dedicated editor.

The problem is that there need to be some way of distinguishing "normal" links from internal links (two different definitions in the mapping).

In my experience, Ckeditor proved to be quite configurable (https://ckeditor.com/docs/), but I haven't worked on this for some time. Maybe @loicjaouen can help.
