### ISSUE TITLE
Deleted group still related and enable in user's reponse

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#1352]
I use `DELETE /admin/groups/<groupIri>` route to delete a temporary group related to all my users (for temporary import permissions).

Using the `GET /admin/groups/<groupIri>` route, the `status` is correctly set to `false`.

But if I ask for user's data (`GET admin/users/email/`), the group is still returned in the response (ok, could be discussed) but its `status` is `true`.

**Comment by subotic** [comment]
I think it is a  caching problem. Thanks for reporting.

**Comment by subotic** [comment]
Also, if a group is deleted, then the users should be removed from the group.

**Comment by gfoo** [comment]
also, in the list of groups returned by the `GET admin/groups`, the group's `status` seems to be `true` instead of `false`

**Comment by subotic** [comment]
This should now be fixed in PR #1368 if you would like to try it out.

**Comment by subotic** [comment]
The new behaviour is that when a group is deleted, all members are also removed from the group. As this is done in the `UsersResponder`,  this will also refresh the cache.

**Comment by gfoo** [comment]
seems to work, thanks.

But there are maybe performance considerations to take into account on real installation? With a local Knora stack having about 200 users to remove from the deleted group, I get this perf:
> webapi_1   | 2019-07-23 14:17:13 | INFO  | M-Main$ | [200] DELETE http://localhost:3333/admin/groups/http:%2F%2Frdfh.ch%2Fgroups%2F0113%2Flumieres-lausanne-import took: 149377ms

**Comment by subotic** [comment]
Yes, good point. I will have to see what is taking so long.
