### ISSUE TITLE
Add admin route to dump project data

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#1358]
Admin route, which returns all data (all ontology graphs, the data graph, project, user, permissions) for a certain project as a trig file.

**Comment by benjamingeer** [comment]
@subotic The TriG file could be very large. Should the route return the whole file over HTTP? Or should it just save it to disk somewhere on the server?

**Comment by subotic** [comment]
I would prefer to download it directly. This is how it currently works with GraphDB.

**Comment by benjamingeer** [comment]
OK.
