### ISSUE TITLE
Refactor Lucene processing in v1 and v2

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#1377]
* According to #1196, the user is supposed to be able to submit `***` as a search string and get any resource. But the [Lucene syntax documentation](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html#Wildcard%20Searches) says that you can't use `*` as the first character of a search string. For some reason, `***` seems to work anyway on GraphDB, but it doesn't work on Fuseki, which I'm trying to support again (#1375).
* Perhaps we should start using the [GraphDB Lucene Connector](http://graphdb.ontotext.com/documentation/standard/lucene-graphdb-connector.html).
* #641

**Comment by tobiasschweizer** [comment]
I think GraphDB Lucene Connector should be added in a separate PR. It does not affect the way search strings are preprocessed to make use of the Lucene syntax.
