### ISSUE TITLE
Wrong link deletion in subclass context 

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#1398]
With the following ontology, it seems that too much links of `hasAdditionalResource` type are deleted when I try to delete a link between a `Biblio` and an `Image`:
```
Biblio -- hasAdditionalResource --> AdditionalResource
Image -- subClassOf -->  AdditionalResource
```
Scenario: create a `Biblio`, create an `AdditionalResource` and link `Biblio` to it, create an `Image` and link `Biblio` to it, delete the latter link to the `Image`, the link  to the `AdditionalResource` seems to be deleted as well...

Before to go further (not very sure of my test case), may you have a look at your code?

**Comment by benjamingeer** [comment]
The code in https://github.com/dhlab-basel/Knora/blob/develop/webapi/src/main/twirl/queries/sparql/v2/deleteLink.scala.txt looks OK to me. Please do provide a test case (a small one if possible).

**Comment by gfoo** [comment]
Could it be related to the fact that `Image` is a subclass of `StillImageRepresentation` (the boring part of the test case to write :P)

**Comment by benjamingeer** [comment]
I don't think so, because class of the target resource isn't considered when deleting a link. Only its IRI is considered.

**Comment by gfoo** [comment]
ok, I try to provide a small test case.

**Comment by gfoo** [comment]
Oups, my mistake!  Deleted wrong link, and then when I deleted the `Image`, the image link was deleted automatically :)

**Comment by benjamingeer** [comment]
No worries! :)
