### ISSUE TITLE
Extend ValueUtilV1.fileValueV12LocationV1 to support file types other than images

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#14]

**Comment by tobiasschweizer** [comment]
create IIIF URLs

**Comment by tobiasschweizer** [comment]
support of text files stored in Sipi: https://github.com/dhlab-basel/Knora/commit/b0ea303bc3d4745e831e25e9464b34c5da46ea24

**Comment by tobiasschweizer** [comment]
Knora supports the creation of Representations that have a text file attached that is stored in SIpi.
