### ISSUE TITLE
Make Example Ontology and write Tests

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#140]
We should extend `webapi/_test_data/ontologies/incunabula-onto` so we can model a `incunabula:misc` in a way that it can be assigned a property of different value types.

Like this, we can test the GUI in a more systematic way.

Soon we will be able to load the test data before running the GUI test. SO we could make a set that only contains these data.

CC @benjamingeer

**Comment by benjamingeer** [comment]
Instead of extending the Incunabula ontology, I made a special ontology just for tests, in `anything-onto.ttl`. It currently has one class, `anything:Thing`, with properties covering all value types (except file values for the moment), all of which are optional.

**Comment by subotic** [comment]
cool :-)
