### ISSUE TITLE
Release Knora 2019-08

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#1404]
Released version https://github.com/dhlab-basel/Knora/releases/tag/v9.0.0

This release contains breaking changes needing data upgrade and Admin API breaking changes.

**Comment by subotic** [comment]
@flavens I had to change the version number to v9.0.0, since data needs to be upgraded.

**Comment by flavens** [comment]
@subotic ohoh... we just released a new version with the updated documentation... Knora v8.2.0 mentioned...

**Comment by kilchenmann** [comment]
@subotic We talked on Monday about new release of Knora, you created Knora v8.1.0 and we prepared everything to work with this version, which was now deleted. We don't understand. Does the new version means a breaking change? Or is it only because of the data update?

**Comment by subotic** [comment]
Yes, I thought that there where no breaking changes (data or API). Since there is a need for data upgrade, this becomes automatically a major release. As for breaking API changes, I'm not sure.

In the future, issues regarding the need for data upgrade or breaking API changes will be communicated through dedicated issues and linked to the release epic. This should help.

**Comment by subotic** [comment]
As far as I know, there is only one breaking change in the Admin-API:

- Moved /admin/groups/members/<groupIri> to /admin/groups/<groupIri>/members

**Comment by kilchenmann** [comment]
@subotic We just updated the Knora-ui modules to v9.0.0 to use Knora v9.0.0. The Kuirl app has also been released in v1.5.0. We should update the Kuirl app on the test-server asap to see if it works well. 
At the moment we're not sure with the Beol app...
