### ISSUE TITLE
Each projet should probably have an ARK so that its data(base) can be cited correctly.

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Knora#1406]
In order for a project to cite its data hosted by the DaSCH while compelling to citation guidelines, each project probably need to have an ARK identifier, and not only for each of the resources produced.

Could we provide this ?

Also, according to the [DCC](http://www.dcc.ac.uk/resources/how-guides/cite-datasets), 
> This URL should belong to a landing page that contains descriptive information about the dataset, as well as links or instructions for accessing it.

More in this on [discuss](https://discuss.dasch.swiss/t/how-should-a-projet-dataset-hosted-by-the-dasch-be-cited-ark-at-project-level-needed/86?u=mrivoal).

**Comment by benjamingeer** [comment]
This is already implemented, but it needs to be better documented.

For a project with shortcode `0001`, the project's ARK looks like this:

```
http://ark.dasch.swiss/ark:/72163/1/0001
```

You can customise the URL that this redirects to in the ARK resolver configuration; see `KnoraProjectRedirectUrl` here:

https://github.com/dhlab-basel/ark-resolver/blob/master/src/ark-registry.ini

**Comment by mrivoal** [comment]
Wonderful! Thanks.
