### ISSUE TITLE
Release Knora 2019-09

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#1409]
- Ask @benjamingeer if we have breaking changes (data or API)

**Comment by benjamingeer** [comment]
Is there an easy way to see the list of PRs that have been merged since the last release?

**Comment by subotic** [comment]
In your git client. There you should see all merged PRs.

The easiest would be to create an issue, assign it to me, and add to the monthly release epic the moment you merge a PR containing an upgrade script or breaking changes for the API. This way I will know for sure.

**Comment by benjamingeer** [comment]
> In your git client. There you should see all merged PRs.

SourceTree shows me a mess like this, and I don't see a way to filter the display to only show merged PRs:

![Screen Shot 2019-08-29 at 16 58 37](https://user-images.githubusercontent.com/558389/63951618-5c048180-ca7e-11e9-9edb-d64f50b74e42.png)

I'm looking for PRs that were merged between 8.0.0 and 9.0.0, right? The only one I see with breaking changes is #1372.

> The easiest would be to create an issue, assign it to me, and add to the monthly release epic the moment you merge a PR containing an upgrade script or breaking changes for the API. This way I will know for sure.

Will do this in future.

**Comment by subotic** [comment]
This is what I see with Tower:

<img width="619" alt="Screenshot 2019-08-29 18 08 57" src="https://user-images.githubusercontent.com/400790/63957230-4c8a3600-ca88-11e9-8990-9db5b359571e.png">

**Comment by subotic** [comment]
The upgrade script is doing upgrades for PR 1367 and PR 1372

**Comment by benjamingeer** [comment]
> The upgrade script is doing upgrades for PR 1367 and PR 1372

Yes, you're right. I'll try Tower.

**Comment by subotic** [comment]
Releasing 2019-09 milestone as `v9.1.0` since there are no `breaking` changes.
