### ISSUE TITLE
All tests pass in Travis, but build fails because it takes too long

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#1410]
We finally have so many tests that Travis won't let us run them all:

https://travis-ci.org/dhlab-basel/Knora/jobs/578410886

For this PR:

https://github.com/dhlab-basel/Knora/pull/1403

@lrosenth Can we please prioritise getting off Travis?

**Comment by subotic** [comment]
I'm waiting on github to let me in into the beta of their new CI service. 

You could add tags to tests, so that we can run them in groups. Each group could then run in a separate Travis job.

**Comment by subotic** [comment]
We have to cleanup the tests anyway, separate the E2E  from the „unit“ tests.
