### ISSUE TITLE
Re-use class for same mappingElement

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#1438]
I have to manage two kinds of `<p>` mapping:
```html
<p>blablabla</p>
<p class="verse">blablabla</p>
```
So I add to the mapping these two tags to the same standoff class `StandoffParagraphTag` and only change `<class>` attribute from `noClass` to `verse`:
```xml
<mappingElement>
        <tag>
            <name>p</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
            <separatesWords>true</separatesWords>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/standoff#StandoffParagraphTag</classIri>
        </standoffClass>
    </mappingElement>

<mappingElement>
        <tag>
            <name>p</name>
            <class>verse</class>
            <namespace>noNamespace</namespace>
            <separatesWords>true</separatesWords>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/standoff#StandoffParagraphTag</classIri>
        </standoffClass>
    </mappingElement>

```
But Knora complains about that:
```json
{"knora-api:error":"org.knora.webapi.BadRequestException: the provided mapping is invalid: cvc-identity-constraint.4.1: Duplicate unique value [http://www.knora.org/ontology/standoff#StandoffParagraphTag] declared for identity constraint \"standoffClass\" of element \"mapping\".","@context":{"knora-api":"http://api.knora.org/ontology/knora-api/v2#"}}
```
is that normal?
If yes, the simple solutino is to create a `StandoffVerseParagraphTag` subclass of `StandoffParagraphTag`?

**Comment by tobiasschweizer** [comment]
> is that normal?

It's expected behavior:

>  The relations expressed in a mapping are one-to-one relations, so the XML can be recreated from the data in RDF. 

https://docs.knora.org/paradox/03-apis/api-v1/xml-to-standoff-mapping.html#creating-a-custom-mapping

Each element can only occur once. The error you see can be detected locally by validating the mapping:

> A mapping can be validated before sending it to Knora with the following XML Schema file: webapi/src/resources/mappingXMLToStandoff.xsd.

https://docs.knora.org/paradox/03-apis/api-v1/xml-to-standoff-mapping.html#validating-a-mapping-and-sending-it-to-knora

> If yes, the simple solutino is to create a StandoffVerseParagraphTag subclass of StandoffParagraphTag?

Yes.  And also make sure you are using another XML element or use in combination with another class. What you do with "verse" seems fine.

**Comment by gfoo** [comment]
Thanks for the answer.

To be sure, also, is that mean that I cannot map for example `<p>` and `<paragraph>` tags to the same  `StandoffParagraphTag` class?

**Comment by tobiasschweizer** [comment]
> To be sure, also, is that mean that I cannot map for example <p> and <paragraph> tags to the same StandoffParagraphTag class?

`StandoffParagraphTag` can only be used once, yes.

**Comment by tobiasschweizer** [comment]
I recommend to validate the mapping locally using `webapi/src/resources/mappingXMLToStandoff.xsd`.

**Comment by gfoo** [comment]
thanks !
