### ISSUE TITLE
Encoded chars in resource label

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#1452]
I get this error when I use a string label with *hard coded encoding* `\u00e9` on resource creation:
```json
{
    "knora-api:error": "org.knora.webapi.AssertionException: Resource <http://rdfh.ch/0001/OkTyiyUIQO6ir52HWHUm3A> was saved, but it has the wrong label",
    "@context": {
        "knora-api": "http://api.knora.org/ontology/knora-api/v2#"
    }
}
```
Input:
```json
{
  "@type" : "anything:Thing",
  "knora-api:attachedToProject" : {
    "@id" : "http://rdfh.ch/projects/0001"
  },
  "rdfs:label": "Pr\u00e9sentation du projet à \"Lausanne\"",
  "@context" : {
    "rdf" : "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "knora-api" : "http://api.knora.org/ontology/knora-api/v2#",
    "rdfs" : "http://www.w3.org/2000/01/rdf-schema#",
    "xsd" : "http://www.w3.org/2001/XMLSchema#",
    "anything" : "http://0.0.0.0:3333/ontology/0001/anything/v2#"
  }
}
```
~~Of course it works with `"rdfs:label": "Présentation du projet à \"Lausanne\""`.~~ (post-edit: nop, it does not work, see @benjamingeer comments below)
Is that normal or should I cleanup the labels?

These encodings come from the usage of `json` package in my python's code:
```
>>> import json
>>> json.dumps("Présentation")
'"Pr\\u00e9sentation"'
```

**Comment by benjamingeer** [comment]
An `AssertionException` means there's a bug somewhere...

**Comment by benjamingeer** [comment]
The bug has nothing to do with the Unicode escape, which works fine. The code that checks whether the resource was saved correctly is just getting confused because it doesn't escape the quotation marks in the label. Try it with `"rdfs:label": "Pr\u00e9sentation du projet à Lausanne"`, it should work. I'll fix the error-checking bug.

**Comment by gfoo** [comment]
oups, sorry for the wrong way! 

`"rdfs:label": "Pr\u00e9sentation du projet à Lausanne"` works.

Post-edited my first message to fix my wrong test.

**Comment by benjamingeer** [comment]
No problem, thanks for the bug report. :)
