### ISSUE TITLE
Sesame/GraphDB bug affecting the import of carriage returns

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#17]
When we import RDF data containing a triple-quoted string that ends with a carriage return, the carriage return is stripped, apparently by Sesame:

https://openrdf.atlassian.net/browse/SES-425?jql=text%20~%20%22carriage%20return%22

https://openrdf.atlassian.net/browse/SES-1736?focusedCommentId=14423&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14423

It may be fixed in Sesame 2.7.9, in which case the fix should appear in GraphDB 7.0, which will use Sesame 2.8:

http://graphdb.ontotext.com/documentation/standard/roadmap.html

**Comment by subotic** [comment]
I still haven't heard from Ontotext regarding a pre-release of GraphDB 7.0.

**Comment by tobiasschweizer** [comment]
https://github.com/dhlab-basel/Knora/issues/101#issuecomment-234352467

**Comment by tobiasschweizer** [comment]
There is still a test for `ResourcesResponderV1Spec` that is skipped: `return a region with a comment containing standoff information (disabled because of issue 17)`.

  And why is there a standoff link pointing to a **value object IRI** in the expected response `expectedRegionFullResource`?

```
StandoffTagV1.link -> Vector(StandoffPositionV1(
                            href = Some("http://localhost:3333/v1/resources/http%3A%2F%2Fdata.knora.org%2F047db418ae06%2Fvalues%2F2428fc96-1383-4457-9704-077b37256103"),
                            resid = Some("http://data.knora.org/047db418ae06/values/2428fc96-1383-4457-9704-077b37256103"),
                            end = 39,
                            start = 36
                        ))
```

**Comment by benjamingeer** [comment]
> And why is there a standoff link pointing to a **value object IRI** in the expected response `expectedRegionFullResource`?

It's clearly wrong. That value IRI isn't even in the test data, and of course it should be a resource IRI. What I don't understand is why the test passes.

**Comment by benjamingeer** [comment]
OK, for the standoff link, the test data was just wrong, but it didn't matter because that test was disabled. I've removed it on my branch.

**Comment by tobiasschweizer** [comment]
It was disabled because of the character problem with newlines etc. in the `valueHasString`

**Comment by subotic** [comment]
The test passes: #420
