### ISSUE TITLE
Add JSON Web Token Support

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#171]

**Comment by subotic** [comment]
https://blog.knoldus.com/2016/06/18/integrate-jwt-with-akka-http/

**Comment by benjamingeer** [comment]
Lukas's reservations about JWT here: https://github.com/dhlab-basel/Knora/issues/520#issuecomment-309732821

**Comment by subotic** [comment]
Thanks for the link to the issue. Didn't see it before.
