### ISSUE TITLE
Transition from Spray HTTP to Akka HTTP

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#173]

**Comment by subotic** [comment]
- soon, the official migration guide: https://github.com/akka/akka/issues/17972
- blog post: https://tech.zalando.de/blog/migrating-spray-akka-http/

**Comment by benjamingeer** [comment]
Migration guide: http://doc.akka.io/docs/akka/2.4/scala/http/migration-from-spray.html
