### ISSUE TITLE
Can textattr and resource_reference be made optional when creating a text value?

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#177]
When you create a text value through the API, it currently complains if you leave out `textattr` and `resource_reference`. This is cumbersome, because many text values do not have markup. Can these be made optional in the route?

**Comment by benjamingeer** [comment]
@tobiasschweizer could you please look at this, since you're working on resource references?

**Comment by tobiasschweizer** [comment]
Yes! That should not be a problem since in the case classes `textattr` and `resource_reference` may be empty. I will try to do that today.

**Comment by tobiasschweizer** [comment]
done in https://github.com/dhlab-basel/Knora/commit/2986064593ee549436536644d2aa759e01437102
