### ISSUE TITLE
Document the Knora API version 1

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#181]
We now have several projects trying to use the Knora API version 1 to add data to Knora, and they're struggling because there's no documentation at all. The PUT and POST routes for `resources` and `values` desperately need documentation. @tobiasschweizer, could you possibly write some?

**Comment by tobiasschweizer** [comment]
I am glad to do so!

On which branch should that be done?

**Comment by benjamingeer** [comment]
Great! You could make a new branch for this.

**Comment by tobiasschweizer** [comment]
Ok, no problem.

**Comment by tobiasschweizer** [comment]
Where should the API V1 documentation go?

**Comment by benjamingeer** [comment]
I think it should go in the RST docs under `docs/rst/knora-api-server/deployment/`.

**Comment by tobiasschweizer** [comment]
ok, I added the skeleton for the documentation and will work on it next week

**Comment by tobiasschweizer** [comment]
Now I have to explain what the software actually does :-)

**Comment by tobiasschweizer** [comment]
https://github.com/dhlab-basel/Knora/commit/7915693ea959309f1e90f7bcdd15ccb14bb57850
