### ISSUE TITLE
Should basepath be part of a project definition in the triplestore?

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#192]
If file paths are stored in the triplestore, this makes it difficult to move a project from one server to another. Instead, the basepath of each project could be stored in the application configuration file.

**Comment by subotic** [comment]
The ``basepath`` is only stored in one place in the triplestore, namely in instances of ``knora-base:knoraProject``. When a project is moved to a new server, then it would need to be changed only in one place, which can easily be done over the API. If the ``basepath`` is stored in ``application.conf`` then this cannot be done over the API, i.e. someone needs to change the file and restart the ``webapi`` server. This would need to be done for every new project, i.e. opening a new project would require restarting the ``webapi`` server, which I don't think is very practical.

Also, if sometime in the future we move the content of ``application.conf`` to a separate named graph inside the triplestore to allow changes without the need to restart the ``webapi`` server, then this information would again live inside the triplestore, just at another place.

**Comment by benjamingeer** [comment]
OK!
