### ISSUE TITLE
E2E Tests Environment

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#194]
Could we make E22 tests use the same framework as the responder tests?

It would be nice if could use this kind of synatx in E2E tests:

```
 storeManager ! SparqlSelectRequest(sparqlQuery)

         

            expectMsgPF(timeout) {
                case response: SparqlSelectResponse =>
                 ...
            }
```

**Comment by subotic** [comment]
Sorry, it is not possible, or at least not feasible. The E2E tests use the Spray testing framework and the Responder tests use the Akka Testkit framework. Completely two different things. We would need to rewrite the Spray testing framework and simulate the Akka syntax.
