### ISSUE TITLE
Store permissions in a single triple for more efficient queries

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#196]
The performance of the extended search is currently limited by the way we store permissions. Because each resource or value can have an arbitrary number of permission assertions, we have to use `GROUP BY` and `GROUP_CONCAT` in SPARQL to concatenate those assertions into a string, so they can be returned in a single table cell in the results. The extended search query has to do this for each matching value. Grouping in SPARQL is fast enough if there are only one or two search criteria, but it gets very slow if there are three criteria (about 10 seconds), and much slower if there are four criteria (over 30 seconds). Grouping in Scala isn't an option, because it would mean returning one row per permission assertion per value, which would result in a huge number of rows being returned.

@lrosenth and I had a discussion about how to deal with this, and we concluded that the best option is to store all of a resource's or value's permission assertions in a string, in a single triple. Basically that string would contain the same thing that `GROUP_CONCAT` produces, but in a more compact format (we could use abbreviated codes instead of IRIs for the permission predicates). This would eliminate the grouping of permissions in SPARQL queries.

The only use case that this wouldn't be adequate for seems to be the case where you want to create a mirror of the publicly-viewable content in a repository. But Lukas had an idea about how to do this: instead of doing it with permissions, we could add a `creativeCommonsLicense` property to resources and values that are publicly viewable, specifying which Creative Commons License applies to the content. Then it would be easy to query for those in SPARQL.

@subotic, does this seem OK to you? If so, I can make a branch off `develop` to work on it.

cc @tobiasschweizer

**Comment by subotic** [comment]
@benjamingeer am I understanding this right? You propose to store something like this

```
<resourceIri> knora-base:hasViewPermission knora-base:KnownUser ;
                        knora-base:hasRestrictedViewPermission knora-base:UnknownUser ;
                        knora-base:hasChangeRightsPermisson knora-base:ProjectMember .
```

into

```
< resourceIri > knora-base:hasPermissions "string representing the permissions"^^xsd:string
```

Just another thought, what if the permissions for each resource and value is stored in a separate object attached through one property? Then querying the PermissionsResponder (which would be cached) for the permissions? I just don't like the idea of storing complex information into strings.

>The only use case that this wouldn't be adequate for seems to be the case where you want to create a mirror of the publicly-viewable content in a repository. But Lukas had an idea about how to do this: instead of doing it with permissions, we could add a creativeCommonsLicense property to resources and values that are publicly viewable, specifying which Creative Commons License applies to the content. Then it would be easy to query for those in SPARQL.

For the publicly-viewable content repository (a separate triplestore), we would need to strip the permission properties away. Your proposed approach would make this easier.

**Comment by benjamingeer** [comment]
> @benjamingeer am I understanding this right? You propose to store something like this

Yes, that's right.

> what if the permissions for each resource and value is stored in a separate object attached through one property? Then querying the PermissionsResponder (which would be cached) for the permissions?

The problem is that the permissions responder would then have to do a very slow query to populate its cache. I experimented with this in the search responder: instead of getting value permissions in the search query, I just collected the IRIs of all the matching values, then ran a separate query (containing a gigantic UNION) to get their permissions. It was even slower than the current approach. And I don't think we can do that query on startup, because then the permissions responder would have to query the permissions on every object in the repository (millions or trillions of objects) before the server could start.

> I just don't like the idea of storing complex information into strings.

I agree it's not elegant, but as Lukas said, "Permissions are not data."

There just doesn't seem to be any way to query permissions efficiently in searches as long as each object can have an arbitrary number of permission assertions. To make these queries efficient, the number of permission assertions has to be fixed, so a SPARQL query can return them in a fixed number of columns. I think a good example of an efficient system is Unix filesystem permissions, where permissions are stored as bits with fixed positions in a single integer. That works because Unix permissions are granted to a fixed set of categories (owner, group, other). But since our objects can grant permissions to an arbitrary number of groups, I don't see an alternative to storing a list in a string.

**Comment by subotic** [comment]
Ok, thanks.

> "Permissions are not data." - Prof. Dr. Lukas Rosenthaler

Sold. Please go ahead.

**Comment by benjamingeer** [comment]
I implemented this and it looks good! A search with 3 criteria, returning 199 results, is done in 157 milliseconds.

<pre>
[info] SearchResponderV1Spec:
[2016-08-03 20:03:08,723] INFO  HttpTriplestoreActor - SearchResponderV1Spec-akka.actor.default-dispatcher-6 - akka://SearchResponderV1Spec/user/storeManager/triplestoreManager/httpTriplestoreRouter/$a - Connection OK: 93
[info] - Load test data (22 seconds, 669 milliseconds)
[info] The search responder
[info] - should return 3 results when we do a simple search for the word 'Zeitglöcklein' in the Incunabula test data (690 milliseconds)
[info] - should return 2 results when we do a simple search for the words 'Zeitglöcklein' and 'Lebens' in the Incunabula test data (51 milliseconds)
[info] - should return 0 results when we do a simple search for the words 'Zeitglöcklein' for the type incunabula:page in the Incunabula test data (26 milliseconds)
[info] - should return 1 result when we do a simple search for the word 'Orationes' (the rdfs:label and title of a book) in the Incunabula test data (19 milliseconds)
[info] - should return 2 results when we do a simple search for the words 'Berthold and Bruder' in the Incunabula test data (41 milliseconds)
[info] - should return 2 books with the title 'Zeitglöcklein des Lebens und Leidens Christi' when we search for book titles containing the string 'Zeitglöcklein' (using a regular expression) in the Incunabula test data (24 milliseconds)
[info] - should return 2 books with the title 'Zeitglöcklein des Lebens und Leidens Christi' when we search for book titles containing the word 'Zeitglöcklein' (using the full-text search index) in the Incunabula test data (12 milliseconds)
[info] - should return 1 book with the title 'Zeitglöcklein des Lebens und Leidens Christi' that was published in 1490 (Julian Calendar) when we search for book titles containing the word 'Zeitglöcklein' (using the full-text search index) in the Incunabula test data (61 milliseconds)
[info] - should return 2 books with the title 'Zeitglöcklein des Lebens und Leidens Christi' when we search for book titles containing the word 'Lebens' but not containing the word 'walfart' (using MATCH BOOLEAN) in the Incunabula test data (21 milliseconds)
[info] - should return 18 books when we search for book titles that do not include the string 'Zeitglöcklein' (using a regular expression) in the Incunabula test data (25 milliseconds)
[info] - should return 2 books with the title 'Zeitglöcklein des Lebens und Leidens Christi' when we search for exactly that book title in the Incunabula test data (8 milliseconds)
[info] - should return 18 books when we search for all books that have a title that is not exactly 'Zeitglöcklein des Lebens und Leidens Christi' (although they may have another title that is) in the Incunabula test data (22 milliseconds)
[info] - should return 19 books when we search for all books that have a title in the Incunabula test data (23 milliseconds)
[info] - should return 19 pages when we search for all pages that have a sequence number of 1 in the Incunabula test data (48 milliseconds)
[info] - should return 79 pages when we search for all pages that have a sequence number greater than 450 in the Incunabula test data (56 milliseconds)
[info] - should return 2 books when we search for all books that were published in January 1495 (Julian date) in the Incunabula test data (11 milliseconds)
[info] - should return 5 books when we search for all books whose publication date is greater than or equal to January 1495 (Julian date) in the Incunabula test data (13 milliseconds)
[info] - should return 13 books when we search for all books whose publication date is less than or equal to December 1495 (Julian date) in the Incunabula test data (18 milliseconds)
[info] - should return all the pages that are part of Zeitglöcklein des Lebens (241 milliseconds)
[info] - should return all the pages that have a sequence number of 1 and are part of some book (24 milliseconds)
[info] - should return all the pages that are part of Zeitglöcklein des Lebens and have a seqnum (240 milliseconds)
<b>[info] - should return all the pages that are part of Zeitglöcklein des Lebens, have a seqnum less than or equal to 200, and have a page number that is not 'a1r, Titelblatt' (157 milliseconds)</b>
[info] - should return all the images from the images-demo project whose title belong to the category 'Sport' (368 milliseconds)
[info] - should return all the images from the images-demo project whose title belong to the category 'Spazieren' (14 milliseconds)
[info] - should return all the images from the images-demo project whose title belong to the category 'Alpinismus' (11 milliseconds)
[info] - should should filter full-text search results using permissions on resources and values (266 milliseconds)
[info] - should should not show resources that the user doesn't have permission to see in an extended search (48 milliseconds)
[info] - should should show standoff links if the user has view permission on both resources, but show other links only if the user also has view permission on the link (33 milliseconds)
[info] Run completed in 26 seconds, 852 milliseconds.
[info] Total number of tests run: 29
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 29, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
</pre>
