### ISSUE TITLE
Permissions Transform Script produces several lines instead of just one

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#199]
This problem occurs when transforming the beol test data (fuseki). `hasPermissions` occurs several times but it should be just one statement.

```
  <http://www.knora.org/ontology/knora-base#hasPermissions> "M knora-base:ProjectMember,knora-base:Owner" ;
  <http://www.knora.org/ontology/knora-base#hasStillImageFileValue> <http://data.knora.org/t0DN-IPHSti3u6kt_1bAnA/values/GH7hv3dOR86xFltcWfftjQ> , <http://data.knora.org/t0DN-IPHSti3u6kt_1bAnA/values/v5AX0iTtTG-kj4YWgVrl4A> ;
  <http://www.knora.org/ontology/knora-base#hasPermissions> "V knora-base:KnownUser" ;
```

I can send you the test data that have to be transformed.

Also, `valueHasString` has to be added to each value object.

**Comment by benjamingeer** [comment]
Fixed: https://github.com/dhlab-basel/Knora/commit/313bc09f5544216e05be07dfb622be41e38b8149
