### ISSUE TITLE
Good Way to determine equality of JSON objects in spray

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#200]
Do you know a good way to determine if two JSON objects are equivalent using spray?

In my opinion, `==` and `equals` should tell us if two objects have the same properties. However, they do not work in the test specs.

```
"{\"bold\":[{\"start\":0,\"end\":4}]}" did not equal "{\"bold\":[{\"end\":4,\"start\":0}]}"
```

Also spacing in the underlying string can make a difference here although we are comparing JsValues (parsed JSON strings).

Interestingly, the same works on the REPL:

```
scala> import spray.json._
import spray.json._

scala> val obj1 = JsonParser("{\"bold\":[{\"start\":0,\"end\":4}]}")
obj1: spray.json.JsValue = {"bold":[{"start":0,"end":4}]}

scala> val obj2 = JsonParser("{\"bold\":[{\"end\":4,\"start\":0}]}")
obj3: spray.json.JsValue = {"bold":[{"end":4,"start":0}]}

scala> obj1 == obj2
res0: Boolean = true
```

**Comment by benjamingeer** [comment]
This works for me if I add it to an E2E test:

```
val test1 = JsonParser("{\"bold\":[{\"start\":0,\"end\":4}]}")
val test2 = JsonParser("{\"bold\":[{\"end\":4,\"start\":0}]}")
assert(test1 == test2)
```

Were you trying to compare two text values? Keep in mind that they contain JSON within JSON: `textattr` contains a `JsString` containing JSON that has to be parsed separately. Could that be the reason for the problem you experienced?

**Comment by tobiasschweizer** [comment]
No, I think I did the same you did.

What about spacing in the string representation? Does it matter?
