### ISSUE TITLE
(start view : last activity) Context of search (within/across projetcs) in top search field should be clear

### ISSUE THREAD

**Issue by jroland01** [dhlab-basel/Knora#202]
![salsah_preview_mode_-_invision](https://cloud.githubusercontent.com/assets/1269913/17766588/22402c52-652c-11e6-9c72-dd68aa00e75c.jpg)

How will searching across projects work ? Here it is implied that "Search" will only cover the current project's scope (as the "Project activity" tab implies that the context is that of one "Project"). [See wireframe](https://projects.invisionapp.com/d/main#/console/7940249/170749729/preview)

**Comment by milchkannen** [comment]
The quick navigation menu (second toolbar row) will change into the search navigation (recent, extended and saved search queries) when the search input field is on focus. While typing we will show an additional "suggest-as-you-type" function.

**Comment by jroland01** [comment]
OK. So that means that each time you focus in the Search field, the whole page will change to display the recent, extended and saved search tabs ? And then, how do I get back to the activity feed (once I have focused in the search field) ? Do I need to click somewhere else in the page ? Shouldn't we have some kind of "global navigation" (always there) that will help users to orientate in Salsah, and switch between the different sections : activity, collections, search, settings, etc. ?

**Comment by milchkannen** [comment]
Not the whole page will change — Only the second toolbar row (own component/module). But yes, perhaps we need a filter button or something like that. Or we generate a suggestion menu (dropdown) below the search input field.
![screen shot 2016-08-30 at 14 46 36](https://cloud.githubusercontent.com/assets/4253580/18089773/df87054e-6ec1-11e6-992b-13664dee16d2.png)
_Suggestions while typing_

![screen shot 2016-08-30 at 14 47 18](https://cloud.githubusercontent.com/assets/4253580/18090127/8e6ea318-6ec3-11e6-8e31-ac8c600befa7.png)
_Recent search tags on input focus_

**Comment by jroland01** [comment]
@milchkannen I would certainly suggest implementing a suggest-as-you type dropdown in the search field instead. You really need to keep some "stability" (top-level menus not being completely replaced by others when you do something) in Salsah from the user's perspective (see #222). This is how a user builds an understanding of what's available where in Salsah (a "mental model"). It central to a good usability.

**Comment by milchkannen** [comment]
I agree and I just changed one mockup. I think it's better to work with an overlay dropdown like they made in Pinterest (as shown in the comment above) or in Tumblr.

![search-panel-focus](https://cloud.githubusercontent.com/assets/4253580/18095155/50d903e6-6ed6-11e6-8e0f-2344f0093e98.png)
_Focus on search input field_

**Comment by milchkannen** [comment]
Done
