### ISSUE TITLE
(start view : last activity) Merge project and user activity in one unique thread

### ISSUE THREAD

**Issue by jroland01** [dhlab-basel/Knora#205]
![salsah_preview_mode_-_invision](https://cloud.githubusercontent.com/assets/1269913/17766837/503643c0-652d-11e6-8892-7919986df5a8.jpg)

What is the rationale for separating Project related activity ("Project activity") from User specific activity ("Last activity") ? We could also imagine having a unique activity tab, but with a possibility to filter (e.g. according to user, project, date, etc.). [See wireframe](https://projects.invisionapp.com/d/main#/console/7940249/170749729/preview)

**Comment by milchkannen** [comment]
Done. There will be one main dashboard with a simple filter.
