### ISSUE TITLE
(start view : my collections) Move all "Collections" types (project, private, shared) to the same section and allow filtering of project, private, shared

### ISSUE THREAD

**Issue by jroland01** [dhlab-basel/Knora#206]
![salsah_preview_mode_-_invision](https://cloud.githubusercontent.com/assets/1269913/17767023/7c2c8d62-652e-11e6-94b2-c8f98f6ef926.jpg)

Will collections include both collections which I have created, as well as collections which I am part of ("Shared collections") ? In that case, the tab's title could be "Collections" (instead of "My Collections"), owned and shared collections could be visually differentiated and a filter could be added (e.g. "My Collections", "Shared Collections", etc.).

**Comment by jroland01** [comment]
![salsah_preview_mode_-_invision_](https://cloud.githubusercontent.com/assets/1269913/17806529/6f66f356-6605-11e6-9abd-2545e42c49d5.jpg)

@milchkannen as I understand "Project Collections" menu (see above) is not a setting, but a menu to view project -level collections ? If that's right I would suggest moving that into a global "Collections" menu, and then allow users to filter out (project, private, shared) collections. It will be easier for users to remember only one menu for collections, than having to figure out each time where to go ("was it a project or a private collection ... ?").

**Comment by milchkannen** [comment]
There will be one collection view with a simple filter or search functionality. I have merged the project and the user collections to one global collection.
