### ISSUE TITLE
(search panel : recent searches) Make sure previous search results are still visible while entering a new query

### ISSUE THREAD

**Issue by jroland01** [dhlab-basel/Knora#207]
![salsah_preview_mode_-_invision](https://cloud.githubusercontent.com/assets/1269913/17767269/9a9f6eee-652f-11e6-90de-40aca978b15c.jpg)

As I understand, the tabs (e.g. Recent, Extended, Saved) appear once the focus is in the "Search" field ? I suppose that once you run a query, the tabs will be replaced by the search results ? If this is the case, there may be a potential issue with that : If a user needs to refine a query (based on search results) in the Search field, she will lose the results list, which may be unpractical. An alternative would be to have one / more explicit link(s) to the "Recent", "Extended" and "Saved searches". Also, a possibility would be to have a "suggest-as-you-type" function that displays a relevant list of "Recent" and "Saved" searches (e.g. based on title, keywords, date), as a user types in the "Search" field.

**Comment by milchkannen** [comment]
Same issue as #202
