### ISSUE TITLE
(search panel : recent searches) Put "Recent searches" and "Saved search queries" next to each other

### ISSUE THREAD

**Issue by jroland01** [dhlab-basel/Knora#208]
I would probably put "Recent searches" and "Saved search queries" next to each other as they are more similar (queries), than "Extended search" (query builder) for the user. Thus e.g. : 1 - Recent, 2 - Saved, 3 - Extended

**Comment by milchkannen** [comment]
Done. Implemented in the new mockup: salsahSearch input:focus
