### ISSUE TITLE
(search panel : recent searches) Merge "normal searches" and "extended searches" in "Recent searches"

### ISSUE THREAD

**Issue by jroland01** [dhlab-basel/Knora#209]
![salsah_preview_mode_-_invision](https://cloud.githubusercontent.com/assets/1269913/17767453/5654ae74-6530-11e6-97c8-769bc47b925f.jpg)

Is there any specific reason why you are separating "normal search" from "extended search" in "Recent searches" ?

**Comment by milchkannen** [comment]
I have merged them.
