### ISSUE TITLE
(search panel : recent searches) Click on "recent search" name to search again, instead of "search again" link

### ISSUE THREAD

**Issue by jroland01** [dhlab-basel/Knora#210]
![salsah_preview_mode_-_invision](https://cloud.githubusercontent.com/assets/1269913/17767582/cbc4e912-6530-11e6-9a25-a0adefa52cf6.jpg)

"Search again" could probably be replaced (and removed) by clicking on the search query itself.

**Comment by loicjaouen** [comment]
you might want to edit the query before running it

**Comment by jroland01** [comment]
@loicjaouen I am not sure I understand your point. What difference will there be between clicking on the query's title, and clicking on the "search again" link ? I suppose also that you could run the query and edit it afterwards in the search field, if the search is fast enough. Furthermore, if the query is to be used as a template, it can be "saved" (and then later on edited). What do you think ?

**Comment by milchkannen** [comment]
Yes we can do the search by clicking direct on the list item. Perhaps we need a "show more"-button if the search query is too long. See the three points at the end of the listed search setting.

**Comment by loicjaouen** [comment]
@jroland01 : I didn't get that it was a list of links, I thought it was possible to edit the query directly there

**Comment by milchkannen** [comment]
Implemented in the new mockups.
