### ISSUE TITLE
(search panel : extended search) Provide a default template, with most common fields, for extended search

### ISSUE THREAD

**Issue by jroland01** [dhlab-basel/Knora#212]
![salsah_preview_mode_-_invision](https://cloud.githubusercontent.com/assets/1269913/17767850/019f977a-6532-11e6-880f-8b894a189d48.jpg)

"Extended search" could provide a default template, with the most common / frequently used fields already visible (e.g. based on each project's resources / fields). This will avoid users having to re-select the same fields for each "Extended search".

**Comment by milchkannen** [comment]
Yes, why not? It's the same idea that I have with the "Saved search queries". The user can do an extended search. At the end he can choose to save the settings as template (with the list of properties only) or inclusive the search values.

**Comment by flavens** [comment]
this will be resolved in KUIRL
