### ISSUE TITLE
(search panel : saved search queries) Search field should "suggest-as-you-type" saved queries, recent searches, etc.

### ISSUE THREAD

**Issue by jroland01** [dhlab-basel/Knora#214]
![salsah_preview_mode_-_invision](https://cloud.githubusercontent.com/assets/1269913/17768132/fea04a14-6532-11e6-8892-f17e960ba82b.jpg)

Once a title has been set for a "Saved query", I suppose the "Search" field will "suggest-as-you-type" saved queries, recent searches, etc. ?

**Comment by milchkannen** [comment]
Yes. See Issue #202
