### ISSUE TITLE
(search results : light table) Use XXX "results" instead of "objects" to indicate number of results

### ISSUE THREAD

**Issue by jroland01** [dhlab-basel/Knora#217]
![salsah_preview_mode_-_invision](https://cloud.githubusercontent.com/assets/1269913/17768564/ce0da700-6534-11e6-8dd5-cbd09a3e8e4f.jpg)

I would probably use : 1234 "results", instead of "objects", as this is a terminology well understood by users when running a search query.

**Comment by milchkannen** [comment]
It was just a first draft.
