### ISSUE TITLE
(search results : table editor) Filtering and sorting should be possible in List view / Table Edit view

### ISSUE THREAD

**Issue by jroland01** [dhlab-basel/Knora#218]
![salsah_preview_mode_-_invision](https://cloud.githubusercontent.com/assets/1269913/17768829/38b3dd62-6536-11e6-97ff-bc63c142d0a8.jpg)

List view / Table Edit view should also allow for filtering (e.g. faceted navigation) and sorting (e.g. in column headers) of results.

**Comment by milchkannen** [comment]
yes sure. That's what i meant with "excel-like".
