### ISSUE TITLE
(settings) Move all settings in one place, whether they are project -level or user -level

### ISSUE THREAD

**Issue by jroland01** [dhlab-basel/Knora#221]
![salsah_preview_mode_-_invision_](https://cloud.githubusercontent.com/assets/1269913/17806865/5b610c6e-6607-11e6-9c60-320d5c483e61.jpg)

Project -level and user -level settings seem to be spread out between two menus (as I understand). Make all settings (user, project, collection, etc.) accessible from the same place, e.g. Top right corner of the screen.

**Comment by milchkannen** [comment]
Done
