### ISSUE TITLE
(general) Add global navigation to help users orientate and navigate the application

### ISSUE THREAD

**Issue by jroland01** [dhlab-basel/Knora#222]
Right now there isn't a global navigation menu (a menu that is always visible, and always the same) in the application. This will make it difficult for users to orientate, navigate and understand the system. A global menu will allow to easily navigate back and forth between the different "areas" of the system (activity feed, search results, collections, resources, team members, settings, etc.) and help users understand what's available in Salsah.

**Comment by milchkannen** [comment]
The main navigation menu is on the top level toolbar. Implemented in the new mockups.

**Comment by jroland01** [comment]
@milchkannen do you plan to make it always visible to users (see my email from last week, with comments about this) ?

**Comment by milchkannen** [comment]
yes. implemented already. this is the reason why I closed the issue.

**Comment by jroland01** [comment]
@milchkannen OK. I am just not sure what you mean by "Implemented in the new mockups", those are not the mockups you've sent last week ?
