### ISSUE TITLE
(Settings:user) Differences between My collections/My resources

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Knora#225]
What is the differences between My collections (owned and/or shared) and My resources ?
What kind of data is expected in « Settings », for a standard user ? For a project admin user ?

**Comment by jroland01** [comment]
@milchkannen My understanding is that in "Collections" you would have resources organized according to collections, while in "Resources" you would have resources organized according to e.g. resource type (such as e.g. "Authors", "Books", etc.) - Is that right ? I also agree with @mrivoal that we should clarify what kinds of settings are available (user, project, admin) and where they are available in the application (see my point in #221).

**Comment by milchkannen** [comment]
The "project settings" item depends on the rights of each user. The rights will be defined by the project admins.
The "user settings" item (user dropdown in the top right corner) should show a form for the user profile settings (Name, eMail, Address, Password etc.).

**Comment by milchkannen** [comment]
This issue refers to the old mockups. We removed the menu item "My resources". It was just the idea to store (or "to like" (heart symbol) on Pinterest or "to star" on GitHub or CodePen) some resources, to have a quick access to them later. But here we can also use the salsahCollection component to store single resources; Something like a default collection called "likes".
