### ISSUE TITLE
(Search results : light table heterogenous)

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Knora#228]
I agree with Julien’s suggestion. Some kind of faceted search should allow the user to select only the resources he is  interested in, given the heterogeneity of the results : for example : Book, Page, Person, etc. 

Moreover, it could be useful to include in this faceted search the resource classes to which the resources of a given project belong to, such as the subclasses of knora-base : Representation : Document, Still image, Moving image, Audio, Text, as well as standard resources with no representation at all.

Date and Creator are also good criteria. Another criteria may be the fact that the object has several incoming and outgoing resource pointers (link to; link from).

**Comment by jroland01** [comment]
For background reference to faceted search, see #216.

**Comment by milchkannen** [comment]
As @jroland01 already mentioned: s. #227
