### ISSUE TITLE
Document that seqnum is required for a depedent resource (partOf)

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#233]
Add a section in `knora-base.pdf` that explains that for a dependent resource (a resource that is part of another resource, e.g. a page belonging to a book) a `seqnum` is required.

> I've been working on the code for the resource context query, and I've just realised that it assumes that if A is part of B, then A must have a seqnum

**Comment by benjamingeer** [comment]
Can we remove this requirement instead? Why force people to add meaningless sequence numbers even if it makes no sense in their data model?

Currently the context query returns no results if the dependent resources have no `seqnum`. That seems wrong to me.

**Comment by tobiasschweizer** [comment]
Do you refer to `knora-base:Resource` that has bot a `seqnum` and a `hasRepresentation`?

```
:Resource rdf:type owl:Class ;

          rdfs:subClassOf [ rdf:type owl:Restriction ;
                            owl:onProperty :isDeleted ;
                            owl:cardinality "1"^^xsd:nonNegativeInteger
                          ] ,
                          [ rdf:type owl:Restriction ;
                            owl:onProperty :hasRepresentation ;
                            owl:minCardinality "0"^^xsd:nonNegativeInteger
                          ] ,
                          [ rdf:type owl:Restriction ;
                            owl:onProperty :hasRepresentationValue ;
                            owl:minCardinality "0"^^xsd:nonNegativeInteger
                          ] ,
                          [ rdf:type owl:Restriction ;
                            owl:onProperty :attachedToUser ;
                            owl:cardinality "1"^^xsd:nonNegativeInteger
                          ] ,
                          [ rdf:type owl:Restriction ;
                            owl:onProperty :attachedToProject ;
                            owl:cardinality "1"^^xsd:nonNegativeInteger
                          ] ,
                          [ rdf:type owl:Restriction ;
                            owl:onProperty :hasPermissions ;
                            owl:maxCardinality "1"^^xsd:nonNegativeInteger
                          ] ,
                          [ rdf:type owl:Restriction ;
                            owl:onProperty :creationDate ;
                            owl:cardinality "1"^^xsd:nonNegativeInteger
                          ] ,
                          [ rdf:type owl:Restriction ;
                            owl:onProperty :lastModificationDate ;
                            owl:maxCardinality "1"^^xsd:nonNegativeInteger
                          ] ,
                          [ rdf:type owl:Restriction ;
                            owl:onProperty :seqnum ;
                            owl:maxCardinality "1"^^xsd:nonNegativeInteger
                          ] ,
                          [ rdf:type owl:Restriction ;
                            owl:onProperty :deleteDate ;
                            owl:maxCardinality "1"^^xsd:nonNegativeInteger
                          ] ,
                          [ rdf:type owl:Restriction ;
                            owl:onProperty :deleteComment ;
                            owl:maxCardinality "1"^^xsd:nonNegativeInteger
                          ] ;

```

Yes, we should get rid bot of `seqnum` and `hasRepresentation`. It also causes problems in the GUI.

**Comment by benjamingeer** [comment]
No, that's not what I mean. Currently a resource that has the property `isPartOf` must also have the property `seqnum` (otherwise the context query doesn't work). This makes sense for pages in books, but doesn't make sense for cities in countries, organs in the body, stars in constellations, ingredients in recipes, and many other part-whole relationships. I think we should remove this requirement. It should be possible to have dependent resources that are not ordered in any way.

**Comment by tobiasschweizer** [comment]
Ok, I get what you mean now. You are referring to **unordered** collections that do not have a `seqnum`. I think this makes sense.

But how would we sort them by default in scala?

I think we should get rid of `seqnum` and  `hasRepresentation` for a `knora-base:resource` anyway.

**Comment by benjamingeer** [comment]
If they have no seqnum, we could sort them by resource IRI.

**Comment by tobiasschweizer** [comment]
Ok, so we have to add that behaviour in scala and make `seqnum` optional in the SPARQL. If it is given, we use it for sorting. If not, we just sort by the IRI (in that case, the order does not matter).

**Comment by benjamingeer** [comment]
We could first group rows by IRI, then sort them by IRI, then sort them by seqnum.

**Comment by benjamingeer** [comment]
Or more efficiently: partition them into ones with a seqnum and ones without, and sort them separately.
