### ISSUE TITLE
Duplicate commits

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#238]
We (1) merged `develop` into `wip/standoff`, then (2) merged a pull request into `develop`, then (3) merged `develop` into `wip/standoff` again. Strangely, the changes that were in commit (1) were also in commit (3). A quick web search on duplicated commits in git seemed to indicate that this could be a symptom of combining `git rebase` and the default behaviour of `git pull`, which creates a merge commit rather than a rebase. Is GitHub's squash merge option using `git rebase`? The whole thing is unclear to me. So for now I've disabled squash merging of pull requests in the GitHub project options.

cc @subotic @tobiasschweizer

**Comment by subotic** [comment]
I think that squash commit is using rebase. As I understand it, we should all use "rebase" when merging ``develop`` into our own branch. If not, weird things like this can/will happen. I think rebasing is needed if we don't wan't to fill the ``develop`` branch with merge commits after merging a pull request, and also, if we don't wan't to fill the local feature branch with merge commits from ``develop``.

The first few paragraphs on this page https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request describes "rebase" in a way that even I understand it now.

**Comment by benjamingeer** [comment]
But doesn't everyone say that you shouldn't use rebase on a branch that more than one person works on? I'm still confused.

**Comment by subotic** [comment]
This is true, because rebase is rewriting the history. So, you would need to tell everybody to commit their changes and stop working on the branch. Then you could do a pull/rebase. Afterwards, everybody also working on this branch would need to checkout this branch again (delete it locally first).

**Comment by benjamingeer** [comment]
That sounds like pain. Tobias and I often work on the same branch, and often when one of is working, the other is not contactable.

**Comment by subotic** [comment]
You only need to coordinate when there is a merge from ``develop`` to this local branch.

The alternative is to always do merge commits and no squashing. Then basically the history in ``develop`` becomes useless, since it is filled with hundreds of meaningless smaller commits and a lot of merge commits.

Nobody said that working with git is fun ;-) We can always change to CVS :-).

**Comment by benjamingeer** [comment]
I think I can live with coordinating. @tobiasschweizer is that OK with you?

**Comment by tobiasschweizer** [comment]
So that means before merging `develop` back into a working branch, we should talk to one another? That should be ok since we do not do this very often. We only have to do this, when a pull request has been merged, and this requires coordination anyway (code reviewing).

**Comment by subotic** [comment]
@benjamingeer Also, you mentioned that when you worked on three feature branches simultaneously, that you merged them between each other. This can potentially be problematic when you do rebase (rewriting history) on one of the feature branches and then later on merge it again with another feature branch.

**Comment by benjamingeer** [comment]
So what should I do? I have pull request A that I want to merge first, pull request B that depends on A, and pull request C that depends on B.

**Comment by subotic** [comment]
This should not be a problem (I think). Just merge the pull requests in the right order.

I'm just saying that merging ``A`` into ``B`` again after ``A``'s commit history was changed can be problematic. After you merge ``A`` into ``develop``, pulling ``develop`` into ``B`` and afterwards into ``C`` should probably be fine.

**Comment by benjamingeer** [comment]
OK could you please document:

* How git clients should be configured
* What we should do when merging
* What we shouldn't do when merging

If there are clear rules, I'll be glad to follow them.

**Comment by benjamingeer** [comment]
After more discussion, the conclusion is:

* Since we squash and merge pull requests, there's no advantage to using rebase instead of merge to avoid merge commits in the commit history of `develop`.
* However, if your feature branch contains commits that are already in `develop`, this makes it harder to review the pull request, so then rebasing the feature branch onto `develop` should make it clearer.
