### ISSUE TITLE
LinkObj: use and definition?

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Knora#247]
I just came accross the `knora-base:LinkObj` class in `knora-base.ttl`. I didn't notice it before.

Unfortunately, the `rdfs:comment` isn't quite transparent for me and I couldn't find any documentation regarding the use of this class in `Knora-base.pdf`. I don't understand why it works with `knora-base:hasLinkTo` and `knora-base:hasLinkToValue`.

**Comment by benjamingeer** [comment]
Thanks for pointing this out. As far as I understand, it exists so you can annotate links. An annotation has to point to a resource. A `LinkObj` is a resource that connects two or more other resources and that can be annotated. I'll add some documentation.

**Comment by mrivoal** [comment]
Thanks!
