### ISSUE TITLE
rdfs:range and rdfs:domain properties in dokubib-onto.ttl

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Knora#248]
I just want to point the fact that `dokubib-onto.ttl` still uses `rdfs:domain` and `rdfs:range` properties instead of `knora-base:subjectClassConstraint` and `knora-base:objectClassConstraint`.

I don't know if you plan to keep this ontology as the demo set, but if so, it should probably be corrected.

**Comment by benjamingeer** [comment]
Thanks, will fix.
