### ISSUE TITLE
GUI wants to submit prop http://www.knora.org/ontology/knora-base#hasStandoffLinkTo

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#254]
When creating a new resource (a region), the GUI sends `http://www.knora.org/ontology/knora-base#hasStandoffLinkTo` with the request which should be prevented as this is a system property (it has no value that would be submitted resulting in a parsing error in the route).

I am having this problem on `develop`. However, this seems new to me.

In `jquery.resadd.js`, it has to be excluded from the submitted props. I have already done this for other properties that are defined in `knora-base.ttl`.

```
propvals["http://www.knora.org/ontology/knora-base#hasRepresentation"] = undefined;
propvals["http://www.knora.org/ontology/knora-base#seqnum"] = undefined;
propvals["http://www.knora.org/ontology/knora-base#hasStillImageFileValue"] = undefined;
propvals["http://www.knora.org/ontology/knora-base#hasStandoffLinkTo"] = undefined;
``` 

Could you handle that in your code change for the label?

**Comment by benjamingeer** [comment]
There is already an issue for this: #162.
