### ISSUE TITLE
Salsah - all created resource hold a label="test"

### ISSUE THREAD

**Issue by loicjaouen** [dhlab-basel/Knora#271]
![salsah-test-label](https://cloud.githubusercontent.com/assets/3933654/18876406/e020fb5e-84c9-11e6-8a4d-2abe15817674.png)

**Comment by loicjaouen** [comment]
Code below has the label of a new resource hard-coded to "test":
https://github.com/dhlab-basel/Knora/blob/develop/salsah/src/public/js/jquery.resadd.js#L1042

**Comment by tobiasschweizer** [comment]
I know: I had to add this because there was no possibility to add a label which is required

Ben and Lukas are working on it :-)

**Comment by loicjaouen** [comment]
Is it a double bug report then? (sorry, I didn't find the original one)
What was the problem? adding a label string there isn't too much of a hassle.
I started changing the JS code for filling the _label_ with something else than the "test" string and it seems to work.
![salsah-test-label-updated](https://cloud.githubusercontent.com/assets/3933654/18877279/076569ea-84cd-11e6-83d5-896a40453d82.png)

Shall I stop or go on then?

**Comment by tobiasschweizer** [comment]
they are working on it right now on the branch wip/label

**Comment by benjamingeer** [comment]
@loicjaouen there's no need for you to do this, we're working on it in pull request #261.
