### ISSUE TITLE
ValuesResponderV1.changeFileValueV1 doesn't check whether the resource exists

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#272]
All the methods that change values check whether the containing resource is deleted (by calling `findResourceWithValue`, which throws `NotFoundException` if the resource is marked as deleted), except `changeFileValueV1`.

I think this could be fixed by having the SPARQL template `getFileValuesForResource.scala.txt` return no results if the resource is deleted. In that case, the responder should throw `NotFoundException` rather than `BadRequestException`. The error message could include something like `(the resource may have been deleted)`.

**Comment by tobiasschweizer** [comment]
Do you want me to fix that?

**Comment by benjamingeer** [comment]
Yes please. I assigned it to you because I think you wrote that method. :)

**Comment by tobiasschweizer** [comment]
I think that you thought that you could make me think I had written that method :-)

**Comment by benjamingeer** [comment]
You have just been geered. :)

**Comment by tobiasschweizer** [comment]
Where is the geer button here?

**Comment by tobiasschweizer** [comment]
done in: https://github.com/dhlab-basel/Knora/pull/336/commits/ee1fcd6aaf7223890be9e2f85dda0cca6a26b792
