### ISSUE TITLE
Editing labels: about "rdfs:label" in issue #261

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Knora#274]
We are are currenly working with the wip/labels branch (because of issue #261) in order to do some test cases both on ontologies and on the way the GUI deals with them. 
 
I was just wondering if the rdfs:label property created for each resource is handled just like any other Knora value. Is this property versioned as well? Is it attached to a user? 

Thanks for the answer.

**Comment by benjamingeer** [comment]
The label can't be a Knora value, because `rdfs:label` is a datatype property; its object is just a string, not a `knora-base:TextValue`. So labels aren't versioned and don't have their own permissions or owners. If you have modify permission on the resource, you can change its label.

**Comment by mrivoal** [comment]
Ok. Thanks!
