### ISSUE TITLE
create another linking property

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#277]
When creating another linking property (one is already existing), the GUI does not ask the ontology responder for the correct resource class information, but for knora-base:Resource

![gui](https://cloud.githubusercontent.com/assets/6000023/18954870/33b8b900-8655-11e6-9e12-db716a603f1b.jpg)

**Comment by tobiasschweizer** [comment]
the problem is in `jquery.resadd.js`: 

```
case 'searchbox':
									{
										attributes.type = 'text';
										create_entry(propname, function(ele, attr) {
											var tmpele = $('<input>', attr).addClass('__searchbox').insertBefore(ele.find('.entrySep'));

											var restype_id = -1;
											var numprops = 1;
											var attrs = rtinfo.properties[pinfo].attributes.split(';');

```

the first time searchbox is created, pinfo is 0, the second time it is 2. This affects the restype that is submitted to the searchbox plugin.

**Comment by tobiasschweizer** [comment]
When you try to add a new value of a linking property in `jquery.propedit.js` by clicking on the green plus icon, the application freezes.

**Comment by SepidehAlassi** [comment]
When you remove an optional linking property in jquery.propedit.js by clicking on red cross button and then later add it by clicking on the green plus icon, the application freezes.

**Comment by tobiasschweizer** [comment]
The "SALSAH.ApiGet ERROR: Internal Server Error error"  is caused by the GUI asking the oOntology Responder for `knora-base:Resource` which we removed from being returned because we do not want people to create instances of `knora-base:Resource`, but only subclasses of it.
