### ISSUE TITLE
extended search "exist"

### ISSUE THREAD

**Issue by loicjaouen** [dhlab-basel/Knora#282]
Here is a list of problems we face when using extended search.

_Context: branch "wip/labels" commit 8708a9d_
# empty search
- searching with default fields (when everything is left with default values) gives the error:

![capture d ecran 2016-10-11 a 11 21 00](https://cloud.githubusercontent.com/assets/3933654/19265283/d527602c-8fa4-11e6-9a3c-a15946fc8102.png)

Request: 

```
GET http://localhost:3333/v1/search/?searchtype=extended&show_nrows=25&start_at=0
```

Error:

```
org.knora.webapi.InconsistentTriplestoreDataException: No value found for SPARQL query variable 'resourceOwner' in query result row"}
```
- selecting a vocabulary limits the proposed fields in the interface, but not the request (enhancement, Salash 1.0 did the same)
# there is an existing resource

let's assume that there is a valid record, in this case a "Note" with property "Note" that holds the value "Note A":
![capture d ecran 2016-10-11 a 10 42 38](https://cloud.githubusercontent.com/assets/3933654/19265619/1b09d8bc-8fa6-11e6-9b17-cf1466984c54.png)

Request:

```
GET http://localhost:3333/v1/search/?searchtype=extended&property_id=http%3A%2F%2Fwww.knora.org%2Fontology%2Fll%23note&compop=MATCH&searchval=note&show_nrows=25&start_at=0&filter_by_restype=http%3A%2F%2Fwww.knora.org%2Fontology%2Fll%23Note&filter_by_project=http%3A%2F%2Fdata.knora.org%2Fprojects%2Ff94fdf5b03
```
# but it is hard to find
- selecting only a project gives no result:

![capture d ecran 2016-10-11 a 11 31 29](https://cloud.githubusercontent.com/assets/3933654/19265731/94512dec-8fa6-11e6-90b0-988aa45bc903.png)

Request:

```
http://localhost:3333/v1/search/?searchtype=extended&show_nrows=25&start_at=0&filter_by_project=http%3A%2F%2Fdata.knora.org%2Fprojects%2Ff94fdf5b03
```
- selecting a project and the resource type gives no result:

Request:

```
http://localhost:3333/v1/search/?searchtype=extended&show_nrows=25&start_at=0&filter_by_restype=http%3A%2F%2Fwww.knora.org%2Fontology%2Fll%23Note&filter_by_project=http%3A%2F%2Fdata.knora.org%2Fprojects%2Ff94fdf5b03
```
- selecting a project, the resource type, it's property being not empty gives no result:

![capture d ecran 2016-10-11 a 11 40 22](https://cloud.githubusercontent.com/assets/3933654/19265923/a05b61ec-8fa7-11e6-8e70-6e6073985770.png)

Request:

```
http://localhost:3333/v1/search/?searchtype=extended&show_nrows=25&start_at=0&filter_by_restype=http%3A%2F%2Fwww.knora.org%2Fontology%2Fll%23Note&filter_by_project=http%3A%2F%2Fdata.knora.org%2Fprojects%2Ff94fdf5b03
```

**Comment by loicjaouen** [comment]
@benjamingeer 
Thanks, that's good news:
- it is not a permission issue as it is the same user that finds the resource with the full-text search, and not with the extended-search
- so it must be a consistency / resource without owner, I will track that.

**Comment by benjamingeer** [comment]
> it is not a permission issue as it is the same user that finds the resource with the full-text search, and not with the extended-search

Unless there's a bug causing the full-text search and the extended search to check permissions differently.

**Comment by loicjaouen** [comment]
I hoped that I could find a resource without owner with this simple request, but I don't find any candidate, @benjamingeer would mind reviewing this request?

```
PREFIX knora-base: <http://www.knora.org/ontology/knora-base#>
select ?s where {     
    ?s a knora-base:Resource .
    minus {?s knora-base:attachedToUser ?p . }
} limit 100 
```

**Comment by benjamingeer** [comment]
This looks like it would work if you enabled inference. Otherwise, this won't match anything:

```
    ?s a knora-base:Resource .
```

Without inference, you need:

```
    ?s a ?resourceClass .
    ?resourceClass rdfs:subClassOf+ knora-base:Resource .
````

**Comment by loicjaouen** [comment]
it is because of a previous import script resulting in:
- trailing `isDeleted` in ontology, which turns ontological statements into data objects
- data declaration of `list` elements that miss the `attachedToUser` and `attachedToProject` statements

that was not obvious to find out, and it helped to turn some logging on (`SearchResponderV1.scala:472` : `_ = println(searchSparql)`) to find out the sparql that is send to the store in order to replicate it in the store's workbench and analyse the result.

**Comment by benjamingeer** [comment]
> trailing `isDeleted` in ontology, which turns ontological statements into data objects

This shouldn't happen. Can I see the example?

**Comment by loicjaouen** [comment]
here you are: `subuser-clean-onto.ttl` and `subuser-tainted-onto.ttl`.
When loading `clean` an extended search for returns no result.
When loading `tainted`, the SPARQL request that is generated to look for data:
```
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix knora-base: <http://www.knora.org/ontology/knora-base#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT
    ?resource
    ?resourceLabel 
    ?resourceClass
    ?previewPath
    ?previewDimX
    ?previewDimY
    ?resourceOwner
    ?resourceProject
    ?resourcePermissions
    
    FROM <http://www.ontotext.com/explicit>

WHERE {
    BIND(STR("en") AS ?preferredLanguage)
    BIND(STR("en") AS ?fallbackLanguage)

    ?resource knora-base:isDeleted false .
    ?resource rdfs:label ?resourceLabel .
    ?resource a ?resourceClass .

    OPTIONAL {
        ?resource knora-base:hasStillImageFileValue ?fileValue .
        ?fileValue a knora-base:StillImageFileValue .
        ?fileValue knora-base:isPreview true .
        ?fileValue knora-base:internalFilename ?previewPath .

        OPTIONAL {
            ?fileValue knora-base:dimX ?previewDimX .
            ?fileValue knora-base:dimY ?previewDimY .
        }
    }

    OPTIONAL {
        ?resource knora-base:hasPermissions ?resourcePermissions .
    }

    OPTIONAL {
        ?resource knora-base:attachedToUser ?resourceOwner .
    }

    OPTIONAL {
        ?resource knora-base:attachedToProject ?resourceProject .
    }
}
LIMIT 500
```

returns, for example:
```
      {
        "resource": {
          "type": "uri",
          "value": "http://www.knora.org/ontology/subuser#Collaborator"
        },
        "resourceLabel": {
          "xml:lang": "fr",
          "type": "literal",
          "value": "Collaborateur"
        },
        "resourceClass": {
          "type": "uri",
          "value": "http://www.w3.org/2002/07/owl#Class"
        }
      },
```

which has no resourceOwner so the check fails and Knora returns an error.

[Archive.zip](https://github.com/dhlab-basel/Knora/files/536417/Archive.zip)

**Comment by benjamingeer** [comment]
OK, I see what happened. This is because the query doesn't check whether the result is really a `knora-base:Resource`. I think I removed this check for performance reasons, but I've put it back now on the `wip/beol-onto` branch, where there's an enhancement under development that allows you to search for subclasses and subproperties (see #281).

**Comment by benjamingeer** [comment]
> selecting a vocabulary limits the proposed fields in the interface, but not the request

Lukas says this is not a bug. The form says "Limit selections by vocabulary". This means that selecting a vocabulary only affects the drop-down menus in the search form. You can't do a search for everything in a given vocabulary. You could, however, do a search for everything in a project.
