### ISSUE TITLE
Transformation Script: change label test to something meaningful

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#294]
In the beol project, all the labels for regions are set to "test" since the were created using the GUI. 

Could we add a new method to the transformation script that copies the `valueHasString` of a specified property of a specified resource class to each class instance?

E.g., every http://www.knora.org/ontology/knora-base#hasComment's `valueHasString` is copied to the region's label.

**Comment by benjamingeer** [comment]
I think "test" is very meaningful! :)

OK, OK.

**Comment by benjamingeer** [comment]
Done in #311.
