### ISSUE TITLE
Update Google Chrome Drivers for Selenium

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#295]
2.2.5 is out: http://chromedriver.storage.googleapis.com/index.html?path=2.25/

With the current version of the drivers we have, the driver did not work on Ubuntu. With 2.2.5 it works fine.

**Comment by subotic** [comment]
How do you know, that it works on Ubuntu with 2.2.5?

**Comment by tobiasschweizer** [comment]
I know because I use Ubuntu and the current driver in Knora did not work.

**Comment by subotic** [comment]
Wouldn't it then be faster to simply commit the new driver yourself? These kind of things are not very high on my todo list.

**Comment by tobiasschweizer** [comment]
I can do it, of course. I just asked you because you were the one that wanted to put it under version control :-)

Maybe we can take it out and just provide the link (it is already documented), otherwise we have to manage different versions.

**Comment by subotic** [comment]
If the link is in the documentation, then I would say, we could remove it altogether from git.

I don't know, whatever you think is easier for the user. I'm fine with both.

**Comment by subotic** [comment]
I had an epiphany in the middle of the night. Why not let ``sbt`` download it (either automatically during build, or manually by calling a SBT task): http://stackoverflow.com/questions/27466869/download-a-zip-from-url-and-extract-it-in-resource-using-sbt

**Comment by subotic** [comment]
We can also check the operating system, so that we only download the one that is needed.

**Comment by subotic** [comment]
Added the newest ```chromedriver``` in this pull request #388 .
