### ISSUE TITLE
error on attempt to delete a value

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#306]
When I want to delete a value, I get a CORS error:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:3333/v1/values/http%3A%2F%2Fdata.knora.org%2Fx5zk7l6cSBm2poXqpl9nEw%2Fvalues%2FK2ZiIlj9SZe0sC9ImQ39NQ. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

![cors](https://cloud.githubusercontent.com/assets/6000023/19963264/e2109636-a1bb-11e6-98af-13e15538c79d.png)

However, this could also be another problem that appears to be a CORS error for the browser. But there is no error message (see #304 ).

**Comment by tobiasschweizer** [comment]
Chrome's devtools indicate that it could indeed be a CORS problem (after the AKKA update):

> XMLHttpRequest cannot load http://localhost:3333/v1/values/http%3A%2F%2Fdata.knora.org%2Fx5zk7l6cSBm2poXqpl9nEw%2Fvalues%2FYA-3gYMXSoKbv0wcw0bwRw. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3335' is therefore not allowed access. The response had HTTP status code 400.

**Comment by benjamingeer** [comment]
Sometimes we get bogus CORS errors when the request could not be parsed; see #179. Could that be the case here?
