### ISSUE TITLE
Some property predicate inheritance is apparently still allowed but what are good pratices?

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Knora#308]
Just to be sure: `knora-base:objectClassConstraint` and `knora-base:subjectClassConstraint` properties have to be defined for each property (including sub-properties) because the consistency checking is seeking for these.

However Knora and Salsah still allow some property predicate inheritance, right? It also echoes @tobiasschweizer's comment in #303 

> salsah-gui:guiElement salsah-gui:Searchbox ; has to be added here since you removed property predicate inheritance. Also permissions are missing.

It may not be the most Knora/Salsah-compliant way of doing so, but let's say I define a property (same example as in #302) `drawings-gods:internalComment` with the following subproperties `drawings-gods:drawingComment`, `drawings-gods:instructionComment`, `drawings-gods:siteComment`. 

If `drawings-gods:internalComment` is defined as such:

```
##  http://www.knora.org/ontology/drawings-gods#internalComment
:internalComment rdf:type owl:ObjectProperty ;
                 rdfs:subPropertyOf knora-base:hasValue ;
                 knora-base:objectClassConstraint knora-base:TextValue ;
                 knora-base:subjectClassConstraint :Commentable ;
                 rdfs:label "Commentaire interne"@fr ,
                     	"Internal comment"@en ;
		 rdfs:comment "Commentaire interne"@fr ,
			"Internal comment"@en ;
		 salsah-gui:guiElement salsah-gui:SimpleText ;
		 salsah-gui:guiOrder "1"^^xsd:integer ;
       		 knora-base:hasDefaultViewPermission knora-base:ProjectMember ;
	         knora-base:hasDefaultDeletePermission knora-base:Owner .
```

and subproperties like this: 

```
###  http://www.knora.org/ontology/drawings-gods#drawingComment
:drawingComment rdf:type owl:ObjectProperty ;
                rdfs:subPropertyOf :internalComment ;
                knora-base:subjectClassConstraint :Drawing ;
                knora-base:objectClassConstraint knora-base:TextValue ;
                rdfs:label "Commentaire interne (dessin)"@fr ,
                     	"Internal comment (drawing)"@en ;
		rdfs:comment "Commentaire interne (dessin)."@fr ,
			"Internal comment (drawing)."@en .

###  http://www.knora.org/ontology/drawings-gods#siteComment
:siteComment rdf:type owl:ObjectProperty ;
             rdfs:subPropertyOf :internalComment ;
             knora-base:subjectClassConstraint :CollectionSite ;
             knora-base:objectClassConstraint knora-base:TextValue ;
             rdfs:label "Commentaire interne (site de collecte)"@fr ,
             	"Internal comment (collection site)"@en ;
	     rdfs:comment "Commentaire interne (site de collecte)"@fr ,
		"Internal comment (collection site)"@en .

###  http://www.knora.org/ontology/drawings-gods#instructionComment
:instructionComment rdf:type owl:ObjectProperty ;
                    rdfs:subPropertyOf :internalComment ;
                    knora-base:subjectClassConstraint :Instruction ;
                    knora-base:objectClassConstraint knora-base:TextValue ;
                    rdfs:label "Commentaire interne (instruction)"@fr ,
                     	"Internal comment (instruction)"@en ;
		    rdfs:comment "Commentaire interne (instruction)"@fr ,
			"Internal comment (instruction)"@en .
```
Then, these subproperties inherit property predicates from `drawings-gods:internalComment`. Consequently, there are displayed correctly within the GUI and I assume they also inherit permissions from `drawings-gods:internalComment`.

So should I repeat for each subproperty the property predicates relevant for the GUI and the permissions or is it fine like this?

**Comment by benjamingeer** [comment]
> However Knora and Salsah still allow some property predicate inheritance, right?

Not after pull request #303 is merged.

> So should I repeat for each subproperty the property predicates relevant for the GUI and the permissions

Yes.

**Comment by mrivoal** [comment]
Ok. I will stick to this, then. Thanks.
