### ISSUE TITLE
Allow user of Salsah-GUI to check basic metadata regarding resources and values

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Knora#309]
This issue is created following the discussion we had with Ben.

Future Salsah-GUI users in 3 different projects have asked if there will be a way in the next Salsah version (e.g. Salsah 1.5 and 1.6) to **review the currentness or relevance of a resource and/or of a value** by viewing metadata about the last modification or data input, such as : 

- identity of the user who last updated the resource/value;
- date of the creation or modification;
- previous value for a given property (optionnal).

Given the fact that Knora already stores this data, it may not be very hard nor time-consuming to do. For example, for the user, those metadata could be accessed by simply mousing over a resource preview or, inside a resource, by mousing over any value.

**Comment by benjamingeer** [comment]
We're working on this now.

**Comment by benjamingeer** [comment]
This is implemented in pull request #315 as an "information" icon next to the value, with a little information bubble that appears on mouseover.

**Comment by mrivoal** [comment]
That's great, thanks. We'll have a look at it.
