### ISSUE TITLE
Unicode characters not returned correctly in JSON from the API

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#313]
If you load this:

```
http://localhost:3333/v1/resources/http%3A%2F%2Fdata.knora.org%2Fc5058f3a
```

It contains strings like this:

```
"ZeitglÃ¶cklein des Lebens und Leidens Christi"
```

This used to work correctly. Could it be related to the switch from Spray to Akka HTTP?

**Comment by tobiasschweizer** [comment]
probably this is missing in the response header: `Content-type: application/json; charset=utf-8`

**Comment by benjamingeer** [comment]
This is actually a browser bug.

> The content-type of `application/json` is fixed to UTF-8 and doesn't allow a charset parameter by its spec.

https://github.com/akka/akka/issues/17409#issuecomment-100162286

Bug report for Chromium: https://code.google.com/p/chromium/issues/detail?id=438464
For Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1166558

It only affects the rendering of JSON in the browser. AJAX works fine.

**Comment by subotic** [comment]
Just as a reference, we already had this in #97 .
