### ISSUE TITLE
HTML representation of a resource does not work

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#314]
When requiring an HTML representation of a resource, JSON is served instead of HTML.

Example: <http://localhost:3333/v1/resources.html/http%3A%2F%2Fdata.knora.org%2Fc5058f3a?noresedit=true&reqtype=properties> returns JSON. The R2R tests pass though.

Response header: 
```
HTTP/1.1 200 OK

Server: akka-http/2.4.11

Date: Tue, 08 Nov 2016 15:42:54 GMT

Content-Type: application/json

Content-Length: 9510

```

Please note that the encoding is missing, see #313

**Comment by benjamingeer** [comment]
In `RouteUtilV1`, `replyMessageTry2HtmlHttpResponse` is never called.

**Comment by subotic** [comment]
> In RouteUtilV1, ``replyMessageTry2HtmlHttpResponse`` is never called.

This was already the case, when I made the change to ``akka-http``. I thought this was intentional. I remember that we created ``replyMessageTry2HtmlHttpResponse`` specifically for the ``/v1/resources.html`` route.

**Comment by subotic** [comment]
#292 also has relevance to this issue, since any error messages returned for this route should be returned as HTML.

**Comment by benjamingeer** [comment]
> This was already the case, when I made the change to ``akka-http``. I thought this was intentional. I remember that we created ``replyMessageTry2HtmlHttpResponse`` specifically for the ``/v1/resources.html`` route.

I thought that you wote all the response-to-HTML code and that it used to work.
