### ISSUE TITLE
Bug when deleting a checkbox

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Knora#318]
When the cardinality of a property whose `knora-base:objectClassConstraint `is `knora-base:BooleanValue` is set to `owl:maxCardinality "1"^^xsd:nonNegativeInteger`, we should be able to delete the checkbox. 

By doing so, we get an error in the browser's console: 
```
 Uncaught ReferenceError: tmp_add_symbol is not defined                            jquery.resadd.js:252
    at HTMLImageElement.<anonymous> (http://platec.unil.ch/salsah/js/jquery.resadd.js:252:26)
    at HTMLImageElement.dispatch (https://code.jquery.com/jquery-2.1.4.min.js:3:6466)
    at HTMLImageElement.r.handle (https://code.jquery.com/jquery-2.1.4.min.js:3:3241)
```

However, when we do so, we can create the resource.

**Comment by benjamingeer** [comment]
Are you talking about deleting a checkbox value from a resource that has already been created? Or just removing an optional checkbox from the form when creating a new resource?

**Comment by mrivoal** [comment]
It is the second case: removing an optional checkbox from the form when creating a new resource.

**Comment by benjamingeer** [comment]
Fixed: https://github.com/dhlab-basel/Knora/commit/d1b9e363e5a169707839cb3f8613544d006d32c9
