### ISSUE TITLE
Unable to move or resize the window after creating a "new entry"

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Knora#320]
While creating a "new entry" for a resource with a `knora-base:hasLinkTo` property, we are unable to move or resize the window.

**Comment by benjamingeer** [comment]
I suspect that the old SALSAH has always had this limitation. Is this really essential, or is it just a minor annoyance?

**Comment by mrivoal** [comment]
You are totally right, it is an old limitation. And it is not essential.
