### ISSUE TITLE
JDC or JDN?

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#327]
We have small inconsistency in our ontology.

In the docs, we speak of Julian Day Numbers (JDN) while we call them Julian Day Count (JDC) in the triplestore.

The difference is that JDNs represent a whole day while JDCs also contain the time of the day as a fraction. However, our JDC props have an object constraint of integer which does not allow for fractions.

**Comment by benjamingeer** [comment]
> our JDC props have an object constraint of integer which does allow for fractions.

Do you mean "doesn't allow"?

**Comment by tobiasschweizer** [comment]
yes :-)

**Comment by benjamingeer** [comment]
OK, I'll fix this by changing the docs to say JDC and changing the properties to have type `xsd:decimal`.

**Comment by tobiasschweizer** [comment]
the problem is that the gui cannot handle fractions

**Comment by benjamingeer** [comment]
So what should we do? Truncate fractions in the GUI?

**Comment by benjamingeer** [comment]
Or disallow fractions in API v1?

**Comment by benjamingeer** [comment]
API v1 could return 400 Bad Request if a fraction is submitted.

**Comment by tobiasschweizer** [comment]
I do not know if day time can be assumed to be a stable concept throughout time and different calendars, I hardly doubt it. So we would need to figure out how to transform to and from JDC first. 

Didn't you write about this in an issue?

**Comment by benjamingeer** [comment]
Yes, I think a conversion to/from times in hours and minutes will be possible only for very recent Gregorian dates (I believe that issue is on GitLab). So perhaps `knora-base:DateValue` should never support times. In that case, we should enforce integer JDNs at all levels. If people want times, we could introduce a `knora-base:DateTimeValue` for that.

**Comment by tobiasschweizer** [comment]
http://git.iml.unibas.ch/salsah-suite/knora/issues/279
