### ISSUE TITLE
Knora Base Ontology and documentation

### ISSUE THREAD

**Issue by hanscools** [dhlab-basel/Knora#328]
- Docu.
	- "Representations": "… resource that has file values must belong to [one] of the subclasses of kb:Representation …"
	- "Standard Resource Classes": proposal to add kb:Representation and kb:Person with a short explanation, and put this section before "Representations".
	- "StandoffLinkTag": "kb:standoffTagHasLink (1)" can be grey, conform.

- kb:hasComment:
	- onto.: Proposal to rephrase the comment: "Represents a comment [as an object (non-literal)]".
	- docu: "Standard Resource Classes": kb:Annotation: "The hasComment property points to the text [object (non-literal)] of the annotation."

- kb:Representation: kb:filename: is this used?

- kb:TextRepresentation: should there be a cardinality restriction of 1-n on property kb:hasTextFileValue?

- kb:DocumentRepresentation: should the restriction be on kb:has[Document]FileValue?

- kb:DocumentFileValue: should there be a cardinality restriction of 0-n on property kb:hasComment?

- kb:MovingImageFileValue: should there be a cardinality restriction of 1 on property kb:qualityLevel?

- Can default permissions also be attributed to a property, e.g. kb:hasStillImageFileValue? If so, should the other similar properties get similar permissions?

- kb:User:
	- Assuming foaf:familyName and foaf:givenName needing to be related to kb:objectCannotBeMarkedAsDeleted (as the rest of the properties with a kb:User subject): a similar solution as for rdfs:label can be applied. A solution can be [kb:familyName rdfs:subPropertyOf foaf:familyName, kb:objectCannotBeMarkedAsDeleted.].
	- kb:isInGroup:
		- rdfs:subPropertyOf foaf:member: impossible since foaf has the inverse meaning of "has member". Can be declared: kb:isMemberOf owl:inverseOf foaf:member. kb:isInGroup rdfs:subPropertyOf kb:isMemberOf.
		- Should the cardinality be 1-n instead of 0-n, assuming a user should be in at least one user group?
	- kb:isInProject:
		- is a project considered a group, because declared as rdfs:subPropertyOf foaf:member, leading to e.g. kb:knoraProject rdfs:subClassOf foaf:Group. For the rest the same issue as for kb:isInGroup.
	- kb:currentproject:
		- rename it to kb:currentProject ?
		- make it rdfs:subPropertyOf kb:isInProject ?
		- cf. comment: why only 1 active project ?
			- if kept -> add cardinality 1 in restriction on it for kb:User ?

- kb:SystemUser
	- is a kb:User named "Knora" -> is kb:SystemUser a foaf:Person ?
	- need to add rdf:type owl:NamedIndividual ?

- kb:UserGroup and kb:Institution: if foaf:name to be related to kb:objectCannotBeMarkedAsDeleted: similar as for foaf:familyName.

- Rename kb:protocol to kb:internetProtocol ?

- kb:Person:
	- kb:hasFamilyName rdfs:subPropertyOf foaf:familyName BUT an object of the former is a non-literal and an object of the latter is a literal, cf. comment of foaf:name. One is entitled to use the subject and object of the sub-property with the property, generating a conflict. Same for kb:hasGivenName and foaf:givenName.
	- kb:hasBirthDate rdfs:subPropertyOf foaf:birthday: also here the first is an object property and the second has a literal object. Additionally foaf only expresses month and day.

- kb:valueHasGeometry: comment: "… [squartes -> squares] …"

- kb:valueHasGeonameCode kb:objectDatatypeConstraint: in ontology xsd:string vs. in docu. xsd:integer

- kb:fps: proposal to add label "Frames per second"

- kb:valueHasListNode:
	- rdf:type [owl:DatatypeProperty -> owl:ObjectProperty]
	- delete [rdfs:subPropertyOf kb:valueHas]

**Comment by benjamingeer** [comment]
Thanks for pointing out these inconsistencies. I've fixed most of these in #330.

> proposal to add kb:Representation and kb:Person with a short explanation, and put this section before "Representations".

You can't create a `kb:Representation`, only a subclass of `kb:Representation`.

I think `kb:Person` is going to be moved into another ontology. We're going to formulate a process for standardising classes that can be used across projects, and those classes will go in separate ontologies.

> Can default permissions also be attributed to a property, e.g. kb:hasStillImageFileValue? If so, should the other similar properties get similar permissions?

Default permissions on properties are going to be removed in #299. They're just there now as a temporary workaround.

> is a kb:User named "Knora" -> is kb:SystemUser a foaf:Person?

It's a not a person, because it just represents the Knora API server itself.

> kb:valueHasListNode:
> * rdf:type [owl:DatatypeProperty -> owl:ObjectProperty]
> * delete [rdfs:subPropertyOf kb:valueHas]

Unfortunately we need `valueHasListNode` to be a subproperty of `valueHas`, because `valueHas` is used in a consistency rule. So I've made `valueHas rdf:type rdf:Property`, so its subproperties can be object properties or datatype properties.

**Comment by hanscools** [comment]
>> is a kb:User named "Knora" -> is kb:SystemUser a foaf:Person?

>It's a not a person, because it just represents the Knora API server itself.

Then I propose to make kb:SystemUser a foaf:Agent (since kb:User a foaf:Person) with e.g. a foaf:name and kb:agentID.
Would you consider starting an instance local name with lower case, e.g. kb:systemUser?
Alternatively (preferably?) you can declare kb:SystemUser rdfs:subClassOf foaf:Agent and kb:knoraAPIServer a kb:SystemUser.

**Comment by hanscools** [comment]
>> is a kb:User named "Knora" -> is kb:SystemUser a foaf:Person?

>It's a not a person, because it just represents the Knora API server itself.

Then I propose to make kb:SystemUser a foaf:Agent (since kb:User a foaf:Person) with e.g. a foaf:name and kb:agentID.
Would you consider starting an instance local name with lower case, e.g. kb:systemUser?
Alternatively (preferably?) you can declare kb:SystemUser rdfs:subClassOf foaf:Agent and kb:knoraAPIServer a kb:SystemUser.

**Comment by benjamingeer** [comment]
> Then I propose to make `kb:SystemUser rdf:type foaf:Agent` (since `kb:User a foaf:Person`) with e.g. a `foaf:name` and `kb:agentID`.

We can't do that, because it has to be usable as the object of `kb:attachedToUser`, which has `kb:objectClassConstraint kb:User`.

What I can do is make `kb:User` a subclass of `foaf:Agent` instead of `foaf:Person`.

> Would you consider starting an instance local name with lower case, e.g. `kb:systemUser`?

Yes, I'll do that.

**Comment by benjamingeer** [comment]
Actually on second thought, I'd really rather not change the case of `kb:SystemUser`, because I'd have to make a data transformation just for that. And we already have `UnknownUser` which starts with an upper-case letter.

**Comment by hanscools** [comment]
>> Then I propose to make `kb:SystemUser rdf:type foaf:Agent` (since `kb:User a foaf:Person`) with e.g. a `foaf:name` and `kb:agentID`.

>We can't do that, because it has to be usable as the object of `kb:attachedToUser`, which has `kb:objectClassConstraint kb:User`.

>What I can do is make `kb:User` a subclass of `foaf:Agent` instead of `foaf:Person`.

foaf:familyName and foaf:givenName cannot be used as superproperties since they have a foaf:Person subject.

**Comment by benjamingeer** [comment]
I was thinking we could just remove the references to `foaf`, would you like to put that in a pull request?

**Comment by benjamingeer** [comment]
@hanscools Are any of these points still relevant? If so, could you please make a pull request with any necessary corrections? Otherwise, let's close this issue.
