### ISSUE TITLE
Check the triplestore for inconsistencies

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#33]
This could be either:

* A program that we can run periodically to find inconsistencies.
* A consistency checker that runs each time an update is performed. But this would pose a problem. To create a resource, we first create an empty resource, and then we add each value, one by one. The constraints won't be met until all the values are added.

Ideally, it would use the existing OWL constraints that are defined in the ontologies in the triplestore.

GraphDB [can do consistency checks](http://graphdb.ontotext.com/documentation/standard/reasoning.html#consistency-checks), but the documentation is not clear to me. I've emailed them to ask for clarification.

**Comment by benjamingeer** [comment]
To make it possible to run a consistency checker on each update, we could implement our own application-level transaction management in the store package. SPARQL update syntax allows you to [concatenate multiple operations together using a semicolon](https://www.w3.org/TR/sparql11-update/#updateLanguage). We could implement something in the store package that would:

* Accept a `StartTransaction` message with an API request ID (which we already have).
* Accept one or more `SparqlUpdateRequest` messages with the same request ID, and store them in memory.
* On receipt of a `CommitTransaction` message, concatenate all the requests together into a valid SPARQL update, and run it in a single triplestore transaction.
* On receipt of a `RollbackTransaction` message, discard the saved update requests.

If someday we use the Sesame API instead of HTTP, this could be implemented to use Sesame's transaction management rather than concatenation.

**Comment by benjamingeer** [comment]
cc @subotic

**Comment by benjamingeer** [comment]
Ontotext have clarified the way their consistency checker works. It looks as if we should be able to check for consistency with OWL cardinalities after every update. I'll try to get it working.

**Comment by subotic** [comment]
> If someday we use the Sesame API instead of HTTP, this could be implemented to use Sesame's transaction management rather than concatenation.

This also holds true with the embedded Jena triplestore, when we get it to work some day.

**Comment by benjamingeer** [comment]
The transaction management idea I suggested above would require a change in the values responder. Currently when it gets a `CreateMultipleValuesRequestV1`, it creates each value and then checks whether the value was created. With transaction management, this check would have to be done after all the whole transaction was committed, which means that it would have to be done by the resources responder.

**Comment by benjamingeer** [comment]
With help from Ontotext, I've got GraphDB's consistency checking working with a simplified ontology, checking `owl:cardinality 1`, `owl:maxCardinality 1`, and `owl:minCardinality 1`. Getting this to work requires inference (but only for updates), so I took GraphDB's inference rules file `builtin_RdfsRules.pie`, and added these rules to make a custom rules file, `KnoraRules.pie`:

```
// Knora consistency checks

Consistency: max_cardinality_1
  i <rdf:type> r
  r <owl:maxCardinality> "1"^^xsd:nonNegativeInteger
  r <owl:onProperty> p
  i p j
  i p k [Constraint j != k]
  ------------------------------------

Consistency: min_cardinality_1
  i <rdf:type> r
  r <owl:minCardinality> "1"^^xsd:nonNegativeInteger
  r <owl:onProperty> p
  ------------------------------------
  i p j

Consistency: cardinality_1_not_greater
  i <rdf:type> r
  r <owl:cardinality> "1"^^xsd:nonNegativeInteger
  r <owl:onProperty> p
  i p j
  i p k [Constraint j != k]
  ------------------------------------

Consistency: cardinality_1_not_less
  i <rdf:type> r
  r <owl:cardinality> "1"^^xsd:nonNegativeInteger
  r <owl:onProperty> p
  ------------------------------------
  i p j
```

Then I created a repository with these parameters set:

```
       owlim:ruleset "/path/to/KnoraRules.pie" ;
       owlim:check-for-inconsistencies "true";
```

If I try to do an update that violates one of these rules (e.g. creating a `page` with two values for `description`, which has `owl:maxCardinality 1`), I get an error message like this:

```
Consistency check max_cardinality_1_0 failed:
http://www.knora.org/data/consistency#page1 http://www.w3.org/1999/02/22-rdf-syntax-ns#type _:node8
_:node8 http://www.w3.org/2002/07/owl#maxCardinality "1"^^<http://www.w3.org/2001/XMLSchema#nonNegativeInteger>
_:node8 http://www.w3.org/2002/07/owl#onProperty http://www.knora.org/ontology/consistency#description
http://www.knora.org/data/consistency#page1 http://www.knora.org/ontology/consistency#description "Title Page 2"
http://www.knora.org/data/consistency#page1 http://www.knora.org/ontology/consistency#description "Title Page 1"
```

I think this can work for our SPARQL updates, as long as they can be modified to work with inference. I hope this can be done by removing all unbound variables referring to properties or OWL classes.

**Comment by benjamingeer** [comment]
In issue #34, we discussed replacing `rdfs:domain` and `rdfs:range` with custom constraint properties in `knora-base`. GraphDB's rule language doesn't support reasoning or consistency checking on literal datatypes, only on classes. However, I think it's still helpful for documentation purposes to indicate the expected datatype of a datatype property. So I think it makes sense to put properties like this in `knora-base`:

```
:subjectClassConstraint rdf:type owl:ObjectProperty ;
    rdfs:comment "Specifies the OWL class that the subject of a property must belong to."@en .

:objectClassConstraint rdf:type owl:ObjectProperty ;
    rdfs:comment "Specifies the OWL class that the object of a property must belong to."@en .

:objectDatatypeConstraint rdf:type owl:AnnotationProperty ;
    rdfs:comment "Specifies the type required as the object of a datatype property."@en .
```

Then we can have rules that check `subjectClassConstraint` and `objectClassConstraint`, but not `objectDatatypeConstraint`, which is just an annotation for documentation purposes:

```
Consistency: subject_class_constraint
  p <knora-base:subjectClassConstraint> t
  i p j
  ------------------------------------
  i <rdf:type> t

Consistency: object_class_constraint
  p <knora-base:objectClassConstraint> t
  i p j
  ------------------------------------
  j <rdf:type> t
```

This works with my simplified ontology.

**Comment by benjamingeer** [comment]
Here's a rule that prevents a resource from having a subproperty of `hasValue` if the resource's class has no cardinality for that property:

```
Consistency: cardinality_any
  i <knora-base:hasValue> j
  i p j [Constraint p != <knora-base:hasValue>]
  ------------------------------------
  i <rdf:type> r
  r <owl:onProperty> p
```

**Comment by benjamingeer** [comment]
On branch `wip/ontology-fixes`, I've implemented the change from `rdfs:domain` and `rdfs:range` with custom constraint properties in `knora-base`.

On branch `wip/transaction-management`, I've refactored the resources and values responders to create the new values for a new resource, then check that they were created. The work is still done by the values responder; the resources responder just has to send an additional message.

**Comment by benjamingeer** [comment]
I've implemented transaction management on branch `wip/transaction-management`.

**Comment by benjamingeer** [comment]
Work-in-progress is on branch [wip/consistency-checking](https://github.com/dhlab-basel/Knora/tree/wip/consistency-checking).

**Comment by benjamingeer** [comment]
I turned on consistency checks for the `knora-test` repository, and it found an inconsistency in `knora-base.ttl`, which I fixed. But when I try to load `incunabula-data.ttl`, I get a cryptic error message:

```
Unable to add data to repository: Failed to upload data: 1000
```

I've emailed Ontotext about it.

**Comment by tobiasschweizer** [comment]
It means: I am a teapot, not a triplestore

——
Dr. phil. des. Tobias Schweizer
Digital Humanities Lab
Universität Basel

**Comment by benjamingeer** [comment]
Vassil Momtchev of Ontotext replied:

> I will open a bug request on behalf of you (OWLIM-2867 GraphDB freezes after a consistency check failure during a file import) with fix versions 6.6.4 and 7.0.0-beta1. The issue can be reproduced with 6.6.2 and the latest 6.6.3 release, so I confirm that there is no easy workaround except switching off the tested consistency check functionality.

**Comment by benjamingeer** [comment]
Update from Vassil:

> The issue you have faced is actually not directly related to the consistency checking. I've updated the issue description to: Big transactions, increasing the total number of pages in the index file, causes database to freeze on rollback with java.lang.ArrayIndexOutOfBoundsException: number.
>
> You can workaround the issue if you import a big file which causes no rollbacks and then delete it. This will increase the index of the pages and you won't have to rollback transactions that mess up with this number.

**Comment by benjamingeer** [comment]
By splitting up `incunabula-data.ttl` into smaller pieces, I managed to run the consistency checker on it. It found manh more inconsistencies in ontologies and in test data. I've fixed all these on branch [wip/consistency-checking](https://github.com/dhlab-basel/Knora/tree/wip/consistency-checking) for now, but many of them will need to be fixed in the export script; see #62.

**Comment by benjamingeer** [comment]
The incunabula and images test data files now pass consistency checking.

I also fixed the values responder test data so it passes, but now the values responder tests will have to be changed, because some of them depended on missing values that were required by ontology constraints.

`SipiV1E2ESpec` doesn't pass. My initial impression is that when we submit several updates concatenated into one HTTP request, GraphDB runs the consistency checker on each update, not on the request as a whole.

In May 2015 we asked Dimitar Manov, the GraphDB product manager, about how transactions work when SPARQL updates are sent over HTTP. He replied:

> Each HTTP update is done in a separate transaction.

The GraphDB docs say:

> Consistency checks are used to ensure that the data model is in a consistent state and are applied whenever an update transaction is committed.

This is why we expect the consistency checker to check the the combined effects of all the operations in the HTTP request.

**Comment by benjamingeer** [comment]
Issue #78 is also blocking consistency checking.

**Comment by benjamingeer** [comment]
Ontotext asked Sesame developer Jeen Broekstra why Sesame doesn't process a sequence of SPARQL updates in a single HTTP request as a single transaction, and the gist of his response is that, while Sesame's current behaviour doesn't violate the spec's requirements (the parts that say MUST), it deviates from the spec's recommendations (the parts that say SHOULD). He opened an issue for an enhancement that would treat an update sequence as atomic:

https://github.com/eclipse/rdf4j/issues/25

However, this is likely to take a while. So we'll have to make do with one update per transaction. This shouldn't actually be very hard. We only need to deal with the case where we create a resource plus its values. This could be done by splitting the existing value creation templates into separate templates for the INSERT and WHERE clauses, and numbering the values to be created, to make unique SPARQL variable names for each value. Then the generated INSERT and WHERE clause statements could be combined into one update.

**Comment by benjamingeer** [comment]
Work in progress is on branch `wip/consistency-checking-v2`.

**Comment by benjamingeer** [comment]
Consistency checking needs to take into account deleted values. Specifically:

* If a resource must have at least one X, it shoudn't be allowed to have only a deleted X.
* If a resource can have at most one X, it should be allowed to have two Xs as long as one of them is deleted.

I think this is possible if we make `knora-base:isDeleted` a required predicate on all resources and values. Then we can write:

```
Consistency: max_cardinality_1
  i <rdf:type> r
  r <owl:maxCardinality> "1"^^xsd:nonNegativeInteger
  r <owl:onProperty> p
  i p j
  j <knora-base:isDeleted> "false"^^xsd:boolean
  i p k [Constraint j != k]
  k <knora-base:isDeleted> "false"^^xsd:boolean
  ------------------------------------

Consistency: min_cardinality_1
  i <rdf:type> r
  r <owl:minCardinality> "1"^^xsd:nonNegativeInteger
  r <owl:onProperty> p
  ------------------------------------
  i p j
  j <knora-base:isDeleted> "false"^^xsd:boolean
```

(I think the second rule can't be written unless `isDeleted` is a required predicate.)

This would require some extra pre-update checks when something is deleted:

* Before deleting a value, we'd have to check whether deleting it would violate a cardinality for its containing resource.
* Before deleting a resource, we'd have to check its incoming links, and see whether deleting the resource would violate a cardinality for any of the referring resources.

To ensure that every resource and value has an `isDeleted` predicate, we could change the cardinality of `isDeleted` to `owl:cardinality 1` on `knora-base:Value` and `knora-base:Resource`.

**Comment by benjamingeer** [comment]
I removed the fake transaction manager added in pull request #50, because:

* GraphDB doesn't currently treat multiple updates in an HTTP request as a single transaction.
* Even if it did, the design of the fake transaction manager was misleading. With real transaction management, you can begin a transaction, do an update, then do a query, and your query will see the result of your update, even before you commit the transaction. This wouldn't be possible with the fake transaction manager.

Until there's a SPARQL HTTP transaction managment standard, I think it's better to make it clear that everything that needs to be done in a single transaction has to be constructed as a single update operation.

**Comment by benjamingeer** [comment]
Two things are turning out to be more difficult than I thought:

1. Ensuring that if a resource has a property, the resource class has some cardinality for the property.
2. Taking deleted values into account in cardinality checks.

I'm seeking more help from Ontotext.

**Comment by benjamingeer** [comment]
While waiting for help from Ontotext, I figured out how to get most of the consistency checks working, with a few changes in `knora-base`.

To make it possible to take `knora-base:isDeleted` into account in consistency checks, I made a distinction between 'content properties' (which point to Knora resources or values, i.e. things that can have `knora-base:isDeleted`) and 'system properties' (all others). This way I could write separate rules for these two categories. I also made `knora-base:isDeleted` required on all resources and values; this will require changes in the export script.

For system properties, all the checks are working. For example, this should prevent a resource from having more than one `knora-base:lastModificationDate`.

For content properties, most of the checks work. This is what doesn't work:

* If a content property has `owl:minCardinality 1` or `owl:cardinality 1`, and the only value of the property is marked as deleted, the consistency checker won't see it as a problem.
* If a resource has a content property but the resource class has no cardinality for that property, the consistency checker won't see it as a problem.

If these limitations turn out to be caused by inherent limitations of the consistency checking language, I think we could live with them.

All the test data Turtle files load and pass consistency checks, except for `all_data/incunabula-data.ttl`, which takes a very long time to load, or perhaps it hangs while loading. I'm going to let it run overnight and see what happens.

**Comment by benjamingeer** [comment]
`all_data/incunabula-data.ttl` took 10 hours to load, with no errors. `images-demo-data.ttl` took 4 minutes, also with no errors.

**Comment by benjamingeer** [comment]
Ontotext have confirmed that some of my consistency checks don't work because of a bug in the consistency checker. They're now tracking it as OWLIM-2937 (Consistency rules with multiple consequents do not trigger). They don't have a fix date yet, because they're in the middle of doing two releases.

**Comment by benjamingeer** [comment]
I commented out the things that don't work or are too slow in the consistency checks. What's left is still useful, but won't work if values are marked as deleted.

What really slows down the loading of data is the check on `isDeleted`. I've asked Ontotext about it.

**Comment by benjamingeer** [comment]
Ontotext say:

> The reasoner performance is heavily affected but rules that includes:
>
>     zId: mySlowRule
>       a <owl:propertyDisjointWith> x
>       a b c
>       x y z
>      --------------------------------
>       a b z
>
> In the above example there are premises with non-shared variables, which are very expensive. You can optimize the rule execution with `[cut]` and `[Context <...>]` operators, but they are not very well documented. Unfortunately, the rule optimization process cannot be easily formally defined. This page [1] can give you some ideas how to proceed.
>
> Alternatively, you can contract Ontotext to optimize the ruleset. Feel free to contact us to clarify the consultancy details.

We're looking into contracting them to do it.

**Comment by benjamingeer** [comment]
We're contracting GraphDB to work on the performance issue.

**Comment by benjamingeer** [comment]
Ontotext have implemented some optimisations for our consistency checks. These are now on the `consistency-check-optimisation` branch, with documentation. The optimisations depend on several bug fixes in GraphDB 7.0.3, which has just been released. However, the rules `min_cardinality_1_any_object` and `cardinality_1_not_less_any_object` aren't working for me with GraphDB 7.0.3, although they worked with GraphDB 6.6.4. I'm waiting to see what Ontotext says.

**Comment by benjamingeer** [comment]
Got a hotfix from Ontotext for that problem, but now `[Cut]` doesn't seem to be working. Asked them to look at it.

**Comment by benjamingeer** [comment]
It turns out `[Cut]` is working fine, I had just misunderstood it. Now I can get pull request #159 ready to merge.
