### ISSUE TITLE
Don't use rdfs:range to check data consistency

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#34]
Currently we use `rdfs:range` for consistency checks when creating values: if a property P has an `rdfs:range` of class C, we check that the value submitted is a C. In other words, we use `rdfs:range` to mean that if a value is not a C, it's invalid to make it an object of P.

Ontotext pointed out that this isn't actually what `rdfs:range` means. As [its definition](https://www.w3.org/TR/rdf-schema/#ch_range) says, it really means that if something is an object of P, it is a C. In other words, `rdfs:range` is for inferring the type of the value, not for imposing constraints. They suggest we use another predicate to avoid confusion.

In fact, as far as I can tell, there's no standard predicate for this, so perhaps we should add one to `knora-base`.

**Comment by lrosenth** [comment]
Yes, I think I understand. If "something" has a property of P, the triplestore knows that this "something" must be a C. Right?

**Comment by benjamingeer** [comment]
> Yes, I think I understand. If "something" has a property of P, the triplestore knows that this "something" must be a C. Right?

That would be `rdfs:domain`. With `rdfs:range`, if something has a property P with value V, the triplestore knows that V must be a C.

Instead of `rdfs:domain` (which Knora doesn't currently check) and `rdfs:range`, we could add properties with names like `knora-base:subjectConstraint` and `knora-base:objectConstraint`. Then you could have:

```
:hasStillImageFileValue rdf:type owl:ObjectProperty ;
              rdfs:subPropertyOf :hasFileValue ;
              :subjectConstraint :StillImageRepresentation ;
              :objectConstraint :StillImageFileValue .
```

**Comment by lrosenth** [comment]
Yes, of course – I always confuse the two ways :-)
I like Your idea with :subjectConstraint and :objectConstraint !

By the way, do we understand the cardinalities correctly??? I'm always a little unsure about this. I will have to learn it for my lecture next semester – do You want to help me ???

**Comment by subotic** [comment]
I find ```subjectConstraint``` and ```objectConstraint``` a good idea. Now that you explained the meaning of ```rdfs:domain```and ```rdfs:range```, I can vaguely remember that we already talked about it a long while ago.

**Comment by benjamingeer** [comment]
I think we do understand cardinalities correctly. GraphDB can use them for constraint checks; they've just been explaining to me how to do it (see issue #33), and that was the context in which they pointed out that we `rdfs:range` means something else. I'd be glad to help you with your class.

**Comment by benjamingeer** [comment]
Moving the discussion of this issue to #33.
