### ISSUE TITLE
Switch from Dispatch to Akka HTTP Client and upgrade to Scala 2.12

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#341]
I would like to upgrade Knora to Scala 2.12.

The [Dispatch](https://github.com/dispatch/dispatch) HTTP client library seems to be the only library we use that isn't available for Scala 2.12. Dispatch has been unmaintained for a while.

Since we're already using Akka HTTP, I think we could use its [HTTP Client API](http://doc.akka.io/docs/akka-http/current/scala/http/introduction.html#http-client-api) instead.

This only seems to affect three files:

* `HttpTriplestoreConnector.scala`
* `GraphProtocolAccessor.scala`
* `CompareApiResults.scala` (which we should really remove because it is no longer relevant)

**Comment by subotic** [comment]
Yes, we should. All our E2E tests use already the HTTP Client API.

**Comment by benjamingeer** [comment]
That's good to know, thanks. Work in progress is in #343.
