### ISSUE TITLE
evaluation of combined expressions

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#345]
`resinfo.locations` is an option of a sequence. I want to check that it is not None and contains only one element.

```
if (resinfo.locations.isEmpty || resinfo.locations.get.size != 1)
```

I assume that the second condition is only reached it the first evaluates to false. Is this safe?

I could also write it like this:

```
if (resinfo.locations.nonEmpty && resinfo.locations.get.size == 1)
```

**Comment by tobiasschweizer** [comment]
```
scala> val test: Option[Seq[Int]] = None
test: Option[Seq[Int]] = None

scala> test.isEmpty || test.get.size != 1 
res12: Boolean = true
```

```
scala> val test: Option[Seq[Int]] = Some(Seq(2,3))
test: Option[Seq[Int]] = Some(List(2, 3))

scala> test.isEmpty || test.get.size != 1 
res10: Boolean = true
```

**Comment by tobiasschweizer** [comment]
```
scala> val test: Option[Seq[Int]] = Some(Seq(2))
test: Option[Seq[Int]] = Some(List(2))

scala> test.isEmpty || test.get.size != 1 
res9: Boolean = false
```

**Comment by benjamingeer** [comment]
Yes, it's safe. This is called a short circuit. See the documentation of the `||` method on `Boolean`:

http://www.scala-lang.org/api/2.12.0/scala/Boolean.html#||(x:Boolean):Boolean

> This method uses 'short-circuit' evaluation and behaves as if it was declared as def ||(x: => Boolean): Boolean. If a evaluates to true, true is returned without evaluating b.

All programming languages that I know of do this.

**Comment by tobiasschweizer** [comment]
Thx, this is also what I remember from my programming classes.

> All programming languages that I know of do this.

Wrong, geer script does not care.
