### ISSUE TITLE
An Example Project: Incunabula

### ISSUE THREAD

**Issue by hanscools** [dhlab-basel/Knora#355]
- The Incunabula Ontology:
	- "...The rdf, rdfs, and owl ontologies contain basic [classes and] properties that are used..."
- Properties:
	- "...There are two [kinds of -> of the] OWL properties [used in the Knora Base Ontology]:..."
- "...because the incunabula project [repåresents -> represents] authors simply by their names..."
- Must a book have a title? A book without a title is still a book, not?
```
incunabula:book
    a owl:Class ;
    rdfs:subClassOf knora-base:Resource , [
        rdf:type owl:Restriction ;
        owl:onProperty incunabula:title ;
        owl:minCardinality "1"^^xsd:nonNegativeInteger ] ,... # -> owl:minCardinality "0" ?
```
- A book is declared as a resource, assuming it is not a representation. A page is declared as a still image representation, not a page of a book itself. Nevertheless it is suggested that this still image of the page is part of that physical book. One could expect a page resource and a page representation. A third element is the page image file, named a value, contained by the representation.
- "...The class knora-base:Representation is used for resources that contain metadata about files stored by Knora. [Each It -> knora-base:Representation] has different subclasses that can hold different types of files..."
- General issue: would a consistent naming be considered?:
	- Class: noun; camel case, upper case first character
	- Instance: noun; camel case, lower case first character; a mere instance, not an entity also being a subclass; e.g. incunabula:Book instead of incunabula:book, idem for 'page'.
	- Property: verb and/or preposition + noun; camel case, lower case first character; e.g. incunabula:hasPageNumber instead of incunabula:pagenum
	- As few abbreviations as possible, for clarity
- "...The class knora-base:Resource has a cardinality for knora-base:seqnum..." This is not explicitly declared in KBO.

**Comment by tobiasschweizer** [comment]
Thank you very much for your comments! Let's discuss them later today (14.15) with Lukas.

**Comment by benjamingeer** [comment]
> Must a book have a title? A book without a title is still a book, not?

There could be books without titles in other projects, but in the Incunabula project, all books have a title.

> A book is declared as a resource, assuming it is not a representation. A page is declared as a still image representation, not a page of a book itself. Nevertheless it is suggested that this still image of the page is part of that physical book. One could expect a page resource and a page representation.

This is explained in [the documentation on representations](http://www.knora.org/documentation/manual/rst/knora-ontologies/knora-base.html#representations):

> There are two ways for a project to design classes for representations. The simpler way is to create a resource class that represents a thing in the world (such as ex:Painting) and also belongs to a subclass of Representation. This is adequate if the class can have only one type of file attached to it. For example, if paintings are represented only by still images, ex:Painting could be a subclass of StillImageRepresentation. This is the only approach supported in version 1 of the Knora API.
>
> The more flexible approach, which is allowed by the Knora base ontology and will be supported by version 2 of the Knora API, is for each ex:Painting to use the kb:hasRepresentation property to point to other resources containing files that represent the painting. Each of these other resources can extend a different subclass of Representation. For example, a painting could have a StillImageRepresentation as well as a DDDrepresentation.

The Incunabula project must take the first approach because it must work with API v1 and the current SALSAH GUI, which only support the first approach.

I would definitely be in favour of a consistent naming convention, and your proposed convention looks good to me. @lrosenth ?

Thanks for pointing out the typos, we'll correct them.

**Comment by benjamingeer** [comment]
I'm sorry I haven't managed to do these corrections yet, would you like to put them in a pull request?

**Comment by benjamingeer** [comment]
@hanscools If this issue is still relevant, could you make a pull request with the necessary changes? Otherwise, let's close this issue.
