### ISSUE TITLE
On resource creation, lastModifiactionDate is created more than once for the resource

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#36]
When creating a resource, `knora-base:lastModificationDate` is created several times instead of just once.

How to reproduce this:
- go to the branch `wipi/sipi_integration`
- run Knora
- in another terminal, call `./create_page_with_binaries.py` in `webapi/_test_data/test_route`
- copy the Iri of the new resource returned by Knora and search for it in the triplestore.

You will see that the property exists several times:

| prop                           | value                                                |
|----------------------------|--------------------------------------------- |
| :lastModificationDate |	2016-02-11T14:40:38.256+01:00 |
| :lastModificationDate |	2016-02-11T14:40:38.257+01:00 |
| :lastModificationDate |	2016-02-11T14:40:38.262+01:00 |
| :lastModificationDate |	2016-02-11T14:40:38.271+01:00 |
| :lastModificationDate |	2016-02-11T14:40:38.303+01:00 |

Now why is that? We had both a look at the SPARQL template `createValue.scala.txt`. There is a statement for `lasModificationDate` in Delete, Insert and Where.

**Comment by benjamingeer** [comment]
When I run `./create_page_with_binaries.py`, I get this error:

```
Knora API answered with an error:

500 Server Error: Internal Server Error for url: http://localhost/v1/resources
{"status":4,"error":"org.knora.webapi.FileWriteException: Data directory /tmp/webapi_tmp/ does not exist on server"}
```

**Comment by benjamingeer** [comment]
After I create the directory `/tmp/webapi_tmp` and try again, I get this error:

```
Knora API answered with an error:

500 Server Error: Internal Server Error for url: http://localhost/v1/resources
{"status":4,"error":"spray.can.Http$ConnectionAttemptFailedException: Connection attempt to localhost:1024 failed"}
```

**Comment by benjamingeer** [comment]
Can you please make a test case for this bug that doesn't involve Sipi?

**Comment by benjamingeer** [comment]
Actually, can you try it with one of the tests that already exist in `ResourcesResponderV1Spec` for creating a new resource? You can copy and paste the function `getLastModificationDate` from `ValuesResponderV1Spec`.

**Comment by tobiasschweizer** [comment]
ah, sorry you do not have sipi running.

I will use an example not involving a binary file.

**Comment by tobiasschweizer** [comment]
Ok, now you can pull and run the ResourcesResponderV1Spec

The test `should query resource that has been created` now fails because more than one lastModificationdate is found

Please note that I have commented out the page creation test. I have to change some of the params because the responder's behaviour has changed.

**Comment by benjamingeer** [comment]
Thanks, I'll do this tomorrow.

**Comment by benjamingeer** [comment]
Fixed on branch `wip/sipi_integration`.

The problem was that when a resource is created with its values, the values responder runs multiple concurrent database transactions to create the values. So several transactions could simultaneously find that the resource had no `lastModificationDate`, and they would all add it. The fix just disables the updating of the resource's `lastModificationDate` in the processing of a `CreateMultipleValuesRequestV1`. Since the resource has just been created, I think it doesn't need a `lastModificationDate` anyway; its `creationDate` is enough.
