### ISSUE TITLE
KBO region; default permissions

### ISSUE THREAD

**Issue by hanscools** [dhlab-basel/Knora#361]
- Cf. kb:hasRegionValue: will there be the following, to link a region to something else than a representation?
```
kb:hasRegion
	kb:subjectClassConstraint kb:Resource;
	kb:objectClassConstraint kb:Region.
```
- hasStillImageFileValue: has 3 default permission properties. Is there the intention to put these also on the other similar properties, e.g. hasMovingImageFileValue, and other properties and classes (currently on kb:LinkObj.)?

**Comment by benjamingeer** [comment]
> link a region to something else than a representation

What else could a region be a region of, besides a representation?

> hasStillImageFileValue: has 3 default permission properties

Default permission properties are being removed from `knora-base` in #299.

**Comment by tobiasschweizer** [comment]
Actually a `knora-base:Region` is a region of a `StillImageRepresentation` since a `GeomValue` only represents a 2D shape (at least this is what the GUI supports).

But a region could actually also be 3D ...
