### ISSUE TITLE
Error when hovering over the info box of "has standoff link to"

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#366]
When hovering over the info box 
<img width="25" alt="infobox" src="https://cloud.githubusercontent.com/assets/6000023/21676359/a137610c-d335-11e6-9117-a22938a73633.png">
  of a "has standoff link to", an error occurs:

<img width="2446" alt="hasstandofflinktoinfobox" src="https://cloud.githubusercontent.com/assets/6000023/21675945/12da6720-d334-11e6-9916-e88c22c1f5d8.png">

This is because a `LinkValue` is queried but it (always) belongs to the system user (and not the user that created the reference or something like that):

<img width="1910" alt="linkvalue" src="https://cloud.githubusercontent.com/assets/6000023/21676171/f9785e3a-d334-11e6-964f-c2c9aa0e3d67.png">

So Knora says:

```
{

    "status": 3,
    "error": "org.knora.webapi.ForbiddenException: User http://data.knora.org/users/PSGbemdjZi4kQ6GHJVkLGF does not have permission to see value http://data.knora.org/-umMNyKDSKy7c5m67rbLow/values/_xvRS7epQjiigZIB8dGTbQ",
    "access": "NO_ACCESS"

}
```

I think we handle this as follows: if the user has the right to see the target resource, he can see the link, otherwise not.

**Comment by benjamingeer** [comment]
The docs say:

> Link values created automatically for resource references in standoff are automatically visible to all users, as long as they have permission to see the source and target resources.

This isn't implemented correctly in the values responder.
