### ISSUE TITLE
[biblio-onto.ttl] Are knora-base:subjectClassConstraint and knora-base:subjectClassConstraint a requirement for each owl:ObjectProperty ?

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Knora#373]
Given the discussion in #302 and #308, I thought each `owl:ObjectProperty` in Knora requiered both `knora-base:objectClassConstraint `and `knora-base:subjectClassConstraint`.

However, investigating through biblio-onto.ttl (I was considering testing it for a different project), I came across this:

```
###  http://www.knora.org/ontology/biblio#hasName

:hasName rdf:type owl:ObjectProperty ;
                    rdfs:label "Name"@de ,
                            "Name"@en ,
                            "nom"@fr ,
                            "nome"@it ;
                    rdfs:comment """Represents a Name."""@en ;
                    knora-base:objectClassConstraint knora-base:TextValue ;
                    salsah-gui:guiElement salsah-gui:SimpleText ;
                    rdfs:subPropertyOf knora-base:hasValue .
```
So, my question is: were there some changes regarding `knora-base:subjectClassConstraint` and `knora-base:subjectClassConstraint ` since we last discussed it or is there something wrong with this ontology? Or is it something else I didn't understand?

**Comment by benjamingeer** [comment]
Only `objectClassConstraint` is required, as explained in the documentation:

http://www.knora.org/documentation/manual/rst/knora-ontologies/knora-base.html#constraints-on-the-types-of-property-subjects-and-objects

**Comment by mrivoal** [comment]
Ok, thanks. I missed this update.
