### ISSUE TITLE
create standoff link to non existing resource Iri

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#374]
Knora creates a standoff link to a non existing resource Iri.

I think this is because `checkPropertyObjectClassConstraintForValue` is not executed for standoff link targets since a `TextValueV1` is not a `LinkUpdateV1`.

**Comment by benjamingeer** [comment]
Fixed:

https://github.com/dhlab-basel/Knora/commit/2cc6cc962b776ea874d265dc109a20644c3abc37
