### ISSUE TITLE
how to set up a fake sipi responder for testing?

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#38]
I am now implementing the integration of Sipi into Knora.

In order to test this, it would be good to have a fake sipi responder that simulates the HTTP conversion request sent to Sipi. Otherwise, we could not test it without having Sipi running.

Could you help me with that?

**Comment by benjamingeer** [comment]
@subotic, I think you already did something like this?

**Comment by subotic** [comment]
There is the AssetsRouteV1 that has some hardcoded responses that I used for testing the Salsah GUI. We could expand this. There is also a setting in ```Application.conf``` that defines where the image server is, so that the responders can generate the right URL. This could help during the development so that when there is a Sipi server, we just need to change the address in one place.

**Comment by tobiasschweizer** [comment]
the path to sip is indeed defined in `application.conf`:

```no-highlighting
sipi {
        url = "http://localhost"
        port = 1024
        path-conversion-route = "convert_path"
        file-conversion-route = "convert_file"
        image-mime-types = ["image/tiff", "image/jpeg", "image/png", "image/jp2"]
        movie-mime-types = []
        sound-mime-types = []
    }
```

Could we just define other values in the test's `application.conf`?

**Comment by subotic** [comment]
Yes, of corse. You can even define different values in the test itself.

**Comment by tobiasschweizer** [comment]
I will refactor this so it is more generic: you should actually to able to define which real actors you want to use and for which you want to provide your implementation (fake responders)

**Comment by subotic** [comment]
Maybe this can help: http://stackoverflow.com/questions/8681444/composing-trait-behavior-in-scala-in-an-akka-receive-method
