### ISSUE TITLE
projects api endpoint not working

### ISSUE THREAD

**Issue by kilchenmann** [dhlab-basel/Knora#381]
java.lang.RuntimeException: Cannot automatically determine case class field names and order for 'org.knora.webapi.messages.v1.responder.projectmessages.ProjectsResponseV1', please use the 'jsonFormat' overload with explicit field name specification

**Comment by loicjaouen** [comment]
I'm stumbling on this too

**Comment by subotic** [comment]
Please see pull request #388 and the fixes on the corresponding branch.

**Comment by tobiasschweizer** [comment]
```
{"status":4,"error":"java.lang.RuntimeException: Cannot automatically determine case class field names
 and order for 'org.knora.webapi.messages.v1.responder.projectmessages.ProjectsResponseV1', please use
 the 'jsonFormat' overload with explicit field name specification"}
```

**Comment by subotic** [comment]
sorry for that. should work now.
