### ISSUE TITLE
Knora API Authentication

### ISSUE THREAD

**Issue by andreas-aeschlimann** [dhlab-basel/Knora#384]
@tobiasschweizer suggested that we talk about the authentication method of the new Salsah GUI / Knora API.

I think that the new API should offer an alternative method to the current approach with cookies because:
- The cookie authentication relies on the browser
- Hence new clients (e.g. native apps) will have difficulties implementing the current auth
- A web client application doesn't have full control of the way auth is handled (unless it manually creates/edits/deletes the cookie)

My suggestion: Instead of using a cookie (with key: `sid`), introduce a header value `sid` that can be sent with every request (GET, POST, PUT, DELETE, etc.). All API endpoints would have to be modified, but the modifications would not require a lot of work.

The login endpoint (`/session`) could basically stay as it is, but should not return a cookie when the client does not ask for it. the `sid` already is in the response body now.

FYI: I know that @subotic would like to implement a web token approach in the future, but the work required for that is huge compared to the `sid` header param suggestion above.

**Comment by benjamingeer** [comment]
> Instead of using a cookie (with key: sid), introduce a header value sid that can be sent with every request

I don't see how this would be different. A cookie is already a header value that is sent with every request. What would be the advantage of using a custom header instead of a standard one?

> The cookie authentication relies on the browser

Cookies are well supported by HTTP client libraries in general, not just by browsers.

**Comment by andreas-aeschlimann** [comment]
I agree that a better way would be to use web token or OAuth2, as the "big" ones do.

And of course, this debate is not a question of operability, but of design.

From my experience, using cookies is not that nice with most HTTP client libraries I have worked with (iOS Objective-C/Swift, Android/Java, Windows/C#). It is possible, but it is much more work compared to using a regular HTTP header param. It is however true that in the browser, the authentication is "on the fly" with cookies, which is nice indeed.

The other (more philosophical) question is: Should a truly RESTful API use cookies? 
I would say the client has to be responsible for the session, not the server. :-)

**Comment by lrosenth** [comment]
Indeed, SIPI internally uses webtokens. I would like to use webtolkens too for Nora. What do You think, @ivan.sibotic@unibas.ch<mailto:ivan.sibotic@unibas.ch> ?


Am 23.01.2017 um 22:38 schrieb Andreas Aeschlimann <notifications@github.com<mailto:notifications@github.com>>:


I agree that a better way would be to use web token or OAuth2, as the "big" ones do.

And of course, this debate is not a question of operability, but of design.

From my experience, using cookies is not that nice with most HTTP client libraries I have worked with (iOS Objective-C/Swift, Android/Java, Windows/C#). It is possible, but it is much more work compared to using a regular HTTP header param. It is however true that in the browser, the authentication is "on the fly" with cookies, which is nice indeed.

The other (more philosophical) question is: Should a truly RESTful API use cookies?
I would say the client has to be responsible for the session, not the server. :-)

**Comment by subotic** [comment]
There is an open issue #171 for adding JSON web token support. So, yes, I have planned to implement it. It's on my todo list :-)

**Comment by benjamingeer** [comment]
@andreas-aeschlimann, a cookie is literally just an HTTP header. If your client library doesn't support it, you can easily add the `Cookie:` header yourself. That's exactly what you would have to do with a custom header. I don't see how it would be less work.

> I agree that a better way would be to use web token or OAuth2, as the "big" ones do.

If you think client library support for cookies is inadequate, wait till you see how inadequate their support for web tokens and OAuth2 is. And those are complex protocols that you don't want to have to implement yourself.

> The other (more philosophical) question is: Should a truly RESTful API use cookies? 
> I would say the client has to be responsible for the session, not the server. :-)

Knora also supports HTTP Basic authentication as an alternative to cookies. And again, HTTP Basic authentication is just an HTTP header.

I'm all for supporting newer, better standards, but let's not reinvent the wheel.
