### ISSUE TITLE
knora-admin.ttl does not pass the consistency check

### ISSUE THREAD

**Issue by loicjaouen** [dhlab-basel/Knora#387]
after droping the repo and while running the `graphdb-se-docker-load-test-data.sh` script, we get:

```
> open knora-test
Opened repository 'knora-test'
knora-test> load ../../knora-ontologies/knora-base.ttl into http://www.knora.org/ontology/knora-base
Loading data...
Data has been added to the repository (182 ms)
knora-test> load ../../knora-ontologies/knora-admin.ttl into http://www.knora.org/ontology/knora-base
Loading data...
Unable to add data to repository: Failed to upload data: org.openrdf.repository.RepositoryException: org.openrdf.sail.SailException: java.lang.Exception: Consistency check object_class_constraint_1 failed:
http://www.knora.org/ontology/knora-base#KnownUser http://www.knora.org/ontology/knora-base#belongsToProject _:node115
http://www.knora.org/ontology/knora-base#belongsToProject http://www.knora.org/ontology/knora-base#objectClassConstraint http://www.knora.org/ontology/knora-base#knoraProject
```

Background:

```
[loic@home scripts]$ git log -n 1
commit 5eacd0c2cf8f016b1cbb3eede906a09293918b4b
Author: Benjamin Geer <benjaminlewis.geer@unibas.ch>
Date:   Wed Jan 18 12:53:54 2017 +0100

    Display a compound resource without images (#358)

    * fix (salsah): Display a compound resource without images (ongoing, #334)

    * fix (salsah): If a compound resource doesn’t have images, use a default image.

    * test: Add browser test for compound resource without images.
```

**Comment by subotic** [comment]
Can you please check, that you have the newest ``knora-admin.ttl``. The ``belongsToProject`` property has only ``maxCardinality`` set to ``1``. This is the relevant part:

```
:UserGroup rdf:type owl:Class ;

           rdfs:subClassOf foaf:Group ,
                           [ rdf:type owl:Restriction ;
                             owl:onProperty :groupName ;
                             owl:cardinality "1"^^xsd:nonNegativeInteger
                           ] ,
                           [ rdf:type owl:Restriction ;
                             owl:onProperty :groupDescription ;
                             owl:maxCardinality "1"^^xsd:nonNegativeInteger
                           ] ,
                           [ rdf:type owl:Restriction ;
                             owl:onProperty :status ;
                             owl:maxCardinality "1"^^xsd:nonNegativeInteger
                           ] ,
                           [ rdf:type owl:Restriction ;
                             owl:onProperty :belongsToProject ;
                             owl:maxCardinality "1"^^xsd:nonNegativeInteger
                           ];

           rdfs:comment "A group of Knora users"@en .
```

**Comment by loicjaouen** [comment]
it is that one, the very last one committed on `develop` as 81dfe00dee95485d41ef58419c52994645eea080

**Comment by benjamingeer** [comment]
Which version of GraphDB are you using?

**Comment by benjamingeer** [comment]
Also, do you get the same result with `graphdb-se-local-load-test-data.sh`?

**Comment by loicjaouen** [comment]
I installed 7.2

**Comment by loicjaouen** [comment]
i should try with 7.1 ?

**Comment by benjamingeer** [comment]
We haven't been able to upgrade to versions 7.2 or 8.0.2 because of regressions in the consistency checker, so we're stuck on 7.1 for now. GraphDB have been fixing these bugs as we report them, so I hope we'll be able to upgrade to 8.1.0 when it's released.

**Comment by loicjaouen** [comment]
it works with 7.1
Thanks!

Note: is it possible to download 7.1? I think one has to keep graphdb zip files he downloaded

**Comment by benjamingeer** [comment]
All versions are here:

http://maven.ontotext.com/content/groups/all-onto/com/ontotext/graphdb/graphdb-se/

**Comment by loicjaouen** [comment]
cool, thanks

**Comment by subotic** [comment]
The current supported version of GraphDB is stored inside the ''knora/triplestores/graphdb'' directory.

**Comment by loicjaouen** [comment]
sorry about that!
i missed this directory so far, I just didn't see it.

And there is a Dockerfile too ;)
I rolled mine at https://github.com/LaDHUL/graphdb4knora/blob/master/Dockerfile.prototype

I will document the set-up we use here, but basically it is:
- salsah : dockerized nginx serving static files
- graphdb : dockerized graphdb
- sipi : dockerized sipi
- knora/proxy : dockerized knora and proxy

knora/proxy is `--link`ed to the other containers, and there is an apache proxy mapping requests on port 80 split by domain to salsah, knora and sipi.

**Comment by subotic** [comment]
Our setup will be basically the same :-) We will have additionally a persistent data container holding files from sipi and graphdb.
