### ISSUE TITLE
Bibliography Ontology

### ISSUE THREAD

**Issue by hanscools** [dhlab-basel/Knora#389]
- Following triple can be removed:
`biblio:Publisher rdfs:subClassOf dcterms:publisher.` # Class vs. property
  - There is already:
`publicationHasPublisher rdfs:subPropertyOf dcterms:publisher.`
- Should `knora-base:subjectClassConstraint biblio:Publication `be added to following properties?
	- biblio:publicationIsReprinted
	- biblio:publicationIsReprintedValue
	- biblio:publicationIsTranslated
	- biblio:publicationIsTranslatedValue
- More general: properties and subproperties with different object value types:
	- `biblio:publicationHasTitle a owl:ObjectProperty; rdfs:subPropertyOf dcterms:title.` But `dcterms:title rdfs:range rdfs:Literal`.
	- `biblio:publicationHasDOI a owl:ObjectProperty; rdfs:subPropertyOf bibo:doi.` But `bibo:doi a owl:DatatypeProperty; rdfs:range rdfs:Literal.`
- More general: for clarity, proposal to expand acronyms in rdfs:label and rdfs:comment, e.g.
	- `biblio:publicationHasDOI rdfs:comment """Represents a *DOI -> digital object-identifier (DOI)*."""@en.`
- More general: proposal to generalize semantics of concepts restricted to 1 project when used in more general class and property declarations, e.g.
	- `biblio:publicationHasAuthor knora-base:objectClassConstraint *beol:Person -> knora-base:Person*.`
	- `biblio:Publication rdfs:subClassOf [
		a owl:Restriction;
		owl:onProperty *beol:comment -> knora-base:hasComment*;
		owl:minCardinality "0"^^xsd:nonNegativeInteger].`

**Comment by SepidehAlassi** [comment]
thanks for reviewing the ontology and the comments. 

specifying the knora-base:subjectClassConstraint is not mandatory but knora-base:objectClassConstraint should be specified. 

in knora, external resources like bibo:doi should be specified as subpropertyOf. 

beol:Person has properties like: hasSon, deathDate , etc which makes it very project specific, that is why Person is removed from Knora-base. 

beol:comment should have salsah-gui:guiElement salsah-gui:SimpleText but knora-base:hasComment  salsah-gui:guiElement salsah-gui:Richtext, that is why for now they are two different resources.

**Comment by hanscools** [comment]
Sorry for the delay. Referring to:
#in knora, external resources like bibo:doi should be specified as subpropertyOf. #
This can be done if both properties have a similar object value type.
But e.g. in `biblio:publicationHasDate rdfs:subpropertyOf dct:issued` the first is an object property, the second has an rdfs:Literal as object.
Concerning beol:Person (and some other classes and properties): there can be a more general class Person, usable for more than one Project;  beol:hasDeathDate can be a more general property. A Person having a son can be called a parent, or a biological parent to be more precise. There are ontologies about Human, (or Organism, Agent) that can be reused for this purpose. Maybe we could get together to discuss this?

**Comment by benjamingeer** [comment]
I suggest we leave aside the issue of integrating standard ontologies with Knora ontologies until API version 2, which will provide a rational way to do this. If there are any other points here that are still relevant, @hanscools could you please submit a pull request? Otherwise, let's close this issue.
