### ISSUE TITLE
Knora Admin Ontology (ka)

### ISSUE THREAD

**Issue by hanscools** [dhlab-basel/Knora#393]
- `ka:institutionDescription rdfs:comment "A description of *a user group -> an institution*"@en.`
- kb:address in KBO -> Admin Ontology?
- ka:email
	`rdfs:comment "The email address *and login name of a user -> of an institution or a user* of Knora"@en;
	kb:subjectClassConstraint ka:User. # BUT also used for ka:Institution -> drop?`
- Should ka:familyName have kb:objectDatatypeConstraint xsd:string ?
- Is :userid abandoned?
- ka:isInProjectAdminGroup:
`###http://www.knora.org/ontology/knora-base#*isAdminForProject -> isInProjectAdminGroup*`  
`ka:isInProjectAdminGroup rdf:type owl:ObjectProperty.`
	- To add: cardinality restriction in the ka:User class declaration?
- ka:isInSystemAdminGroup: 
`###http://www.knora.org/ontology/knora-base#*isActiveUser -> isInSystemAdminGroup*`  
`ka:isInSystemAdminGroup rdf:type owl:DatatypeProperty.`
- owl:NamedIndividual abandoned in declaration of individual?
- ka:projectShortname is not declared.
- More general: where xsd:string is declard as a kb:objectDatatypeConstraint of a property, one would expect a datatyped object "x"^^xsd:string instead of a pain literal "x" in a triple with this property.
- Should ka:familyName and ka:givenName have kb:objectDatatypeConstraint xsd:string?
- Should ka:currentproject be restricted on cardinality in the ka:User class declaration?

**Comment by afa-unibas** [comment]
Any status/opinions here?
Should I just try to proceed and propose some resolutions in a PR?

**Comment by benjamingeer** [comment]
Thanks for these, I know Ivan has been quite busy, so if you'd like to make a PR with some proposed solutions, I think that would be great.

**Comment by subotic** [comment]
Yes, thanks. This looks all good to me. A PR would be wonderful.

**Comment by subotic** [comment]
Maybe do this as part of #429?

**Comment by benjamingeer** [comment]
@hanscools, if these points are still relevant, we'd be grateful for a pull request to address them. Otherwise, let's close this issue.
