### ISSUE TITLE
SALSAH: Add global variable for active_project and use it during resource creation

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#394]
- the ``active_project`` should be stored in a global variable whenever the user changes it in the selection
 - adapt ``jquery.resadd.js:1154``: setting the user's active project -> #118

**Comment by tobiasschweizer** [comment]
Could you also have a look at the vocabulary selection when creating a new resource or doing an extended search? Instead of `All`, `Image Collection Demo` is selected (I am logged on as anything user)

**Comment by benjamingeer** [comment]
Since pull request #435, the user can select the active project from a pull-down menu, and it is stored in `SALSAH.userprofile.active_project`. But it is not yet used to choose the default vocabulary when creating a new resource. Since that is #422, I'm closing this issue.
