### ISSUE TITLE
Password checking does not seem to work (authentication)

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#40]
When I submit credentials (username and password), the password does not seem to be checked correctly. Only the existence of the username seems to be checked.

This happens both with HTTP header auth. and when the params are set in the ULR (Get params).

**Comment by subotic** [comment]
I have started working on a spec for testing authentication in the wip/authentication branch. Both tests in 89cf2cd6f633a7493a30ba2101ddd4ad935deee6 pass. I will add more tests until I catch your problem.

**Comment by subotic** [comment]
Fixed in 0e900a2eddf6974beb0c9d41e861fc67431ebbb4
