### ISSUE TITLE
Move Sipi configuration files to the Knora repository

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#404]
I would like to move the Knora relevant Sipi configuration files to the Knora repository.

Which configuration files are needed? There are a few with Knora in the name:

Used for?
 - ``sipi.fake-knora-test-config.lua``

Used for?
 - ``sipi.init-no-knora-test.lua``
 - ``sipi.no-knora-test-config.lua`` 

Testing (serving leaves.jpg)
 - ``sipi.init-knora-test.lua``
 - ``sipi.knora-test-config.lua``
 
Production:
 - ``sipi.init-knora.lua``
 -  ``sipi.knora-config.lua``

**Comment by tobiasschweizer** [comment]
see also https://github.com/dhlab-basel/Sipi/issues/112

**Comment by benjamingeer** [comment]
> sipi.fake-knora-test-config.lua

Used by Sipi's tests (run by `make check`), in which `nginx` is used as a fake Knora.

> sipi.init-no-knora-test.lua
> sipi.no-knora-test-config.lua

These will be deleted, but I'm leaving them for now because they don't work, and I'd like to understand why.

**Comment by subotic** [comment]
Cool, thanks. So we are basically left with:

Testing (serving leaves.jpg)
 - ``sipi.init-knora-test.lua``
 - ``sipi.knora-test-config.lua``
 
Production:
 - ``sipi.init-knora.lua``
 -  ``sipi.knora-config.lua``

**Comment by subotic** [comment]
I will take another stab at this.
