### ISSUE TITLE
complete Knora-Sipi integration tests 

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#410]
In `src/it/org/knora/webapi/e2e/v1/SipiV1ITSpec` there is already one test that tries to add a Knora resource of type `knora-base:StillImageRepresentation` involving an image ("create an 'incunabula:page' with binary data").

Could you write the remaining tests? You find the corresponding python scripts in `_test_data/test_route`. Both the GUI and the non GUI cases are tested.

They can be removed once they are implemented in scala.

**Comment by tobiasschweizer** [comment]
you will have to change the name of the root user to "root@example.com"

**Comment by subotic** [comment]
I wouldn't necessary use the **root** user in tests anymore, except if you want to test something that only the **root** user is allowed to do. With the **root** user, permission checking is basically turned off.

More or less, all the defined projects have a user in the two main groups (``ProjectAdmin`` and ``ProjectMember``). There is also the ``SharedAdminTestData`` object, which contains everything from ``admin-data.ttl``.

**Comment by benjamingeer** [comment]
This is blocked by https://github.com/dhlab-basel/Sipi/issues/121.
