### ISSUE TITLE
knora-base:standoffTagHasInternalReference

### ISSUE THREAD

**Issue by hanscools** [dhlab-basel/Knora#411]
Should :subjectClassConstraint and :objectClassConstraint be swapped or property renamed to knora-base:isInternalReferenceOfStandoffTag?
```
###  http://www.knora.org/ontology/knora-base#standoffTagHasInternalReference
:standoffTagHasInternalReference rdf:type owl:ObjectProperty ;
                 rdfs:subPropertyOf :objectCannotBeMarkedAsDeleted ;
                 :objectClassConstraint :StandoffTag ;
                 :subjectClassConstraint :StandoffInternalReferenceTag .
```

**Comment by benjamingeer** [comment]
This is correct as it is. A `StandoffInternalReferenceTag` is a standoff tag that has a reference to another standoff tag. For example, a footnote reference tag could contain a reference to a footnote content tag.

**Comment by tobiasschweizer** [comment]
You can find more information here <http://www.knora.org/documentation/manual/rst/knora-ontologies/knora-base.html#internal-links-in-a-textvalue> and here <http://www.knora.org/documentation/manual/rst/knora-api-server/api_v1/create-a-mapping.html#internal-references-in-an-xml-document>

**Comment by tobiasschweizer** [comment]
The definition in knora-base looks like follows:

```
###  http://www.knora.org/ontology/knora-base#StandoffInternalReferenceTag

:StandoffInternalReferenceTag rdf:type owl:Class ;

                        rdfs:subClassOf :StandoffDataTypeTag,
                                        :ValueBase,
                                        [ rdf:type owl:Restriction ;
                                          owl:onProperty :standoffTagHasInternalReference ;
                                          owl:cardinality "1"^^xsd:nonNegativeInteger
                                        ] ;

                        rdfs:comment "Represents an internal reference in a TextValue"@en .


```
