### ISSUE TITLE
Knora Standoff Ontology and dc:

### ISSUE THREAD

**Issue by hanscools** [dhlab-basel/Knora#412]
In the Knora Standoff Ontology is:

`@prefix dc: <http://www.knora.org/ontology/dc#> .
`

Can this be removed, because dc: is further not used?

**Comment by tobiasschweizer** [comment]
Yes, absolutely. I tend to copy and paste prefixes from other ontologies.

Actually I would like to get rid of the `:` prefix as it is relative to the file and may cause problems when moving definitions to other files.

**Comment by benjamingeer** [comment]
@hanscools, if you would like to make this change, please make a pull request for it.
