### ISSUE TITLE
After an image is uploaded, the field "new entry" doesn't open where expected

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Knora#413]
I have several resources linked to each others with a `knora-base:hasLinkTo` property.

Those properties work fine (meaning that by selecting it, I am able to open a new window in which a new instance of the linked resource is created) as long as I don't upload an image.

But if I have a resource` rdfs:subClassOf` `knora-base:StillImageRepresentation`, once I uploaded the image, the "new entry" box is not displayed in front of the right property but much higher (which first made me think that it wasn't displayed at all).

![capture d ecran 2017-02-08 a 13 53 15](https://cloud.githubusercontent.com/assets/17294309/22738102/48452296-ee06-11e6-9191-950c6b72062d.png)

**Comment by tobiasschweizer** [comment]
This might be a CSS problem. How could we reproduce this? Does it also occur when you try to add a incunabula:page?

**Comment by mrivoal** [comment]
No, it doesn't happen with incunabula:page.

I think it only occurs when several resources are imbricated with a `knora-base:hasLinkTo` property.

To reproduce it, you will need to create first a resource with a `knora-base:hasLinkTo` property pointing to a subclass of `knora-base:StillImageRepresentation` and you will need this subclass of `knora-base:StillImageRepresentation` to have a  `knora-base:hasLinkTo` property to another resource. And I guess it is more likely to happen if you have quite a long list of properties for this resource, because it also depends on where you are in the window when you select the `knora-base:hasLinkTo` property (it looks like the nearer you are from the bottom of the window, the higher the "new entry" label will be).

I can provide you with the ontology I have been working on, if you want.

**Comment by tobiasschweizer** [comment]
What about the page's part_of?

**Comment by mrivoal** [comment]
It doesn't happen because the exact case is not reproduced. For the problem to (maybe) occur in incunabula, I should land on incunabula:page from a  `knora-base:hasLinkTo` property in another resource. If I landed in incunabula:page from a `knora-base:hasLinkTo` property in incunabula:Book, maybe it would occur. 

That why I suggested I can give you the ontology I am talking about.

**Comment by tobiasschweizer** [comment]
There might be sidebands that refer to images.

**Comment by mrivoal** [comment]
Here it is.

[ddd-ttl.zip](https://github.com/dhlab-basel/Knora/files/773458/ddd-ttl.zip)
*You will find the "data" named graph, because this project comes with a lot of lists but I don't think you need it.*

You can log in with ddd@unil.ch and "test" password.

In order to reproduce the problem, in **drawings-gods** project, try to add a resource **Personne**.
The property **a dessiné** is a `knora-base:hasLinkTo property`. Choose "nouvelle entrée".

Then, you can create a **Dessin**, a resource class that is a subclass of `knora-base:StillImageRepresentation`. Upload an image for the **a fichier d'image** property.

Then scroll down (I guess you will have too because the window is too small) to the **Instruction suivie** property (or the **Contrôle qualité associé**, like in the screenshot above), which is an new `knora-base:hasLinkTo property`. Then, the "nouvelle entrée" tab should be invisible or at least much higher in the window than expected.

The browser I am using is Chrome, by the way.

**Comment by loicjaouen** [comment]
just for reference for when we tackle this, the problem comes from [jquery.searchbox.js:L202](https://github.com/dhlab-basel/Knora/blob/develop/salsah/src/public/js/jquery.searchbox.js#L202):

```
					$this.on('focusin.searchbox', function() {
						initialize_searchboxlist($this, new_dialog_title);
						pos = $this.position();
						if (!$this.hasClass('propedit_frame')) {
							pos.top +=  $this.closest('.propedit_frame').scrollTop() + $this.outerHeight();
						}
						localdata.ele.sel.css({
							left: pos.left,
							top: pos.top
						}).show();
						$this.val('');
					});
```

this line is misbehaving:

```
pos.top +=  $this.closest('.propedit_frame').scrollTop() + $this.outerHeight();
```

**Comment by loicjaouen** [comment]
So there is no need for special data.  
Just add a resource, this resource has a link to another resource that pops-up in a new window.  
If that other resource has a searchbox, then you would better not be playing with the scroll bar, or it will confuse the computation of [jquery.searchbox.js:L202](https://github.com/dhlab-basel/Knora/blob/develop/salsah/src/public/js/jquery.searchbox.js#L202) cited above that tells where this searchbox should be displayed.

here's an animated gif showing it:
![jumping-select-box](https://cloud.githubusercontent.com/assets/3933654/25740589/76914e30-3187-11e7-9619-6b44c53cd714.gif)

I am looking at the code right now.
