### ISSUE TITLE
Running tests with graphdb

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#42]
I have installed graphdb SE 6.62 on my machine (Mac).

I ran the following scripts:
- webapi/scripts/graphdb-se-load-test-data.sh (test)
- webapi/scripts/graphdb-free-ci-prepare.sh (test-unit)

Now, using graphdb with Knora (test repo) works fine (setting in `application.conf`), but the tests do not work with graphdb: 

```
Load test data *** FAILED *** (1 second, 828 milliseconds)
```

The test data cannot be loaded into test-unit. But the test-unit repository exists (I can access it in the over the webinterface). I remember that we had that problem before but thought that running the script would solve it.

What am I doing wrong?

**Comment by benjamingeer** [comment]
Have you tried restarting Tomcat?

**Comment by tobiasschweizer** [comment]
yes :-)

**Comment by tobiasschweizer** [comment]
I have just rebooted it again and now it works

I have recognised that the bug with lastModificationData only only occurs with graphdb.

I have not pulled your changes yet and in ResourcesReponderV1Spec the test fails for graphdb, but not for fuseki:

```
should query resource that has been created *** FAILED *** (56 milliseconds)
[info]   false did not equal true (ResourcesResponderV1Spec.scala:307)
```

**Comment by benjamingeer** [comment]
If I remember correctly, Fuseki doesn't do concurrent updates.

**Comment by benjamingeer** [comment]
Also, `graphdb-free-ci-prepare.sh` is for GraphDB Free, but you're using GraphDB SE, so you should run `graphdb-se-ci-prepare.sh`. And then if I remember correctly, you have to restart Tomcat, for reasons we don't understand.

**Comment by tobiasschweizer** [comment]
I ran ` webapi/scripts/graphdb-se-ci-prepare.sh`, I juste copied and pasted the wrong name above :-)
