### ISSUE TITLE
After logging in Salsah, the default project selected is not the one the user belongs to

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Knora#422]
After a user belonging to a project has identified himself, when he want to add a new resource, the default project selected is not the current project he belongs to. 

![capture d ecran 2017-02-16 a 11 00 20](https://cloud.githubusercontent.com/assets/17294309/23016549/293e8e3c-f437-11e6-828e-d41fe75deccf.png)

Here, it is the Image Collection Demo that appears to be the default project while I am logged as a "stardom" project member.

I don't know if it is related to #415?

**Comment by benjamingeer** [comment]
Since pull request #435, the user can select the active project from a pull-down menu, and it is stored in `SALSAH.userprofile.active_project`. But it is not yet used to choose the default vocabulary when creating a new resource.

**Comment by loicjaouen** [comment]
fixed since #477
