### ISSUE TITLE
Salsah is not able to handle an image with a "restricted view"

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Knora#425]
Sipi gives a '404 Not found' error when a user tries to open a resource with a Restricted View permission.

Then, Salsah gives a Time Out.

It is linked to #86.

**Comment by benjamingeer** [comment]
Are you sure it's Sipi returning a 404? Or is it Knora? Have you tried this with the current `develop` branch of Sipi? There's a test for this, which passes for me. If you type `make check` in Sipi's `build` directory, one of the tests that's run says: `Sipi should return a restricted image in a smaller size`. Does it pass or fail for you? If it passes, then the problem is in Knora or Salsah, not in Sipi.

**Comment by mrivoal** [comment]
No, I am not sure. I have discussed it with @loicjaouen, he tends to believes it is Sipi but we haven't run the test you mentioned. We will when he comes back on monday 27th (as I am not sure where is the Sipi build directory on our test server).

**Comment by loicjaouen** [comment]
yes, it is sipi, when viewing an resource, salsah knows that it has to display an image and sends the request to sipi, a regular: 
```
http://sipi-test.unil.ch/knora/4f3uXGsi7Zk-Bn4eBnsdE2G.jpx/full/1000,666/0/default.jpg
```

and sipi complains about:
```
Sipi: Accepted connection from 172.18.0.5
cookie key is invalid: __utma=145475696.990924912.1487255275.1487255275.1487255275.1; __utmc=145475696; __utmz=145475696.1487255275.1.1.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided)
Sipi: File  not found
```

and sends back an `http 404 Not Found` response.

The same call ends up successfully when the user is logged in.

**Comment by loicjaouen** [comment]
ah, and sipi version says: 
```
Sipi Version 1.0 Beta (build 2017-02-03 09:47)
```

**Comment by benjamingeer** [comment]
`__utma` is a Google Analytics cookie, I wonder why Sipi is seeing it. Could you make me a set of test data that I can use to reproduce this?

**Comment by tobiasschweizer** [comment]
Sipi expects the key value pair `sid=<sessionid>` to be present in the request's cookie header.

`sipi.init-knora.lua`:
```
-- tries to extract the Knora session id from the cookie:
        -- gets the digits between "sid=" and the closing ";" (only given in case of several key value pairs)
        -- returns nil if it cannot find it
        session_id = string.match(cookie, "sid=(%d+);?")
```

When you login to Knora, a second request is sent to Sipi, setting `sid` (see `index.html` in SALSAH). In each following request, `sid` is sent to Sipi, so it can authenticate the user to Knora.

This is not very elegant and therefor we are going to get rid of the roundtrip.

**Comment by loicjaouen** [comment]
and could it be that `sipi` answers by a `404 not found` when `sid` is not in the cookie header?

**Comment by benjamingeer** [comment]
I just don't understand why the browser would send a `google.com` cookie to Sipi at all. Each cookie is supposed to be sent only to the domain that produced it.

**Comment by mrivoal** [comment]
@benjamingeer, do you still need a set of data? What would you need?

I can give you ontology + admin + permission + data named graphs, but you won't have the images...
So maybe, the best option would be that I give you ontology + permissions + admin and that I guide you through data input? What do you think?

**Comment by tobiasschweizer** [comment]
> and could it be that sipi answers by a 404 not found when sid is not in the cookie header?

In that case, Sipi asks Knora about view permissions for an unknown user because the client cannot be identified.

> I just don't understand why the browser would send a google.com cookie to Sipi at all. Each cookie is supposed to be sent only to the domain that produced it.

I experienced some problems in the past because the cookie contained weird data (this is the most exact term I can provide you with :-), sorry). This is why I introduced a regex because we cannot assume that the cookie header starts with `sid`.

**Comment by benjamingeer** [comment]
> do you still need a set of data? What would you need?

You could email me a zip file containing:

* Turtle files for:
  * your ontology
  * The resource and file value you're trying to view
* the admin data for the project
* the image file you're trying to view
* your Sipi config file

Basically anything necessary to configure Knora and Sipi from scratch to reproduce this on `localhost`. Please test it yourself first on `localhost`. Before I can debug it, I need to be able to reproduce it.

> I experienced some problems in the past because the cookie contained weird data

There's just no way a browser should send a cookie from `google.com` to `sipi-test.unil.ch`. Something very strange is happening.

**Comment by mrivoal** [comment]
Ok, we will test it on localhost and send you our Sipi config file when @loicjaouen is back (it may not look like it but he is in holidays until neek week).

**Comment by mrivoal** [comment]
I have been unsuccessful in my attempts to reproduce the issue locally.

Once we have updated our current instances of Knora and Sipi, I will let you know if I face the same problem again. For now, I consider the issue closed  but I will let you close it, as some (other?) issues have been raised ealier by @tobiasschweizer in the topic.

Thanks for your help.

**Comment by benjamingeer** [comment]
OK no problem.

**Comment by loicjaouen** [comment]
@benjamingeer 
> There's just no way a browser should send a cookie from google.com to sipi-test.unil.ch. 

the cookies were attached to `.unil.ch`

**Comment by benjamingeer** [comment]
@loicjaouen Was this a problem with your configuration or web proxy, or do you think it's a bug in Knora or Sipi?

**Comment by loicjaouen** [comment]
For the cookies specifically, we are accessing our test set-up which is behind a web proxy.

So the services are bound to DNS aliases: {salsah-test, knora-test, sipi-test}.unil.ch.
They all point to the same IP where an apache instance proxies the traffic to docker containers (on the same host).

Whether it is a bug in Knora or Sipi, I can't say, we couldn't reproduce it on a fresh install on our test set-up.

Here are the cookies:
![capture d ecran 2017-02-28 a 15 41 39](https://cloud.githubusercontent.com/assets/3933654/23409845/647667fa-fdcd-11e6-9b80-5ffdede90202.png)

And here is the picture now showing up, blurred as it should be, still with the cookies in the request:
![capture d ecran 2017-02-28 a 15 42 42](https://cloud.githubusercontent.com/assets/3933654/23409930/bc653522-fdcd-11e6-97f0-8668e1ef9f35.png)

No more `404`.

The update was just about building new images and new containers, the docker set-up, network set-up or proxy config remained as they were.

Let's keep this for the record if it something similar pops up later, bot for now it can be closed.

**Comment by benjamingeer** [comment]
I wonder if your web proxy is confusing the browser, making it think that a cookie from `google.com` actually came from `unil.ch`. Since these are Google Analytics cookies, this might be helpful:

https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage
