### ISSUE TITLE
Documentation of DateValue type missing

### ISSUE THREAD

**Issue by SepidehAlassi** [dhlab-basel/Knora#431]
Example: instead of 1974 , date_value should be GREGORIAN:1974 . This is not documented.

**Comment by benjamingeer** [comment]
@tobiasschweizer I looked everywhere for it in the docs but couldn't find it. Did I miss it somewhere?

**Comment by tobiasschweizer** [comment]
Do you mean the formal specification of a Knora date value string in API V1 format? 

There is some information here: http://www.knora.org/documentation/api/modules/_basicmessagecomponents_.basicmessagecomponents.html#datestring

**Comment by benjamingeer** [comment]
Thanks, that's it. But it's too hard to find. I'll add it to the RST docs.

**Comment by tobiasschweizer** [comment]
Ok, that's fine. Can you think for other things that might have to be added there?
