### ISSUE TITLE
Generate XML schema from ontology

### ISSUE THREAD

**Issue by SepidehAlassi** [dhlab-basel/Knora#434]
- there should be a route which extracts xsd from ontology
- this xsd should be used by user and by Knora to validate xml

**Comment by benjamingeer** [comment]
Then it should be possible to put `GREGORIAN:1974` in a `TextValue` if someone really wants to do that.

**Comment by benjamingeer** [comment]
Also, we should separate the `id` of the element from the `rdfs:label` of the resource that's created. I suspect that `id` will generally come from a database table primary key, while the label will be descriptive text, which might not be unique.

**Comment by benjamingeer** [comment]
Lukas decided that it's clearer and less error-prone to specify the value type in the XML, like this:

```
<biblio:publicationHasDate type="date">GREGORIAN:1974</biblio:publicationHasDate>
```

It will also be easier to parse it this way.

**Comment by benjamingeer** [comment]
Splitting this issue into several issues.
