### ISSUE TITLE
add file handling to ValuesRoute

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#44]

**Comment by tobiasschweizer** [comment]
cc @benjamingeer 

Adding support for changing an existing file in the values route, the following questions occurred to me. Normally, the path for changing an existing value (HTTP Put-request ) looks like this: `v1/values/valueIri`

But in case of a file value, the user does not know about the value Iri since file values are treated specially in Knora's response format: as locations (see `ResourcesResponderV1.scala`, line 1266).

That means that the user does not know the 'real' value (nor its Iri) that represents the file value in Knora (for example a `hasStillImageFileValue`).

Do we need another path for this case ? For example `v1/values/fileValue/resourceIri`?

And then a Put-request would just add a new version to the file value, replacing the current one.

**Comment by benjamingeer** [comment]
We'll do this in API v2.
