### ISSUE TITLE
Timeout at login

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#443]
After having updated to the latest commit on `develop`, I sometimes have this problem logging in from the browser:

```
{"status":4,"error":"java.util.concurrent.TimeoutException: Futures timed out after [3 seconds]"}

"NetworkError: 500 Internal Server Error - :3333/v1/session"
```

This does only happen sometimes right after having loaded all the data and started webapi. Could we increase the timeout? Maybe the new hashlib is slower than the old one?

```
[2017-03-01 15:47:40,782] ERROR - KnoraService(akka://webapi) - Unable to run route :3333/v1/session
webapi java.util.concurrent.TimeoutException: Futures timed out after [3 seconds]
webapi  at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:255)
webapi  at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:259)
webapi  at scala.concurrent.Await$.$anonfun$result$1(package.scala:190)
webapi  at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:167)
webapi  at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3313)
webapi  at scala.concurrent.forkjoin.package$ForkJoinPool$.managedBlock(package.scala:22)
webapi  at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:165)
webapi  at scala.concurrent.Await$.result(package.scala:123)
webapi  at org.knora.webapi.routing.Authenticator$.org$knora$webapi$routing$Authenticator$$getUserProfileByEmail(Authenticator.scala:480)
webapi  at org.knora.webapi.routing.Authenticator$.org$knora$webapi$routing$Authenticator$$authenticateCredentials(Authenticator.scala:298)
webapi  at org.knora.webapi.routing.Authenticator$.org$knora$webapi$routing$Authenticator$$extractCredentialsAndAuthenticate(Authenticator.scala:281)
webapi  at org.knora.webapi.routing.Authenticator.doLogin(Authenticator.scala:73)
webapi  at org.knora.webapi.routing.Authenticator.doLogin$(Authenticator.scala:71)
webapi  at org.knora.webapi.routing.v1.AuthenticateRouteV1$.doLogin(AuthenticateRouteV1.scala:33)
webapi  at org.knora.webapi.routing.v1.AuthenticateRouteV1$.$anonfun$knoraApiPath$8(AuthenticateRouteV1.scala:65)
webapi  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResult$2(BasicDirectives.scala:61)
webapi  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:154)
webapi  at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$2(RouteConcatenation.scala:47)
webapi  at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
webapi  at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
webapi  at akka.http.scaladsl.util.FastFuture$.flatMap$extension(FastFuture.scala:26)
webapi  at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi  at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRequestContext$2(BasicDirectives.scala:43)
webapi  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:154)
webapi  at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$2(RouteConcatenation.scala:47)
webapi  at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
webapi  at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
webapi  at akka.http.scaladsl.util.FastFuture$.flatMap$extension(FastFuture.scala:26)
webapi  at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi  at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$2(RouteConcatenation.scala:47)
webapi  at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
webapi  at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
webapi  at akka.http.scaladsl.util.FastFuture$.flatMap$extension(FastFuture.scala:26)
webapi  at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi  at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi  at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi  at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi  at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi  at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi  at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi  at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi  at akka.http.scaladsl.server.directives.ExecutionDirectives.$anonfun$handleExceptions$2(ExecutionDirectives.scala:32)
webapi  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResultWith$2(BasicDirectives.scala:67)
webapi  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:154)
webapi  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResult$2(BasicDirectives.scala:61)
webapi  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:154)
webapi  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResultWith$2(BasicDirectives.scala:67)
webapi  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:154)
webapi  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResultWith$2(BasicDirectives.scala:67)
webapi  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:154)
webapi  at akka.http.scaladsl.server.directives.ExecutionDirectives.$anonfun$handleExceptions$2(ExecutionDirectives.scala:32)
webapi  at akka.http.scaladsl.server.Route$.$anonfun$asyncHandler$1(Route.scala:73)
webapi  at akka.stream.impl.fusing.MapAsync$$anon$23.onPush(Ops.scala:1147)
webapi  at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:747)
webapi  at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:649)
webapi  at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
webapi  at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:423)
webapi  at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
webapi  at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
webapi  at akka.actor.Actor.aroundReceive(Actor.scala:484)
webapi  at akka.actor.Actor.aroundReceive$(Actor.scala:484)
webapi  at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
webapi  at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
webapi  at akka.actor.ActorCell.invoke(ActorCell.scala:495)
webapi  at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
webapi  at akka.dispatch.Mailbox.run(Mailbox.scala:224)
webapi  at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
webapi  at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
webapi  at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
webapi  at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
webapi  at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by tobiasschweizer** [comment]
I wonder where the timeout of 3 seconds comes from. Having had a look at `Authenticator.scala`, I found this line twice:

`Await.result(userProfileV1Future, Duration(3, SECONDS))`

**Comment by subotic** [comment]
In the long run, we should try to get rid of ``await``, but as a quick fix, we could increase the timeout. As @benjamingeer said, if it takes longer than a fraction of a second, then there is another problem. If this is happening intermittently then it could be a problem with GraphDB, i.e. slowing down.

**Comment by tobiasschweizer** [comment]
I experienced the login to take quite some time lately, so I wonder if the await could be a reason for that too.

**Comment by benjamingeer** [comment]
The await doesn't make anything take longer than it would otherwise. It's just a maximum time limit before a timeout exception is thrown. It would be a bottleneck under high concurrency, but that's not the case in your tests.

**Comment by benjamingeer** [comment]
Three seconds is an arbitrary number, we can increase it but we should find out what's taking so long.

**Comment by subotic** [comment]
Well, ``scrypt`` is meant to take longer [Scrypt](https://en.wikipedia.org/wiki/Scrypt), but 3 seconds is a lot of time.

**Comment by tobiasschweizer** [comment]
When I open the extended search window in the GUI before logging in, I do not get the timeout when doing the login.

Since quite some time I experience the first request to webapi to be slow.

**Comment by subotic** [comment]
> This does only happen sometimes right after having loaded all the data and started webapi.

Could you try to wait some time after loading the data? Maybe GraphDB needs a few more minutes to finish creating the index?

**Comment by tobiasschweizer** [comment]
When starting webapi, the ontology cahce is built. This involves a lot of queries as well. Shouldn't it time out then as well?

**Comment by benjamingeer** [comment]
> When starting webapi, the ontology cahce is built. This involves a lot of queries as well. Shouldn't it time out then as well?

This suggests that the problem is in Knora or Akka rather than in GraphDB.

**Comment by benjamingeer** [comment]
You can try scrypt yourself on the command line, it's practically instantaneous.

**Comment by benjamingeer** [comment]
And I've been seeing this problem for months, since long before we switched to scrypt.

**Comment by tobiasschweizer** [comment]
> This suggests that the problem is in Knora or Akka rather than in GraphDB.

I guess you could be right.

**Comment by loicjaouen** [comment]
we should profile to check

**Comment by benjamingeer** [comment]
Loic is right, who wants to do this? I have quite a lot of PRs on my plate at the moment.

**Comment by benjamingeer** [comment]
Tobias, can you reproduce this with Fuseki?

**Comment by tobiasschweizer** [comment]
The problem is that I experience that behavior with the timeout on login only on the BEOL VM, not locally.

**Comment by benjamingeer** [comment]
OK but I often experience a delay of a second or two when logging into SALSAH just after starting webapi (at least with GraphDB, I haven't checked with Fuseki). It's not long enough to cause a timeout, but it still seems much longer than necessary.

**Comment by benjamingeer** [comment]
I've done some investigation on the `wip/performance-debugging` branch. One thing that stands out:

```
webapi [2017-03-15 17:16:30,830] DEBUG - UsersResponderV1 - ************* UsersResponderV1.userDataQueryResponse2UserProfile: getting projectInfos took 514 millis
```

I added a config option `profile-queries`, which times SPARQL queries. All the queries done during login seem very fast, much faster than half a second. So I don't understand where this delay is coming from.

**Comment by subotic** [comment]
> getting projectInfos

If all SPARQL queries run fast, then maybe it is Akka? Is it possible that the `ProjectsResponderV1` actor takes in some cases longer to **start** processing the request? Maybe we have to many actors running per default (large actor pools), so when running on an underpowerd machine, Akka gets congested?

**Comment by benjamingeer** [comment]
I'll try profiling it with [VisualVM](https://visualvm.github.io/), which [can be integrated into IntelliJ IDEA](https://plugins.jetbrains.com/plugin/7115-visualvm-launcher).

**Comment by tobiasschweizer** [comment]
if it works, could you write a short guide explaining how to do that and add it to the docs? Thx.

**Comment by benjamingeer** [comment]
When I try to run Knora in VisualVM, I get an out of memory error as IntelliJ tries to compile a large class:

```
Information:Module "webapi" was fully rebuilt due to project configuration/dependencies changes
Information:17/03/17 15:42 - Compilation completed with 1 error and 34 warnings in 1m 27s 826ms
Error:scalac: Error while emitting org/knora/webapi/responders/v1/ResourcesResponderV1SpecContextData$
Java heap space
Warning:scalac: java.lang.OutOfMemoryError: Java heap space
Warning:scalac: 
Warning:scalac: 	at scala.tools.asm.tree.analysis.Frame.<init>(Frame.java:88)
Warning:scalac: 	at scala.tools.asm.tree.analysis.Frame.<init>(Frame.java:99)
Warning:scalac: 	at scala.tools.asm.tree.analysis.Analyzer.newFrame(Analyzer.java:439)
Warning:scalac: 	at scala.tools.asm.tree.analysis.Analyzer.merge(Analyzer.java:509)
Warning:scalac: 	at scala.tools.asm.tree.analysis.Analyzer.analyze(Analyzer.java:274)
Warning:scalac: 	at scala.tools.nsc.backend.jvm.analysis.BackendUtils$AsmAnalyzer.<init>(BackendUtils.scala:37)
Warning:scalac: 	at scala.tools.nsc.backend.jvm.opt.LocalOpt.removeUnreachableCodeImpl(LocalOpt.scala:488)
Warning:scalac: 	at scala.tools.nsc.backend.jvm.opt.LocalOpt.removalRound$2(LocalOpt.scala:275)
Warning:scalac: 	at scala.tools.nsc.backend.jvm.opt.LocalOpt.methodOptimizations(LocalOpt.scala:354)
Warning:scalac: 	at scala.tools.nsc.backend.jvm.opt.LocalOpt.$anonfun$methodOptimizations$1(LocalOpt.scala:195)
Warning:scalac: 	at scala.tools.nsc.backend.jvm.opt.LocalOpt.$anonfun$methodOptimizations$1$adapted(LocalOpt.scala:194)
Warning:scalac: 	at scala.tools.nsc.backend.jvm.opt.LocalOpt$$Lambda$1667/273875226.apply(Unknown Source)
Warning:scalac: 	at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:157)
Warning:scalac: 	at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:157)
Warning:scalac: 	at scala.collection.TraversableOnce$$Lambda$93/467079109.apply(Unknown Source)
Warning:scalac: 	at scala.collection.Iterator.foreach(Iterator.scala:929)
Warning:scalac: 	at scala.collection.Iterator.foreach$(Iterator.scala:929)
Warning:scalac: 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1406)
Warning:scalac: 	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
Warning:scalac: 	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
Warning:scalac: 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
Warning:scalac: 	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:157)
Warning:scalac: 	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:155)
Warning:scalac: 	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
Warning:scalac: 	at scala.tools.nsc.backend.jvm.opt.LocalOpt.methodOptimizations(LocalOpt.scala:194)
Warning:scalac: 	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase$Worker2.$anonfun$localOptimizations$1(GenBCode.scala:248)
Warning:scalac: 	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase$Worker2.localOptimizations(GenBCode.scala:248)
Warning:scalac: 	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase$Worker2.run(GenBCode.scala:267)
Warning:scalac: 	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.buildAndSendToDisk(GenBCode.scala:384)
Warning:scalac: 	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.run(GenBCode.scala:350)
Warning:scalac: 	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1418)
Warning:scalac: 	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1403)
```

Does anyone happen to know how to tell IntelliJ to allocate more memory to the `scalac` compiler? @SepidehAlassi?

**Comment by loicjaouen** [comment]
@benjamingeer have a look at #458

**Comment by benjamingeer** [comment]
@loicjaouen Will do, thanks!

**Comment by loicjaouen** [comment]
it's here on `run config` in the `VM options`:
https://github.com/dhlab-basel/Knora/blob/d4d5a823adccbe8fd423289da291efe73d31c7e9/docs/rst/knora-api-server/development/figures/app-config-setup.png

**Comment by benjamingeer** [comment]
OK, I found a performance problem with the profiler:

![profiler-2](https://cloud.githubusercontent.com/assets/558389/24141251/3007d3da-0e23-11e7-9904-3e5e8b39dd0f.png)

That's because of these two lines in `ProjectsResponderV1.createProjectInfoV1()`:

```
log.debug(s"createProjectInfoV1FromProjectResponse - projectResponse: ${MessageUtil.toSource(projectResponse)}")

...

log.debug(s"createProjectInfoV1FromProjectResponse - projectProperties: ${MessageUtil.toSource(projectProperties)}")
```

The problem is that `MessageUtil.toSource` is very slow. If I comment out those lines, getting the project infos is much faster:

```
UsersResponderV1.userDataQueryResponse2UserProfile: getting projectInfos took 16 millis
```

I originally wrote `MessageUtil` to help with making test data, but I realise it's tempting to use it for debugging. Either we just should use `toString` instead, or if we use `MessageUtil`, it should be commented out.

**Comment by loicjaouen** [comment]
as a kind reminder, it is usually recommended to:
- never run production with the log level 'debug' (if one experience time-outs or slowness, first try without debug)
- either test the log level first (`if(log.isDebugEnabled()) log.debug("build my complex string");`)
- or delegate the string building (`log.debug("no complex string build {}", myVar);` with `myVar` having a `toString()` that makes sense)

**Comment by benjamingeer** [comment]
> never run production with the log level 'debug'

We don't, but this problem occurs regardless of your log level. The `log.debug` function produces no output if your log level is higher than `DEBUG`, but the parameters passed to `log.debug` still have to be evaluated first, which means that the string building happens anyway, and that's what's slow here. If you know the string building is going to be slow, `if(log.isDebugEnabled())` would be fine, but it's verbose and it would be a shame to have to write it everywhere. If the problem is just with `MessageUtil.toSource`, then I think the simplest solution is just not to use it in debug messages.

**Comment by subotic** [comment]
@benjamingeer for a short time we had another method for making nice printouts. Maybe they have updated their library so it works with our version of Scala? Maybe this library is faster?

But I guess,  for now, we can comment these lines out.

**Comment by benjamingeer** [comment]
@subotic I think it was this one:

https://bitbucket.org/inkytonik/kiama

But this one looks better:

http://www.lihaoyi.com/upickle-pprint/pprint/

**Comment by benjamingeer** [comment]
Here's an idea:

* We use a nice pretty printer like [PPrint](http://www.lihaoyi.com/upickle-pprint/pprint/).
* We write our own wrapper function for `log.debug` that only builds the log message string if we're actually at `DEBUG` level.

The wrapper could look like this:

```scala
def logDebug(log: LoggingAdapter, messageFun: () => String): String = {
    if (log.isDebugEnabled) {
        log.debug(messageFun())
    }
}
```

**Comment by subotic** [comment]
I'm a bit confused now. According to https://logging.apache.org/log4j/2.x/performance.html, this should not be necessary. Maybe if we would pass the PrittyPrint string as a parameter, this would behave as expected?

Here is the relevant excerpt:

**Asynchronous Logging Parameterized Messages**

Many logging libraries offer an API for logging parameterized messages. This enables application code to look something like this:

```
logger.debug("Entry number: {} is {}", i, entry[i]);
```

In the above example, the fully formatted message text is not created unless the DEBUG level is enabled for the logger. Without this API, you would need three lines of code to accomplish the same:

```
if (logger.isDebugEnabled()) {
    logger.debug("Entry number: " + i + " is " + entry[i].toString());
}
```
If the DEBUG level is enabled, then at some point the message needs to be formatted. When logging asynchronously, the message parameters may be changed by the application thread before the background thread had a chance to log the message. This would show the wrong values in the log file. To prevent this, Log4j 2, Log4j 1.2 and Logback format the message text in the application thread before passing off the log event to the background thread.

**Comment by benjamingeer** [comment]
Aha, now I understand! Yes, that looks better.
