### ISSUE TITLE
How will Knora or Sipi find resource class icons?

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#45]
The definition of `knora-base:LinkObj` says:

```
         :resourceIcon "link.gif"^^xsd:string ;
```

How can this work? Should it be changed to something else?

**Comment by tobiasschweizer** [comment]
The icons can all be served directly by Sipi, using a IIIF URL.

We just need to be sure that every icon that is used by Knora exists on the Sipi server. We could use a special prefix for that.

**Comment by subotic** [comment]
Strictly speaking, aren't ressource class icons something that the gui (Salsah) would need to take care of? Salsah can have a default mapping of ressource classes to icons, which then could be changed in the project specific settings.

**Comment by tobiasschweizer** [comment]
I think this is a good way to do it! So then we would place the icon files in the salsah-app?

**Comment by subotic** [comment]
Yes, that's what I was thinking. For now we could create a folder under ```app/icons``` and put all resource class icons inside. Then somewhere in Salsah, we will need to define the mappings between the classes and the icons. Later on, these default icons could then be changed by adding custom project specific themes to Salsah, or something like this.

**Comment by tobiasschweizer** [comment]
Now, I added a function that creates URLs for resource icons: <https://github.com/dhlab-basel/Knora/commit/e2a141b45a9207bbed0865860eb8331eb1330cbd>

It takes the Iri of a resource class and gets out the name of the ontology it was defined in. Then it is expected that the actual icon is in a folder with that name in Salsah's icon project folder: http://localhost:3335/project-icons/incunabula/page.gif
