### ISSUE TITLE
get userdata doesn't work

### ISSUE THREAD

**Issue by kilchenmann** [dhlab-basel/Knora#450]
It's not possible to get the users data as defined in UsersRouteV1 (line: 65, branch: admin-fixes-3):
http://localhost:3333/v1/users/super.user%40example.com

I get the following message:
HTTP method not allowed, supported methods: PUT

**Comment by subotic** [comment]
This is correct :-)

Could you please try `http://localhost:3333/v1/users/email/super.user%40example.com`?

**Comment by kilchenmann** [comment]
Ah yes, that works fine. Thank you!
