### ISSUE TITLE
List of Users

### ISSUE THREAD

**Issue by kilchenmann** [dhlab-basel/Knora#460]
How do I get a list of every user? I need it in the new admin interface.

**Comment by subotic** [comment]
As it seems you can't :-) I will add it.

**Comment by kilchenmann** [comment]
And where's the list of the users of a project now? Before the changes there was the members route on the API. 
Short: I need for the admin interface a list of every user, a list of users in a specific project and a list of projects where a specific user is member of.

**Comment by subotic** [comment]
> And where's the list of the users of a project now?

The same place as before this last change :-) There should be a list of members Inside each project info.

**Comment by subotic** [comment]
Sorry, wrong information. There are these two routes: `v1/project/members/iri` and `v1/project/members/shortname`

They will give you all members inside a project.

The users route will give you all registered users.

**Comment by subotic** [comment]
Also, you are allowed to look at the code, namely `ProjectsRouteV1` and `UsersRouteV1` :-)

**Comment by subotic** [comment]
There are these two routes: `v1/project/members/iri` and `v1/project/members/shortname`

They will give you all members inside a project.

The users route will give you all registered users, which is not implemented at the moment.

**Comment by subotic** [comment]
>  I need for the admin interface a list of every user

Not implemented at the moment.

> a list of users in a specific project

`v1/project/members/iri` and `v1/project/members/shortname`

> a list of projects where a specific user is member of

part of the user's information: `v1/users/email` or `v1/users/iri`

**Comment by kilchenmann** [comment]
My fault. I was looking at the code, but in the wrong branch :( Sorry. 
Of course, it's still there...

**Comment by subotic** [comment]
Todo: Add user route that returns all registered users.

**Comment by subotic** [comment]
Done in #420
