### ISSUE TITLE
Multiple standoff links can cause UpdateNotPerformedException on GraphDB

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#462]
This is because of a bug in RDF4J: https://github.com/eclipse/rdf4j/issues/781

There doesn't seem to be a workaround that would guarantee that this wouldn't happen. We're discussing it with Ontotext.

**Comment by tobiasschweizer** [comment]
More precisely, the error occurs when attempting to create multiple standoff links from a text value to resources that are instances of a class that is not an immediate subclass of knora-base:Resource. In my case I tried ro create multiple standoff links to a resource class that is a sublcass ofknora-base:StillImageRepresentation.

**Comment by tobiasschweizer** [comment]
Now that I think about it: I was able to create standpff links to beol:letter, which is not an immediate subclass of knora-base:Resource https://github.com/dhlab-basel/Knora/blob/wip/beol-import/webapi/_test_data/ontologies/beol-onto.ttl#L559

**Comment by benjamingeer** [comment]
Ontotext's fix for this is in GraphDB `8.0.6-RC1`.
