### ISSUE TITLE
Delete user

### ISSUE THREAD

**Issue by kilchenmann** [dhlab-basel/Knora#463]
In the documentation I've found the following instruction for:
Delete user (-> update user):
Required permission: SystemAdmin / User
Effects property: knora-base:isActiveUser with value true or false

I tested it with Postman, but the property isActiveUser with the value false takes no effect. I tried as SystemAdmin and as user.

**Comment by kilchenmann** [comment]
Okay, indeed it deletes the user, but the response from the server has still the value true on isActiveUser.

**Comment by benjamingeer** [comment]
Probably the user is cached until you restart the server.

**Comment by loicjaouen** [comment]
BTW: caching users and rights is not quite a good idea

**Comment by kilchenmann** [comment]
No, it doesn't work  ...need help

**Comment by benjamingeer** [comment]
I think it should be OK to cache them as long as we reload the cache after updating a user. @subotic can you help?

**Comment by subotic** [comment]
I will take a look at it. The idea with caching is as Ben said, to delete or update the cache after each change.

**Comment by subotic** [comment]
resolved in #486
