### ISSUE TITLE
I that your stuff in the DHLab fridge?

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#469]
![2017-03-23 14 28 32](https://cloud.githubusercontent.com/assets/6000023/24250429/292f1d2e-0fd7-11e7-8c23-acc100374380.jpg)

**Comment by loicjaouen** [comment]
That's ours, sorry about that, it was meant to be open-source for anybody (brave enough) to share and enjoy.  
But don't wait for bugs in need of fixing, please dump the rotten branch before.

Be aware though that it is only the tip of the iceberg and that there is more in the freezer, it is all yours if you fancy it.
