### ISSUE TITLE
Search does not work properly for Knora documentation on knora.org

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#470]
When I do a search on <http://www.knora.org/documentation/manual/search.html> I get very few or no results for things that occur often. Locally, I get the proper set of results.

Example: <http://www.knora.org/documentation/manual/search.html?q=Ontology+Checking>

Is there some problem with absolute URLs etc. when deploying the HTML build of the docs?

Have you changed something recently, the design looks different than before.

**Comment by benjamingeer** [comment]
I have no idea. I switched from the ugly `haiku` theme to the better-looking `agogo` theme, which is working fine on the Sipi web site. But I don't have time to figure out Sphinx's JavaScript right now, so I made PR #471 to revert back to `haiku`.

**Comment by benjamingeer** [comment]
This seems to have fixed itself.

**Comment by tobiasschweizer** [comment]
Wow. Self-patching code.
