### ISSUE TITLE
salsah: get the user's project selected by default

### ISSUE THREAD

**Issue by loicjaouen** [dhlab-basel/Knora#476]
and the project's vocabulary too

when typing in data, having to select the project and vocabulary over and over is making the user pull out his hair.

**Comment by benjamingeer** [comment]
A user can be in more than one project. So which one should we select by default?

**Comment by loicjaouen** [comment]
the first in the row:
https://github.com/dhlab-basel/Knora/blob/develop/salsah/src/public/index.html#L95

**Comment by benjamingeer** [comment]
If I'm not mistaken, the projects are returned in a random order. @subotic ?

**Comment by subotic** [comment]
Yes, random.

**Comment by benjamingeer** [comment]
The project only has to be selected once, after the user logs in. Surely this would not cause the user to tear their hair out? However, this choice is not yet used to choose the default vocabulary when creating a new resource (#422).

**Comment by musicEnfanthen** [comment]
What about a `default_project` (general) in `userprofile` (that can be determined by project admin)? That'll be the one that is activated as `active_project` after login (it concerns [header] layout & default vocabulary). If necessary, the User can switch to another project he is member of (selection list?) with the pull down menu from pull request  [#435](https://github.com/dhlab-basel/Knora/pull/435).

I definitely agree with @loicjaouen that the current active project & vocabulary should  be selected by default in pull down menus in terms of economy.

**Comment by loicjaouen** [comment]
@benjamingeer :
> The project only has to be selected once, after the user logs in.

for searching, you have to select the project on each new search  
for creating: the selection of the project where the newly created entities land is made once and it's fine.

> Surely this would not cause the user to tear their hair out?
> However, this choice is not yet used to choose the default vocabulary when creating a new resource (#422).

it is the process of selecting the vocabulary on each new entry that is tedious.
