### ISSUE TITLE
org.knora.webapi.testing.tagobjects.DbTest extends nonexistent class

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#48]
`org.knora.webapi.testing.tagobjects.DbTest` extends `org.knora.rapier.testing.tags.DbTest`, which doesn't exist (`rapier` was changed to `webapi`, and `DbTest` was changed to `SipiTest`).

**Comment by subotic** [comment]
This is fixed in aba21f56d8614159b30f0150eb3535ca09a6a589 which is in the wip/authentication branch.

**Comment by subotic** [comment]
Crap, missed the package name. Its fixed in 9abcac3fde7250bd414c6d241a35bc924e848cb8.
