### ISSUE TITLE
knora-base:hasTextValue

### ISSUE THREAD

**Issue by hanscools** [dhlab-basel/Knora#484]
Hi,
Is there a reason why there is not kb:hasTextValue? There is 
```
kb:hasComment
   kb:subjectClassConstraint kb:Resource ;
   kb:objectClassConstraint kb:TextValue.
```
But 'comment' is more specific.

**Comment by tobiasschweizer** [comment]
I think this is a just a generic property which can be further extended to represent a text that is meant to be a comment on something. 

```
### ###########################################
### incunabula:book_comment

:book_comment rdf:type owl:ObjectProperty ;

              rdfs:subPropertyOf knora-base:hasComment ;

              rdfs:label "Kommentar"@de ,
                         "Commentaire"@fr ,
                         "Commento"@it ,
                         "Comment"@en ;

              rdfs:comment """Unstrukturierte Bemerkungen zu einem Objekt"""@de ;

              knora-base:subjectClassConstraint :book ;

              knora-base:objectClassConstraint knora-base:TextValue ;

              salsah-gui:guiOrder "12"^^xsd:integer ;

              salsah-gui:guiElement salsah-gui:Textarea ;

              salsah-gui:guiAttribute "width=95%" ,
                                      "rows=7" ,
                                      "wrap=soft" .
```

Probably it should not be in knora-base since it is rather semantic. However, it should be in a common place so it can be reused.

**Comment by hanscools** [comment]
Can kb:hasTextValue be added in KBO (by analogy with other resource-value properties)?

**Comment by tobiasschweizer** [comment]
There is already `knora-base:hasValue` which can be extended by making subproperties of it. This works the same for all value types. Then every property has a `knora-base:objectClassConstraint`.

What would be the benefit of such a thing as `knora-base:hasTextValue`? Is it just more specific than `knora-base:hasValue` (the object class constraint is always a `TextValue`)?

In our Sparql queries, we distinguish between `knora-base:hasValue` and `knora-base:hasLinkTo`. But all value properties are treated the same way.

**Comment by hanscools** [comment]
I will create then a general property `:hasTextValue` whose range or object class constraint is of course always a text value, in broadest sense. `:hasName`, `:hasComment`, `:hasDefinition`, `:hasDescription`, and the like, as object properties, are all sub-properties thereof. It will be in a project independent ontology.

**Comment by tobiasschweizer** [comment]
I think we should move `hasComment` out of knora base because it is about semantics. We could put it into an ontology that is shared among projects.

Of course you could add `hasTextValue` to knora base. But unless we have an actual use case in a SPARQL query for it, I do not see the benefit.
