### ISSUE TITLE
A probable bug on permissions prevent members of a group to view the label of resources

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Knora#492]
Back with drawings-gods permissions.

The problem is the following:
the user **ddd1**, member of the group `drawings-gods-snf-team`, create resources.
After he created the given resources, according to his permissions on the resources, he can delete it.
```
"CR http://data.knora.org/groups/drawings-gods-admin|D http://data.knora.org/groups/drawings-gods-snf-team,knora-base:Creator|V knora-base:ProjectMember,http://data.knora.org/groups/drawings-gods-add-drawings,http://data.knora.org/groups/drawings-gods-meta-annotators"
```
However, there is a problem with the `rdfs:label` property. **dd1** simply can't view the label of the resource he creates. And he can't either view the label of resources created by other users (**ddd2**).

See here : 

![capture d ecran 2017-04-28 a 11 59 48](https://cloud.githubusercontent.com/assets/17294309/25524360/83e2b95c-2c0a-11e7-8d70-0f1b811e4e39.png)

However, for **ddd2** user who is member of another group (`drawings-gods-admin`) with a little more permissions, there is no problem.
I can't see the difference between the 2 groups (`AdministrativePermissions` and `DefaultObjectAccessPermissions` on groups are the same) that would justify a change of behaviour. So, I guess it has something to do with `DefaultObjectAccessPermissions` on resource classes of on properties but I didn't define any `DefaultObjectAccessPermission` on `rdfs:label`.

So, please, could you help?

I will update **ddd files** in [other.v1.DrawingsGodsV1Spec](https://github.com/dhlab-basel/Knora/tree/develop/webapi/_test_data/other.v1.DrawingsGodsV1Spec) so that you can check the problem (even though drawings-gods_permissions-data.ttl and drawings-gods_admin-data.ttl have not changed much if at all).

**Comment by benjamingeer** [comment]
This is strange, because labels have no permissions. If you can view a resource, you should be able to view its label.

**Comment by benjamingeer** [comment]
Perhaps this issue has nothing to do with permissions, and something else is wrong with the display of labels in the GUI.

**Comment by loicjaouen** [comment]
allright :) i came to the opposite conclusion ("if the same resource shows up differently for two dfferent users, it can't be the GUI"), but I will check!

**Comment by benjamingeer** [comment]
On branch `wip/test-labels`, I added a test to `DrawingsGodsV1Spec` that creates a resource as user `ddd1`, then queries and checks its label. This works fine. If you'd like me to try to reproduce this with the GUI, please let me know what type of resource you are creating. Better yet, please write a series of exact steps to reproduce the bug, in this format:

**Steps to Reproduce**

1. Run script `xyz.sh` to load the test data into GraphDB.
2. Start Sipi with configuration file `xyz.lua`.
3. Start Knora and Salsah.
4. Log in as user `ddd1` with password `test`.
5. Click on such-and-such button.
6. Click on such-and-such other button.

**Expected result**

"Something something something" should be displayed.

**Actual result**

"Something else something else" is displayed.
