### ISSUE TITLE
[Salsah 1.5] [CKeditor] - support for non breakable space

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Knora#494]
CKeditor should support the `&nbsp;` character.

**Comment by tobiasschweizer** [comment]
probably this could be done with this option: http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-basicEntities

entities is set to false because no entities should be used fro Umlauts (ä, ü etc.)

**Comment by loicjaouen** [comment]
in a ckEditor text-area, `  ` (two spaces) are replaced by: `&nbsp; ` as well as a new line by:

```
<p>&nbsp;</p>

<p>&nbsp;</p>
```

**Comment by loicjaouen** [comment]
the config : `entities: false` or `entities: true` doesn't make a difference, we still get send `&nbsp;`.

**Comment by loicjaouen** [comment]
Talking with @tobiasschweizer , the tag '<nbsp>' is planned to be recognized by the standoff parser.

For now we decided to switch '&nbsp;' by its character.

**Comment by loicjaouen** [comment]
@tobiasschweizer we talked about generalizing to other entities but:
- ckEditor doesn't escape in entities the `ü`, `'` and the likes
- the rest of the basic entities `&lt;`, `&gt;`, `&amp;` are parsed (as tested in [XMLToStandoffUtilSpec.scala](https://github.com/dhlab-basel/Knora/blob/develop/webapi/src/test/scala/org/knora/webapi/util/standoff/XMLToStandoffUtilSpec.scala))

**Comment by loicjaouen** [comment]
so I think we are safe; I let you review.

**Comment by tobiasschweizer** [comment]
> ckEditor doesn't escape in entities the ü, ' and the likes

Yes, with `config.basicEntities = false;`. I initially had the problem that `ü` was converted to `&uuml;`.

> the rest of the basic entities &lt;, &gt;, &amp; are parsed (as tested in XMLToStandoffUtilSpec.scala)

I think this is because they are predefined entities. Otherwise, a DTD would have to be provided to resolve them.

> Talking with @tobiasschweizer , the tag '' is planned to be recognized by the standoff parser.

What do you mean here :-)? I think you should put markup inside backticks ...
