### ISSUE TITLE
[Salsah 1.5] Is there a limit to the number or characters supported by the rdfs:label field?

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Knora#495]
Is there a limit to the number or characters supported either by the GUI or by Knora in the `rdfs:label` property?

When I first created the resource with the following label :
_Aristote, La Poétique Texte, traduction, notes par Roselyne Dupont-Roc et Jean Lallot._
everything was fine. 

However, if I want to add more character, I can't. So I decided to copy and paste the label above and it looks like the field only accept a limited number of character because **my label is shortened**: 
_Aristote, La Poétique Texte, traduction, notes par Roselyne Dupo_

![capture d ecran 2017-05-01 a 12 01 57](https://cloud.githubusercontent.com/assets/17294309/25577592/801f848a-2e67-11e7-8c7b-be5cafbb9e4c.png)

Given the fact that the `rdfs:label` is the property that is searched for when you want to link two resources with a` knora-base:hasLinkTo` subproperty, I think **we should consider allowing a little bit more characters** for the `rdfs:label`.

Entering a whole bibliographic notice as `rdfs:label` can actually make some sense.

**Comment by benjamingeer** [comment]
This seems to be hard-coded in just one place, in `salsah/src/public/js/imagebase.js`:

```
            data.props.__label__ = {
                attributes: "size=64;maxlength=64",
 ```

Could you please make a pull request to increase this limit?
