### ISSUE TITLE
[Salsah 1.5] Where is the "drag to destination" icon?

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Knora#497]
After discussing drag and drop features with @kilchenmann and @musicEnfanthen [here](https://github.com/dhlab-basel/Salsah/issues/22), I realized that the "drag to destination" icon that I can see for your projects (Anything, Incunabla, Images, etc.) remains invisible for ours. 

Do you have any idea why? 

![capture d ecran 2017-05-01 a 15 00 38](https://cloud.githubusercontent.com/assets/17294309/25580299/30964e76-2e80-11e7-9c8d-6896ca4233b5.png)

**Comment by benjamingeer** [comment]
Please provide precise steps to reproduce this issue, along with all necessary test data, in the format given here:

https://github.com/dhlab-basel/Knora/issues/492#issuecomment-298628691

**Comment by loicjaouen** [comment]
the link is added in `imagebase.js:44`:

```
			propedit = $('<div>').addClass('propedit');
			if (resource.resinfo.restype_iconsrc)
			{
				propedit
				.append(
					$('<img>').attr({src: resource.resinfo.restype_iconsrc, title: 'DRAG TO DESTINATION'}).addClass('propedit resicon').dragndrop('makeDraggable', 'RESID', {resid: resource.resdata.res_id})
				);
```

For resources that do not define an icon, the 'DRAG TO DESTINATION' link is not added.

We will work-out our ontologies to add:

```
      knora-base:resourceIcon "thing.png" ;
```

on our resources definitions.

**Comment by loicjaouen** [comment]
I'll also add a default icon when none is provided

**Comment by benjamingeer** [comment]
Thanks for figuring this out! A pull request to add the default icon would be much appreciated.
