### ISSUE TITLE
[Salsah 1.5] Strange behaviours with incoming and outgoing links

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Knora#498]
I have a bibliographic ontology (based on `biblio-onto.ttl`) and a project-specific ontology for a new project named Fabula.

In Fabula ontology, a resource class `Author` is linked to bibliographical records (for example `Book`, from the bibliographic ontology) with a property `hasStructuredReferences` (_Références structurées_ in the GUI), subproperty of `knora-base:hasLinkTo`.

The resource class `Book` itself is linked to the resource class `Author` with a property `hasAuthor` which is a subproperty of `knora-base:hasLinkTo`. (I know it introduces some redundancy with outgoing and incoming links between `Author` and `Book`, but it is fine for what we want).

When I want to add a `Structured reference` for an `Author`, I click on `New entry` and fill the form in the new window. Once I have saved the new resource, a new line shows up under _Références structurées_ in the _Auteur_ form. This is fine.

![capture d ecran 2017-05-01 a 15 42 37](https://cloud.githubusercontent.com/assets/17294309/25581075/bd69aa64-2e85-11e7-98e1-b38a0bc74f93.png)

However, if I refresh, this line disappears and then shows up under the "Other objects referencing this object" part of the form. 

![capture d ecran 2017-05-01 a 15 44 09](https://cloud.githubusercontent.com/assets/17294309/25581081/c8a09906-2e85-11e7-8258-05d8a5bd70c2.png)

It is not exactly wrong, but I expected some redundancy : I thought I would see the book under _Références structurées_ and under the tab "Other objects referencing this object". 

Would you consider what happens a normal thing or is it a bit odd?

**Comment by benjamingeer** [comment]
> However, if I refresh, this line disappears

What do you mean by "if I refresh"? Do you mean that you click the reload button in the browser?

Please provide precise steps to reproduce this issue, along with all necessary test data, in the format given here:

https://github.com/dhlab-basel/Knora/issues/492#issuecomment-298628691

**Comment by mrivoal** [comment]
My bad. I simply forgot to save the link I created from the resource `Auteur` to the resource `Livre`. Thus, this link to could not appear under the _Références structurées_ property for the resource `Auteur` once I had closed and reopened the window.

Sorry. One less issue to deal with.
