### ISSUE TITLE
The API server needs to know the user's active project

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#5]
The user should be able to select one project as active, meaning that new resources and values are created in that project by default. Routes and responders need to know which is the active project.

**Comment by subotic** [comment]
There are two approaches:
 1. This information is stored globally on the server, i.e. when the user changes the active project then this information is stored somewhere (e.g., UserProfile) on the server
 2.  This information is passed with every call, where it is needed

I think we talked about doing 2 but I'm not sure anymore.
