### ISSUE TITLE
rdfs:Class

### ISSUE THREAD

**Issue by hanscools** [dhlab-basel/Knora#508]
When introducing a project-related ontology in Knora, classes instantiated with `rdfs:Class` are not recognized.
Is there a reason why `owl:Class` is chosen to instantiate Knora classes?
The only rationale I see is adherence to OWL DL (description logics, a restriction of OWL Full), but as far as I know this is not the case for Knora.
Would it then be possible to replace `owl:Class` with `rdfs:Class` or to implement somewhere that `owl:Class rdfs:subClassOf rdfs:Class` or even `owl:Class owl:equivalentClass rdfs:Class` (OWL Full)?
In NIE we deal with external ontologies using `rdfs:Class` (e.g. [CIDOC](http://www.cidoc-crm.org/html/5.0.4/cidoc-crm.html), [FRBR](http://iflastandards.info/ns/fr/frbr/frbroo/)), and the W3C and basic ontologies such as DC, use `rdfs:Class`. To provide semantic interoperability a system should offer subsumption at the highest level.

**Comment by benjamingeer** [comment]
We've used `owl:Class` to leave open the possibility of using OWL semantics in the future.

We could certainly support `rdfs:Class` as well.

**Comment by hanscools** [comment]
Please do, thanks!

**Comment by benjamingeer** [comment]
As we discussed yesterday, if you have time to implement this, please do so and submit a pull request.

**Comment by hanscools** [comment]
I will implement it and submit a pull request.
