### ISSUE TITLE
Fulltext search does not return all results (Salsah 1.3)

### ISSUE THREAD

**Issue by musicEnfanthen** [dhlab-basel/Knora#518]
(Not knowing where to post issues with the old Salsah 1.3.1 I leave it here for the moment. Feel free to move it to a more appropriate place.)

Obviously not all imported property entries from FileMaker are found by fulltext search in Salsah. In many cases, we have to open the property field and save it again, then it is found via extended search. Maybe it is kind of a cache bug?

I add an example to illustrate the bug:

Starting point:
![ausgangssituation](https://cloud.githubusercontent.com/assets/21059419/26585576/cbb38bac-454c-11e7-9dd2-a16b4e6ce81b.png)

"resaving":
![speichersituation](https://cloud.githubusercontent.com/assets/21059419/26585600/deb43b5c-454c-11e7-8437-5f3270316e9b.png)

 result:
![endsituation](https://cloud.githubusercontent.com/assets/21059419/26585607/e78b6278-454c-11e7-821f-3c4cb6f7625f.png)

@lrosenth  How can this be solved? Do we need a script that opens each and one of the properties in the project and saves them untouched afterwards?

**Comment by loicjaouen** [comment]
We have seen that too

**Comment by loicjaouen** [comment]
can you send the details of the two get search requests?

**Comment by musicEnfanthen** [comment]
Not sure whether this is exactly what you mean:

### SimpleSearch for "Skizzenbuch" (with filter to Webern project)

**Request:**
GET /api/search/Skizzenbuch?searchtype=fulltext&show_nrows=-1&start_at=0&progvalfile=prog_619663.salsah&filter_by_project=6 HTTP/1.1

### ExtendedSearch for Opus 23 
It should be displayed as a result of the request above because it has a source description containing: "[Skizzen (17 S., in **Skizzenbuch** 3)] PSS (Mappe 55)":

**Request:**
GET /api/search/?searchtype=extended&property_id%5B%5D=389&compop%5B%5D=EQ&searchval%5B%5D=23&show_nrows=25&start_at=0&progvalfile=prog_681802.salsah&filter_by_restype=43&filter_by_project=6 HTTP/1.1

**Comment by loicjaouen** [comment]
It was to compare the two fulltext search requests to check that they were really the same.
If they are, it might also be a question of rights, as after you saved the resource, its rights have changed.

But it is not a question of fulltext search, as the extended search shows the same behaviour:
<img width="557" alt="capture d ecran 2017-05-30 a 23 07 54" src="https://cloud.githubusercontent.com/assets/3933654/26605105/0cfe46ca-458d-11e7-8e6e-f133bf04fa25.png">

**Comment by musicEnfanthen** [comment]
Good point. Unfortunately, I can't see any difference between the property's value rights of object op. 18 (which is in the result list) and op. 23 (which is not, but should be there). All entries have the `value_rights `set to `"1"`. You can compare it here:

op. 18: http://www.salsah.org/api/resources/55909_-_local
op. 23: http://www.salsah.org/api/resources/55964_-_local

But maybe you're right and it is not a question of the search. But if it were a question of access rights, the whole `Quelle` property within `Werk` wouldn't be displayed for  (at least) unregistered users, I guess? But when you search for `Werk` (Resource) & `Opus = 23` (property) manually, and open the op. 23 object, you are (correctly) allowed to see the `Quelle` property (containing the `Skizzenbuch` entry), even without any login:

http://www.salsah.org/webern/resources/55964

Or is there any difference in the access rights defined for the different user roles and the access rights of the search routines?

**Comment by loicjaouen** [comment]
Yet, the rights are the same, still, the owner changes, you can compare the values that you didn't change in the `op. 18` to one that you changed:

http://www.salsah.org/api/resources/55913_-_local
http://www.salsah.org/api/resources/2135515_-_local

It is actually not related to anything I could track on our usage of salsah and I don't know the PHP implementation... You are right: only @lrosenth will help.

But we would rather wait to see the behaviour once the data is imported in knora, wouldn't we?

**Comment by musicEnfanthen** [comment]
Since it is a question of daily work for us, I would classify it as quite urgent. So I will have a look at it with @lrosenth .
Thanks for your help, I really appreciate.

**Comment by musicEnfanthen** [comment]
So, thanks to @lrosenth we traced down this issue yesterday: It is due to the way richtext properties were internally structured and handled at the very beginning of Salsah. As far as I understand, there was only an id based pointer to a richtext object from any specific project’s richtext value, the actual text value was not incorporated. This behaviour was revised later, but only adapted to new entries. Entries which already existed at least at the end of 2012, preserved the former behaviour. (That’s why when we re-saved a richtext field [see above], it was treated the revised way and finally was re-found via fulltext search).

@lrosenth is preparing a script that looks at the behaviour of the richtext values (pointing to either resource id or text value) and adapts the old entries to the new behaviour.

**Comment by musicEnfanthen** [comment]
Thanks to @lrosenth this issue was solved today (via php script in release 1.3.1). All richtext values now incorporate the actual textvalue.
