### ISSUE TITLE
Add an untyped key-value store backed by the triplestore

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#524]
The new SALSAH GUI would like to be able to persist some state, such as draft ontologies that the user is developing, but not permanently. We can provide a simple key-value store for this, backed by the triplestore, with data stored in a separate named graph.

**Comment by benjamingeer** [comment]
@subotic I'm thinking that maybe this isn't such a good idea after all, if we want to minimise the load on the triplestore. We could run a separate service for this instead. What do you think?

**Comment by subotic** [comment]
Yes, I agree.

**Comment by subotic** [comment]
In the spirit of microservices, this is a good candidate for a separate service.

**Comment by benjamingeer** [comment]
OK, then I will make a PR to remove the bit of code I started to add for this.

**Comment by subotic** [comment]
great, thanks 😀
