### ISSUE TITLE
update ckeditor

### ISSUE THREAD

**Issue by loicjaouen** [dhlab-basel/Knora#526]
We are on [4.6](http://ckeditor.com/release/CKEditor-4.6.2), [4.7](http://ckeditor.com/release/CKEditor-4.7.0) is out.

Why do we want to update ckEditor to a newer version?
- [best practices](http://docs.ckeditor.com/#!/guide/dev_best_practices) recommendations
- it works better with word import
- at least, I was more successful when installing [footnotes](http://ckeditor.com/addon/footnotes) addon

**Comment by tobiasschweizer** [comment]
Please make a new branch, add the new version to `vendor` and test it :-)

Maybe you could find a way to test CKeditor in the browser tests. I think a test doing that is ignored at the moment.

**Comment by tobiasschweizer** [comment]
`/salsah/src/public/vendor/ckeditor`

**Comment by loicjaouen** [comment]
@tobiasschweizer 
> Please make a new branch
of course, as always, or do you mean something else than a `wip` branch?

> add the new version to vendor
sounds right

> and test it :-)
sure! ;)

> Maybe you could [...]
maybe I could...

**Comment by tobiasschweizer** [comment]
No, I mean exactly that :-) Sorry for repeating the obvious.

This is the test that has to be ignored:

`/scala/org.knora.salsah/browser/SearchAndEditSpec.scala`

```
        "edit the description of a page" ignore {

            page.load()

            page.doLogin(email = incunabulaUserEmail, password = testPassword, fullName = incunabulaUserFullName)

            doZeitgloeckleinSearch()

            val rows = page.getExtendedSearchResultRows

            // open a page
            rows(1).click()

            val window = page.getWindow(1)


            // get metadata section
            val metadataSection: WebElement = page.getMetadataSection(window)

            // get a list of editing fields
            val editFields = page.getEditingFieldsFromMetadataSection(metadataSection)

            val descriptionField = editFields(7)

            page.clickEditButton(descriptionField)

            val ckeditor = eventually {
                page.findCkeditor(descriptionField)
            }

            ckeditor.sendKeys("my text")

            page.clickSaveButton(descriptionField)

            // read the new value back
            val seqnumValueContainer = page.getValueContainer(descriptionField)

            assert(descriptionField.getText.substring(0, 7) == "my text")

            page.doLogout()
        }
```

The problem is that I did not success in making that work with Selenium in Chrome. I could not get a focus on CKeditor. I think the problem is that CKeditor is in its own iframe. When CKeditor is initialized, a textarea is replaced with an iframe.

`/Users/tobi/gitreps/Knora_github/salsah/src/public/js/jquery.htmleditor.js`

```
// init editor (textarea will be replaced by an iframe)
localdata.editor = CKEDITOR.replace(textarea[0], config);
```

Maybe you could find a better way to do it. I would be glad to help if you have questions.

**Comment by tobiasschweizer** [comment]
this is related to https://github.com/dhlab-basel/Knora/issues/399 and https://github.com/dhlab-basel/Knora/issues/146

**Comment by loicjaouen** [comment]
I'll investigate, but it's all new to me

**Comment by tobiasschweizer** [comment]
In general, we simulate user interactions with XPath expressions (to select elements in the DOM) and the triggering of events. We have written methods for the most common operations.

Maybe you want to have a look at the Selenium documentation: <https://seleniumhq.github.io/selenium/docs/api/java/>

The way we had to do it is actually horrible. This is why we write tests from the very beginning for the new GUI.

**Comment by loicjaouen** [comment]
# Install

Using ckeditor's site [builder](http://ckeditor.com/builder) chose basic _preset_, added plugins _Remove Format_ and _Source Editing Area_ , Moona-Lisa skin, and 4 languages (english, french, German CH, Italian)

Once downloaded, find the `samples` sub-directory and open `index.html` in a browser.  
Click on `toolbar configurator`, change to fit what we currently have.  
Then click on `get toolbar config` that looks like:

```
CKEDITOR.editorConfig = function( config ) {
	config.toolbarGroups = [
		{ name: 'document', groups: [ 'mode', 'document', 'doctools' ] },
		{ name: 'clipboard', groups: [ 'clipboard', 'undo' ] },
		{ name: 'editing', groups: [ 'find', 'selection', 'spellchecker', 'editing' ] },
		{ name: 'forms', groups: [ 'forms' ] },
		{ name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] },
		{ name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align', 'bidi', 'paragraph' ] },
		{ name: 'links', groups: [ 'links' ] },
		{ name: 'insert', groups: [ 'insert' ] },
		{ name: 'styles', groups: [ 'styles' ] },
		{ name: 'colors', groups: [ 'colors' ] },
		{ name: 'tools', groups: [ 'tools' ] },
		{ name: 'others', groups: [ 'others' ] },
		{ name: 'about', groups: [ 'about' ] }
	];

	config.removeButtons = 'Cut,Copy,Paste,Anchor,NumberedList,BulletedList,Outdent,Indent,About';
};
```

Edit [jquery.htmleditor.js](https://github.com/dhlab-basel/Knora/blob/develop/salsah/src/public/js/jquery.htmleditor.js) to reflect the this config (around line 142).

Version and copy the code to `public/vendor`.  
In this case it is `public/vendor/ckeditor_4.7.0`.

Edit the `index.html` to load ckeditor from that directory:

```
	<script src="vendor/ckeditor_4.7.0/ckeditor.js" charset="utf-8"></script>
```

<img width="594" alt="capture d ecran 2017-06-01 a 16 00 30" src="https://cloud.githubusercontent.com/assets/3933654/26683318/ad4b4680-46e3-11e7-81b0-3e2062eb5d8c.png">

**Comment by loicjaouen** [comment]
compared to the previous one:
<img width="258" alt="capture d ecran 2017-06-01 a 16 03 03" src="https://cloud.githubusercontent.com/assets/3933654/26683357/d5743400-46e3-11e7-91b3-d5c92bb63d00.png">

there is an additional feature to go back and forth on the current history of changes; I like it and it has no incidence on the output, but shout if you think it is armful.

**Comment by loicjaouen** [comment]
so far, so good:

```
[info] Run completed in 1 minute, 27 seconds.
[info] Total number of tests run: 28
[info] Suites: completed 3, aborted 0
[info] Tests: succeeded 28, failed 0, canceled 0, ignored 1, pending 0
[info] All tests passed.
```

**Comment by loicjaouen** [comment]
@tobiasschweizer : I have three more questions:
- As I changed `jquery.htmleditor.js`, I should also stamp it with the version of ckEditor we are using because that may break the compatibility to the previous version, and the link is made in `index.html`, so not quite explicit... but let's say that one can use git to `blame` and track the changes on all files in one PR.

- Do you mind if we put the test in a different issue because I have to move forward with additional ckEditor features?

- if I add features in ckEditor that break the standard mapping, I guess that I create a release branch for that specific version of salsah? Or I could add a jquery.special_htmleditor.js and a matching element in salsah ontology... what do you think?

**Comment by loicjaouen** [comment]
also for testing, this addon might help: [Div Editing Area](http://ckeditor.com/addon/divarea)

> This plugin uses a `<div>` element (instead of the traditional `<iframe>` element) as the editable area in the themedui creator. Much similar to inline editing, it benefits from allowing the editor content to inherit from host page styles.
