### ISSUE TITLE
When a TextValue containing standoff links is deleted, decrement the links' reference counts

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#53]
Currently they're kept.

cc @lrosenth @subotic

**Comment by tobiasschweizer** [comment]
If references count would be zero, I think yes, the links should be deleted.

**Comment by benjamingeer** [comment]
OK, then value deletion in the values responder needs to be rewritten.

**Comment by tobiasschweizer** [comment]
Otherwise, there would be still a link, but the text that contained the reference is not there anymore. 
So it would be a link without a reason.

Do I understand this correctly?

**Comment by benjamingeer** [comment]
Yes, that's right. Currently when we delete a text value, we just copy the contents of the value (using `deleteValue.scala.txt`. In order to update the links' reference counts, we can't just copy the contents of the value. We'll have to regenerate the value. The template `addValueVersion.scala.txt` already handles updating standoff links, it could probably used to delete values too, if it took a `delete` argument.

**Comment by benjamingeer** [comment]
We also need to add pre-update cardinality checks before deleting a value:

https://github.com/dhlab-basel/Knora/issues/33#issuecomment-197784772

**Comment by benjamingeer** [comment]
Moved to #132 because of the standoff redesign.

**Comment by benjamingeer** [comment]
Reopening because the standoff design has changed and this is now relevant again.

**Comment by benjamingeer** [comment]
Currently when we mark a value as deleted, we make a new version of the value. This introduces some redundancy, and I believe the reason for it was to make the code simpler. After looking at the code again, I don't think it actually makes a big difference, so I'd rather change it to mark the existing version of the value as deleted. So we have three cases:

* Delete a link
    * Already handled by `deleteLink.scala.txt`
* Delete a text value
    * Add `isDeleted true` and `deleteDate` to the existing value
    * Update links for resource references
* Delete any other value
    * Just add `isDeleted true` and `deleteDate` to the existing value

Work in progress is on `wip/delete-value`.

**Comment by benjamingeer** [comment]
The only exception is `LinkValue`. In order to mark it as deleted, you have to decrement its reference count, which means you have to make a new version of it. Perhaps this was why I originally wanted to make a new version of any value when marking it as deleted, for consistency.
