### ISSUE TITLE
GraphQL technology

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#533]
I stumbled upon GraphQL (http://graphql.org) a few days ago. It is basically a query language for APIs. To use a buzzword, IoC (Inversion of Contol). It is touted as the next big thing

In short, the idea is to have only one endpoint and then allow the user of the API to specify in detail what he would like to get back. No under- or over-serving anymore. By defining a schema, all objects, and their properties which can be queried are specified. Both read and write access is supported.

I don't think this is something for querying resources, but for the admin part of the API (users, projects, groups, lists) this might be feasible.

**Comment by loicjaouen** [comment]
It is pretty cool and well integrated with express, so building a rest service should be really easy (but requires some work to shape the data).  

The main difference with RDF is that it is a graph structure; the links have no semantic values.

(it comes from facebook and should be well coded, tested, packaged)

**Comment by benjamingeer** [comment]
Tobias and I were looking at this and saw two obstacles to using it. First, it seems difficult or impossible to use it if your data comes from SPARQL queries:

> the limitation is that while "you don't have to deal with complex, multi-JOINs”, the described
control model for graphql resolvers (as per the api definitions) entails implementing what
are necessarily, internally joins as nested loops.
it is as if one were to segment a sparql query into nested service clauses and stipulate that
the implementation must pass exactly one values clause with each remote service invocation.
this does not tend to be the best approach for an rdf store.
>
>the graphql->sparql translation process is more likely to yield an effective implementation
and it would be nice if one could integrate that into the resolver architecture, but it is
not clear whether the api affords access to the necessary query state to be able to perform
a high-level translation.

http://mail-archives.apache.org/mod_mbox/jena-users/201705.mbox/%3C0102015bc3da1944-613c0e27-761a-4aa8-9046-46bff1c11d6a-000000@eu-west-1.amazonses.com%3E

Second, it doesn't seem to play well with JSON-LD:

https://github.com/graphql/graphql-js/issues/271

**Comment by subotic** [comment]
Thanks. It doesn't seem to be easily implemented. I will close the issue.
