### ISSUE TITLE
Example JSON to create new resource via API

### ISSUE THREAD

**Issue by janCstoffregen** [dhlab-basel/Knora#539]
Sorry, I think I found the answer, I will close this for now.

**Comment by loicjaouen** [comment]
ok ;)

as an easy way to debug this kind of issues, I would recommend to set up the `salsah` GUI and see what request the GUI sends to knora.

**Comment by janCstoffregen** [comment]
ok, thank you, it is explained in the documentation as well, I think it will work now, I will update the documentation with an example afterwards, there is one python example that creates the request, but not the plain json without representation, but it's easily deducible now, thanks again!

**Comment by benjamingeer** [comment]
See http://www.knora.org/documentation/manual/rst/knora-api-server/api_v1/adding-resources.html

which refers to http://www.knora.org/documentation/api/modules/_createresourceformats_.createresourceformats.html

there are examples in https://github.com/dhlab-basel/Knora/blob/develop/webapi/src/test/scala/org/knora/webapi/e2e/v1/ResourcesV1R2RSpec.scala

**Comment by benjamingeer** [comment]
> not the plain json without representation

There are several examples like that in `ResourcesV1R2RSpec`. The ones that create `anything:Thing` resources should be especially useful because they cover a lot of different value types.

**Comment by janCstoffregen** [comment]
I did not see the examples in the third link, thank you so much, that was very helpful, I will include this link in the documentation then with some additional stuff and make a pull request and see if you like it! :) Have a great weekend and thanks again! 
Jan
