### ISSUE TITLE
Add user, group, and project management capabilities

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#54]
Need to add a route and extend the user responder.

**Comment by subotic** [comment]
Work-in-progress is on branch [wip/user-management](https://github.com/dhlab-basel/Knora/tree/wip/user-management)

**Comment by subotic** [comment]
Are users only allowed to be created by users with certain privileges, and if so, which privileges are these? Or are we going to allow self-registration, and only require that an user with certain privileges can add this new user to a project?

I think that the second case is easier to implement.

@benjamingeer @tobiasschweizer @lrosenth

**Comment by subotic** [comment]
#51 contains discussion regarding hashing of passwords, where we came to an agreement to use BCrypt    with the provision to take further steps as described in http://blog.ircmaxell.com/2012/12/seven-ways-to-screw-up-bcrypt.html.

**Comment by subotic** [comment]
https://crackstation.net/hashing-security.htm contains further best practices for generating/storing/using passwords.

**Comment by subotic** [comment]
Work in progress is on branch: [wip/user-management](https://github.com/dhlab-basel/Knora/tree/wip/user-management)

I have added a section about user, project, and group administration, proposing in broad strokes what each Knora endpoint should/could do. I will implement the basic behavior (as proposed), which we can then tweak over time. For easier access, I have attached the documentation as a pdf: [Administration.pdf](https://github.com/dhlab-basel/Knora/files/171689/Administration.pdf)

**Comment by subotic** [comment]
Proposed ontology changes:

- [ ] Should I add ```knora-base:groupName``` (change from ```foaf:name```) and make it a ```rdfs:subPropertyOf  foaf:name``` instead? This would be the same definition as for  ```knora-base:projectShortname```.

- [ ] Should I add ```knora-base:groupDescription``` and make it a ```rdfs:subPropertyOf  knora-base:description```?

- [ ] Should I make  ```knora-base:projectDescription``` a ```rdfs:subPropertyOf  knora-base:description```?

**Comment by benjamingeer** [comment]
This all looks OK to me, and I'd answer yes to all three proposed ontology changes. One thing I'm not sure about is that in the document you wrote, it looks like a lot of common operations, like adding a user to a group, require sysadmin privileges, which would mean a lot of work for the sysadmin, especially when Knora has hundreds of projects. I'm not sure what the best solution would be. I'd expect a common use case to be that a project wants to create its own groups and manage them by itself, and that several "project admins" would like to share that responsibility (similar to the way a mailing list can have several admins who share the responsibility of dealing with requests to join the list). We could imagine scenarios like this:

* I'm teaching a class and I have the names and email addresses of all the students. I want to create a project, divide the students into groups (which will only be relevant to this project, e.g. one group for each section of the class), and put some students in each group. I don't want people to be able to join the project or the group by themselves.
* I'm a Unibas librarian managing several archiving projects. I need to give everyone at the university permission to view all these projects. I want to create a group called UnibasUser that everyone with a Unibas email address will automatically belong to. Most of the resources in those projects can then grant view permission to UnibasUser. Or perhaps the group will be SwitchUser, for anyone at a Swiss university. Or something even broader.
* I'm doing a crowdsourcing project, which involves several different groups that work on different tasks. I'm hoping for thousands of users, and I'd like anyone to be able to join the project and add themselves to any group they want (as long as Knora verifies their email address), without needing approval from me.

These are just some thoughts. I'm not sure what our priorities should be.

**Comment by subotic** [comment]
Yes, I agree fully.

The 'Required Permission' bullet point should probably be better called 'Required Role'. In a role-based permission system, the permissions are defined for the roles, which are then attached to some entities (e.g., user, groups).

This is why we would then have the  ```system admin```, ```project admin```, and ```group admin``` roles. These roles, i.e. the permissions coming with a role, would then need to be "attached" to a user. I we take our group centric approach, we could create groups that have those roles attached and all users in this group would then have the privileges brought on by the role, i.e. all user in a group with the ```system admin``` role attached, would then become system administrators, and so on.

I probably didn't explained this good enough in the documentation.

Applied to your use cases:

- The teacher gets the ```system admin``` role and creates the project, or another user with this role creates the project. Then the teacher gets the ```project admin``` role for **this** project. As such, she is allowed to create groups, and by doing so is given the ```group admin``` role for these groups. Now she is allowed to add users to those groups or maybe just to invite them. As a user with the ```project admin``` role, she has the permission to grant permissions to the groups she created in regards to her project.

- The Unibas librarian having the ```project admin``` role for his projects, can create _smart groups_ to which a user belongs (or is invited) automatically. He can then give these smart groups permissions for accessing his projects.

- This could be solved by having groups with self-registration turned on, so that a user can join a group without needing approval of a user with the ```group admin``` role.

These are all just rough thoughts on how these use cases could be covered. I will add your use cases and my thoughts to the document. As for the priorities, I would say starting from the top and going down the list :-) The first use case seems to be the most _basic_ one, i.e. this is something which is expected that a system should be able to provide. The other two are a bit more advanced and would come after the first use case is covered.

**Comment by benjamingeer** [comment]
OK. So just to clarify, roles are simply sets of permissions that can be granted to a group, so each permission doesn't have to be granted separately.

Currently we have properties like `has*Permission` that grant permissions to groups. We could then have properties like `has*Role`, which would do the same thing but for sets of permissions. In principle roles could be configurable, but for now we could just have the three hard-coded roles you mentioned (system admin, project admin, group admin).

So I guess this means that projects have owners?

I agree, let's focus on the first use case. If we imagine that the course instructor has teaching assistants, and that she wants to give the teaching assistants some admin roles, it's similar to this use case, which should be very common:

* I'm the director of a research project and my team is divided into groups for different tasks. I want three people in the team to be able to administer the project and its users and groups (add users, add them to the project, create groups, and add users to groups).

We could then have something like this:

```
:ProjectX rdf:type knora-base:Project ;
    knora-base:attachedToUser :Sally ; # Sally created the project
    knora-base:hasProjectAdminRole :ProjectXAdminGroup .

:ProjectXAdminGroup rdf:type rdf:type knora-base:UserGroup .
```

Issue #1 is for figuring out what sorts of permissions projects need; I've assigned it to you.

**Comment by subotic** [comment]
Yes, roles can be used to group permissions. For now I would suggest to have only a small set of predefined roles to make it more simpler. In the future we can then expand this and allow user defined roles.

>  So I guess this means that projects have owners?

Yes. I'm not sure if groups should also be allowed to have groups attached to them:

```
<ProjectXAdminGroup> rdf:type knora-base:UserGroup ;
    knora-base:attachedToUser :Sally ; # Sally created the group
    knora-base:hasGroupAdminRole <ProjectXAdminGroupAdminGroup> .

<ProjectXAdminGroupAdminGroup> rdf:type rdf:type knora-base:UserGroup .
```

and so on ...

Probably if we want to attach group administrators, then we would do it directly:

```
<ProjectXAdminGroup> rdf:type knora-base:UserGroup ;
    knora-base:attachedToUser <Sally> ; # Sally created the group
    knora-base:hasGroupAdminRole <UserXY> .
```

The main differentiation between projects and groups would be that a group belongs to a specific project and has roles attached to it. It will make things easier if a group can only belong to one project.

```
<ProjectXContributorGroup> rdf:type rdf:type knora-base:UserGroup ;
    knora-base:attachedToProject <ProjectX> ;
    knora-base:hasRole :hasModifyRole . # gives ModifyPermission (and all lesser permissions)
```

Right know, every resource and property has permissions attached to them, granting directly some permissions to a group of users. Using roles attached to groups would allow a more indirect way of setting permissions, where a resource belonging to a project, would automatically grant a user the permissions he received by the role attached to the group the user belongs to. This means that the user:

```
<UserZ> rdf:type knora-base:User ;
    knora-base:isInGroup <ProjectXContributorGroup>
```

would get modify permissions to the following resource:

```
<http://data.knora.org/691e7e2244d5> rdf:type images:bild ;
    knora-base:attachedToUser <Sally> ;
    knora-base:attachedToProject <ProjectX> ;
    knora-base:hasViewPermission knora-base:KnownUser ;
    knora-base:hasRestrictedViewPermission knora-base:UnknownUser ;
    knora-base:hasChangeRightsPermission knora-base:Owner ;
```

This would be complementary to the current (direct) way of giving permissions. I think that in the majority of cases it will be enough to set the permissions through roles on groups belonging to a project (indirectly), while granting individual permissions to single resources for each group (directly), would be a more specialized use case. Just think of the nightmare of changing permissions. If we add a new group that has some set of permissions for all resources and values of a project, we would then need to change _all_ resources and values belonging to this project. A lot of things that would need to be touched. In the old Salsah I think that this wasn't even possible, i.e. new permissions would only be applied to newly created instances.

**Comment by subotic** [comment]
There would also be two distinct groups of roles:

1. Roles giving permissions for acting upon resources and values, e.g.,  ```ModifyRole```
2. Roles giving permissions for acting upon users, groups, and projects, e.g, ```hasGroupAdminRole```

What I would like to achieve is that the roles are all objects (like the ```ModifyRole```) and not properties like in the ```hasGroupAdminRole```.

**Comment by benjamingeer** [comment]
> For now I would suggest to have only a small set of predefined roles to make it more simpler. In the future we can then expand this and allow user defined roles.

OK.

> I'm not sure if groups should also be allowed to have groups attached to them

Looks complicated. Instead, if we take your idea that every group is specific to some project, then we could say that a project admin could administer all of the project's groups. Would that be good enough?

> ```
> <ProjectXContributorGroup> rdf:type rdf:type knora-base:UserGroup ;
>     knora-base:attachedToProject <ProjectX> ;
>     knora-base:hasRole :hasModifyRole . # gives ModifyPermission (and all lesser permissions)
> ```

If you're in this group, you get permission to modify any resource in `ProjectX`? Do you also get permission to modify the project itself (its name, etc.)?

> I think that in the majority of cases it will be enough to set the permissions through roles on groups belonging to a project (indirectly), while granting individual permissions to single resources for each group (directly), would be a more specialized use case. Just think of the nightmare of changing permissions.

I agree completely, but can you try to figure out roughly how much work it will be to implement this? If it's going to be a lot of work, we need to think about whether to prioritise it now or save it for later.

Also, there's something that's been bothering me about the names of all our permission properties. We have triples like `:someResource :hasSomePermission :someGroup`, which sounds as if it means that the resource has the permission, when actually it means that the resource *grants* the permission to the group. I think it would be clearer to have triples like `:someResource :grantsSomePermissionTo :someGroup`.

**Comment by subotic** [comment]
>> I'm not sure if groups should also be allowed to have groups attached to them

> Looks complicated. Instead, if we take your idea that every group is specific to some project, then we could say that a project admin could administer all of the project's groups. Would that be good enough?

For me it would be good enough. If Lukas wants more, then we could add this, but at a later time. So for now we would only have _system admin_ and _project admin_, while the _group admin_ would be scratched for now.

>> ```
>> <ProjectXContributorGroup> rdf:type rdf:type knora-base:UserGroup ;
>>     knora-base:attachedToProject <ProjectX> ;
>>     knora-base:hasRole :hasModifyRole . # gives ModifyPermission (and all lesser permissions)
>> ```

> If you're in this group, you get permission to modify any resource in `ProjectX`? Do you also get permission to modify the project itself (its name, etc.)?

Not necessarily. This would depend on the definition of the `ModifyRole`. For now I would say that the `ModifyRole` grants only the permission to change resources belonging to a project, and if someone wants to be able to modify the project itself, then he would need to have permissions given by the `ProjectAdminRole`.

>> I think that in the majority of cases it will be enough to set the permissions through roles on groups belonging to a project (indirectly), while granting individual permissions to single resources for each group (directly), would be a more specialized use case. Just think of the nightmare of changing permissions.

> I agree completely, but can you try to figure out roughly how much work it will be to implement this? If it's going to be a lot of work, we need to think about whether to prioritise it now or save it for later.

I have the feeling that it will be complicated, but we have already a working system in place, so we are not in a hurry. I would suggest that we first concentrate on applying RBAC (Role-Based Access Control) to user, project and group management. This will allow us to fine tune it and only then start thinking to apply it to the resources and values.

> Also, there's something that's been bothering me about the names of all our permission properties. We have triples like `:someResource :hasSomePermission :someGroup`, which sounds as if it means that the resource has the permission, when actually it means that the resource *grants* the permission to the group. I think it would be clearer to have triples like `:someResource :grantsSomePermissionTo :someGroup`.

Yes, true. This is not very consistent. In those cases we are "normally" using `isSomething` like in `:user :isInGroup :someGroup`. Applied to the permissions this would be something like `:someResource :isGrantingSomePermissionTo :someGroup`, but yours is also perfectly fine. We just need to be consistent. Makes it easier for a human to understand the meaning.

**Comment by benjamingeer** [comment]
> I have the feeling that it will be complicated, but we have already a working system in place, so we are not in a hurry.

We don't yet have a working system, because the current design doesn't say how you get permission to do these things:

* create users, groups, or projects
* put a user in a project or a group
* create a new resource in a project

What we need very soon is for someone to be able to set up a new project from scratch, using an admin interface, without having to bother the Knora sysadmin (who will probably be you :) ) every time they need to put a user in a group. Do we need RBAC for that? What's the minimum we need for Knora 1.0?

> isGrantingSomePermissionTo

Sounds weird in English. :) 'Grants' sounds more natural.

**Comment by subotic** [comment]
> We don't yet have a working system, because the current design doesn't say how you get permission to do these things:
- create users, groups, or projects
- put a user in a project or a group
- create a new resource in a project

What I meant is that we have a working system (or way of doing it) in regards to _directly_ defined permissions on resources and value. Yes, we don't have anything for users, groups, or projects, and this is what I would like to tackle on first. This would completely cover the first two points. Depending on what is enough for version Knora 1.0, also the third one. If it is enough to be able to create a resource (or value) and give it a predefined set of permissions (defined at project level), then this shouldn't be to hard. But if you also want to be able to change permissions on all resources of a project on the fly when changing the permissions defined at project level, than this is a bit harder, which would definitely be simpler to do if the _indirect permission resolving scheme_ is also in place for resources/values.

What I also meant, is to first implement the _indirect permission resolving scheme_ for user, group and project management, and then when this is fleshed out, implement it for resources/values.

> Do we need RBAC for that? What's the minimum we need for Knora 1.0?

Yes, we need RBAC if we want to implement the _indirect permission resolving scheme_. In the first iteration I would make the roles very simple and backed-in. Basically convert the current permissions into roles. Later on when we have time and the need arises we can expand on it.

To put this into context, the alternative is to stick with the current Discretionary Access Control (DAC) in form of Access Control Lists (ACL), where each resource has a list attached of who is allowed to do what. But this makes it a bit more complicated and involving when changing permissions on project level (think of `chmod -R` and `chown -R`).

I'm still trying to wrap my head around this myself. This [Wikipedia article](https://en.wikipedia.org/wiki/Computer_access_control) provides a high level overview over the different posibilities.

**Comment by subotic** [comment]
>> isGrantingSomePermissionTo

> Sounds weird in English. :) 'Grants' sounds more natural.

Yes, that's why we have you :-)

**Comment by benjamingeer** [comment]
OK, that all sounds reasonable to me. Can you please call Lukas and discuss it with him, and decide what's needed for Knora 1.0 (so that people can start creating new projects)? He's working at home this afternoon.

**Comment by subotic** [comment]
I talked to Lukas. The good news is that we don't need to version permission changes, that bad news is that I need to think everything more through :-) In short, we need to have the permissions directly attached to the resources, as the user should be able to create a resource with whatever permissions he likes.

**Use case:** User creates a resource and gives it whatever permissions he choses. He can give the resource any permissions on the spot (in the GUI), give it a personally predefined set of permissions, apply project default permissions if defined, or system default permissions if nothing else is defined.

**Comment by benjamingeer** [comment]
To get the SALSAH GUI working, Tobias has had to implement code that gets the list of all 'vocabularies' (ontologies) as well as all the resource classes defined in each one. For now he's using the list of ontology named graphs in `application.conf` as the list of ontologies. Given the named graph of an ontology, it's easy to query the resource classes that are defined in it. I don't see any other way that can be done.

This means that it is now a requirement to put each ontology in its own named graph. Once this information is in the triplestore instead of in `application.conf`, there will still need to be a way to get a list of all the ontologies in use and the named graphs they're stored in. (I guess the ontology IRI could be different from the name of its named graph.) I think it should also be possible for different projects to use the same ontology.

**Comment by subotic** [comment]
I have reworked the proposal for user, project, and group management, making it more in-line with the current way of assigning permissions. I think that it is also much simpler then before.

Here is an excerpt of the documentation with the relevant section: [Administration.pdf](https://github.com/dhlab-basel/Knora/files/179805/Administration.pdf)

Please take a look and let me know if you think that I missed something or whatever :-)

@benjamingeer @tobiasschweizer @lrosenth

**Comment by benjamingeer** [comment]
I'm just leaving for a week's holiday now, and I haven't been able to go over this in detail, but I had a quick look and it seems OK. My only question: currently resources/values grant permissions to groups. In other words, the resource is the subject of the permission predicate, and the group is the object of the permission predicate. In your design, sometimes the group is the subject of the permission predicate (e.g. hasProjectAdminPermissions). What are the advantages or disadvantages of that? Would it be better to be consistent, so that all permissions predicates point in the same direction (towards the group)? Please look at the method `PermissionUtilV1.getUserPermissionV1`, which is where all permission-checking currently happens, and see what you would have to change in either case. Either way is OK with me as long as you think it through and you're sure it won't be too complicated to implement.

I don't want to delay the implementation of this any more than necessary, so how about if you try to get Tobias's feedback on Monday, then start on the implementation?

**Comment by subotic** [comment]
>My only question: currently resources/values grant permissions to groups. In other words, the resource is the subject of the permission predicate, and the group is the object of the permission predicate. In your design, sometimes the user is the subject of the permission predicate (e.g. hasProjectAdminPermissions). What are the advantages or disadvantages of that? Would it be better to be consistent, so that all permissions predicates point in the same direction (towards the group or user)? 

I don't understand the question. Are you asking why it isn't like this: ``<Group-IRI> :grantsGoupAdminPermissionTo <User-IRI>`` ?

I would like to attach all properties to the user, so that it is easier to query, i.e. it can be retrieved by the same query used now to query all information about the user.

As far as ``PermissionUtilV1.getUserPermissionV1`` goes, there would be two additional built-in groups (``SystemAdmin`` and  ``ProjectAdmin``) that would need to be considered. All the information needed to decide if the user is part of those groups would be readily available in ``UserProfileV1``.

**Comment by benjamingeer** [comment]
Yes, that was my question and you've answered it. :) Sounds fine to me!

**Comment by subotic** [comment]
Here is an advanced copy of the administration/permission design. All comments are welcome.

[Knora-Permission-Redesign.pdf](https://github.com/dhlab-basel/Knora/files/329526/Knora-Permission-Redesign.pdf)

@lrosenth @benjamingeer @tobiasschweizer
