### ISSUE TITLE
`DefaultObjectAccessPermission` permissions defined on `Resource` are not hiding the ones defined on `ProjectAdmin` group

### ISSUE THREAD

**Issue by loicjaouen** [dhlab-basel/Knora#543]
If we set:
- `knora-base:DefaultObjectAccessPermission` for two groups:
  - `knora-base:ProjectMember` and
  - `knora-base:ProjectAdmin`
- and `knora-base:DefaultObjectAccessPermission` on an a Resource

Then:  
The Resource's permissions are selected for the project member group,
but the group's permissions are selected for the admin group.

**Comment by loicjaouen** [comment]
test case is on the way

**Comment by loicjaouen** [comment]
@subotic : I am very sorry to assign this to you, please let me know if it is not clear and if we can further assist... we will do our best as it is and urgent issue for us.
I leave the tag `in-progress` if you feel like working on this branch.

**Comment by subotic** [comment]
Thanks for the work ;-)

**Comment by subotic** [comment]
Just to make sure that I understand the problem:

 - found permissions: "RV knora-base:UnknownUser|V knora-base:KnownUser|M knora-base:ProjectMember|CR knora-base:ProjectAdmin", as defined on `knora-base:ProjectMember`  

 - expected permissions: "D knora-base:ProjectMember|CR knora-base:ProjectAdmin", as defined on `admin-group-rights:Concept`

So basically, the precedence rule is not working as it should, as the permissions defined on a resource class should precede the permissions defined on the ProjectMember group.

**Comment by mrivoal** [comment]
Actually, it is the other around: the precedence rule doesn't work when
1)  a DOAP permission is set on `knora-base:ProjectAdmin`
and
2) a DOAP permission (more restrictive) is set on a resource class (`admin-group-rights:Concept`).

But it works fine when a DOAP permission is set on `knora-base:ProjectMember`.

**Comment by subotic** [comment]
In that case, the precedence rule is working just fine :-)

Here the relevant excerpt from the documentation:

```
The following list is sorted by the permission precedence level in descending order:

    - permissions on ``knora-base:ProjectAdmin`` (highest level)
    - permissions on resource classes and property combination (own project)
    - permissions on resource classes and property combination (``knora-base:SystemProject``)
    - permissions on resource classes / properties (own project)
    - permissions on resource classes / properties (``knora-base:SystemProject``)
    - permissions on custom groups
    - permissions on ``knora-base:ProjectMember``
    - permissions on ``knora-base:KnownUser`` (lowest level)
```

Here you can see that DOA permissions defined on `knora-base:ProjectAdmin` have precedence over anything else.

Are you sure? The test @loicjaouen added fails for the normal user, which is only in the `knora-base:ProjectMember` group.

**Comment by mrivoal** [comment]
I will check with him first thing in the morning!

**Comment by mrivoal** [comment]
Ok, you are right. This is going to be very confusing... But in fact, in this case, I would expect the DOAP on knora-base:ProjectAdmin to have a lesser precedence than the DOAP set on a resource class. I expected the precedence rule for DOAP on knora-base:ProjectAdmin to work just like the DOAP on knora-base:ProjectMember actually do. Thence the quiproquo.

Because it makes sense to define DOAP on resource classes and property that gives a more restrictive permissions than the one you would set on a group (including knora-base:ProjectAdmin). But I realize now than I can overcome this by creating a project-specific admin group (like I did already). In that case, the precedence rule for custom group would apply.

Let me know what you think but I guess I have wasted your time (especially yours, @loicjaouen, I am really sorry :-(

**Comment by loicjaouen** [comment]
@subotic 
> In that case, the precedence rule is working just fine :-)

cool ;)

> The test @loicjaouen added fails for the normal user, which is only in the knora-base:ProjectMember group.

Strange, that's not what I get:

```
> graphdb:testOnly *AdminGroupRightsV1Spec*

/// ... ///

[info] - Load test data (6 seconds, 101 milliseconds)
[info] issue: admin
[info] - should retrieve the admin-group-rights users' profiles (116 milliseconds)
[info] - should return correct admin-group-rights:Concept resource permissions string for admin user *** FAILED *** (35 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected DefaultObjectAccessPermissionsStringResponseV1(CR knora-base:ProjectAdmin|D knora-base:ProjectMember), found DefaultObjectAccessPermissionsStringResponseV1(CR knora-base:ProjectAdmin|M knora-base:ProjectMember|V knora-base:KnownUser|RV knora-base:UnknownUser)

/// ... ///

[info] - should return correct admin-group-rights:Concept resource class permissions string for member user (15 milliseconds)
[info] Run completed in 8 seconds, 782 milliseconds.
[info] Total number of tests run: 4
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 3, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
```

That's the admin user as far as I see it.

@mrivoal : I should have read the doc more carefully too :(  
sure it takes time, but writing a test case is the best to make sure we all see and talk about the same thing.

**Comment by subotic** [comment]
@mrivoal don't worry

@loicjaouen yes, you are right. The test fails for the admin user case.

Can I close this issue and the PR, or are there any other questions?

**Comment by loicjaouen** [comment]
Thanks Ivan.  
Sure, let's close this.
