### ISSUE TITLE
Limit the max. execution time of a query for graphdb

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#549]
The max. execution time of a read query in graphdb can be limited: http://graphdb.ontotext.com/documentation/standard/configuring-a-repository.html#configuring-a-repository-configuration-parameters-query-timeout

We could add the option `owlim:query-timeout  "XY" ;` to the configuration.

There is also the options to set a timeout specifically for a repository: http://docs.rdf4j.org/rest-api/#_repository_queries

**Comment by benjamingeer** [comment]
Let's also set `query-limit-results`, "the maximum number of results returned from a query". We can set it to a very high number, but if someone does a query that returns a trillion triples (even if it returns them very fast), something is wrong and it should throw an exception.

**Comment by benjamingeer** [comment]
See also #550.

**Comment by tobiasschweizer** [comment]
In `webapi/util/ConstructResponseUtilV2.scala` we would have to handle the case that some required triples are not returned because of the global LIMIT and throw an apt exception.

**Comment by benjamingeer** [comment]
Let's try it and see what happens. Maybe GraphDB returns an exception if the limit is exceeded?

**Comment by tobiasschweizer** [comment]
Ok, let's do that next week!

**Comment by tobiasschweizer** [comment]
webapi/scripts/graphdb-se-knora-test-repository-config.ttl.tmpl

```
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix rep: <http://www.openrdf.org/config/repository#>.
@prefix sr: <http://www.openrdf.org/config/repository/sail#>.
@prefix sail: <http://www.openrdf.org/config/sail#>.
@prefix owlim: <http://www.ontotext.com/trree/owlim#>.

[] a rep:Repository ;
   rep:repositoryID "knora-test" ;
   rdfs:label "Knora test repository" ;
   rep:repositoryImpl [
     rep:repositoryType "openrdf:SailRepository" ;
     sr:sailImpl [
       # owlim:ruleset "empty" ;
       owlim:ruleset "PIE_FILE" ;
       owlim:check-for-inconsistencies "true";
       sail:sailType "owlim:Sail" ;
       owlim:base-URL "http://data.knora.org/" ;
       owlim:repository-type "file-repository" ;
       owlim:query-timeout "5" ;
       owlim:query-limit-results "200000";
       owlim:throw-QueryEvaluationException-on-timeout "true";
      ]
   ].
```

**Comment by tobiasschweizer** [comment]
setting the max execution time to 2 seconds prevents the problem reported in #685

if the setting is > 2 seconds, however, the triplestore still crashes
