### ISSUE TITLE
How to create an ActorRef outside an actor?

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#55]
Hi

What would be the best way to create an `ActorRef`outside an Actor (outside a class that extends `Actor`)?

On my branch `wip/setup_fake_responders`, I created a `TestResponderManagerV1` that extends `ResponderManager` and has access to all its definitions of the live routes.

However, each of these routes can be overridden in case someone passes a mock or fake responder:

```scala
override val sipiRouter = actor("mocksipi")(new Act {
        become {
            case sipiResponderConversionFileRequest: SipiResponderConversionFileRequestV1 => future2Message(sender(), imageConversionResponse(sipiResponderConversionFileRequest), log)
            case sipiResponderConversionPathRequest: SipiResponderConversionPathRequestV1 => future2Message(sender(), imageConversionResponse(sipiResponderConversionPathRequest), log)
        }
    })
``` 

What would be the best way to create an actor in a test like `SipiV1E2ESpec` to pass it to `TestResponderManagerV1` then?

The problem is that extending `Actor` and `ActorLogging` provides a lot of stuff that you have to explicitly deal with outside this context, like the logger or the `ActorContext` (` implicit ActorRefFactory required: if outside of an Actor you need an implicit ActorSystem, inside of an actor this should be the implicit ActorContext`).

So somehow I am breaking the design by creating those actors outside of an Actor.

CC: @subotic @benjamingeer

**Comment by benjamingeer** [comment]
> On my branch `wip/setup_fake_responders`, I created a `TestResponderManagerV1` that extends `ResponderManager` and has access to all its definitions of the live routes.

I'm looking on that branch, and I can't find anything called `TestResponderManagerV1`.

> What would be the best way to create an actor in a test like `SipiV1E2ESpec`

If I understand correctly, you're already doing that, in two different ways. First, you have this:

```
class SipiResponderManagerTest extends Actor
```

Second, you have this:

```
val sipiRouter = actor("mocksipi")(new Act {
```

It looks like `new Act` creates an actor. So it seems as if you already have two ways to create an actor in a test.

**Comment by benjamingeer** [comment]
Probably I just don't understand the question.

**Comment by subotic** [comment]
Exactly as Ben described it. There are these two ways. Both give you an ActorRef which you can pass around.

**Comment by tobiasschweizer** [comment]
On branch `wip/setup_fake_responders` in test there is a a file called `TestResponderManagerV1`: <https://github.com/dhlab-basel/Knora/blob/wip/setup_fake_responders/webapi/src/test/scala/org/knora/webapi/responders/v1/TestResponderManagerV1.scala>.

`TestResponderManagerV1` extends `ResponderManagerV1`, inheriting all of his routes which I made `protected` (instead of `private`).

What I would like to do, is moving the definition of an actor outside this context. So for example, I would like to define an actor simulating the Sipi Server in a test an pass it to `TestResponderManagerV1` when instantiating it, overriding the live actor inherited from `ResponderManagerV1` this way.

So in `ResourcesResponderV1Spec`, how would I define an actor and pass its reference to `TestResponderManagerV1` (line 72)?

**Comment by benjamingeer** [comment]
I'm on the train so I can't try this for you, but it looks to me as if you already have the actor you want, it's called `sipiRouter`. Have you tried moving its definition to a test, and passing it to the constructor of `TestResponderManagerV1`?

**Comment by tobiasschweizer** [comment]
Yes, I already have everything I want, I just wondered if I can move the definition of an actor to the test itself, so the `TestRespondermanager` would not actually have to contain the concrete implementations, but accept it as an argument. That would make it more generic.

But as far as I can tell, our design does not make it easy to define an actor outside a class extending actor. So maybe it is better to keep this definition where it is now.

**Comment by benjamingeer** [comment]
> I just wondered if I can move the definition of an actor to the test itself

What happens when you try that?

**Comment by tobiasschweizer** [comment]
> The problem is that extending Actor and ActorLogging provides a lot of stuff that you have to explicitly deal with outside this context, like the logger or the ActorContext (implicit ActorRefFactory required: if outside of an Actor you need an implicit ActorSystem, inside of an actor this should be the implicit ActorContext).

**Comment by benjamingeer** [comment]
I believe all the test specs already have an ActorSystem and a logger, which they get from CoreSpec.

**Comment by benjamingeer** [comment]
Have you tried writing the definition of your fake Sipi actor by putting something like this in your test?

```
class FakeSipiResponder extends ResponderV1
```

And then instantiating it with `new FakeSipiResponder` and passing it to the constructor of `TestResponderManagerV1`?

**Comment by benjamingeer** [comment]
(It would need a `receive` method like any other responder.)

**Comment by benjamingeer** [comment]
Sorry, not with `new` but with `system.actorOf` as shown here:

http://doc.akka.io/docs/akka/snapshot/scala/actors.html

**Comment by tobiasschweizer** [comment]
Yes, you are right. `system.actorOf` has to be used, not `new`. This was another problem I had :-)

Thanks for the hints. I will give it a try and let you know.

**Comment by tobiasschweizer** [comment]
done in <https://github.com/dhlab-basel/Knora/commit/9b794fa0645eebf0df4762cabbb655c6b40f901b>

I am wondering if there is a better way to handle the arguments passed to `TestResponderManagerV1`. In case a mock responder is not given, nothing has to be done at all. Is here some kind of conditional override?

**Comment by benjamingeer** [comment]
How about passing a `Map[String, ActorRef]` (name and actor) instead of all those options?
