### ISSUE TITLE
salsah-gui:guiOrder works for the "add resource" icon but not when you look at a resource already created

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Knora#555]
`salsah-gui:guiOrder` should also define the way the properties of a resource are displayed after the resource is created.

![capture d ecran 2017-06-29 a 11 26 03](https://user-images.githubusercontent.com/17294309/27681007-031057dc-5cbe-11e7-9a62-9fc3439ed230.png)

**Comment by loicjaouen** [comment]
- the request for building the "AddResource" view is: `http://localhost:3333/v1/resourcetypes/http://www.knora.org/ontology/anything#Thing` where the properties are ordered by `guiorder`
- the request viewing the resource is: `http://localhost:3333/v1/resources/http%3A%2F%2Frdfh.ch%2Fanything%2Ffh-OV832SDycvjxCcRI1TQ` and the `props` are not sorted by `guiorder`

**Comment by subotic** [comment]
Did you already created a branch for this?

**Comment by subotic** [comment]
It would be one line on the API side to fix this, if you want.

**Comment by loicjaouen** [comment]
yes, I have a fix gui side on the way

**Comment by subotic** [comment]
so no need for an API side fix? Or should we have one anyway, as this would provide a more consistent API behaviour?

**Comment by loicjaouen** [comment]
> so no need for an API side fix?

no need right now, thanks.

> Or should we have one anyway, as this would provide a more consistent API behaviour?

yes, I think so :)  

But I might have a biased point-of-vue as I have my head in salsah right now.

**Comment by loicjaouen** [comment]
<img width="1104" alt="capture d ecran 2017-06-30 a 07 57 11" src="https://user-images.githubusercontent.com/3933654/27722789-de61dcc4-5d69-11e7-9590-e8995af0511e.png">
