### ISSUE TITLE
Importing Pictures over API with Python - Akka Error message

### ISSUE THREAD

**Issue by janCstoffregen** [dhlab-basel/Knora#561]
Dear readers,
long story short: I get the following error message and wonder if you already know it. If not, do you have by chance a working script that imports a picture as part of a resource belonging to the test-ontologies given on Github? 

I get the following error message:
````scala
"status":4,"error":"org.knora.webapi.SipiException: Unknown error: akka.http.impl.engine.client.OutgoingConnectionBlueprint$UnexpectedConnectionClosureException: The http server closed the connection unexpectedly before delivering responses for 1 outstanding requests"}

````

I took this python script as an example to import a picture to Knora:
http://www.knora.org/documentation/manual/rst/knora-api-server/api_v1/adding-resources.html?highlight=import

It is almost the same as the original:
```
import requests, json

# a Python dictionary that will be turned into a JSON object
resourceParams = {
   'restype_id': 'http://www.knora.org/ontology/image#Photograph',
   'properties': {

   },
   'label': "Zuerich",
   'project_id': 'http://data.knora.org/projects/images'
}

# the name of the file to be submitted
filename = "/Users/system/Desktop/logo.jpg"

# a tuple containing the file's name, its binaries and its mimetype
file = {'file': (filename, open(filename, 'rb'), "image/jpeg")} # use name "file"

# do a POST request providing both the JSON and the binaries
r = requests.post("http://130.60.24.65:3333/v1/resources",
                  data={'json': json.dumps(resourceParams)}, # use name "json"
                  files=file,
                  auth=('multi.user@example.com', 'test'))

#r.raise_for_status()
print (r.text)
```
I left the properties empty because there is no property with cardinality 1 or 1-n. In the example in the docs, the property http://www.knora.org/ontology/knora-base#hasStillImageFileValue is not directly defined so it should work, right? Authentication works and I have created the folder /tmp/webapi_tmp on the server which was the previous error. Sipi prints accepted connection after executing the script. 

Thank you so much for your time and best regards,
Jan

**Comment by loicjaouen** [comment]
Hello @janCstoffregen 

preliminary question: is it right that your ontology is `image` and your project `images`?

Where is this error showing up, in which log?

You can try this which works for me, it is nearly the same as yours, but on the ontology `anything`:
```python
import requests, json

# a Python dictionary that will be turned into a JSON object
resourceParams = {
    'restype_id': 'http://www.knora.org/ontology/anything#ThingPicture',
    'properties': {
    },
    'label': "test resource",
    'project_id': 'http://data.knora.org/projects/anything'
}

# the name of the file to be submitted
filename = "myimage.jpg"

# a tuple containing the file's name, its binaries and its mimetype
file = {'file': (filename, open(filename, 'rb'), "image/jpeg")}  # use name "file"

# do a POST request providing both the JSON and the binaries
r = requests.post("http://localhost:3333/v1/resources",
                  data={'json': json.dumps(resourceParams)},  # use name "json"
                  files=file,
                  auth=('anything.user02@example.org', 'test'))

# r.raise_for_status()
print(r.text)
```

**Comment by loicjaouen** [comment]
ah... I got some answers to my questions:

> is it right that your ontology is image and your project images?

yes

> Where is this error showing up, in which log?

in the text of the http 500 response

> You can try this which works for me

it doesn't work for you as you have not set up `anything` on your server

**Comment by janCstoffregen** [comment]
I have the standard anything ontology from Github and am importing the ontology to the server right now and will try it out. Thank you so much for your fast response, I will get back right away when I have further information.

**Comment by janCstoffregen** [comment]
Should I not try it with the anything ontology first?

**Comment by loicjaouen** [comment]
you can do both in the order you prefer ;)

**Comment by janCstoffregen** [comment]
ok, :) I will try your script first and see if it works. Then the reason for this fault must be sth with my ontology.

**Comment by janCstoffregen** [comment]
Dear all,
please find attached all information to reconstruct the error.

Files and error message:
I have created a github repo where you can find the config files etc: https://github.com/janCstoffregen/Import-to-Knora-Akka-Error-Files
You can find the error message there as well. Please let me know if you need additional information. If you are interested in reconstructing the error on the server, you can send me your public key and have a look at it as well. 

I used the standard anything library and the exact same script that was mentioned above. It is in the repo as well. 

Regarding the Sipi logs, it just says "Sipi: Accepted connection from 130.60.24.65", I don't know where to find additional logs, would you mind letting me know if there is a file that I have not seen?

I used the Knora version on https://github.com/nie-ine/Knora, which was forked from your develop - branch.

For Sipi, I have installed all dependencies like described here: https://dhlab-basel.github.io/Sipi/documentation/building.html, and performed the build process with ignoring the errors that appear because I created some needed folders before starting the built process. The same error already occurred before I installed the dependencies.

I have researched the error and found some entries with the same error but it's a very general error message so the information in the forums seems to not be so applicable.

Thank you so much for helping me out!
I am looking forward to your answers and wish you a nice morning!
Jan

**Comment by benjamingeer** [comment]
@janCstoffregen What command are you using to start Sipi? You didn't say which Sipi config file you are using.

**Comment by benjamingeer** [comment]
https://github.com/dhlab-basel/Sipi/pull/198#issuecomment-316086467

https://github.com/dhlab-basel/Sipi/issues/200
