### ISSUE TITLE
[bulk xml import] min cardinality issue in xsd

### ISSUE THREAD

**Issue by SepidehAlassi** [dhlab-basel/Knora#573]
Example: 
In Biblio ontology, EditedBook is subclass of Book,  and Book is subclass of Publication.
I should be able to set publicationHasTitle which belongs to Publication in EditedBook,  see below:

  <biblio:EditedBook id="sequences_and_their_applications">
    <knoraXmlImport:label>sequences_and_their_applications</knoraXmlImport:label>
    <biblio:publicationHasTitle>Sequences and their applications</biblio:publicationHasTitle>
  </biblio:EditedBook>

But the xsd fails with message:

Invalid content was found starting with element 'biblio:publicationHasTitle'. One of '{\"http://api.knora.org/ontology/biblio/xml-import/v1#\":beol__comment, \"http://api.knora.org/ontology/biblio/xml-import/v1#\":bookHasISBN, \"http://api.knora.org/ontology/biblio/xml-import/v1#\":collectionNumber, \"http://api.knora.org/ontology/biblio/xml-import/v1#\":hasLink, \"http://api.knora.org/ontology/biblio/xml-import/v1#\":isPartOfCollection, \"http://api.knora.org/ontology/biblio/xml-import/v1#\":numPages, \"http://api.knora.org/ontology/biblio/xml-import/v1#\":numVolumes, \"http://api.knora.org/ontology/biblio/xml-import/v1#\":publicationHasAuthor, \"http://api.knora.org/ontology/biblio/xml-import/v1#\":publicationHasDOI, \"http://api.knora.org/ontology/biblio/xml-import/v1#\":publicationHasDate}' is expected."}

 These are properties  with minCardinality=0, but publicationHasTitle has minCardinality=1?

**Comment by benjamingeer** [comment]
I think this is because `publicationHasDate` is also required, and `publicationHasDate` comes before `publicationHasTitle` in the sequence of the properties of `EditedBook`. So you have to give `publicationHasDate` before you can give `publicationHasTitle`.
