### ISSUE TITLE
Fulltext Search and Extended Search documentations are not up to date

### ISSUE THREAD

**Issue by SepidehAlassi** [dhlab-basel/Knora#575]
The parameters filter_by_project , filter_by_restype, and filter_by_owner of documentation are renamed in code to filterByProject, filterByRestype and filterByOwner. 
It causes confusion for readers of documentation.

**Comment by tobiasschweizer** [comment]
Your are surely right pointing out the inconsistency in the naming of these parameters and the case classes that are used within Knora. We did this in order to be compliant with the old SALSAH Api (the GET URL parameters used by the old GUI). 

The documentation refers to the GET URL parameters that are processed in `SearchRouteV1.scala`:

```
        params.get("searchtype") match {
            case Some(List("extended")) => ()
            case other => throw BadRequestException(s"Unexpected searchtype param for extended search")
        }

        // only one value is expected
        val restypeIri: Option[IRI] = params.get("filter_by_restype") match {
            case Some(List(restype: IRI)) => Some(InputValidation.toIri(restype, () => throw BadRequestException(s"Unexpected param 'filter_by_restype' for extended search: $restype")))
            case other => None
        }

        // only one value is expected
        val projectIri: Option[IRI] = params.get("filter_by_project") match {
            case Some(List(project: IRI)) => Some(InputValidation.toIri(project, () => throw BadRequestException(s"Unexpected param 'filter_by_project' for extended search: $project")))
            case other => None
        }

        // only one value is expected
        val ownerIri: Option[IRI] = params.get("filter_by_owner") match {
            case Some(List(owner: IRI)) => Some(InputValidation.toIri(owner, () => throw BadRequestException(s"Unexpected param 'filter_by_owner' for extended search: $owner")))
            case other => None
        }

        // here, also multiple values can be given
        val propertyIri: Seq[IRI] = params.get("property_id") match {
            case Some(propertyList: Seq[IRI]) => propertyList.map(
                prop => InputValidation.toIri(prop, () => throw BadRequestException(s"Unexpected param 'property_id' for extended search: $prop"))
            )
            case other => Nil
        }
```

I think the user does not have to know how they are called internally. But for V2 we should stick to a consistent naming scheme whenever using GET parameters (although I would like to avoid using them as far as possible).

**Comment by tobiasschweizer** [comment]
We had a look at the problem and found out that the problem was that the parameters' values (Iris) were URL encoded twice. 

I will add a message to the `BadRequestException` in case of an invalid Iri that gives the client a hint that this is a common source of problem.
