### ISSUE TITLE
Salsah tests not passing since last commit

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#588]

**Comment by tobiasschweizer** [comment]
Where would I see the results of the failed tests for `develop`? I am only familiar with pull requests.

**Comment by subotic** [comment]
The `salsah` tests are not executed on Travis. For now, they need to be run manually. I was updating the `chromedriver` to the newest version and as I was trying it out, I saw that on test is failing.

**Comment by tobiasschweizer** [comment]
I guess that the expected order in the tests do not match anymore.

**Comment by tobiasschweizer** [comment]
`SearchAndEditSpec` ->

```
        "change the publication date of a book" in {

            page.open()

            page.doLogin(email = incunabulaUserEmail, password = testPassword, fullName = incunabulaUserFullName)

            page.clickExtendedSearchButton()

            page.selectVocabulary("0") // select all

            page.selectRestype("http://www.knora.org/ontology/incunabula#book")

            page.submitExtendedSearch()

            val rows = page.getExtendedSearchResultRows

            // open page of a book
            rows.head.click()

            val window = page.getWindow(1)


            // get metadata section
            val metadataSection: WebElement = page.getMetadataSection(window)

            // get a list of editing fields
            val editFields = page.getEditingFieldsFromMetadataSection(metadataSection)

            val pubdateField = editFields(7)
```

Number had to changed from 10 to 7

**Comment by subotic** [comment]
@loicjaouen If you like, you can use PR #590 for these changes. In the `wip/chromedriver` branch, I have commented out the failing browser tests which need fixing.

Unfortunately, on Travis the browser tests are a bit flaky and need to be restarted sometimes. Locally though, they should pass without any problems.

**Comment by tobiasschweizer** [comment]
@loicjaouen Do you need more help on this?

**Comment by loicjaouen** [comment]
@tobiasschweizer thanks for the offer, I should be fine with the explanation you provided above... of course re-ordering all the fields break these tests :)

**Comment by loicjaouen** [comment]
@subotic : is there a way to re-run the build? It fails at places that don't make sense according to the changes I made and I would like to check its consistency

**Comment by subotic** [comment]
Yes, for this you have to go to travis-ci.org and login. There you can restart the failed job. This happens from time to time. Browser tests are flaky, as the resources provided by Travis are limited and we have to run the whole stack.

**Comment by subotic** [comment]
Are those tests working locally?

I have found that for some tests to work on Travis, I needed to add `eventually` to a few right spots. I suppose that the lack of resources, surfaces race conditions, which are not present when running tests locally.

**Comment by loicjaouen** [comment]
yes, it works locally.

Most of the tests are working now on travis, only 2 still fail, I will do a few more trials to see what's wrong with them.

(It is a pain to change the git history for trying changes and wait 10 minutes to see the result)

**Comment by loicjaouen** [comment]
added comments about what works locally and can be switched from `ignore` to `in`.

Those last two cases, imho, require debug logging which is a pain to set-up right.

Can we set that as a separate issue and move on?

**Comment by subotic** [comment]
I would say so. Just create a new issue, so that this does not get forgotten.
