### ISSUE TITLE
Mouldy Dreams

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#594]
Interesting experiment in the fridge

![20170821_083605](https://user-images.githubusercontent.com/6000023/29509270-fbabeaec-8657-11e7-9b1c-058de9d176f1.jpg)
![20170821_083628](https://user-images.githubusercontent.com/6000023/29509271-fbcceddc-8657-11e7-96d4-672b11c369b1.jpg)

**Comment by subotic** [comment]
Looks like a lot of carbohydrates and vegan, so surely not mine ;-)

**Comment by sofiag** [comment]
haha, I was really curious what kind of salsah issue could be vegan! No, not mine either! ...

**Comment by BiancoA** [comment]
Not mine either :) 

but you could ask if it knows Scala or C++, it could be helpful!

**Comment by loicjaouen** [comment]
[molds are much smarter than they look](http://www.nature.com/news/how-brainless-slime-molds-redefine-intelligence-1.11811)

**Comment by tobiasschweizer** [comment]
probably they would write better code than us
