### ISSUE TITLE
[Salsah 1.5] Knora's IRIs syntax results in a cryptic projects' names for users

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Knora#595]
After our discussion in Basel in march and @lrosenth's mail on 16.03.2017 (DaSCH-Mise en place), it was decided that Knora's IRIs would comply to this syntax: http://rdfh/projectId/resourceId, "projectId" being a number of 4 digits.

As far as we understand, the "projectId" is to be set in the admin named graph like this :
```
<http://data.knora.org/projects/0001> a knora-base:knoraProject ;
        knora-base:projectBasepath "/data/SALSAH/parole-religieuse"^^xsd:string ;
        knora-base:projectLongname "Embarras de la parole religieuse"^^xsd:string ;
>>>        knora-base:projectShortname "0001"^^xsd:string ;
	knora-base:projectDescription "blablabla."^^xsd:string ;
	knora-base:projectKeywords "religion, genre, médias, sociologie des controverses, problèmes publics, démocratie libérale, approche quali-quantitative, réseaux"^^xsd:string ;
	knora-base:projectOntologyGraph "http://www.knora.org/ontology/parole-religieuse"^^xsd:string ;
        knora-base:projectDataGraph "http://www.knora.org/data/parole-religieuse"^^xsd:string ;
        knora-base:status "true"^^xsd:boolean ;
        knora-base:hasSelfJoinEnabled "false"^^xsd:boolean .
```

But `knora-base:projectShortname` is also the place where Salsah 1.5 looks for the name of a project to display it to the user. And this results in non-transparent projects names, such as here: 

![capture d ecran 2017-08-21 a 14 41 29](https://user-images.githubusercontent.com/17294309/29520414-37596e2e-8681-11e7-8b9f-c385d9b81309.png)

It is not very convenient and as the number of projects grows, it might become very obscure. I don't know the way it is supposed to work in Salsah 2.0 (will things be different there?) but I think there should be another way to display the name of the projects to the users.

At the moment, relying on `knora-base:projectLongname` is not an option because the lenght of some project's title will raise display issues... unless the long/official name of the project is recorded in the project metadata as discussed in #566? 

Any suggestion on how we could deal with it and provide greater clarity to the user?

**Comment by loicjaouen** [comment]
#472 "remove short names in Salsah from voc and project"  
It was done for vocabularies, not for projects.  
For sure, having long names twice in the top bar (next to salsah's logo) won't fit.  
And mislabelling "project code" as "short name" will sooner or later lead to errors.

**Comment by benjamingeer** [comment]
I just talked about this with Lukas. His suggestion is to store both project code and project short name.

Also, now that the DaSCH is using handle.net for persistent URLs, Lukas and I think we should use them as resource IRIs, too. There doesn't seem to be any need for `rdfh.ch` anymore. So resource IRIs would look like this:

[https://hdl.handle.net/20.500.12062/0801.c5058f3a](https://hdl.handle.net/20.500.12062/0801.c5058f3a)

That one redirects to the old SALSAH. We will set up a mechanism that redirects to SALSAH 1.5.

**Comment by benjamingeer** [comment]
(20.500.12062 is the prefix for the DaSCH, 0801 is the project code, and c5058f3a is the resource ID.)

**Comment by mrivoal** [comment]
Thanks, Ben. 
A few questions then:
* Does it means that a new property `projectCode` will be created in Knora-base and that `projectShortname` will then be used for what it means ?
* If we get rid of `rdfh.ch`, does it means that every triple in Knora will have an handle ID  (including values, lists, list nodes, users, permissions, projets) ?
* What will be the IRIs for the value of a resource? 

We are in production, which means that we already have a fair amount of triples using `rdfh.ch`. So, in any case, we will need your help for this. If our current IRIs doesn't fit into the handle syntax, we will also need your help to refactor completely our triples.

So, could we have a handle ID like this (if values have handle IDs like resources) :
`https://hdl.handle.net/20.500.12062/0801.2ZgaMKAjRsSNF178k3xIJQ.values.UHJNY8r5R2euNCfuU5KNpg`

**Comment by benjamingeer** [comment]
> Does it means that a new property `projectCode` will be created in Knora-base and that `projectShortname` will then be used for what it means ?

Yes.

> If we get rid of `rdfh.ch`, does it means that every triple in Knora will have an handle ID  (including values, lists, list nodes, users, permissions, projets) ?

Not every triple, just every Knora resource.

> What will be the IRIs for the value of a resource? 

Good question. We probably don't want to make values dereferenceable. Perhaps we could keep `rdfh.ch` for value IRIs.

> We are in production, which means that we already have a fair amount of triples using `rdfh.ch`. So, in any case, we will need your help for this. If our current IRIs doesn't fit into the handle syntax, we will also need your help to refactor completely our triples.

If it's important to you to have dereferenceable resource IRIs, we can convert your existing IRIs.

**Comment by benjamingeer** [comment]
Hmm... on second thought, there is code that depends on the fact that value IRIs are just resource IRIs with something extra added to them. I'll have to talk this over with Lukas.

**Comment by mrivoal** [comment]
>> If we get rid of rdfh.ch, does it means that every triple in Knora will have an handle ID (including values, lists, list nodes, users, permissions, projets) ?

> Not every triple, just every Knora resource.

Ok, but it is getting a little bit confusing now, because for resources, the right IRIs will be handle ID, for values (after what you are saying below) that would be `rdfh.ch` and for some others (but which ones?) the rights IRIs would be http://data.knora.org/xxxx. After you have discussed with Lukas and come to a decision regarding values IRIs, I will try and provide a sum up of what we currently do (with lists, list nodes, users, permissions, projets) and have it checked by you. I imagine it could be useful for others as well.

>> What will be the IRIs for the value of a resource?

> Good question. We probably don't want to make values dereferenceable. Perhaps we could keep `rdfh.ch` for value IRIs.

I agree. I don't think values sould be dereferenceable.

>> We are in production, which means that we already have a fair amount of triples using `rdfh.ch`. So, in any case, we will need your help for this. If our current IRIs doesn't fit into the handle syntax, we will also need your help to refactor completely our triples.

>If it's important to you to have dereferenceable resource IRIs, we can convert your existing IRIs.

That would be much appreciated :-)

**Comment by benjamingeer** [comment]
Just talked to Lukas about this again.

Currently all randomly generated IRIs have the `rdfh.ch` domain. We think it makes sense to change this just for resource IRIs. All other IRIs will stay as they are now.

When I make PR for this change, I'll add documentation so everything is clear. I'll also make a tool for updating existing IRIs.

**Comment by mrivoal** [comment]
Great :-)
Thanks a lot.

**Comment by benjamingeer** [comment]
I think this issue is resolved, since now we have project shortname as well as project ID. If not, please reopen it or open a new issue.
