### ISSUE TITLE
Refactor extended search v2

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#598]
Refactor the extended search v2 so it supports paging:

1. do a prequery possibly involving ORDER BY criteria that returns an ordered list of the Iris of the main resource. If no ORDER BY criteria are given, sort by the Iri of the main resource. The prequery is a SELECT query with a WHERE clause containing all the user provided restrictions. The SELECT query has an OFFSET and a LIMIT. The prequery does not get information about the value objects where this is not needed for making the restrictions.

2.  For a certain amount of Iris returned by the prequery, do a CONSTRUCT query (add Filters that restrict the variable representing the main resources to these Iris). Its WHERE clause contains all the user provided restrictions and gets information about the value object. Information about the value objects are obtained in a generic way: 
    ```
    ?mainRes knora-base:hasValue ?valueObject .
    ?valueObject a knora-base:Value .            
    GRAPH <http://www.ontotext.com/explicit> {
         ?valueObject knora-base:isDeleted false .

         ?valueObject a ?valueObjectType ;
         ?valueObjectProperty ?valueObjectValue .
    } 
    ``` 
    Check all resource and value object permissions in Scala: **The user must have permissions on all values in the WHERE clause, otherwise the main resource cannot be returned.**

    Look a the information in the user-provided CONSTRUCT clause and ignore the properties that are not mentioned. Since all the values of a resource are requested in a generic way, the CONSTRUCT query may return more information than the  user wants to see.

**Comment by tobiasschweizer** [comment]
Sample query 1:

Return all the pages of the book "[Das] Narrenschiff (lat.)" ordered by their sequence number. The result has to include the pagenum.

The user provides this query:

```
PREFIX incunabula: <http://api.knora.org/ontology/incunabula/simple/v2#>
PREFIX knora-api: <http://api.knora.org/ontology/knora-api/simple/v2#>

    CONSTRUCT {
        ?page knora-api:isMainResource true .

        ?page knora-api:isPartOf <http://data.knora.org/b6b5ff1eb703> .

        ?page incunabula:pagenum ?pagenum

    } WHERE {

        ?page a incunabula:page .
        ?page a knora-api:Resource .

        ?page incunabula:partOf <http://data.knora.org/b6b5ff1eb703> .
        incunabula:partOf knora-api:objectType knora-api:Resource .

        <http://data.knora.org/b6b5ff1eb703> a knora-api:Resource .

        ?page incunabula:seqnum 10 .
        incunabula:seqnum knora-api:objectType xsd:integer .

    }
```

Prequery: 
```
SELECT DISTINCT ?page ?seqnum__valueHasInteger
WHERE {
    ?page <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.knora.org/ontology/knora-base#Resource> .
    ?page <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.knora.org/ontology/incunabula#page> .
    GRAPH <http://www.ontotext.com/explicit> {
        ?page <http://www.knora.org/ontology/knora-base#isDeleted> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
    }
    ?page <http://www.knora.org/ontology/incunabula#partOf> <http://data.knora.org/b6b5ff1eb703> .
    <http://data.knora.org/b6b5ff1eb703> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.knora.org/ontology/knora-base#Resource> .
    GRAPH <http://www.ontotext.com/explicit> {
        <http://data.knora.org/b6b5ff1eb703> <http://www.knora.org/ontology/knora-base#isDeleted> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
    }
    
    ?page <http://www.knora.org/ontology/knora-base#seqnum> ?seqnum .
    GRAPH <http://www.ontotext.com/explicit> {
        ?seqnum <http://www.knora.org/ontology/knora-base#isDeleted> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
        ?seqnum <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.knora.org/ontology/knora-base#IntValue> .
        ?seqnum <http://www.knora.org/ontology/knora-base#valueHasInteger> ?seqnum__valueHasInteger .
    }
    
    ?page <http://www.knora.org/ontology/incunabula#pagenum> ?pagenum .
    
} ORDER BY ?seqnum__valueHasInteger OFFSET 0 LIMIT 400
```

**Comment by tobiasschweizer** [comment]
PREFIX knora-base: <http://www.knora.org/ontology/knora-base#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX incunabula: <http://www.knora.org/ontology/incunabula#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
 ?page knora-base:isMainResource true .
 ?page rdf:type knora-base:Resource .
 
 ?page knora-base:isDeleted false .
 ?page rdfs:label ?page__ResourceLabel .
 ?page rdf:type ?page__ResourceType .
 ?page knora-base:attachedToUser ?page__ResourceCreator .
 ?page knora-base:hasPermissions ?page__ResourcePermissions .
 ?page knora-base:attachedToProject ?page__ResourceProject . 
    
 <http://data.knora.org/b6b5ff1eb703> rdf:type knora-base:Resource .
 <http://data.knora.org/b6b5ff1eb703> knora-base:isDeleted false .
 <http://data.knora.org/b6b5ff1eb703> rdfs:label ?httpdataknoraorgb6b5ff1eb703__ResourceLabel .
 <http://data.knora.org/b6b5ff1eb703> rdf:type ?httpdataknoraorgb6b5ff1eb703__ResourceType .
 <http://data.knora.org/b6b5ff1eb703> knora-base:attachedToUser ?httpdataknoraorgb6b5ff1eb703__ResourceCreator .
 <http://data.knora.org/b6b5ff1eb703> knora-base:hasPermissions ?httpdataknoraorgb6b5ff1eb703__ResourcePermissions .
 <http://data.knora.org/b6b5ff1eb703> knora-base:attachedToProject ?httpdataknoraorgb6b5ff1eb703__ResourceProject .
 
    
 ?page knora-base:hasValue ?valueObject .
 ?page ?prop ?valueObject .
 ?valueObject a knora-base:Value .            
 ?valueObject knora-base:isDeleted false .

 ?valueObject a ?valueObjectType ;
 ?valueObjectProperty ?valueObjectValue .

    
} WHERE {
 ?page rdf:type knora-base:Resource .
 ?page rdf:type incunabula:page .
 #FILTER(?page = <http://data.knora.org/7bbb8e59b703>)
            
 GRAPH <http://www.ontotext.com/explicit> {
     ?page knora-base:isDeleted false .
     ?page rdfs:label ?page__ResourceLabel .
     ?page rdf:type ?page__ResourceType .
     ?page knora-base:attachedToUser ?page__ResourceCreator .
     ?page knora-base:hasPermissions ?page__ResourcePermissions .
     ?page knora-base:attachedToProject ?page__ResourceProject .
 }

 ?page incunabula:partOf <http://data.knora.org/b6b5ff1eb703> .
 GRAPH <http://www.ontotext.com/explicit> {
     ?page ?page__httpwwwknoraorgontologyincunabulapartOf__httpdataknoraorgb6b5ff1eb703__linkProp <http://data.knora.org/b6b5ff1eb703> .
 }
    
 ?page knora-base:hasValue ?page__httpwwwknoraorgontologyincunabulapartOf__httpdataknoraorgb6b5ff1eb703__linkObj .
 
    GRAPH <http://www.ontotext.com/explicit> {
     ?page ?page__httpwwwknoraorgontologyincunabulapartOf__httpdataknoraorgb6b5ff1eb703__linkValueProp ?page__httpwwwknoraorgontologyincunabulapartOf__httpdataknoraorgb6b5ff1eb703__linkObj .
     ?page__httpwwwknoraorgontologyincunabulapartOf__httpdataknoraorgb6b5ff1eb703__linkObj knora-base:isDeleted false .
     ?page__httpwwwknoraorgontologyincunabulapartOf__httpdataknoraorgb6b5ff1eb703__linkObj rdf:type knora-base:LinkValue .
     ?page__httpwwwknoraorgontologyincunabulapartOf__httpdataknoraorgb6b5ff1eb703__linkObj rdf:subject ?page .
     ?page__httpwwwknoraorgontologyincunabulapartOf__httpdataknoraorgb6b5ff1eb703__linkObj rdf:predicate ?page__httpwwwknoraorgontologyincunabulapartOf__httpdataknoraorgb6b5ff1eb703__linkProp .
     ?page__httpwwwknoraorgontologyincunabulapartOf__httpdataknoraorgb6b5ff1eb703__linkObj rdf:object <http://data.knora.org/b6b5ff1eb703> .
 
 }
 <http://data.knora.org/b6b5ff1eb703> rdf:type knora-base:Resource .
    
 GRAPH <http://www.ontotext.com/explicit> {
     <http://data.knora.org/b6b5ff1eb703> knora-base:isDeleted false .
     <http://data.knora.org/b6b5ff1eb703> rdfs:label ?httpdataknoraorgb6b5ff1eb703__ResourceLabel .
     <http://data.knora.org/b6b5ff1eb703> rdf:type ?httpdataknoraorgb6b5ff1eb703__ResourceType .
     <http://data.knora.org/b6b5ff1eb703> knora-base:attachedToUser ?httpdataknoraorgb6b5ff1eb703__ResourceCreator .
 
     <http://data.knora.org/b6b5ff1eb703> knora-base:hasPermissions ?httpdataknoraorgb6b5ff1eb703__ResourcePermissions .
 
     <http://data.knora.org/b6b5ff1eb703> knora-base:attachedToProject ?httpdataknoraorgb6b5ff1eb703__ResourceProject .
 }

 ?page <http://www.knora.org/ontology/incunabula#seqnum> ?seqnum .
 GRAPH <http://www.ontotext.com/explicit> {
     ?seqnum <http://www.knora.org/ontology/knora-base#isDeleted> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
 } 
    ?page <http://www.knora.org/ontology/incunabula#pagenum> ?pagenum .
 GRAPH <http://www.ontotext.com/explicit> {
     ?pagenum <http://www.knora.org/ontology/knora-base#isDeleted> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
 }
    
    ?page knora-base:hasStillImageFileValue ?file
GRAPH <http://www.ontotext.com/explicit> {
     ?file <http://www.knora.org/ontology/knora-base#isDeleted> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
 }
    

?page knora-base:hasValue ?valueObject .
   ?valueObject a knora-base:Value .            
GRAPH <http://www.ontotext.com/explicit> {
        ?page ?prop ?valueObject .
     ?valueObject knora-base:isDeleted false .

     ?valueObject a ?valueObjectType ;
     ?valueObjectProperty ?valueObjectValue .
} 
 
    
 }

**Comment by tobiasschweizer** [comment]
@benjamingeer says: in the example query above, you don't need to check the `rdf:subject`, `rdf:predicate` and `rdf:object` of the `LinkValue` in SPARQL, because you can do this in Scala. You just need to get the explicit link property in SPARQL. The CONSTRUCT query will return all the link values in the resource. In Scala you need to look at the subject, predicate, and object of the link, and find the corresponding link value so you can check its permissions.

**Comment by benjamingeer** [comment]
Two things just occurred to me:

First, instead of using a FILTER to provide the IRIs of the main resources in the CONSTRUCT query, I think this is what `VALUES` is for:

https://www.w3.org/TR/sparql11-query/#inline-data

Second, since the pre-query and the CONSTRUCT query are now pretty fast, maybe we could just put the pre-query inside the CONSTRUCT query as a subquery. It would be worth seeing whether it's any slower that way now.

**Comment by tobiasschweizer** [comment]
I will see if that is possible, thanks for the hint.

In ordr to find out, if all the values are returned after checking their permission in Scala, we could mark them in the Construct clause, lie we do for the main resource. E.g., ?valobj knora-base:isRequested true

Before passing them ro the Scala processor, we could partition out those predicates and remember the Iris of the value objects. When the results are there, we see if all the value object Iris are still there. If not, the resource is not returned.

**Comment by tobiasschweizer** [comment]
I ähad this idea while swimming.

Also what happens if we order by a property that has multiple instances? Maybe we shoudl always include the main resource's Iri as the last order by criterion.

**Comment by benjamingeer** [comment]
> Also what happens if we order by a property that has multiple instances?

If a single property has multiple matching values in a single resource, the SELECT query will return multiple rows for that resource. To me this doesn't seem like a problem in itself. We just need the order of results to be deterministic. What could be a problem is if there are two resources with the same order value. What order should they be returned in? In that case I think you're right, we should include the resource's IRI as an ORDER by criterion, to make the order predictable.

If the same resource has multiple matching values for the same property, we'll get that resource several times in the results. We can filter out redundant resources in the results we return to the client. Again, this would mean that the number of results per page will be unpredictable. But I think this is OK. I think the important thing is that there's a way to get the next page or the previous page without missing any results.

**Comment by tobiasschweizer** [comment]
```
 CONSTRUCT {
 ?page <http://www.knora.org/ontology/knora-base#isMainResource> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
 ?page <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.knora.org/ontology/knora-base#Resource> .
 ?page <http://www.knora.org/ontology/knora-base#isDeleted> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
 ?page ?page__ResProp ?page__ResObj .
 ?page <http://www.knora.org/ontology/knora-base#hasValue> ?page__Value .
 ?page ?page__hasValue ?page__Value .
 ?page__Value <http://www.knora.org/ontology/knora-base#isDeleted> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
 ?page__Value ?page__Value__hasValue ?page__Value__Value .
 ?page <http://www.knora.org/ontology/knora-base#isPartOf> <http://data.knora.org/b6b5ff1eb703> .
 <http://data.knora.org/b6b5ff1eb703> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.knora.org/ontology/knora-base#Resource> .
 <http://data.knora.org/b6b5ff1eb703> <http://www.knora.org/ontology/knora-base#isDeleted> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
 <http://data.knora.org/b6b5ff1eb703> ?httpdataknoraorgb6b5ff1eb703__ResProp ?httpdataknoraorgb6b5ff1eb703__ResObj .
 <http://data.knora.org/b6b5ff1eb703> <http://www.knora.org/ontology/knora-base#hasValue> ?httpdataknoraorgb6b5ff1eb703__Value .
 <http://data.knora.org/b6b5ff1eb703> ?httpdataknoraorgb6b5ff1eb703__hasValue ?httpdataknoraorgb6b5ff1eb703__Value .
 ?httpdataknoraorgb6b5ff1eb703__Value <http://www.knora.org/ontology/knora-base#isDeleted> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
 ?httpdataknoraorgb6b5ff1eb703__Value ?httpdataknoraorgb6b5ff1eb703__Value__hasValue ?httpdataknoraorgb6b5ff1eb703__Value__Value .
 } WHERE {
 VALUES ?page { <http://data.knora.org/df2ebbecbb03> <http://data.knora.org/40c11d94b703> <http://data.knora.org/693ad961bc03> <http://data.knora.org/7c06d252ba03> <http://data.knora.org/8fd2ca43b803> <http://data.knora.org/f2fab3ddb903> <http://data.knora.org/2df524a3b903> <http://data.knora.org/b7004318ba03> <http://data.knora.org/68ef9568b903> <http://data.knora.org/54d8597eb803> <http://data.knora.org/7bbb8e59b703> <http://data.knora.org/a3e9062eb903> <http://data.knora.org/a4344a27bc03> <http://data.knora.org/cacc3b09b803> <http://data.knora.org/901d0e3dbb03> <http://data.knora.org/2e40689cbc03> <http://data.knora.org/05c7acceb703> <http://data.knora.org/cb177f02bb03> <http://data.knora.org/55239d77bb03> <http://data.knora.org/0612f0c7ba03> <http://data.knora.org/dee377f3b803> <http://data.knora.org/19dee8b8b803> <http://data.knora.org/1a292cb2bb03> <http://data.knora.org/410c618dba03> <http://data.knora.org/f345f7d6bc03> }
 {
 ?page <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.knora.org/ontology/knora-base#Resource> .
 GRAPH <http://www.ontotext.com/explicit> {
     ?page <http://www.knora.org/ontology/knora-base#isDeleted> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
 }
 GRAPH <http://www.ontotext.com/explicit> {
     ?page ?page__ResProp ?page__ResObj .
 }
 FILTER NOT EXISTS {
  ?page <http://www.knora.org/ontology/knora-base#resourceProperty> ?page__ResObj .
 
 }
 } UNION {
 ?page <http://www.knora.org/ontology/knora-base#hasValue> ?page__Value .
 GRAPH <http://www.ontotext.com/explicit> {
     ?page ?page__hasValue ?page__Value .
 }
 GRAPH <http://www.ontotext.com/explicit> {
     ?page__Value <http://www.knora.org/ontology/knora-base#isDeleted> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
 }
 GRAPH <http://www.ontotext.com/explicit> {
     ?page__Value ?page__Value__hasValue ?page__Value__Value .
 }
 }
 ?page <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.knora.org/ontology/knora-base#StillImageRepresentation> .
 ?page <http://www.knora.org/ontology/knora-base#isPartOf> <http://data.knora.org/b6b5ff1eb703> .
 {
 <http://data.knora.org/b6b5ff1eb703> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.knora.org/ontology/knora-base#Resource> .
 GRAPH <http://www.ontotext.com/explicit> {
     <http://data.knora.org/b6b5ff1eb703> <http://www.knora.org/ontology/knora-base#isDeleted> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
 }
 GRAPH <http://www.ontotext.com/explicit> {
     <http://data.knora.org/b6b5ff1eb703> ?httpdataknoraorgb6b5ff1eb703__ResProp ?httpdataknoraorgb6b5ff1eb703__ResObj .
 }
 FILTER NOT EXISTS {
  <http://data.knora.org/b6b5ff1eb703> <http://www.knora.org/ontology/knora-base#resourceProperty> ?httpdataknoraorgb6b5ff1eb703__ResObj .
 
 }
 } UNION {
 <http://data.knora.org/b6b5ff1eb703> <http://www.knora.org/ontology/knora-base#hasValue> ?httpdataknoraorgb6b5ff1eb703__Value .
 GRAPH <http://www.ontotext.com/explicit> {
     <http://data.knora.org/b6b5ff1eb703> ?httpdataknoraorgb6b5ff1eb703__hasValue ?httpdataknoraorgb6b5ff1eb703__Value .
 }
 GRAPH <http://www.ontotext.com/explicit> {
     ?httpdataknoraorgb6b5ff1eb703__Value <http://www.knora.org/ontology/knora-base#isDeleted> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
 }
 GRAPH <http://www.ontotext.com/explicit> {
     ?httpdataknoraorgb6b5ff1eb703__Value ?httpdataknoraorgb6b5ff1eb703__Value__hasValue ?httpdataknoraorgb6b5ff1eb703__Value__Value .
 }
 }
 ?page <http://www.knora.org/ontology/knora-base#seqnum> ?seqnum .
 GRAPH <http://www.ontotext.com/explicit> {
     ?seqnum <http://www.knora.org/ontology/knora-base#isDeleted> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
 }
 ?page <http://www.knora.org/ontology/knora-base#hasStillImageFileValue> ?file .
 GRAPH <http://www.ontotext.com/explicit> {
     ?file <http://www.knora.org/ontology/knora-base#isDeleted> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
 }
 }
```

**Comment by tobiasschweizer** [comment]
```
CONSTRUCT {
	   ?resource <http://www.knora.org/ontology/knora-base#isMainResource> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .

    ?resource <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.knora.org/ontology/knora-base#Resource> .

    ?resource ?page__ResProp ?page__ResObj .
    ?resource <http://www.knora.org/ontology/knora-base#hasValue> ?page__Value .

    ?resource ?page__hasValue ?page__Value .
    ?page__Value ?page__Value__hasValue ?page__Value__Value .

} WHERE {
	VALUES ?resource {
        <http://data.knora.org/df2ebbecbb03> <http://data.knora.org/40c11d94b703> <http://data.knora.org/693ad961bc03> <http://data.knora.org/7c06d252ba03> <http://data.knora.org/8fd2ca43b803> <http://data.knora.org/f2fab3ddb903> <http://data.knora.org/2df524a3b903> <http://data.knora.org/b7004318ba03> <http://data.knora.org/68ef9568b903> <http://data.knora.org/54d8597eb803> <http://data.knora.org/7bbb8e59b703> <http://data.knora.org/a3e9062eb903> <http://data.knora.org/a4344a27bc03> <http://data.knora.org/cacc3b09b803> <http://data.knora.org/901d0e3dbb03> <http://data.knora.org/2e40689cbc03> <http://data.knora.org/05c7acceb703> <http://data.knora.org/cb177f02bb03> <http://data.knora.org/55239d77bb03> <http://data.knora.org/0612f0c7ba03> <http://data.knora.org/dee377f3b803> <http://data.knora.org/19dee8b8b803> <http://data.knora.org/1a292cb2bb03> <http://data.knora.org/410c618dba03> <http://data.knora.org/f345f7d6bc03>
    }

    GRAPH <http://www.ontotext.com/explicit> {
	       ?resource ?page__ResProp ?page__ResObj .
    }

    ?resource <http://www.knora.org/ontology/knora-base#hasValue> ?page__Value .

    GRAPH <http://www.ontotext.com/explicit> {
        ?resource ?page__hasValue ?page__Value .
        ?page__Value ?page__Value__hasValue ?page__Value__Value .
    }

    GRAPH <http://www.ontotext.com/explicit> {
         <http://data.knora.org/b6b5ff1eb703> ?book_prop ?book_value .
    }

    <http://data.knora.org/b6b5ff1eb703> <http://www.knora.org/ontology/knora-base#hasValue> ?page__Value .

}
```
