### ISSUE TITLE
Replace salsa-gui:guiOrder with an annotation on resource classes

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#601]
The `salsah-gui:guiOrder` property predicate affects all uses of the property it's attached to, but it would make more sense to specify property order per resource class. We can do this by attaching an annotation to the resource class, containing a comma-separated list of property IRIs.

cc @kilchenmann @sofiag

**Comment by tobiasschweizer** [comment]
Would this mean that `salsah-gui:guiOrder` would be removed? Would v1 and the Salsah 1.5 GUI have to be adapted?

**Comment by benjamingeer** [comment]
The v1 API and the SALSAH 1.5 GUI can stay the same, we're just going to store the information in a different way in the triplestore.

**Comment by mrivoal** [comment]
Does it means that we will have to refactor our current ontologies accordingly in order for it to work in Salsah 2.0?

**Comment by benjamingeer** [comment]
> Does it means that we will have to refactor our current ontologies accordingly in order for it to work in Salsah 2.0?

Yes, but maybe I can make a tool to help with this.

**Comment by mrivoal** [comment]
That would very be helpful!

**Comment by loicjaouen** [comment]
On a second thought, I am not so fond of a comma separated list; it duplicates information (properties of a resource will be listed in cardinalities and in this list) and that lets room for the two lists to diverge.

Feature wise, it is still better than what we have now... and I guess that:
- with a comma separated list, one can change the list on the fly (without having to reload the ontology)
- eventually we will have a tool to automate ontology writing and the ontology editor will make sure to sync the two lists

**Comment by benjamingeer** [comment]
@loicjaouen You're right, on second thought I don't like it either. Let me see if I can put an annotation property on the cardinality (i.e. on the `owl:Restriction`) instead.
