### ISSUE TITLE
Shouldn't a knora-base:SystemAdmin be allowed to create resources in every project ?

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Knora#610]
Just wondering... According to Knora documentation, 

> The knora-base:SystemAdmin group receives implicitly the following permissions:
> 
> - receives implicitly ProjectAllAdminPermission for all projects.
> - receives implicitly ProjectResourceCreateAllPermission for all projects.
> - receives implicitly CR on all objects from all projects.
> 
> Theses permissions are baked into the system, and cannot be changed.

By reading 
> receives implicitly ProjectResourceCreateAllPermission for all projects.

I thought that there was no need to indicate for a `knora-base:SystemAdmin` that he was in a project or member of a group within a project. But, as **I got the following error in attempting to create a new resource as knora-base:SystemAdmin**: 
```
error
Bad request
The request content was malformed:
Object is missing required member 'project_id' 
```
I guess I should precise something. But what is it? The projects IRIs? The projects IRIs and their group IRIs respectively? or should I use the property `knora-base:isInProjectAdminGroup` and have it point to all the project IRIs ? I tried the last option and I still had the same error message as above.

Isn't the whole point of being a `knora-base:SystemAdmin` not being forced to define every project and/or group IRIs for test purpose? However, what should I do to be able to access several projects as a member of their `knora-base:admin group` (I think it should be possible, shouldn't it)?

**Comment by subotic** [comment]
Hi Marion

Yes, `knora-base:SystemAdmin` should be able to create a new resource. From the error, I assume that the IRI of the project for which this resource should be created is missing.

**Comment by mrivoal** [comment]
Hi Ivan,

Thanks, but the IRI of the project should be the object of `knora-base:isInProjectAdminGroup` property, right?
If so, even when the IRI of the project is given, I get the same error (saying that, actually, the project-id is missing).

**Comment by mrivoal** [comment]
I am quite convinced that is a bug. Could you please have a look at this?

**Comment by subotic** [comment]
To make sure, I have created a test in this PR: https://github.com/dhlab-basel/Knora/pull/624

As far as I can tell, creating a resource as system admin is working.

Could you please take a look, and see if this test is doing the same thing you are trying to do?

**Comment by mrivoal** [comment]
Yes, I will and I will let you know. Thanks!

**Comment by mrivoal** [comment]
Hum... From your test, I am having a hard time to understand how to set up an admin user correctly.
One precision though: all I am currently doing is through Salsah 1.5 GUI.

Here is what I did: 
```
<http://rdfh.ch/users/mRivoal> a knora-base:User ;
        knora-base:userid "mRivoal"^^xsd:string ;
        knora-base:givenName "Marion"^^xsd:string ;
        knora-base:familyName "Rivoal"^^xsd:string ;
        knora-base:password "$e0801$GixW+508x22RZIcS10IWtXHJjn4znFNQpObreAavsiclAazUAPh99XJD5gycaPo72EyR5XBdfiTbR/NW2Dgsdg==$ZECNsLwMliVbfl2dhVBpU/ctMJqg4SFOP701D8ChrIw="^^xsd:string ;
        knora-base:email "marion.rivoal@unil.ch"^^xsd:string ;
        knora-base:preferredLanguage "fr"^^xsd:string ;
        knora-base:status "true"^^xsd:boolean ;
        knora-base:isInProject <http://www.knora.org/ontology/knora-base#SystemProject> ;
        knora-base:isInGroup <http://rdfh.ch/groups/drawings-gods-admin> ;
        knora-base:isInSystemAdminGroup "true"^^xsd:boolean .
```

With this data, I don't get the error I mentionned earlier but I get a new one:

```
{"status":11,"error":"org.knora.webapi.BadRequestException: The resulting request would lead to an empty permissions string, which is not allowed. Are all the necessary default object access permissions defined?"}
```

**Comment by subotic** [comment]
For a user to be considered a `SystemAdmin` you only need to have `knora-base:isInSystemAdminGroup "true"^^xsd:boolean`. You should remove `knora-base:isInProject <http://www.knora.org/ontology/knora-base#SystemProject>`, because this is probably causing the issues.

**Comment by mrivoal** [comment]
If I remove `knora-base:isInProject <http://www.knora.org/ontology/knora-base#SystemProject>`, I still get the error pointing at permissions:
```
{"status":11,"error":"org.knora.webapi.BadRequestException: The resulting request would lead to an empty permissions string, which is not allowed. Are all the necessary default object access permissions defined?"}
```
Here is my `SystemAdmin` user:
```
<http://rdfh.ch/users/mRivoal> a knora-base:User ;
        knora-base:userid "mRivoal"^^xsd:string ;
        knora-base:givenName "Marion"^^xsd:string ;
        knora-base:familyName "Rivoal"^^xsd:string ;
        knora-base:password "$e0801$GixW+508x22RZIcS10IWtXHJjn4znFNQpObreAavsiclAazUAPh99XJD5gycaPo72EyR5XBdfiTbR/NW2Dgsdg==$ZECNsLwMliVbfl2dhVBpU/ctMJqg4SFOP701D8ChrIw="^^xsd:string ;
        knora-base:email "marion.rivoal@unil.ch"^^xsd:string ;
        knora-base:preferredLanguage "fr"^^xsd:string ;
        knora-base:status "true"^^xsd:boolean ;
        knora-base:isInProject <http://www.knora.org/ontology/knora-base#SystemProject> ;
        knora-base:isInGroup <http://rdfh.ch/groups/drawings-gods-admin> ;
        knora-base:isInSystemAdminGroup "true"^^xsd:boolean .
```
I have also tried to remove `knora-base:isInGroup <http://rdfh.ch/groups/drawings-gods-admin> ;` and I ended up with the same error. 

Finally, I also tried to create a resource in a project with the `root@example.com` user and I had the same error.

**Comment by subotic** [comment]
So this has probably to do something with your default permissions. Is it the DrawingsGods project? If so, could you please update the files that are under `_test_data/other.v1.DrawingsGodsV1Spec`?

**Comment by mrivoal** [comment]
I just did. But you should know that I had the same error when I try to create a resource in other projects as well, not only for Drawings-gods.

**Comment by subotic** [comment]
Thanks, I will let you know as soon as I find something.

**Comment by subotic** [comment]
hmm, did you push your changes?

**Comment by subotic** [comment]
found it.

**Comment by subotic** [comment]
Ah, yes. Now I see it. You are using `http://rdfh.ch/groups/drawings-gods-meta-annotators` instead of `http://data.knora.org/groups/drawings-gods-meta-annotators`. This messes up the permission calculation.

@benjamingeer I don't know anymore what was decided regarding `http://rdfh.ch`, but I think that internal IRIs like the ones for users, groups, projects, and permissions are to stay at `http://data.knora.org`? Does those need to be dereferenceable?

**Comment by mrivoal** [comment]
Hum! I think it would be really useful to have a documentation summing up the syntaxes of all the IRIs we use. My mistake might be the first of a series if there is no such a synthesis.

At least, we are still a bit confused with this and it is difficult for us (being far far away) to keep updated on the matter.

**Comment by mrivoal** [comment]
(and thanks, by the way, @subotic, for spotting this)

**Comment by benjamingeer** [comment]
I think we should talk about IRI formats again with Lukas. The last discussion we had is in #595, where we basically decided:

* Only resource IRIs need to be dereferencable.
* Resource IRIs will be `handle.net` IRIs.
* Therefore there's no need for `rdfh.ch`.
* Since other IRIs don't need to be dereferencable, they can be whatever we want. We need to decide what they should be.

**Comment by mrivoal** [comment]
You are right, I remember this issue. So we should follow your suggestion and take a moment to discuss it with Lukas on wednesday. Having this question set once and for all would be very convenient.
