### ISSUE TITLE
Documentation of Graphview

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#612]
In the docs about how to use the graphview (<http://www.knora.org/documentation/manual/rst/knora-api-server/api_v1/reading-and-searching-resources.html#get-a-graph-of-resources>), the path contains the segment `search` which is wrong. 

@janCstoffregen Thanks for pointing this out. About your problem with the depth parameter: Could you try this query with the `anything` test data: <http://localhost:3333/v1/graphdata/http%3A%2F%2Fdata.knora.org%2F0C-0L1kORryKzJAJxxRyRQ?depth=4>

**Comment by tobiasschweizer** [comment]
Are you sure that there are enough link-levels in the data so it makes actually a difference?

**Comment by janCstoffregen** [comment]
Sorry, now it's working, maybe there are more links now than yesterday, we updated the data again today, thank you very very much for your help. I will come back if I can reproduce the error.

**Comment by tobiasschweizer** [comment]
No problem! Just as a hint for the next time you encounter such a problem: could you try the test data first to rule out a problem in the api-code (the easiest thing is to look at the automated tests, they give you an idea what you could try out)?

Then we would already have an idea that it could be about the data.

**Comment by janCstoffregen** [comment]
Yes, I will refer to the test data next time, I understand that it's much more usefull and reproducable that way, thank you for the hint!

**Comment by tobiasschweizer** [comment]
Great! The issue will be closed when the PR is merged. Thx.

**Comment by janCstoffregen** [comment]
Ok, thank you!
