### ISSUE TITLE
Bulk Import / Get XML Schemas

### ISSUE THREAD

**Issue by hanscools** [dhlab-basel/Knora#615]
In NIE 6 OWL-ontologies are created so far.
At attempting to get their XML schemas for 4 of them there is an error:
"java.util.NoSuchElementException: key not found: http://www.knora.org/ontology/[ontology#property].
(Otherwise no other problems detected.)
What causes this? Too strong  ontology-interdependencies?
Can this problem be solved?

**Comment by benjamingeer** [comment]
A `NoSuchElementException` is surely a bug in the Knora code. To help us find it, please provide your ontologies, and specify the exact steps needed to reproduce the problem.

**Comment by hanscools** [comment]
The ontologies are here:
https://github.com/nie-ine/Knora/tree/develop/webapi/_test_data/ontologies

XML schemas for event-ontology-knora.ttl and text-ontology-knora.ttl can be obtained.

For
HTTP GET to http://[host]/v1/resources/xmlimportschemas/http%3A%2F%2Fwww.knora.org%2Fontology%2Fhuman
there is:
"java.util.NoSuchElementException: key not found: http://www.knora.org/ontology/event#hasEndDate"

For
HTTP GET to http://[host]/v1/resources/xmlimportschemas/http%3A%2F%2Fwww.knora.org%2Fontology%2Fwork
there is:
"java.util.NoSuchElementException: key not found: http://www.knora.org/ontology/human#hasCreatingPeriod"

For
HTTP GET to http://[host]/v1/resources/xmlimportschemas/http%3A%2F%2Fwww.knora.org%2Fontology%2Fimage
there is:
"java.util.NoSuchElementException: key not found: http://www.knora.org/ontology/human#hasCreatingPeriod"

For
HTTP GET to http://[host]/v1/resources/xmlimportschemas/http%3A%2F%2Fwww.knora.org%2Fontology%2Fkuno-raeber
there is:
"java.util.NoSuchElementException: key not found: http://www.knora.org/ontology/human#hasCreatingPeriod"

**Comment by benjamingeer** [comment]
I have a fix for this. I would like to make a pull request in your forked Knora repository. Could you please add me as a collaborator with write permission in the GitHub settings of that repository? Then I can create a new branch there for the pull request.
