### ISSUE TITLE
Nondeterministic behaviour of EntityInfoV1.getPredicateObject

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#627]
Example:

```
PredicateInfoV1(
objectsWithLang = Map(
"de" -> "Urspr\u00FCnglicher Dateiname",
"fr" -> "Nom de fichier original"
),
objects = Set(),
ontologyIri = "http://www.knora.org/ontology/incunabula",
predicateIri = "http://www.w3.org/2000/01/rdf-schema#label"
)
```

The ordering of `de` and `fr` is arbitrary. So when the preferred and system language are `en`, then it is not clear what we will receive.

Issue came up while running `OntologyResponderV1Spec` in the `get all the resource classes with their property types for incunabula named graph` in conjunction with `AllegroGraph`.

**Comment by benjamingeer** [comment]
The ordering of `de` and `fr` is arbitrary because it's also arbitrary in the triplestore. What behaviour would you like in this case?

**Comment by benjamingeer** [comment]
Should we just sort by language code in order to have a deterministic response?

**Comment by subotic** [comment]
Sorting by language code sounds good.
