### ISSUE TITLE
Lucene indexing

### ISSUE THREAD

**Issue by SepidehAlassi** [dhlab-basel/Knora#629]
when I import resources as bulk import without specifying graphdb as triplestore in application.conf, import is complete but fulltext search fails. I guess it is due to missing Lucene indexes for imported resources. By specifying graphdb as triplestore in application.conf file and redoing the import, fulltext search works!

Can you please tell me a bit about how configuration of triplestore affects Lucene indexing? shouldn't all imported resources have Lucene Index regardless of triplestore type?

**Comment by benjamingeer** [comment]
When you say "without specifying graphdb", do you mean that your `application.conf` is configured to use `graphdb-free`?

**Comment by SepidehAlassi** [comment]
yes

**Comment by benjamingeer** [comment]
Lucene is built into the triplestore, so it can't be independent of the triplestore type. Some triplestores include Lucene, others do full-text indexing in some other way. I don't know the situation with Lucene and GraphDB Free, but I thought it was basically the same as GraphDB SE. @subotic ?

**Comment by SepidehAlassi** [comment]
@benjamingeer  I see. Thanks for replying so fast :-)

**Comment by benjamingeer** [comment]
You're welcome!

**Comment by subotic** [comment]
>  I don't know the situation with Lucene and GraphDB Free, but I thought it was basically the same as GraphDB SE

Yes, it should've, but I have found a slight discrepancy in the code. I will open a PR with the fix.

**Comment by subotic** [comment]
@SepidehAlassi PR #633 has the fix. Could you maybe try it out and see if it works for you?
