### ISSUE TITLE
Shall I add .sbtrc to the Gitrep?

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#63]
Shall I add `.sbtrc` to the gitrep?

When starting `sbt` from the console, it automatically switches to the project `webapi`.

```bash
alias boot = ;reload ;project webapi ;iflast shell
```

CC: @subotic @benjamingeer

**Comment by subotic** [comment]
Please don't. If someone wants it, he or she can easily do it locally.

**Comment by tobiasschweizer** [comment]
ok :-)
