### ISSUE TITLE
Is it possible to query/filter boolean values in Knora v1

### ISSUE THREAD

**Issue by sacha-alex** [dhlab-basel/Knora#635]
Hello,

  we are using boolean datatypes in our project and want to perform queries which includes conditions if these properties are True or False. Is there a way to do this in Knora V1?
Unfortunately there is no information in the documentation. There is a list of several value types at
http://www.knora.org/documentation/manual/rst/knora-api-server/api_v1/reading-and-searching-resources.html#search-for-resources (Date Value, Integer Value, Float Value, Text Value, Geometry Value, Resource Pointer, Color Value and List Value), but a Boolean Value is missing.
I am grateful for any hint. Thanks in advance.

Best
Sascha

**Comment by benjamingeer** [comment]
It looks like this hasn't been implemented in v1, but I think it would not be hard to add it. How soon do you need it?

**Comment by sacha-alex** [comment]
Thanks for the answer. It would be nice, if we could use it in the next couple of days (the sooner the better). Many thanks in advance.

**Comment by benjamingeer** [comment]
That's very short notice. I don't know if I can do it in the next couple of days, but I will try to do it this week.

**Comment by tobiasschweizer** [comment]
@benjamingeer I think I can help you next week with that

**Comment by tobiasschweizer** [comment]
We would have to support a query like the following: <http://localhost:3333/v1/search/?searchtype=extended&property_id=http%3A%2F%2Fwww.knora.org%2Fontology%2Fanything%23hasBoolean&compop=EQ&searchval=1&show_nrows=25&start_at=0&filter_by_restype=http%3A%2F%2Fwww.knora.org%2Fontology%2Fanything%23Thing&filter_by_project=http%3A%2F%2Fdata.knora.org%2Fprojects%2Fanything>

**Comment by tobiasschweizer** [comment]
@sacha-alex I have created a PR, it is ready for review.
