### ISSUE TITLE
Configure wich routes / versions can be used in Knora

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#639]
Could routes and versions be activated/disabled from within `application.conf`?

V2 should not be used yet on productive systems. This is especially important for the NIE-INE project.

@sacha-alex

**Comment by benjamingeer** [comment]
NIE-INE’s fork would also have to be patched.

**Comment by tobiasschweizer** [comment]
Good point, thx. Hopefully Knora main rep can be merged into the fork in the future, that would make updates easier.

**Comment by subotic** [comment]
I think that the only issue with the merging of `develop` into their fork was because of us dropping `fuseki`. I don't know what the current state is regarding them using `GraphDB`.
