### ISSUE TITLE
LinkObj missing in Ontology Response

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#644]
<http://localhost:3333/v2/ontologies/classes/http%3A%2F%2Fapi.knora.org%2Fontology%2Fknora-api%2Fv2%23LinkObj>

```
{"status":9,"error":"org.knora.webapi.NotFoundException: Some requested classes were not found: http://api.knora.org/ontology/knora-api/v2#LinkObj"}
```

**Comment by tobiasschweizer** [comment]
ForbiddenResource needs to be added to the API ontologies.

**Comment by tobiasschweizer** [comment]
isPartOf and isPartOfValue are also missing. 

@benjamingeer Is this intended? Should only subproperties of these properties be used?

**Comment by benjamingeer** [comment]
> Is this intended?

Not intended, sorry.

**Comment by tobiasschweizer** [comment]
Not `isPartOf` your masterplan? 

I will add it. :-)

**Comment by tobiasschweizer** [comment]
done in https://github.com/dhlab-basel/Knora/pull/651/commits/7a65ea11dc25f95ede1cbed8b37a609a943bda40 and https://github.com/dhlab-basel/Knora/pull/651/commits/8a8f961f68c27681e8105ebdc9614bc10bfeba14
