### ISSUE TITLE
Serve salsah-gui and standoff ontologies

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#648]
```
{"status":9,"error":"org.knora.webapi.NotFoundException: Named graph not found: http://www.knora.org/ontology/standoff"}
```

The ontology responder doesn't have these ontologies, so we may need to encode them in Scala.

**Comment by benjamingeer** [comment]
Actually it does have the standoff ontology, but in a completely separate data structure.

**Comment by benjamingeer** [comment]
@tobiasschweizer We have to serve the standoff classes that are defined in `knora-base`, as part of serving the `knora-api` ontologies. But the problem is that, because these classes are derived from the `ValueBase` classes, they have predicates like `valueHasStartJDN`. The same thing could actually happen with any custom standoff tag, because you could always make a custom subclass of `StandoffDateTag`.

Maybe the solution is to treat the standoff datatype tags specially, and transform their properties depending on which ontology schema we're using.

**Comment by tobiasschweizer** [comment]
Couldn't we re-use the exact same logic we have already developed for the different value types?

**Comment by benjamingeer** [comment]
I was thinking that we could hard-code all the standoff entities in `knora-api`. For each entity, there could also be a set of `knora-base` predicates to be replaced. So then, when serving a tag class T:

1. Does T have a standoff datatype?
2. If so, look up the datatype definition D.
    a. Get the predicates to be replaced from D, and remove them from T.
    b. Add all of D’s predicates to T.

Actually we could do the same thing for everything in `knora-base`, then we would only have to store the labels and comments once. :)

**Comment by benjamingeer** [comment]
I was just proposing having a table of properties in standoff classes that should be replaced with other properties when we serve those classes via the API.

> re-use existing logic

The existing logic is for serving instances, but here we are talking about serving class definitions. How could we re-use the existing logic for that?

**Comment by tobiasschweizer** [comment]
When you serve a definition for a `knora-api:DateValue` in the ontology route, how would a standoff tag of type date be different form that? They both inherit from `DateBase`.

Maybe I do not understand what you are referring to.

**Comment by benjamingeer** [comment]
Ah, I thought you were talking about the existing logic for serving values (not value classes).

When I serve a definition for `knora-api:DateValue`, I just serve a hard-coded definition. But I can’t do that for standoff classes, because people can make their own standoff classes. If you make a standoff class called `MyDateTag`, we can’t serve a hard-coded definition of that class, because we don’t have one.

In the triplestore, the class `MyDateTag` will inherit predicates like `valueHasStartJDN` from `knora-base:DateBase`. When the definition of `MyDateTag` is served, those predicates have to be replaced dynamically with ones like `dateValueHasStartYear`.

So what I’m suggesting is to maintain a table of the predicates that need to be replaced.

We can’t just use the predicates from `DateValue`, because `DateValue` has a comment and a label that describe it as a date value, which wouldn’t apply to a standoff tag. It also has cardinalities for things like permissions, which standoff tags don’t have. So we couldn’t just dump everything from `DateValue` into a standoff tag class.

We could perhaps add `DateBase` to the hard-coded `knora-api` ontologies, and have `DateValue` and `StandoffDateTag` inherit from it, as in `knora-base`. But currently, in the hard-coded `knora-api` ontologies, there is no cardinality inheritance.

**Comment by benjamingeer** [comment]
Also, if we’re going to let people use standoff in the simple API schema, we need to think about what `StandoffDateTag` should look like in that schema. I guess it should have a `knora-api:Date` in it, rather than `dateValueHasStartYear`, etc.

**Comment by tobiasschweizer** [comment]
Ok, now I understand what you mean :-)

> Also, if we’re going to let people use standoff in the simple API schema, we need to think about what StandoffDateTag should look like in that schema. I guess it should have a knora-api:Date in it, rather than dateValueHasStartYear, etc.

This is the way it actually works, see https://github.com/dhlab-basel/Knora/blob/cff43fb18828e113e71d7d342233a1b1d0bb5a42/webapi/_test_data/test_route/texts/HTML.xml#L15

This is probably what we also need for KnarQL (knora-api simple).

**Comment by benjamingeer** [comment]
Serving `salsah-gui` is taken care of in #746, along with serving `standoff` as-is (not adapting it for the schema).

For the rest, I'm starting to think that instead of maintaining fully hard-coded API ontologies in Scala, it would be easier to maintain some representation of the differences between internal and external ontologies.

**Comment by benjamingeer** [comment]
I now think we should convert `knora-base` into the `knora-api` ontologies, adding and subtracting things as needed. This would include logic for transforming standoff classes, and the same logic could be applied when serving the `standoff` ontology` as well as standoff classes in project-specific ontologies.

In #746 I refactored ontology caching to make this easier. Now each ontology, including `knora-base`, is cached in a `ReadOntologyV2`.

**Comment by tobiasschweizer** [comment]
> I now think we should convert knora-base into the knora-api ontologies

Are you saying we should get rid of the hard-coded ontologies in Scala?

**Comment by benjamingeer** [comment]
I think we should just hard-code the specific differences, e.g. `knora-api:DateValue`, but not the whole `knora-api` ontology.

**Comment by benjamingeer** [comment]
Moved the rest of this to #762.
