### ISSUE TITLE
Store an optional short code and multiple ontologies per project

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#654]
Each project needs to be able to have an optional short code, which is a hexadecimal number of at least four digits. Both the short code and the project's short name must be unique. When the projects responder returns information about a project, it should return the short code if present.

Although the short code is optional for now, we could make it required later.

Each project also needs to have one or more ontologies associated with it. In the API, we need to be able to get a list of a project's ontologies.

The IRI of the named graph of each ontology should simply be the IRI of the ontology, rather than being configurable. Therefore the projects responder doesn't need to store the IRI of the ontology's named graph separately.

The IRI of the named graph of the project's data should be predictable from the project IRI, rather than being configurable.

If a short code is provided, the project IRI could contain it instead of a UUID.

See also #595 and #472.

**Comment by subotic** [comment]
Thanks for writing up the issue.

**Comment by benjamingeer** [comment]
Currently `ResourcesResponderV1` uses `projectInfoResponse.project_info.shortname` to construct an IRI for a new resource (it calls `knoraIdUtil.makeRandomResourceIri()` in two places to do this, passing the shortname). When support for project codes is added, it should use the project code instead.

**Comment by subotic** [comment]
@benjamingeer should the `shortcode` be changeable, i.e. be possible to be added to an existing project without one? Maybe such a change should be done `offline`, as this would require changing the ontology IRI, named graphs, etc.

**Comment by benjamingeer** [comment]
I agree with you. I don’t think we need to be able to change it via the API. We can make an offline procedure for that.
