### ISSUE TITLE
Check Mapping and Standoff Tags

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#657]
Compare mappings for BEBB and Goldbach as well as Meditationes and see if the tags are used consistently.

It would also be good to see if the underlying XML could be made more TEI-like, so a later TEI-export would be easier to do.

**Comment by tobiasschweizer** [comment]
also check the markup of the Mediationes

**Comment by tobiasschweizer** [comment]
XML elements currently used in BEOL:

**BEBB** (Basler Edition der Bernoulli-Briefwechsel):

- `<p>`: paragraph (logical unit in text)
- `<ref>`: footnote (contained in running text), moved to the end of the text when XSL transformation is applied
- `<i>`: italics
- `<u>`: underlined
- `<b>`: bold
- `<sup>`: superscript
- `<sub>`: subscript
- `math`: mathematical notation in LaTeX
- `<nowiki>`: MediaWiki  specific tag to escape a special character
- `<a>`: anchor/link
- `<entity>`: reference to another letter in the Wiki
- `<figure>`: link to a figure on the manuscript
- `<facsimile>`: link to a facsimile (image), represents a pagebreak
- `<pb>`: pagebreak without coordination with facsimile
- `<table>`: tabular structure (contains `<tr>` and `<td>`)
- `<dl>`: definition list
- `<br>`: linebreak
- `<hr>`: horizontal bar

**Comment by SepidehAlassi** [comment]
Goldbach:  most of BEBB markups and following one:

- <small> : small capitals

**Comment by tobiasschweizer** [comment]
Standoff Tags and relation to TEI-elements:

- paragraph (logical unit in text): `standoff:StandoffParagraphTag` -> http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-p.html
- reference/footnote in text: `beol:StandoffReferenceTag` -> http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-ref.html
- italics: `standoff:StandoffItalicTag` -> http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-hi.html (with attribute `rend="italic"`)
- underline: `standoff:StandoffUnderlineTag` -> http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-hi.html (with attribute `rend="underline"`)
- bold: `standoff:StandoffBoldTag` -> http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-hi.html (with attribute `rend="bold"`)
- superscript: `standoff:StandoffSuperscriptTag` -> http://www.tei-c.org/Vault/P5/2.4.0/xml/tei/Exemplars/temp-dir-for-ant/OPS/ref-sup.html
- subscript: `standoff:StandoffSubscriptTag` -> ?
- mathematical notation: `beol:StandoffMathTag` -> http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-formula.html
- hyperlink (reference to an online resource): `standoff:StandoffHyperlinkTag` -> http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-ptr.html
- figure or image: `beol:StandoffFacsimileTag`, `beol:StandoffFigureTag` -> http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-graphic.html
- pagebreak: `beol:StandoffPbTag` -> http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-pb.html
- table, tabular structure: `standoff:StandoffTableTag` -> http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-table.html
- list: `standoff:StandoffOrderedListTag`, `standoff:StandoffUnorderedListTag` -> http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-list.html
 - line break -> http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-lb.html

**Comment by tobiasschweizer** [comment]
If me manage to make a mapping from standardized standoff tags to TEI/XML elements, we could possibly offer a generic export to TEI/XML (regardless of how the original XML looked like as long as it could be correctly mapped to standoff).

**Comment by tobiasschweizer** [comment]
And we could map any standard TEI/XML document to standoff on the fly, e.g., the Newton project (however, since TEI/XML can e quite different, we would have to make some restrictions or provide custom configurations).
