### ISSUE TITLE
Namespace collisions between projects and standoff

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#663]
There seems to be a namespace collision between standoff mappings:

`http://data.knora.org/projects/standoff/mappings/StandardMapping/elements/4b-Cx4qYQOyy9mUswmvW7`

and projects:

`http://data.knora.org/projects/[shortcode/][shortname]` or now `http://rdfh.ch/projects/[shortcode/][shortname]`

Maybe you could use something like this:

``http://data.knora.org/standoff/mappings/StandardMapping/elements/4b-Cx4qYQOyy9mUswmvW7`?

**Comment by subotic** [comment]
Or is there a project called `standoff`?

**Comment by loicjaouen** [comment]
The init [script](https://github.com/dhlab-basel/Knora/blob/develop/webapi/scripts/graphdb-knora-prod-data.expect) puts the onto and data are respectively in `http://www.knora.org/ontology/standoff` and `http://www.knora.org/data/standoff`.
But there is no standoff project _per se_.

**Comment by subotic** [comment]
I will change it to `http://rdfh.ch/standoff`
