### ISSUE TITLE
extended search: condition exists fails

### ISSUE THREAD

**Issue by loicjaouen** [dhlab-basel/Knora#665]
Conditions:
- with a fresh Salsah 1.5 session, 
- when making an extended search on 
- a resource
- that has a link to another resource
- and the search condition is that this linked resource exists

Salsah then complains about: `Bad request error`
![api-error](https://user-images.githubusercontent.com/3933654/32837500-15abb324-ca0e-11e7-88bc-535d282a3051.gif)

**Comment by loicjaouen** [comment]
Looking at knora's response, we find a bit more:
```
org.knora.webapi.BadRequestException: propertyId, compop, and searchval are not given parallelly
```

which is thrown at (v1/SearchRouteV1.scala#L10)[https://github.com/dhlab-basel/Knora/blob/fd825e7eb1e13273714b59384d3002df37010e82/webapi/src/main/scala/org/knora/webapi/routing/v1/SearchRouteV1.scala#L105]

when there is one of the three (propertyId, compop, and searchval) is missing.

The comment even talks about our case:
```
        // propertyId, compop, and searchval are parallel structures (parallel arrays): they have to be of the same length
// in case of "compop" set to "EXISTS", also "searchval" has to be given as a param with an empty value (parallel arrays)
```

Thanks to the devs who write comments.

**Comment by loicjaouen** [comment]
which is correctly set in [jquery.extsearch.js#L750](https://github.com/dhlab-basel/Knora/blob/fd825e7eb1e13273714b59384d3002df37010e82/salsah/src/public/js/jquery.extsearch.js#L750)

**Comment by tobiasschweizer** [comment]
you just have to add "searchval=" when using the EXISTS operator

**Comment by loicjaouen** [comment]
@tobiasschweizer mid-air collision :)

**Comment by tobiasschweizer** [comment]
in any case, looking at the URL hat is produced by the GUI helps :-)

**Comment by loicjaouen** [comment]
apparently ajax is smart enough to remove it when sending at [01_salsah_api.js#L114](https://github.com/dhlab-basel/Knora/blob/fd825e7eb1e13273714b59384d3002df37010e82/salsah/src/public/js/01_salsah_api.js#L114)

**Comment by tobiasschweizer** [comment]
built-in intelligence - the root of all evil ;-)

**Comment by loicjaouen** [comment]
ready for review, do you like it better?
