### ISSUE TITLE
Use type information from the triplestore

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#668]
Currently we get all values as strings from the triplestore, without any type information. Each responder does its own type conversions, because it knows what types to expect.

For Knora API v2, we could have `HttpTriplestoreConnector` use the type information supplied in the triplestore's responses, and convert to integers, booleans, etc., accordingly. This would move that work down a level in the API server architecture, simplifying the work of the responders and response classes.

In particular, `PredicateInfoV2` needs to know which of its objects are IRIs, so it can convert their schemas when needed. If type information from the triplestore was preserved, `PredicateInfoV2` would be able to distinguish between IRIs and other strings.

**Comment by subotic** [comment]
as a reminder:

```
abstract case class LiteralV2
case class StringV2 extends LiteralV2
case class BooleanV2 extends LiteralV2
...

case class SparqlExtendedConstructResponse(statements: Map[IRI, Map[IRI, Seq[LiteralV2]]])
```
