### ISSUE TITLE
getting incoming Links in nestResources is slow and inefficient

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#675]
<https://github.com/dhlab-basel/Knora/blob/8dddfd8b100737b6d013b6bd9d88098527b6d67b/webapi/src/main/scala/org/knora/webapi/util/ConstructResponseUtilV2.scala#L274> is very slow when the following KnarQL query is executed: 

```
 PREFIX knora-api: <http://api.knora.org/ontology/knora-api/simple/v2#>  
        CONSTRUCT {
        
            ?mainRes knora-api:isMainResource true .
            
            ?mainRes <http://0.0.0.0:3333/ontology/beol/simple/v2#mentionsPerson> ?propVal0 .
        
        } WHERE { 
        
            ?mainRes a knora-api:Resource .
            
            ?mainRes a <http://0.0.0.0:3333/ontology/beol/simple/v2#letter> .
            
            ?mainRes <http://0.0.0.0:3333/ontology/beol/simple/v2#mentionsPerson> ?propVal0 .
                
                <http://0.0.0.0:3333/ontology/beol/simple/v2#mentionsPerson> knora-api:objectType <http://api.knora.org/ontology/knora-api/simple/v2#Resource> .
                ?propVal0 a <http://api.knora.org/ontology/knora-api/simple/v2#Resource> .
                   
        }
```

I think this is because for every call of `nestResources`, incoming links for the given resource Iri are searched in all the results `flatResourcesWithValues`  (and this has to happen for all resources).

Instead, an analyzer that is only run once should build a data structure that could be accessed from within `nestResources`, providing access to the incoming links for the current resource Iri by the its Iri (key).

**Comment by tobiasschweizer** [comment]
@benjamingeer At first, I thought it was the triplestore ;-) But then I realized that it was all my fault :-) calming ...

**Comment by benjamingeer** [comment]
Now you just have a nice optimisation task. :)

**Comment by tobiasschweizer** [comment]
hopefully :-) I'll keep you posted
