### ISSUE TITLE
Create new project: ontology IRI is not accepted

### ISSUE THREAD

**Issue by kilchenmann** [dhlab-basel/Knora#684]
I'm trying to create a new project, but the API doesn't accept the ontology IRI. 

I'm sending the following data:
```
{
	id: null,
	keywords: null,
	longname: "Test no 18",
	ontologies: [
            "http://www.knora.org/ontology/0018/test18"
        ],
	selfjoin: false,
	shortcode: "0018",
	shortname: "test18",
	status: true,
}
```

...and I get this answer:

```
{
	"project_info": {
		"ontologies": [],
		"shortname": "test18",
		"description": null,
		"institution": null,
		"shortcode": "0018",
		"logo": null,
		"id": "http://rdfh.ch/projects/0018",
		"status": true,
		"selfjoin": false,
		"keywords": null,
		"longname": "Test no 18"
	},
	"status": 0
}
```

**Comment by subotic** [comment]
This won't work. You will not be able to add/remove an ontology directly to/from the project. There is going to be an `admin/ontologies` endpoint, with which you will be able to create a new ontology. Creating a new ontology will also add it to the project.
