### ISSUE TITLE
Knora handling of project-specific properties and subproperties, classes and subclasses

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Knora#689]
I have a question regarding the correct/expected behaviour of Knora when one defines a subproperty for a given project-specific property.

Here is my use case (a customed bibliographical ontology based on BEOL, see definitions below): 
I have a `Document` class and an `Edition` class which is a subclass of `Document`.
`Document` class has a `documentHasAuthor` property and `Edition` has an ` editionHasDirector` property, which is a subproperty of `documentHasAuthor`.

I was (very pleasantly) surprised to see that, for `Edition`, the property ` editionHasDirector` is displayed instead of `documentHasAuthor`. It was the behaviour I was hoping for, but I didn't know Knora and Salsah would "read" the ontology this way. I wanted to check with you if this is the correct and expected behaviour?

Besides, I tested this further and, when you define a second subproperty of `documentHasAuthor`, for example a `editionHasDirector2`, then only the latter subproperty will be displayed for `Edition`. Which I find a bit strange because it can actually make perfectly sense to have 2 subproperties of the same properties displayed for one class (for a `Book`, subclass of `Document`, we could have an Author and its subproperty, a Director (or editeur scientifique)). So, what do you think? Right now, it is fine as it is, but I am just asking with other future projects in mind.

------

```
# ------------ properties

###  http://www.knora.org/ontology/0103/theatre-societe-biblio#documentHasAuthor
theatre-societe-biblio:documentHasAuthor rdf:type owl:ObjectProperty ;
                    rdfs:subPropertyOf knora-base:hasLinkTo ;
                    rdfs:label "Author"@en ,
                    rdfs:comment """Represents the author of the document."""@en ,
		 			"""Auteur du document (livre, manuscrit, etc…)."""@fr ;
                    knora-base:objectClassConstraint theatre-societe:Person ;
                    knora-base:subjectClassConstraint theatre-societe-biblio:Document ;
                    salsah-gui:guiElement salsah-gui:Searchbox .

###  http://www.knora.org/ontology/0103/theatre-societe-biblio#editionHasDirector
theatre-societe-biblio:editionHasDirector rdf:type owl:ObjectProperty ;
                    rdfs:subPropertyOf theatre-societe-biblio:documentHasAuthor ;
                    rdfs:label "Editeur scientifique de l'édition"@fr ;
                    rdfs:comment """Représente l'éditeur scientifique d'une édition critique."""@fr ;
                    knora-base:objectClassConstraint theatre-societe:Person ;
                    knora-base:subjectClassConstraint theatre-societe-biblio:Edition ;
                    salsah-gui:guiElement salsah-gui:Searchbox .
                    
# ------------ classes

###  http://www.knora.org/ontology/0103/theatre-societe-biblio#Document
theatre-societe-biblio:Document rdf:type owl:Class ;
                    rdfs:subClassOf knora-base:Resource , 
                                    [ rdf:type owl:Restriction ;
                                      owl:onProperty theatre-societe-biblio:documentHasAuthor ;
                                      owl:minCardinality "0"^^xsd:nonNegativeInteger
                                    ], 
                                    [ rdf:type owl:Restriction ;
                                      owl:onProperty theatre-societe-biblio:documentHasAuthorValue ;
                                      owl:minCardinality "0"^^xsd:nonNegativeInteger
                                    ] ;
                    rdfs:label "[Document]"@en ,
                               "[Document]"@fr ;
                    rdfs:comment "A resource representing a document"@en .

###  http://www.knora.org/ontology/0103/theatre-societe-biblio#Edition
theatre-societe-biblio:Edition rdf:type owl:Class ;
                    rdfs:subClassOf knora-base:Resource ,
                    				theatre-societe-biblio:Document ,
                                        [ rdf:type owl:Restriction ;
	                                       owl:onProperty theatre-societe-biblio:editionHasDirector ;
	                                       owl:minCardinality "0"^^xsd:nonNegativeInteger
	                                    ] ,
	                                    [ rdf:type owl:Restriction ;
	                                       owl:onProperty theatre-societe-biblio:editionHasDirectorValue ;
	                                       owl:minCardinality "0"^^xsd:nonNegativeInteger
	                                    ] ;
                    rdfs:label "Edition"@en ,
                               "Edition (critique)"@fr ,
                    rdfs:comment "A resource representing an edition"@en .
```

**Comment by benjamingeer** [comment]
> It was the behaviour I was hoping for, but I didn't know Knora and Salsah would "read" the ontology this way. I wanted to check with you if this is the correct and expected behaviour?

Yes, glad you like it. :) This is in [the knora-base docs](http://www.knora.org/documentation/manual/rst/knora-ontologies/knora-base.html#owl-cardinalities):

> cardinalities in the subclass can override cardinalities that would otherwise be inherited from the superclass. Specifically, if a superclass has a cardinality on a property P, and a subclass has a cardinality on a subproperty of P, the subclass’s cardinality overrides the superclass’s cardinality.

Let me make sure I understand correctly what you mean here:

> when you define a second subproperty of `documentHasAuthor`, for example a `editionHasDirector2`, then only the latter subproperty will be displayed for `Edition`

If I understand correctly:

* Both `editionHasDirector` and `editionHasDirector2` are subproperties of `documentHasAuthor`.
* `Edition` has cardinalities for `editionHasDirector` and `editionHasDirector2`.

Is that right? If so, I think both `editionHasDirector` and `editionHasDirector2` should be available in `Edition`. If not, it seems like a bug to me.

Could you provide a test case? Or at least, provide a complete example ontology that demonstrates the problem?

**Comment by mrivoal** [comment]
> cardinalities in the subclass can override cardinalities that would otherwise be inherited from the superclass. Specifically, if a superclass has a cardinality on a property P, and a subclass has a cardinality on a subproperty of P, the subclass’s cardinality overrides the superclass’s cardinality.

Yes, but it is more a matter of "label" than cardinality, here. I didn't know it would worked for labels as it does for cardinalities. But this great.

>   -  Both `editionHasDirector` and `editionHasDirector2` are subproperties of `documentHasAuthor`.

Exactly.
>    - `Edition` has cardinalities for `editionHasDirector` and `editionHasDirector2`.

`Edition` has these 2 properties, each with its cardinality and label.

> Is that right? If so, I think both editionHasDirector and editionHasDirector2 should be available in Edition. If not, it seems like a bug to me.

You are probably right. I will provide you with a example ontology very soon.

**Comment by mrivoal** [comment]
Ok, please forget what I said. I must have done some mistake while writing the ontology the first time, there is no bug here. With the example ontology I prepared, everything works fine and I can see the 2 subproperties for  `Edition`.

So I will just close the issue. Thanks for your support!

**Comment by benjamingeer** [comment]
No problem!
