### ISSUE TITLE
bad image rendition

### ISSUE THREAD

**Issue by loicjaouen** [dhlab-basel/Knora#695]
In Salsah 1.5, when uploading a picture, the image is rendered in a much worse resolution than the original.

Here is a crop of the original image uploaded to sipi (through salsah):
![chaeg_380_bis](https://user-images.githubusercontent.com/3933654/34102826-d41834e0-e3ea-11e7-8f02-965422207100.jpg)

And its rendition in salsah:
![capture d ecran 2017-12-15 a 12 03 39](https://user-images.githubusercontent.com/3933654/34102870-f7aa532a-e3ea-11e7-8f7b-a02b8d600b73.png)

**Comment by loicjaouen** [comment]
investigations rule out loss of resolution in sipi and points to:
https://github.com/dhlab-basel/Knora/blob/5119f91569f7d0170fc1ac3acc51dfe945b3c217/salsah/src/public/js/imagebase.js#L2908
https://github.com/dhlab-basel/Knora/blob/5119f91569f7d0170fc1ac3acc51dfe945b3c217/salsah/src/public/js/imagebase.js#L3098
```js
							if (Math.max(viewer_settings.pic[i].nx, viewer_settings.pic[i].nx) < viewer_settings.img_maxsize) {
```

The idea is to have a limit in the size that Salsah shows, defined in `viewer_settings.img_maxsize`.

Sipi response gives a different sizes that the client can request, Salsah compares those sizes to its maximum size and selects the best resolution fitting this requirement.

By the way, there is a bug there, in order to compare the size of the image in length and width, this should read:
```js
Math.max(viewer_settings.pic[i].nx, viewer_settings.pic[i].ny)
```

So Salsah limits the rendition of images to a maximum of 1200 pixels at these lines:
https://github.com/dhlab-basel/Knora/blob/5119f91569f7d0170fc1ac3acc51dfe945b3c217/salsah/src/public/js/imagebase.js#L2866
https://github.com/dhlab-basel/Knora/blob/5119f91569f7d0170fc1ac3acc51dfe945b3c217/salsah/src/public/js/imagebase.js#L3136

**Comment by loicjaouen** [comment]
in Salsah 2, the whole renderer is replaced by [OpenSeaDragon](https://openseadragon.github.io/) that can talk directly to Sipi in `iiif`.

Salsah has no config file but the code here.

Should I just change the `img_maxsize` value where it is now, or add a variable next to:
https://github.com/dhlab-basel/Knora/blob/5119f91569f7d0170fc1ac3acc51dfe945b3c217/salsah/src/public/js/00_init_javascript.js#L33 ?

**Comment by tobiasschweizer** [comment]
you can change the resolution in the upper left corner, there should be 5 different you cab choose from

**Comment by tobiasschweizer** [comment]
in the response to a resource request, you can find different pre-configured resolutions: http://www.knora.org/documentation/api/interfaces/_resourceresponseformats_.resourceresponseformats.resinfo.html#locations

**Comment by loicjaouen** [comment]
@tobiasschweizer : 
> you can change the resolution in the upper left corner

So cool! I did not notice it so far:

![capture d ecran 2017-12-18 a 14 54 33](https://user-images.githubusercontent.com/3933654/34109411-c6f4588e-e403-11e7-991b-7b93420a1ade.png)

Thank you very much Tobias :)

**Comment by tobiasschweizer** [comment]
:)
