### ISSUE TITLE
FOAF Properties Naming

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#70]
In ```OntologyConstants``` we have the following:

```
object Foaf {
        val FirstName = "http://xmln.com/foaf/0.1/firstName"
        val LastName = "http://xmln.com/foaf/0.1/lastName"
    }
```

In ```knora-base.ttl``` we have the following definition:

```
###  http://www.knora.org/ontology/knora-base#User

:User rdf:type owl:Class ;
      
      rdfs:subClassOf <http://xmlns.com/foaf/0.1/Person> ,
                      [ rdf:type owl:Restriction ;
                        owl:onProperty <http://xmlns.com/foaf/0.1/familyName> ;
                        owl:cardinality "1"^^xsd:nonNegativeInteger
                      ] ,
                      ...
                      [ rdf:type owl:Restriction ;
                        owl:onProperty <http://xmlns.com/foaf/0.1/givenName> ;
                        owl:cardinality "1"^^xsd:nonNegativeInteger
                      ], 
                      ...
      
      rdfs:comment "Represents a Knora user"@en .
```

According to the [FOAF](http://xmlns.com/foaf/spec/) spec, we have these options: ```foaf:givenName``` which is used alongside ```foaf:familyName``` and ```foaf:firstName```which is used alongside ```foaf:lastName```. The spec prefers the givenName / familyName combination.

I suppose that we should then stick to ```foaf:givenName``` / ```foaf:familyName```?

Also there is a mix of both usages in the test/demo data, which I would like to clean up as soon as it is clear what we will use.

@lrosenth 
@benjamingeer 
@tobiasschweizer

**Comment by benjamingeer** [comment]
This is all fixed on the `wip/consistency-checking` branch.

**Comment by subotic** [comment]
For completeness sake, we are using ```foaf:givenName``` / ```foaf:familyName```.

Can you then please close this ticket when the ```wip/consistency branch``` is merged? Until then this issue is technically not resolved ;-)

**Comment by benjamingeer** [comment]
OK. :) I'm hoping to make a pull request for it later today.

**Comment by subotic** [comment]
cool, thanks :-)
