### ISSUE TITLE
Missing persons in images demo data

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#71]
In `images-demo-data`, the consistency checker is finding a lot of references to missing resources of type `images:person`, which are the objects of properties like `images:urheber`. There are too many of these references to change them all manually. (In the original source data, there are hundreds of different `:person` resources.) We need to fix this somehow before consistency checking can be merged.

**Comment by subotic** [comment]
Yes, I see what you mean. I will cut the demo data down to 10 images and add the missing ```images:person``` by hand.

**Comment by subotic** [comment]
This commit should fix it. If I missed a referenced ```images:person``` somewhere, then you can fix it very simply by using the only one in the data.

**Comment by benjamingeer** [comment]
That fixed it, thanks1
