### ISSUE TITLE
Two warnings while compiling webapi

### ISSUE THREAD

**Issue by kilchenmann** [dhlab-basel/Knora#710]
I get the following warnings with the newest version from develop branch (2018-01-25):

`[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn]
[warn] 	* com.github.jsonld-java:jsonld-java:0.10.0 is selected over 0.5.1
[warn] 	    +- org.apache.jena:jena-arq:3.0.0                     (depends on 0.5.1)
[warn] 	    +- org.knora:webapi_2.12:0.1.0-beta                   (depends on 0.5.1)
[warn]
[warn] Run 'evicted' to see detailed eviction warnings
[info] Compiling 294 Scala sources to [...]/knora/webapi/target/scala-2.12/classes...
[warn] [...]/knora/webapi/src/main/scala/org/knora/webapi/responders/admin/GroupsResponderADM.scala:88: non-variable type argument org.knora.webapi.messages.store.triplestoremessages.LiteralV2 in type pattern scala.collection.immutable.Map[String,org.knora.webapi.messages.store.triplestoremessages.LiteralV2] (the underlying of Map[String,org.knora.webapi.messages.store.triplestoremessages.LiteralV2]) is unchecked since it is eliminated by erasure
[warn]                 case (groupIri: IRI, propsMap: Map[String, LiteralV2]) =>
[warn]                                                ^
[warn] [...]/knora/webapi/src/main/scala/org/knora/webapi/responders/admin/UsersResponderADM.scala:110: non-variable type argument org.knora.webapi.messages.store.triplestoremessages.LiteralV2 in type pattern scala.collection.immutable.Map[org.knora.webapi.IRI,org.knora.webapi.messages.store.triplestoremessages.LiteralV2] (the underlying of Map[org.knora.webapi.IRI,org.knora.webapi.messages.store.triplestoremessages.LiteralV2]) is unchecked since it is eliminated by erasure
[warn]                 case (userIri: IRI, propsMap: Map[IRI, LiteralV2]) =>
[warn]                                               ^
[warn] two warnings found`

**Comment by benjamingeer** [comment]
The warnings about `GroupsResponderADM` and `UsersResponderADM` are fixed in #707. The one about version conflict(s) in library dependencies is probably not a real problem.

**Comment by subotic** [comment]
The warning about version conflicts is solved in PR #653. There I have analyzed what versions are needed for which library and fine-tuned `WebapiBuild.sbt`. I should probably extract this part as a separate PR.

@benjamingeer thanks for solving the `GroupsResponderADM` and `UsersResponderADM` warnings. Now I can remove them from my todo list :-)
