### ISSUE TITLE
[SALSAH] Icon name with unmappable characters

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#717]
```
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /src/src/public/project-icons/Lumi??res.Lausanne
```

Could we please get rid of the special characters? Java doesn't like it.

**Comment by benjamingeer** [comment]
You need to set your ``LANG`` environment variable to tell Java to use UTF-8. Explanation here:

https://github.com/src-d/engine/pull/257/files

**Comment by subotic** [comment]
ok, thanks. I will try that.

**Comment by mrivoal** [comment]
But we can also get rid of those icon names (in fact, we are not currently using those icons). Just let us know.

**Comment by subotic** [comment]
I solved it by setting some `utf-8` environment variables. But in general, I don't think that it is a good idea to have special characters in paths and filenames, as those things have a tendency to become a problem ;-)

**Comment by mrivoal** [comment]
You are completely right. But I wasn't fully aware of that kind of things, back then. This dates back to my very first project in Salsah, when @tobiasschweizer imported Lumières.Lausanne data in Salsah 1.0... More than 3 years ago!

**Comment by benjamingeer** [comment]
I think at some point I encouraged Marion and Loïc to use UTF-8 in filenames. I was probably thinking, "This is the 21st century, UTF-8 should be fine." :)

**Comment by loicjaouen** [comment]
@benjamingeer : you convinced me then and I still think that it's the way to go, we should not adapt to these machines, they should be usable in other languages than English and thus should accept utf-8 in every ways.

#183

**Comment by subotic** [comment]
@loicjaouen not a problem. Any bugs resulting from this will be automatically assigned to you ;-) be careful what you wish for :-)

**Comment by loicjaouen** [comment]
of course; starting from this one obviously (assigned to me and fixed by you: thanks @subotic  ;)  )
