### ISSUE TITLE
User's password management API

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#718]
Hi folks !
Is there a way with the Knora user/auth API to : 
- change the current password (by sending current pwd/new pwd) 
- deal with forgotten password (send email to the user with a URL link to reset password or something like that...)

If not, is it planned ?

**Comment by subotic** [comment]
> change the current password (by sending current pwd/new pwd)

this is implemented

> deal with forgotten password (send email to the user with a URL link to reset password or something like that...)

not implemented, but we probably should at some point in the future. I will open an issue.

**Comment by gfoo** [comment]
cool, thanks a lot, I finally found "change password" in the doc, probably swagger #714 will be a good news, for me a least ;-)
