### ISSUE TITLE
(xsd) problem with shortcode in IRI 

### ISSUE THREAD

**Issue by SepidehAlassi** [dhlab-basel/Knora#724]
I have defined shortcode 0801 for beol project. 
In xsd file generated by Knora, shortcode of project is added to prefix, see below:

` <xs:element type="knoraXmlImport:richtextValueType" maxOccurs="unbounded" minOccurs="0" name="p0801-beol__comment"/>`

which expects the local tag of this property in xml file to be as:
`<biblio:p0801-beol__comment knoraType="richtext_value">Oslo</biblio:p0801-beol__comment>`

adapting the xml, validation is successful however import fails due to wrong property Iri:
`status":4,"error":"java.util.NoSuchElementException: key not found: http://www.knora.org/ontology/p0801-beol#comment`

this propertyIRI should actually be : http://www.knora.org/ontology/0801/beol#comment right?
To regenerate the problem please use branch: goldbach_beta_release which has the shortcode defined.

I believe it is better to fix the xsd generation so that shortcode is not part of prefix, what do you think?

**Comment by benjamingeer** [comment]
I made the shortcode part of the prefix because there could be two different ontologies with the same name in different projects. Could you add the full stack trace here for the `NoSuchElementException`?

**Comment by benjamingeer** [comment]
Looks like the bug is in `StringFormatter.toPropertyIriFromOtherOntologyInXmlImport`.

**Comment by benjamingeer** [comment]
We have so many tests now, we're going to need a supercomputer to run them.

**Comment by benjamingeer** [comment]
I think I fixed it, could you check? But first, please add the full stack trace here for the `NoSuchElementException`, because I didn't get that exception, but I'd like to fix it too, so I need to know where it's being thrown from.

Then please pull from the `goldbach_beta_release` branch and test again.

**Comment by SepidehAlassi** [comment]
:D I was fixing it at the same time as you :-D 

here is the stack trace: 

`webapi [2018-02-07 11:17:11,653] ERROR - Dispatcher - key not found: http://www.knora.org/ontology/p0801-beol#mentionedIn
webapi java.util.NoSuchElementException: key not found: http://www.knora.org/ontology/p0801-beol#mentionedIn
webapi 	at scala.collection.MapLike.default(MapLike.scala:232)
webapi 	at scala.collection.MapLike.default$(MapLike.scala:231)
webapi 	at scala.collection.AbstractMap.default(Map.scala:59)
webapi 	at scala.collection.MapLike.apply(MapLike.scala:141)
webapi 	at scala.collection.MapLike.apply$(MapLike.scala:140)
webapi 	at scala.collection.AbstractMap.apply(Map.scala:59)
webapi 	at org.knora.webapi.responders.v1.ResourcesResponderV1.$anonfun$checkResource$1(ResourcesResponderV1.scala:1442)
webapi 	at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:157)
webapi 	at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:157)
webapi 	at scala.collection.immutable.Map$Map2.foreach(Map.scala:146)
webapi 	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:157)
webapi 	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:155)
webapi 	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
webapi 	at org.knora.webapi.responders.v1.ResourcesResponderV1.checkResource(ResourcesResponderV1.scala:1440)
webapi 	at org.knora.webapi.responders.v1.ResourcesResponderV1.$anonfun$createMultipleNewResources$42(ResourcesResponderV1.scala:1331)
webapi 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:304)
webapi 	at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$1(FastFuture.scala:37)
webapi 	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
webapi 	at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
webapi 	at akka.http.scaladsl.util.FastFuture$.transformWith$extension0(FastFuture.scala:37)
webapi 	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.transformWith(FastFuture.scala:86)
webapi 	at scala.concurrent.Future.flatMap(Future.scala:303)
webapi 	at scala.concurrent.Future.flatMap$(Future.scala:303)
webapi 	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.flatMap(FastFuture.scala:77)
webapi 	at org.knora.webapi.responders.v1.ResourcesResponderV1.$anonfun$createMultipleNewResources$38(ResourcesResponderV1.scala:1312)
webapi 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
webapi 	at scala.collection.immutable.List.foreach(List.scala:389)
webapi 	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
webapi 	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
webapi 	at scala.collection.immutable.List.map(List.scala:295)
webapi 	at org.knora.webapi.responders.v1.ResourcesResponderV1.$anonfun$createMultipleNewResources$36(ResourcesResponderV1.scala:1307)
webapi 	at scala.util.Success.$anonfun$map$1(Try.scala:251)
webapi 	at scala.util.Success.map(Try.scala:209)
webapi 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:289)
webapi 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
webapi 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
webapi 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
webapi 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
webapi 	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
webapi 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
webapi 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
webapi 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
webapi 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
webapi 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
webapi 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
webapi 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
webapi 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
webapi 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)`

**Comment by SepidehAlassi** [comment]
I pulled your changes, it fixes the issue. Thanks :)

**Comment by benjamingeer** [comment]
No problem! Thanks for the stack trace, I've fixed the exception.
