### ISSUE TITLE
What is example.ttl? Should it exist?

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#727]
I cannot find the file. Why should it be loaded?

https://github.com/dhlab-basel/Knora/blob/f804346ed457f69ae3a65ab0b4a3da4c8d60feb7/webapi/scripts/graphdb-knora-test-data.expect#L49

**Comment by tobiasschweizer** [comment]
```
Loading data...
Failed to load data: ../_test_data/ontologies/example.ttl (No such file or directory)

```

**Comment by benjamingeer** [comment]
It should not exist, you can remove that line from the script.

**Comment by tobiasschweizer** [comment]
ok, it will be done once PR #722 is merged
