### ISSUE TITLE
Thinking about better (read: nicer looking, easier to use, etc.) documentation

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#733]
There is now an extension to markdown, allowing us to do all the things that made us change to RST in the first place:

- https://github.com/lightbend/paradox
- https://developer.lightbend.com/docs/paradox/latest/

Main advantages:
- based on markdown and thus easier to use than RST. we could simply copy/paste markdown from issues/pull-request. think of release notes, documentation, examples.
- source (markdown) also directly usable on Github (links between pages work). no need to compile anything to have the newest documentation
- making it easier to use, lowers the barrier for developers to actually write documentation (which is enough painful in itself)
- developed and maintained by the Akka people

Disadvantages:
- need to convert RST to MD but this could be automated with a [script](https://gist.github.com/zaiste/77a946bbba73f5c4d33f3106a494e6cd) using pandoc.

**Comment by subotic** [comment]
@benjamingeer and I talked about making [www.knora.org](http://www.knora.org) more informative. This would be one of the important puzzle pieces.

**Comment by benjamingeer** [comment]
Paradox looks great! Let's switch.

I think knora.org should look something like these pages:

* https://akka.io/
* https://jekyllrb.com/

Most important:

* They make it clear what the software does
* They have a clearly visible "quick start" ("get up and running", "try Akka")
