### ISSUE TITLE
Thinking about better www.knora.org website

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#734]
Github pages support https://jekyllrb.com. Maybe we could create a simple site with some nice styling using jekyll. All pages would be written in markdown and the automatically build and published by Github.

**Comment by benjamingeer** [comment]
I think knora.org should look something like these pages:

* https://akka.io/
* https://jekyllrb.com/

Most important:

* They make it clear what the software does
* They have a clearly visible "quick start" ("get up and running", "try Akka")
