### ISSUE TITLE
Release process

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#735]
Necessary steps for each release:

 0. Create a new branch, e.g., `releasing-v1.2.0`
 1. Update the version number in `WebapiBuild.sbt`, `SalsahBuild.sbt`, `conf.py`
 2. Check if all release notes are there. They should be added as part of the pull-request introducing any code changes
 3. Remove the `(not released yet)` text in the title of the release notes
 4. Create a new page with the next version number including the `(not released yet)` text and add page to TOC
 5. On Github - Move any open issues from current release milestone to the next release milestone.
 6. On Github - Close current milestone
 7. Run `GenerateContributorsFile`, passing it a GitHub API token (`runMain org.knora.webapi.util.GenerateContributorsFile [ -t TOKEN ]`), to generate `Contributors.md`, then commit that file.
 8. Push and merge PR to `develop`
 9. On Github - Tag the commit with the version string, e.g., `v1.2.0` and create a release.
 10. On Github - Copy the release notes from the docs to the release
 11. Publish documentation

-> in general, releases should be cut at least once per month and on the last working day of the month.

-> update Knora documentation by adding these steps somewhere!

**Comment by musicEnfanthen** [comment]
If `git flow` is still a considerable workflow (compare #522), the procedure there would be to checkout a separate `release` branch from `develop` in the state in which it shall be released, then do all the release relevant stuff you mention in 1-4, then merging this `release` branch to `master` with tags, and at the same time back-merge to develop (without tags). Finally remove the release branch. I can’t say if it makes sense to have a tagged `develop` branch because you normally would expect a numbered version of any software to be kind of "stable", at least nothing in develop state, would’nt you?

**Comment by subotic** [comment]
This was also my/our initial idea based on [this](http://nvie.com/posts/a-successful-git-branching-model/) article. This is the reason why we have a `develop` branch.

But this was a few years back, and now the trend goes towards only one `master` branch, like described [here](https://softwareengineering.stackexchange.com/questions/312022/the-trend-of-the-develop-branch-going-away). In our case, the `develop` branch is actually our `master` branch. Maybe we should rename it some time.

This also seems much simpler to me. We (should) have enough tests in place so that we can consider every commit in `develop` production worthy. If you look at the release steps, then you will not find anything there about special tests. It is simply tagging a commit and calling it a release. We simply bundle it a bit.

**Comment by musicEnfanthen** [comment]
Yes, I can see your point. And as is obvious from the sources you mentioned, it is definitely a question of taste or even ideology. In my own project, I always liked the feeling of having a "high-stable" `master` branch with only tagged releases on it, and a (also always stable) `develop` branch that collects all new features until the new release. It feels like having a "two-way authentication" for the final release. But you are right, having sufficient tests in place (incl. travis) provides another step of "authentication" that maybe makes a separate `develop` branch redundant.
