### ISSUE TITLE
Allow text values to have a language tag

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#736]
We need to be able to:

* Create text values with language tags in API v1 via bulk import.
* Filter text values by language in KnarQL in API v2.

Implementation in API v1:

* Add a property `language` to `knora-base`, and give `TextValue` an optional cardinality for it.
* Add an optional attribute for it in the bulk import XML schema.
* Add `def language: Option[String]` to `TextValueV1`, and corresponding member variables in `TextValueSimpleV1` and `TextValueWithStandoffV1`.
* In `ResourcesRouteV1`, get the optional language tag from the bulk import XML and use it when constructing text value objects.
* In `generateInsertStatementsForCreateValue.scala.txt`, insert a statement for the language if provided by `TextValueSimpleV1` or `TextValueWithStandoffV1`.

Implementation in API v2:

* Add `language: Option[String]` to `TextValueContentV2`, and output it in `TextValueContentV2.toJsonLDValue`.
* In `ConstructResponseUtilV2.createValueContentV2FromValueRdfData`, use the language read from the triplestore when constructing a `TextValueContentV2`.
* Accept the [lang function](https://www.w3.org/TR/2013/REC-sparql11-query-20130321/#func-lang) in `SearchParserV2` (the KnarQL parser).
* Generate appropriate SPARQL for that function in `SearchResponderV2`.

**Comment by SepidehAlassi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [language Specification for textValue](https://trello.com/c/kJ8xvtHo/85-language-specification-for-textvalue)
