### ISSUE TITLE
salsah-gui:guiAttributeDefinition is undocumented and inconsistent

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#744]
As part of #737, I'm writing documentation on `salsah-gui`, and I've noticed some things that seem inconsistent.

### guiAttributeDefinition

It looks like `guiAttributeDefinition` defines the types of attributes that are accepted by each `Guielement`. But:

* `Pulldown` has `guiAttributeDefinition "selection=api:lists"`, and `List` has no `guiAttributeDefinition`. In the test ontologies, both `Pulldown` and `List` have `salsah-gui:guiAttribute "hlist=..."`. What is `api:lists`? What is the difference between `Pulldown` and `List`?
* `Radio` has `guiElement "selection=api:list"`. I guess this should be `guiAttributeDefinition`? Is `api:list` different from `api:lists` (which is used in `Pulldown`), or is it a typo?
* `Searchbox` has `guiAttributeDefinition` `"resource=api:resources"`. What is `api:resources`?
  * In `images-onto.ttl`, there are properties that use `Searchbox` and have `guiAttribute` values like `"restypeid=33"`. That can't be right.
  * In `dokubib-ontol.ttl`, there's no `restypeid`, but there is `"numprops=1"`. What does that mean?

### guiElement and guiAttribute in the ontology update API

The ontology update API should allow the user to attach `guiElement` and `guiAttribute` to property definitions, right? In that case, it should check that the `guiAttribute` values provided are valid for the `guiElement` chosen. This means it will have to parse the objects of `guiAttributeDefinition`. And this means that those objects need a clear syntax that's consistent with existing ontologies.

**Comment by benjamingeer** [comment]
Also, what is ``salsah-gui:Iconclass``?

**Comment by benjamingeer** [comment]
In test ontologies, `salsah-gui:Radio` also has `salsah-gui:guiAttribute "hlist=..."`.

**Comment by benjamingeer** [comment]
How is `Textarea` different from `Richtext`? Is the difference that `Textarea` is unformatted?

**Comment by mrivoal** [comment]
Maybe I can help you with something, for a change :) 

> What is the difference between `Pulldown` and `List`?

`Pulldown` is used to display a flat list whereas `List` is for hierarchical list.

> How is `Textarea` different from `Richtext`? Is the difference that `Textarea` is unformatted?

Yes.

**Comment by lrosenth** [comment]
Not Yet Impleneted. Should be like geonames or GND a link to iconcalss.org <http://iconcalss.org/>… Need a GUI component to select a iconclass ID (iconographic autority file)…

Work in progress (standing still in the moment…)

Lukas

**Comment by lrosenth** [comment]
TextArea has no standoff/formatting, RichText ads the CKEditor...

**Comment by benjamingeer** [comment]
Do `restypeid` and `numprops` here have something to do with `restype_id` and `numprops` in [Search for Resources by their Label](http://www.knora.org/documentation/manual/rst/knora-api-server/api_v1/reading-and-searching-resources.html#search-for-resources-by-their-label)? If so, is this something that's needed only for API v1? Can this just be handled by KnarQL queries in v2?

**Comment by tobiasschweizer** [comment]
> Do restypeid and numprops here have something to do with restype_id and numprops in Search for Resources by their Label? If so, is this something that's needed only for API v1?

Yes, I think so.

**Comment by benjamingeer** [comment]
I found several incorrect cases of `salsah-gui:guiAttribute "hlist=<...>"` in the test ontologies. I'm thinking I should make the ontology responder check, when it loads the ontology, that the `hlist` IRIs used in `salsah-gui:guiAttribute` actually exist and refer to lists.

**Comment by benjamingeer** [comment]
In #737 I redesigned how `guiAttributeDefinition` works, so the API server can validate the objects of `guiAttribute` when it loads ontologies from the triplestore (and will later be able to do so when creating new properties via the API). I think I also fixed all the GUI attribute errors in the test data.
