### ISSUE TITLE
In which data graph should we store a new list if there are multiple ontologies defined?

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#747]
When I want to create a new list, then I need to create it inside the project's data graph to which the list belongs.

Before, we had only one data graph. Now with the possibility to define multiple ontologies, into which data graph should the list go?

Into which data graph do new resources go when there are multiple ontologies defined?

Can we maybe require that one of the ontologies defined needs to have the IRI ``http://www.knora.org/ontology/<project_shortcode>/<project_shortname>``? This way we could then use this ``http://www.knora.org/data/<project_shortcode>/<project_shortname>`` as the default location.

**Comment by subotic** [comment]
@benjamingeer I think that before we had a method somewhere that could calculate the data graph IRI from the ontology IRI. Do you maybe know where to find it?

**Comment by benjamingeer** [comment]
Unless I'm confused, each project can have:

* Exactly one data graph. All the project's resources go into this graph. The project's lists could go there, too.
* One or more ontology graphs.

The method `StringFormatter.projectDataNamedGraph` generates the IRI for a project's data named graph.

**Comment by benjamingeer** [comment]
Also I think these two lines can be deleted:

https://github.com/dhlab-basel/Knora/blob/5fe34b13a68d10583bfaae54dc946ce8fbd65c4b/webapi/src/main/scala/org/knora/webapi/responders/admin/ProjectsResponderADM.scala#L399
https://github.com/dhlab-basel/Knora/blob/5fe34b13a68d10583bfaae54dc946ce8fbd65c4b/webapi/src/main/scala/org/knora/webapi/responders/admin/ProjectsResponderADM.scala#L400

**Comment by benjamingeer** [comment]
You added the method `StringFormatter.projectDataNamedGraph` in this commit:

https://github.com/dhlab-basel/Knora/commit/59c47710e83f7797da64ae9fbd2ec7857152b0bc#diff-659c65d367a0897435d7612e0d1b8a4bR1515

😀

**Comment by subotic** [comment]
I'm getting old. Cant even remember what I did 3 months ago.

I was also slightly panicking. I don't know why I thought that we would need more than one graph for the data.

Thanks :-)

**Comment by benjamingeer** [comment]
No worries. :)
