### ISSUE TITLE
LiteralV2 / StringLiteralV2 / BooleanLiteralV2

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#750]
It seems that LiteralV2, StringLiteralV2, and BooleanLiteralV2 are defined in:

- `org.knora.webapi.messages.store.triplestoremessages.TriplestoreMessages.scala`
- `org.knora.webapi.messages.v2.responder.KnoraResponseV2.scala`

This makes it highly confusing to use with IntelliJ. I will rename the ones in `TriplestoreMessages` to something like `LiteralTS`, etc.

**Comment by benjamingeer** [comment]
Probably I meant to move them to KnoraResponseV2, and forgot to remove them from the other place. I thought they shoud be in the more generic package because I needed to use them in ontology messages. Can we just have them in one place? Sorry for the confusion.

**Comment by subotic** [comment]
No problem. Are they the same? There are slight differences.

**Comment by subotic** [comment]
The ones defined in KnoraResponseV2 don't seem to be used anywhere. Could they be deleted?

**Comment by benjamingeer** [comment]
Yes, clearly I got confused while I was working on that code. Looking at the code again now, I think you can delete the ones in `KnoraResponseV2` and leave the ones in `TriplestoreMessages` as they are. They will eventually be used in ontology messages, too, but I guess that's OK.

**Comment by subotic** [comment]
great, thanks 😄

glad that I’m not the only one who gets confused from time to time 😉
