### ISSUE TITLE
Compiling errors

### ISSUE THREAD

**Issue by kilchenmann** [dhlab-basel/Knora#754]
After pulling the newest setup from develop branch, I get the following errors while compiling:

[info] Compiling 309 Scala sources to [...]/knora/webapi/target/scala-2.12/classes ...
[warn] [...]/knora/webapi/src/main/scala/org/knora/webapi/messages/v2/responder/KnoraResponseV2.scala:27:60: imported 'LiteralV2' is permanently hidden by definition of trait LiteralV2 in package responder
[warn] import org.knora.webapi.messages.store.triplestoremessages.LiteralV2
[warn]                                                            ^
[error] [...]/knora/webapi/src/main/scala/org/knora/webapi/util/ConstructResponseUtilV2.scala:579:38: type mismatch;
[error]  found   : scala.collection.immutable.Map[org.knora.webapi.IRI,org.knora.webapi.messages.store.triplestoremessages.LiteralV2]
[error]     (which expands to)  scala.collection.immutable.Map[String,org.knora.webapi.messages.store.triplestoremessages.LiteralV2]
[error]  required: Map[org.knora.webapi.IRI,org.knora.webapi.messages.v2.responder.LiteralV2]
[error]     (which expands to)  Map[String,org.knora.webapi.messages.v2.responder.LiteralV2]
[error]             resourceInfos = Map.empty[IRI, LiteralV2]
[error]                                      ^
[warn] one warning found
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 18 s, completed Feb 26, 2018 10:00:36 AM

**Comment by benjamingeer** [comment]
Oops. :)

**Comment by subotic** [comment]
No, `develop` compiles just fine. Did you try to do an `sbt clean`?

**Comment by kilchenmann** [comment]
> Did you try to do an sbt clean?

That was a good point. My mistake, I'm sorry. Thanks!
