### ISSUE TITLE
Does the distinction between hasProperties and hasStandoffProperties make sense?

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#760]
In the JSON-LD returned by the ontology routes, some properties go in `hasProperties` (if they’re used on resources or values), and others go in `hasStandoffProperties` (if they’re used on standoff tags). But what if a property is used both on values and on standoff tags (like `valueHasUri`)? Where should it go? Should we even have this distinction, or could we get rid of it?

**Comment by benjamingeer** [comment]
And actually, do we need `hasStandoffClasses`? Could we just have a boolean `isStandoffTag` on each standoff class?

**Comment by tobiasschweizer** [comment]
> Could we just have a boolean isStandoffTag on each standoff class?

I guess that would make sense. Actually, we also flagged properties in a way so they can be distinguished from resource classes. So  we could also flag standoff props.

**Comment by tobiasschweizer** [comment]
sorry, I meant value classes and standoff classes.

**Comment by benjamingeer** [comment]
OK, so I will make it like this:

* `hasClasses`
* `hasProperties`
* `hasIndividuals`

And I will add flags to distinguish resource classes from standoff classes, and resource properties from standoff properties.

**Comment by tobiasschweizer** [comment]
Just keep in mind that the ontology service in the SALSAH GUI might have to be adapted accordingly.

**Comment by benjamingeer** [comment]
Actually, sorry, what I just said makes no sense, because is `valueHasUri` a standoff property? It's used in standoff classes but also in values.

Do we actually need to flag standoff properties? Isn't it enough that we have the cardinalities in standoff classes, to find out which properties they need?

**Comment by tobiasschweizer** [comment]
If they show up like other properties, the GUI will display them in the extended search form if they cannot be distinguished from other props.

**Comment by benjamingeer** [comment]
> If they show up like other properties, the GUI will display them in the extended search form if they cannot be distinguished from other props.

Doesn't that just mean that the GUI needs to know which properties are resource properties (which it should use in the extended search form)? Why would it need to distinguish between, say, `valueHasColor` (which is used in `StandoffColorTag` as well as in `ColorValue`) and `dimX` (which is used in `StillImageFileValue` but not in any standoff tag)?
