### ISSUE TITLE
refactor splitMainResourcesAndValueRdfData so it uses SparqlExtendedConstructResponse

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#763]
- use `SparqlExtendedConstructResponse` so the language tag can be taken into account
- do not return a list node's label for a list value. Instead, the client has to make a request to the v2 list route (requires a change in SALSAH)
- make case class for `Map[IRI, ConstructResponseUtilV2.ResourceWithValueRdfData]`
- make case class for `Map[IRI, Seq[ValueRdfData]]`

**Comment by tobiasschweizer** [comment]
```
 ```
def createValueContentV2FromValueRdfData(valueObject: ValueRdfData, mappings: Map[IRI, MappingAndXSLTransformation]): ValueContentV2 = {
        val stringFormatter = StringFormatter.getGeneralInstance

        // every knora-base:Value (any of its subclasses) has a string representation
        val valueObjectValueHasString: String = valueObject.assertions(OntologyConstants.KnoraBase.ValueHasString).head.toString

        // every knora-base:value (any of its subclasses) may have a comment
        val valueCommentOption: Option[String] = valueObject.assertions.get(OntologyConstants.KnoraBase.ValueHasComment) match {
            case Some(literals: Seq[LiteralV2]) => Some(literals.head.toString)
            case None => None
        }

        valueObject.valueObjectClass match {
            case OntologyConstants.KnoraBase.TextValue =>

                if (valueObject.standoff.nonEmpty) {
                    // standoff nodes given
                    // get the IRI of the mapping
                    val mappingIri: IRI = valueObject.assertions.getOrElse(OntologyConstants.KnoraBase.ValueHasMapping, throw InconsistentTriplestoreDataException(s"no mapping IRI associated with standoff belonging to textValue ${valueObject.valueObjectIri}")).head.toString

                    val mapping: MappingAndXSLTransformation = mappings(mappingIri)

                    val standoffTags: Vector[StandoffTagV1] = StandoffTagUtilV1.createStandoffTagsV1FromSparqlResults(mapping.standoffEntities, valueObject.standoff.map {
                        case (standoffNode: IRI, assertion: Map[IRI, Seq[LiteralV2]]) =>
                            (standoffNode, assertion.map {
                                case (standoffProp, standoffObjs) =>
                                    (standoffProp, standoffObjs.head.toString)
                            })
                    })

                    TextValueContentV2(valueHasString = valueObjectValueHasString, standoff = Some(StandoffAndMapping(standoff = standoffTags, mappingIri = mappingIri, mapping = mapping.mapping, XSLT = mapping.XSLTransformation)), comment = valueCommentOption)

                } else {
                    // no standoff nodes given
                    TextValueContentV2(valueHasString = valueObjectValueHasString, standoff = None, comment = valueCommentOption)
                }


            case OntologyConstants.KnoraBase.DateValue =>

                val startPrecision: String = valueObject.assertions(OntologyConstants.KnoraBase.ValueHasStartPrecision) match {
                    case startPrec: Seq[StringLiteralV2] if startPrec.size == 1 =>  startPrec.head.value
                    case other => throw InconsistentTriplestoreDataException(s"Expected ${OntologyConstants.KnoraBase.ValueHasStartPrecision} to exist and be of type String")
                }

                val endPrecision: String = valueObject.assertions(OntologyConstants.KnoraBase.ValueHasEndPrecision) match {
                    case startPrec: Seq[StringLiteralV2] if startPrec.size == 1 =>  startPrec.head.value
                    case other => throw InconsistentTriplestoreDataException(s"Expected ${OntologyConstants.KnoraBase.ValueHasEndPrecision} to exist and be of type String")
                }

                val calendar = valueObject.assertions(OntologyConstants.KnoraBase.ValueHasCalendar) match {
                    case cal: Seq[StringLiteralV2] if cal.size == 1 =>  cal.head.value
                    case other => throw InconsistentTriplestoreDataException(s"Expected ${OntologyConstants.KnoraBase.ValueHasCalendar} to exist and be of type String")
                }

                DateValueContentV2(
                    valueHasString = valueObjectValueHasString,
                    valueHasStartJDN = valueObject.assertions(OntologyConstants.KnoraBase.ValueHasStartJDN) match {
                        case startJDN: Seq[IntLiteralV2] if startJDN.size == 1 => startJDN.head.value
                        case other => throw InconsistentTriplestoreDataException(s"Expected ${OntologyConstants.KnoraBase.ValueHasStartJDN} to exist and be of type Integer")
                    },
                    valueHasEndJDN = valueObject.assertions(OntologyConstants.KnoraBase.ValueHasEndJDN) match {
                        case endJDN: Seq[IntLiteralV2] if endJDN.size == 1 => endJDN.head.value
                        case other => throw InconsistentTriplestoreDataException(s"Expected ${OntologyConstants.KnoraBase.ValueHasEndJDN} to exist and be of type Integer")
                    },
                    valueHasStartPrecision = KnoraPrecisionV1.lookup(startPrecision),
                    valueHasEndPrecision = KnoraPrecisionV1.lookup(endPrecision),
                    valueHasCalendar = KnoraCalendarV1.lookup(calendar),
                    comment = valueCommentOption
                )

            case OntologyConstants.KnoraBase.IntValue =>

                val integerVal: Int = valueObject.assertions(OntologyConstants.KnoraBase.ValueHasInteger) match {
                    case intVal: Seq[IntLiteralV2] if intVal.size == 1 => intVal.head.value
                    case other => throw InconsistentTriplestoreDataException(s"Expected ${OntologyConstants.KnoraBase.ValueHasInteger} to exist and be of type Integer")
                }

                IntegerValueContentV2(valueHasString = valueObjectValueHasString, valueHasInteger = integerVal, comment = valueCommentOption)

            case OntologyConstants.KnoraBase.DecimalValue =>

                val decimalVal: BigDecimal = valueObject.assertions(OntologyConstants.KnoraBase.ValueHasDecimal) match {
                    case decVal: Seq[DecimalLiteralV2] if decVal.size == 1 => decVal.head.value
                    case intVal: Seq[IntLiteralV2] if intVal.size == 1 => intVal.head.value
                    case other => throw InconsistentTriplestoreDataException(s"Expected ${OntologyConstants.KnoraBase.ValueHasDecimal} to exist and be of type Decimal")
                }

                DecimalValueContentV2(valueHasString = valueObjectValueHasString, valueHasDecimal = decimalVal, comment = valueCommentOption)

            case OntologyConstants.KnoraBase.BooleanValue =>

                val booleanVal: Boolean = valueObject.assertions(OntologyConstants.KnoraBase.ValueHasBoolean) match {
                    case boolVal: Seq[BooleanLiteralV2] if boolVal.size == 1 => boolVal.head.value
                    case other => throw InconsistentTriplestoreDataException(s"Expected ${OntologyConstants.KnoraBase.ValueHasBoolean} to exist and be of type Boolean")
                }

                BooleanValueContentV2(valueHasString = valueObjectValueHasString, valueHasBoolean = booleanVal, comment = valueCommentOption)

            case OntologyConstants.KnoraBase.UriValue =>

                val uriValue: String = valueObject.assertions(OntologyConstants.KnoraBase.ValueHasUri) match {
                    case uriVal: Seq[StringLiteralV2] if uriVal.size == 1 => uriVal.head.value
                    case other => throw InconsistentTriplestoreDataException(s"Expected ${OntologyConstants.KnoraBase.ValueHasUri} to exist and be of type String")
                }

                UriValueContentV2(valueHasString = valueObjectValueHasString, valueHasUri = uriValue, comment = valueCommentOption)

            case OntologyConstants.KnoraBase.ColorValue =>

                val colorValue: String = valueObject.assertions(OntologyConstants.KnoraBase.ValueHasColor) match {
                    case colorVal: Seq[StringLiteralV2] if colorVal.size == 1 => colorVal.head.value
                    case other => throw InconsistentTriplestoreDataException(s"Expected ${OntologyConstants.KnoraBase.ValueHasColor} to exist and be of type String")
                }

                ColorValueContentV2(valueHasString = valueObjectValueHasString, valueHasColor = colorValue, comment = valueCommentOption)

            case OntologyConstants.KnoraBase.GeomValue =>

                val geomValue: String = valueObject.assertions(OntologyConstants.KnoraBase.ValueHasGeometry) match {
                    case geomVal: Seq[StringLiteralV2] if geomVal.size == 1 => geomVal.head.value
                    case other => throw InconsistentTriplestoreDataException(s"Expected ${OntologyConstants.KnoraBase.ValueHasBoolean} to exist and be of type String")
                }

                GeomValueContentV2(valueHasString = valueObjectValueHasString, valueHasGeometry = geomValue, comment = valueCommentOption)

            case OntologyConstants.KnoraBase.GeonameValue =>

                val geonameValue: String = valueObject.assertions(OntologyConstants.KnoraBase.ValueHasGeonameCode) match {
                    case geonameVal: Seq[StringLiteralV2] if geonameVal.size == 1 => geonameVal.head.value
                    case other => throw InconsistentTriplestoreDataException(s"Expected ${OntologyConstants.KnoraBase.ValueHasGeonameCode} to exist and be of type String")
                }

                GeonameValueContentV2(valueHasString = valueObjectValueHasString, valueHasGeonameCode = geonameValue, comment = valueCommentOption)

            case OntologyConstants.KnoraBase.ListValue =>

                val listNodeIri: IRI = valueObject.assertions(OntologyConstants.KnoraBase.ValueHasListNode) match {
                    case listNode: Seq[IriLiteralV2] if listNode.size == 1 => listNode.head.value
                    case other => throw InconsistentTriplestoreDataException(s"Expected ${OntologyConstants.KnoraBase.ValueHasListNode} in assertions for a value object of type list value.")
                }

                val listNodeName: String = valueObject.listNode(OntologyConstants.Rdfs.Label) match {
                    case nodeNames: Seq[StringLiteralV2] => nodeNames.head.value // TODO: get the preferred language!
                    case other => throw InconsistentTriplestoreDataException(s"Expected ${OntologyConstants.Rdfs.Label} in assertions for a value object of type list value.")
                }

                HierarchicalListValueContentV2(valueHasString = valueObjectValueHasString, valueHasListNode = listNodeIri, listNodeName = listNodeName, comment = valueCommentOption)

            case OntologyConstants.KnoraBase.IntervalValue =>

                val startIntervalValue: BigDecimal = valueObject.assertions(OntologyConstants.KnoraBase.ValueHasIntervalStart) match {
                    case startIntValDec: Seq[DecimalLiteralV2] if startIntValDec.size == 1 => startIntValDec.head.value
                    case startIntValValInt: Seq[IntLiteralV2] if startIntValValInt.size == 1 => startIntValValInt.head.value
                    case other => throw InconsistentTriplestoreDataException(s"Expected ${OntologyConstants.KnoraBase.ValueHasIntervalStart} to exist and be of type String")
                }

                val endIntervalValue: BigDecimal = valueObject.assertions(OntologyConstants.KnoraBase.ValueHasIntervalEnd) match {
                    case endIntValDec: Seq[DecimalLiteralV2] if endIntValDec.size == 1 => endIntValDec.head.value
                    case endIntValValInt: Seq[IntLiteralV2] if endIntValValInt.size == 1 => endIntValValInt.head.value
                    case other => throw InconsistentTriplestoreDataException(s"Expected ${OntologyConstants.KnoraBase.ValueHasIntervalEnd} to exist and be of type String")
                }

                IntervalValueContentV2(valueHasString = valueObjectValueHasString, valueHasIntervalStart = startIntervalValue, valueHasIntervalEnd = endIntervalValue, comment = valueCommentOption)

            case OntologyConstants.KnoraBase.LinkValue =>

                val sourceResourceIri = valueObject.assertions(OntologyConstants.Rdf.Subject).head.toString
                val targetResourceIri = valueObject.assertions(OntologyConstants.Rdf.Object).head.toString

                val linkValue = LinkValueContentV2(
                    valueHasString = valueObjectValueHasString,
                    subject = sourceResourceIri,
                    predicate = valueObject.assertions(OntologyConstants.Rdf.Predicate).head.toString,
                    target = targetResourceIri,
                    comment = valueCommentOption,
                    incomingLink = valueObject.incomingLink,
                    nestedResource = None
                )

                valueObject.nestedResource match {

                    case Some(nestedResourceAssertions: ResourceWithValueRdfData) =>

                        val nestedResourceIri = if (!valueObject.incomingLink) {
                            targetResourceIri
                        } else {
                            sourceResourceIri
                        }

                        // add information about the referred resource
                        linkValue.copy(
                            nestedResource = Some(constructReadResourceV2(nestedResourceIri, nestedResourceAssertions, mappings)) // construct a `ReadResourceV2`
                        )

                    case None => linkValue // do not include information about the referred resource

                }


            case OntologyConstants.KnoraBase.StillImageFileValue =>

                val isPreviewStr: Option[String] = valueObject.assertions.get(OntologyConstants.KnoraBase.IsPreview) match {
                    case Some(isPrev: Seq[StringLiteralV2]) => Some(isPrev.head.value)
                    case None => None
                    case other => throw InconsistentTriplestoreDataException(s"Expected ${OntologyConstants.KnoraBase.OriginalMimeType} to be of type String")
                }

                val isPreview = stringFormatter.optionStringToBoolean(isPreviewStr, throw InconsistentTriplestoreDataException(s"Invalid boolean for ${OntologyConstants.KnoraBase.IsPreview}: $isPreviewStr"))

                val dimensionX: Int = valueObject.assertions(OntologyConstants.KnoraBase.DimX) match {
                    case dimX: Seq[IntLiteralV2] if dimX.size == 1 => dimX.head.value
                    case other => throw InconsistentTriplestoreDataException(s"Expected ${OntologyConstants.KnoraBase.DimX} to exist and be of type Integer")
                }

                val dimensionY: Int = valueObject.assertions(OntologyConstants.KnoraBase.DimY) match {
                    case dimY: Seq[IntLiteralV2] if dimY.size == 1 => dimY.head.value
                    case other => throw InconsistentTriplestoreDataException(s"Expected ${OntologyConstants.KnoraBase.DimY} to exist and be of type Integer")
                }

                val originalMimetype: Option[String] = valueObject.assertions.get(OntologyConstants.KnoraBase.OriginalMimeType) match {
                    case Some(origMime: Seq[StringLiteralV2]) => Some(origMime.head.value)
                    case None => None
                    case other => throw InconsistentTriplestoreDataException(s"Expected ${OntologyConstants.KnoraBase.OriginalMimeType} to be of type String")
                }

                val qualityLevel: Int = valueObject.assertions(OntologyConstants.KnoraBase.QualityLevel) match {
                    case qualLevel: Seq[IntLiteralV2] if qualLevel.size == 1 => qualLevel.head.value
                    case other => throw InconsistentTriplestoreDataException(s"Expected ${OntologyConstants.KnoraBase.QualityLevel} to exist and be of type Integer")
                }

                StillImageFileValueContentV2(
                    internalMimeType = valueObject.assertions(OntologyConstants.KnoraBase.InternalMimeType).head.toString,
                    internalFilename = valueObject.assertions(OntologyConstants.KnoraBase.InternalFilename).head.toString,
                    originalFilename = valueObject.assertions(OntologyConstants.KnoraBase.OriginalFilename).head.toString,
                    originalMimeType = originalMimetype,
                    dimX = dimensionX,
                    dimY = dimensionY,
                    qualityLevel = qualityLevel,
                    isPreview = isPreview,
                    valueHasString = valueObjectValueHasString,
                    comment = valueCommentOption
                )

            case OntologyConstants.KnoraBase.TextFileValue =>

                val originalMimetype: Option[String] = valueObject.assertions.get(OntologyConstants.KnoraBase.OriginalMimeType) match {
                    case Some(origMime: Seq[StringLiteralV2]) => Some(origMime.head.value)
                    case None => None
                    case other => throw InconsistentTriplestoreDataException(s"Expected ${OntologyConstants.KnoraBase.OriginalMimeType} to be of type String")
                }

                TextFileValueContentV2(
                    internalMimeType = valueObject.assertions(OntologyConstants.KnoraBase.InternalMimeType).head.toString,
                    internalFilename = valueObject.assertions(OntologyConstants.KnoraBase.InternalFilename).head.toString,
                    originalFilename = valueObject.assertions(OntologyConstants.KnoraBase.OriginalFilename).head.toString,
                    originalMimeType = originalMimetype,
                    valueHasString = valueObjectValueHasString,
                    comment = valueCommentOption
                )

            case other =>
                throw NotImplementedException(s"not implemented yet: $other")
        }

    }

```
```

**Comment by tobiasschweizer** [comment]
https://github.com/dhlab-basel/Knora/issues/763

**Comment by benjamingeer** [comment]
> do not return a list node's label for a list value

In that case, how do we display a list value in the simple schema? Currently it is just the label: #708

**Comment by tobiasschweizer** [comment]
One possibility would be the Iri like in the case of a resource reference:

```
"beol:hasAuthor": {
"@id": "http://rdfh.ch/biblio/QNWEqmjxQ9W-_hTwKlKP-Q"
}
```

And then the client would have to make another request to get more information. I want to implement support for that in the GUI (for the complex schema): when you get a list node Iri, request the whole list using the root node's Iri and cache it.

However, in 
https://github.com/dhlab-basel/Knora/issues/708#issuecomment-358921620 we thought about a reason why it should be a string and not an Iri.

> If the list represents keywords, you would just display the keyword associated with a list node. And since this is read only, we do not care about the Iri.
> And when you search for a list node, you search for its string representation.
So if you have seasons, you search for "summer".

But when you do a search for list value, you use a controlled vocabulary which is different from a full text search. In the extended search component for GUI, list values to search for should be picked from a list.  

If we want a different behavior depending on the requested schema, then this gets more complicated.

**Comment by benjamingeer** [comment]
> One possibility would be the Iri like in the case of a resource reference

That seems OK to me.

**Comment by tobiasschweizer** [comment]
> do not return a list node's label for a list value. Instead, the client has to make a request to the v2 list route (requires a change in SALSAH)

The necessary logic is now in preparation in https://github.com/dhlab-basel/Knora-ui/pull/170

**Comment by gfoo** [comment]
> the client has to make a request to the v2 list route 
I use the `/v2/lists/IRI` end point to get node label, is that correct?

**Comment by tobiasschweizer** [comment]
> I use the /v2/lists/IRI end point to get node label, is that correct?

Yes. Currently, we still return it with the value in the resource response but this behavior is not deterministic when you have labels in different languages, so we want to fetch the labels using the list route as you already do.
