### ISSUE TITLE
Travis testing of NIE-INE Ontologies

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#773]
@janCstoffregen wrote:

Lieber Ivan,
ich habe im Branch https://github.com/dhlab-basel/Knora/tree/NIE-328-migrate-ontologies/webapi/_test_data/ontologies unsere repo als Submodul hinzugefügt. Nun habe ich ein wenig mit dem .travis.yml herumprobiert, wie das Testen von unseren Ontologien sinnvoll integriert werden kann, sodass bei Änderungen der Ontologie - Schreibweise von Knora diese durch den Test sichtbar werden. Ein einfaches Einlesen der Ontologien in graphdb reicht wohl nicht, da dann die ganzen Knora compliance tests nicht durchgeführt werden. Derzeit funktioniert das Einlesen nicht, da ich die Pfade in dem eingefügten Script noch nicht angepasst habe, nicht dass Du jetzt viel Zeit damit verbringst, den Fehler zu suchen!

Hättest Du diese oder nächste Woche einmal Zeit für einen Termin? Ich würde gern vorbei kommen und ein wenig Hilfe in Anspruch nehmen, wenn Du Zeit hast.

Vielen Dank für Deine Antwort und viele schöne Grüsse,
Jan

---

@subotic replied:

Lieber Jan

> Ein einfaches Einlesen der Ontologien in graphdb reicht wohl nicht, da dann die ganzen Knora compliance tests nicht durchgeführt werden.

Was meinst du mit einfachem Einlesen? Wenn eure Ontologien als Teil von einem Test geladen werden, dann sollte nur dieser Test failen, was ja auch das Ziel wäre. Daraufhin, solltet ihr informiert werden. Entweder wird dann der Fehler schnell gelöst, oder der Test deaktiviert. Sollte also kein grosses Problem sein.

Was mir beim ganzen nicht gefällt ist, dass du eure Repo als Submodul hinzugefügt hast. Wenn du vielleicht eure Ontologien direkt hinzufügen (kopieren) könntest, wäre ich sehr dankbar. Wir möchten keine Submodule haben: https://codingkilledthecat.wordpress.com/2012/04/28/why-your-company-shouldnt-use-git-submodules/

Liebe Grüsse,
Ivan

Mentioned:
@hanscools 
@sacha-alex

**Comment by janCstoffregen** [comment]
Lieber Ivan,
mir war nicht bewusst, dass ihr Submodule nicht möchtet. Somit werden wir unsere Ontologien einfach reinkopieren. Wäre es in Ordnung, unsere Ontologien in dem Test - Data - Ordner in einem extra Ordner zu haben, sodass erkenntlich ist, dass die NIE-INE Ontologien eine Einheit bilden und sodass das kopieren ein wenig handlicher wird?

Mit dem "Einlesen" der Ontologien meine ich das neu Starten von Knora, nachdem die Ontologien in GraphDB eingelesen werden. Da Knora bei einem Neustart die Ontologien auf ihre Schreibweise prüft, würden wir das gerne bei travis mit durchführen, sodass eventuelle Änderungen der Ontologie - Vorgaben bei Knora auf diese Weise auffallen.

Vielen Dank und viele schöne Grüsse,
Jan

**Comment by subotic** [comment]
> in einem extra Ordner zu haben

Unbedingt :-) So wie die bestehenden Ordner strukturiert sind, z.Bsp. `other.v1.NieIneV1Spec` oder `other.v2.NieIneV2Spec` jeh nachdem in welchem Package der Test leben wird.

> Mit dem "Einlesen" der Ontologien meine ich das neu Starten von Knora ...

Ach so. Nein es funktioniert anders. Am Anfang von jedem Test, werden die Daten neu geladen. Während diesem Ladevorgang, sagt GraphDB ob es Probleme gab oder nicht. Zu keinem Zeitpunkt wir GraphDB neu gestartet. Somit können wir einen einfachen Test schreiben, welcher nichts anderes macht, als euere Daten zu laden.

**Comment by benjamingeer** [comment]
GraphDB prüft die Ontologien leider nicht, denn die „consistency check“-Regeln, die wir für GraphDB programmiert haben, behandeln nicht die Ontologien, sondern nur die Daten (das heißt die Ressourcen), die man lädt. Aber Knora prüft die Ontologien, wenn es sie lädt. Wir können also wirklich einen Test hinzufügen, welcher nichts anderes macht, als die NIE-Ontologien zu laden.

**Comment by benjamingeer** [comment]
Aber die Kontrollen, die Knora den Ontologien unterzieht, wenn es sie lädt, sind bisher auch ziemlich begrenzt. Wenn man aber eine neue Ontologie mit der Knora-API v2 schafft, wird sie besser kontrolliert:

http://www.knora.org/documentation/manual/rst/03-knora-api-server/api_v2/ontology-information.html

Die strenge Prüfung von geladenen Ontologien ist ein Ziel, das wir eines Tags erreichen wollen.

**Comment by janCstoffregen** [comment]
Ok, ich werde mir mal anschauen und einen Test einrichten. Vielen Dank für die Hinweise, ich denke, es wird so funktionieren!

**Comment by janCstoffregen** [comment]
Hi, I have removed the submodule and added the nie ontologies. Would you mind pointing me in the right direction how I can write a test which only loads the ontologies. I have to admit that I don't have any idea how to do that.

**Comment by subotic** [comment]
on what branch are you on? is there an open PR?

**Comment by janCstoffregen** [comment]
Hi, I'm still on the same branch, I have to change the graphdb input script to its old version so it will work and I wanted to write a test that imports the ontologies like Ben described it, then I can make a pull request.. Would you mind sending a link to an example test that tests another ontology? That would be amazing!

**Comment by benjamingeer** [comment]
Here's an example:

https://github.com/dhlab-basel/Knora/blob/develop/webapi/src/test/scala/org/knora/webapi/other/v1/DrawingsGodsV1Spec.scala

**Comment by janCstoffregen** [comment]
Cool, thank you, that is very helpful for me!

**Comment by benjamingeer** [comment]
You only need the test in `"Load test data"`. The `LoadOntologiesRequest` goes to `OntologyResponderV2`, which loads the ontologies. If the `LoadOntologiesResponse` message is received, this means that the responder found no errors. (Although as I said, it does very little error-checking at the moment. See #778.)

**Comment by janCstoffregen** [comment]
ok, I'll work on it today, thank you for this hint, after I understand it maybe we can participate in the consistency checking, @hanscools did lots of consistecy checking for Raeber, directly over Sparql, maybe those tests can be generalized so that we can integrate them as well, he found quite some faults in the imported data at fist, I have a feeling it might be helpful for other data as well, I will come back at that after I have understood it better, thank you again!!

**Comment by benjamingeer** [comment]
`OntologyResponderV2` reads all the ontologies and converts them to Scala data structures. It also allows new ontologies to be created (in Knora API v2):

http://www.knora.org/documentation/manual/rst/03-knora-api-server/api_v2/ontology-information.html

When you create a new ontology using API v2, it is checked very strictly in Scala. So the code to do these checks is already there. It just needs to be refactored so that ontologies read from the triplestore are also checked. That's what issue #778 is about.

**Comment by subotic** [comment]
You can take a look at `DrawingsGodsV1Spec`. There you can see how a basic test is written. As @benjamingeer already wrote, you only need the first part with `"Load test data"`.

Also, please put all your ontologies and test data in a folder which is named like the test, e.g., if your test lives in `org.knora.webapi.other.v1.NieIneV1Spec`, then put all your ontologies and data inside `_test_data/other.v1.NieIneV1Spec`

**Comment by subotic** [comment]
Also, I have opened PR #786, so going forward, any implementation specific discussion should be held there.

**Comment by benjamingeer** [comment]
When #806 is merged (hopefully next week), the Knora API server will check ontologies much more strictly on startup.

**Comment by janCstoffregen** [comment]
Thanks for the hint, I posted a question, I'll be in Basel next week, could I step by? That might be faster than through Github..

**Comment by benjamingeer** [comment]
I won't be in the office again until 30 April.

**Comment by janCstoffregen** [comment]
ok, thanks for this info, I will try to reach you over github then if needed.
