### ISSUE TITLE
Making Project-Shortcode required

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#787]
I think that we should finally make project-shortcode a required property. Up until now, we supported also projects without a defined project-shortcode.

Soon, we will need them for ARK, to be able to route requests to their correct servers.

So, now would be a good time to clean up the test data and any production data by adding the project-shortcode and move all IRI's to `http://rdfh.ch` like described in the  [documentation](http://www.knora.org/documentation/manual/rst/03-knora-api-server/api_v2/knora-iris.html#id6).

**Comment by subotic** [comment]
Since I'm currently working on a bug with the lists API caused by the old style data in the `anything` project, I will make the changes to the `anything` project.

**Comment by subotic** [comment]
An also to `Knora-Admin` making this a required property.

**Comment by benjamingeer** [comment]
OK!

**Comment by benjamingeer** [comment]
This is going to affect @loicjaouen and @mrivoal, because they have at least one project without a shortcode.

**Comment by benjamingeer** [comment]
Or rather, they used the shortcode as the project name.

**Comment by loicjaouen** [comment]
@benjamingeer thanks for thinking of us, but we are up to date with short codes and project names now, (at least on prod, we are using v1.1.0)

**Comment by benjamingeer** [comment]
OK then I’ll change the IRI validation in webapi to require the shortcode.

**Comment by tobiasschweizer** [comment]
> Since now every project is required to have its shortcode, I will give biblio the code 0802. Keep in mind to migrate the ontology and data when the time comes, i.e. you want to run this version. The changes would need to be done manually.

This would have to happen when you update the production server on which beol beta is running. The biblio data ttl file would have to be adapted (the prefix definition for biblio and the biblio project's IRI) and loaded back into the triplestore. Emacs works pretty good to edit big text files like ttl dumps :-)

**Comment by tobiasschweizer** [comment]
@subotic I know the handy emacs commands for search and replace operations. Let me know if I can help :-)
