### ISSUE TITLE
Redesign default permissions

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#79]
Currently the permissions for a a new resource come from the default permissions attached to the resource class, and permissions for a new value come from default permissions attached to the property definition. But this won't work for classes and properties that are defined only in `knora-base` and not extended in project-specific ontologies.

@lrosenth and I discussed this today and agreed to get rid of class-specific and property-specific default permissions. Instead, each user will be able to configure a set of default permissions for all new resources, and a set of permissions for all new values. If the user doesn't have any such defaults configured, we'll fall back to defaults attached to the project.

**Comment by subotic** [comment]
Attaching default permissions to projects has something to do with issue #54 , i.e. it involves the projects endpoint which I'm working on. So if can already do some ground work just let me know. I'm already considering this use case in the documentation.

**Comment by benjamingeer** [comment]
Sure! :)

**Comment by benjamingeer** [comment]
Can we get a status update on this? Nobody can create resources until it's fixed.

**Comment by subotic** [comment]
Good question. The last thing that we discussed was, that permissions should/must be sent with every "create resource" request, but I didn't implement this in the ``ResourcesResponder`` yet. Maybe we can take a look at this together and see how and where the permissions need to be available during the "create resource" request, and then I can implement it. You know the ``ResourcesResponder`` much better then I do :)

**Comment by benjamingeer** [comment]
OK. But maybe [this](https://github.com/dhlab-basel/Knora/issues/54#issuecomment-196849754) needs to be implemented first:

> **Use case:** User creates a resource and gives it whatever permissions he choses. He can give the resource any permissions on the spot (in the GUI), give it a personally predefined set of permissions, apply project default permissions if defined, or system default permissions if nothing else is defined.

In other words, we need a way to configure those default permissions per user, per project, and for the system. Then we need a way to offer them to the user as suggestions.

**Comment by subotic** [comment]
Yes, this is true. I should then probably make some progress with my user/project/group api :) In a first iteration, we could store/serve this information over this API.

**Comment by benjamingeer** [comment]
That would be great! This is currently blocking part of of GUI integration, and will also block projects like RTI that need to use the API to put data into Knora, so I think the sooner it's resolved, the better.

**Comment by subotic** [comment]
I have a suggestion, on how we could proceed.

Given the use case that you mentioned, the user needs to be able to finely define permissions somwhere in the GUI, which needs to be implemented first. In SALSAH 1.5 (old GUI using webapi), I suggest that the user is not going to be able to define any permissions. Instead, when he creates a new resource, the GUI will first send a request to the ``v1/projects`` api endpoint and ask for the "recommended" project permissions, and send this set of permissions along with the "create resource" request. Then, in SALSAH 2.0 (New GUI), we will provide the user with a GUI, where he will be able to set the permissions as he likes.

This way, we don't need to spend a lot of time developing new features for the old GUI, but already use the "new way" of setting permissions. This behavior would also be consistent with the current behavior of SALSAH 1.3.1.

Something else popped into my mind. What if the project leaders want to restrict the permissions to a fixed set? To implement this wouldn't be that hard. The GUI could query the ``v1/projects`` endpoint and see if the project allows the user to define his own permissions for new resources. Something that we maybe need to keep in mind.

**Comment by benjamingeer** [comment]
@tobiasschweizer what do you think?

**Comment by subotic** [comment]
> Sounds good!

Cool :)

> But what about people using an import script to create resources using directly the API? 
Then if the user is not able to freely define the permissions, what would happen?

To restrict permissions when used over the API, we could add an additional check in the relevant responders, to see if the supplied permissions are allowed.

> About the idea that permissions could be restricted to a set: if your are creating a resource, you are it owner. And then you can do anything with it including setting the permissions, right? So how would that restriction you mentioned fit into our permission system?

It would not fit. But are we sure that every project owner wants to give this freedom to each user working on his project? Again, this is just a use case that popped into my mind. Maybe its something, maybe its nothing. Time will tell :)

**Comment by benjamingeer** [comment]
Fixed in #186.

**Comment by benjamingeer** [comment]
Sorry, confused this with another issue.
