### ISSUE TITLE
Knarql and creationDate/lastModificationDate Resource

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#793]
is there a way to query the creationDate/lastModificationDate properties of a Resource ?

I know that they are not of type knora-api:Date, but I didn't find an other way.

My attempt :

```
PREFIX knora-api: <http://api.knora.org/ontology/knora-api/simple/v2#>
PREFIX ll: <http://0.0.0.0:3333/ontology/0113/lumieres-lausanne/simple/v2#>
    CONSTRUCT {

        ?fc knora-api:isMainResource true .
        ?fc ll:freeContentHasName ?name .
        ?fc knora-api:creationDate ?creationDate .

    } WHERE {
        ?fc a knora-api:Resource .
        ?fc a ll:FreeContent .

        ?fc ll:freeContentHasName ?name .
        ll:freeContentHasName knora-api:objectType xsd:string .
        ?name a xsd:string .

        ?fc knora-api:creationDate  ?creationDate .
        knora-api:creationDate knora-api:objectType knora-api:Date .
        ?creationDate a knora-api:Date .

} ORDER BY ?creationDate

```

in sparql of course : 

```
prefix ll: <http://www.knora.org/ontology/0113/lumieres-lausanne#>
prefix kb: <http://www.knora.org/ontology/knora-base#>
select * where { 
	?s a ll:FreeContent .
    ?s kb:creationDate ?date
} ORDER BY ?date  limit 100 
```

thanks

**Comment by tobiasschweizer** [comment]
We designed KnarQL for the querying of resources' properties (as defined in project ontologies) and their values. The creationDate/lastModificationDate of resources and values, however, are properties controlled by the system and I haven't thought about querying them in KnarQL at all.

A `knora-api:Date` is actually a `knora-base:DateValue` (support of different calendars and precisions), but the creationDate/lastModificationDate is just a timestamp.

The thing is that we try to hide some complexity to the outside by treating value objects as if they were literals (knora api simple schema). But in your example it just affects the resource so this is surely doable. 

I guess we could think about extending KnarQL. It would also make sense to include the resource's `rdfs:label`. Do you think we could specify the necessary extensions and see how it could be implemented?

What are going to do for v2 is a route to get the history of a value where you see all previous versions.

**Comment by gfoo** [comment]
👍 Good news if there is a way to get the creationDate/lastModificationDate with KnarQL, will be very helpfull. I have no use case currently for label, probably more needs about permissions (to know if a user can modify a Resource without making a new http call to know that), but I didn't make any tests.

I'm still using the v1 API, but my plan is to more easily map my Typescript classes with Ontology classes, so KnarQL is the ideal solution to drive what I (only) want as data returned and convert "fluently" jsonld to my classes (by thinking about ORM tools like [Spring/Hibernate](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/) or [Mongoose](http://mongoosejs.com/))

If you consider that KnarQL is enough stable let me know if I can start to use it now. (Anyway I will use it in the future to implement advanced search forms in our app)

**Comment by gfoo** [comment]
I've seen that now we have in the resource jsonld result the : 
- knora-api:creationDate
- knora-api:lastModificationDate
- knora-api:attachedToUser
- knora-api:hasPermissions
👍 

But :
- could we order resources by using those creationDate/lastModificationDate ?
- could you set lastModificationDate = creationDate when the resource is created ? (to order by lastModificationDate for example)
- could we have the last modification user id ? 

thx

**Comment by lrosenth** [comment]
The information is there – probably just a question of adding options to the PSARQL queries…

Lukas

Am 04.09.2018 um 15:07 schrieb Gilles Faucherand <notifications@github.com<mailto:notifications@github.com>>:


I've seen that now we have in the resource jsonld result the :

  *   knora-api:creationDate
  *   knora-api:lastModificationDate
  *   knora-api:attachedToUser
  *   knora-api:hasPermissions
👍

But :

  *   could we order resources by using those creationDate/lastModificationDate ?
  *   could you set lastModificationDate = creationDate when the resource is created ? (to order by lastModificationDate for example)
  *   could we have the last modification user id ?

thx

**Comment by benjamingeer** [comment]
> could we order resources by using those creationDate/lastModificationDate ?

We can add this feature to Gravsearch.

> could you set lastModificationDate = creationDate when the resource is created ? (to order by lastModificationDate for example)

Sounds reasonable to me.

> could we have the last modification user id ?

The only way to get this would be to look at all the values in the resource, find the one with the most recent `valueCreationDate`, and look at its `attachedToUser`. I think it would make sense for this to be part of the planned API operations for querying the resource's version history.

**Comment by gfoo** [comment]
If you have planned in your next devs the previous cited features : 
 - order by crea/last date 
 - last modification user id
 - by default last modif = creation date
It is no more required for us, don't waste precious dev time for that :)

**Comment by benjamingeer** [comment]
Thanks for letting us know. :)
