### ISSUE TITLE
Add LIMIT to SELECT COUNT in search queries

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#8]
This might require doing a subquery with a limit, then using COUNT in the outer query.

**Comment by tobiasschweizer** [comment]
Also, to only get the number of results (countSparql) we do not need any more information about the resources found. This, we only need in the second query. In fact, now we are querying information in the first query we just throw away and re-query them in the second one. 

It is convenient to have both queries in one template, but perhaps this also makes the template hard to read (a lot of if-constructs).

**Comment by benjamingeer** [comment]
We just have to make sure that both queries return the same number of results.

**Comment by tobiasschweizer** [comment]
Is this issue still relevant after the changes you made to search?

**Comment by benjamingeer** [comment]
No, not relevant anymore.
