### ISSUE TITLE
Remove remaining dependencies on API v1 code from API v2 code

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#803]
I did most of this in #796. What's left:

* `ConstructResponseUtilV2` uses:
  * `StandoffEntityInfoGetResponseV1`
  * `KnoraCalendarV1`
  * `KnoraPrecisionV1`
  * `MappingXMLtoStandoff`
* `TextValueContentV2` uses `StandoffTagUtilV1`
* `StandoffAndMapping` uses:
  * `StandoffTagV1`
  * `MappingXMLtoStandoff`
* `SearchResponderV2` uses `JulianDayNumberValueV1`
* `OntologyResponderV2` uses `StandoffDataTypeClasses`
* `ReadClassInfoV2` uses `StandoffDataTypeClasses`

**Comment by tobiasschweizer** [comment]
@benjamingeer Do you think refactoring v1 standoff responder and messages should also be part of #699?

**Comment by benjamingeer** [comment]
Which do you think would be easier? Doing a simpler refactoring first to remove these dependencies (e.g. by copying and pasting code into V2), and then doing #699 separately? Or doing both at the same time?

**Comment by tobiasschweizer** [comment]
I guess adding new stuff to the existing v1 version wouldn't make any sense at all, so a simple refactoring at the very beginning seems reasonable to me.

**Comment by benjamingeer** [comment]
OK, would you mind doing this while I work on #800? I'd really like to have a V2 codebase free of V1 code before adding more new features.

**Comment by tobiasschweizer** [comment]
> OK, would you mind doing this while I work on #800? I'd really like to have a V2 codebase free of V1 code before adding more new features.

I will have a look and make an outline of the required refactoring and estimate the time I need.

**Comment by tobiasschweizer** [comment]
I will try to refactor `StandoffResponderV1` and `StandoffMessagesV1` as well as `StandoffTagUtilV1` so that V1 calls V2 but V2 is self contained. We did this for `OntologyResponderV1` and `OntologyResponderV2`.

Also I want to do #396.

**Comment by tobiasschweizer** [comment]
I guess this refactoring will take a couple of days, probably most of next week.

**Comment by tobiasschweizer** [comment]
@benjamingeer I have just realized that I am about to dive into V2 JSON-LD handling :-) 

this time also turning JSON-LD into case classes for the creation of a mapping, but the logic is already there thanks to the ontology writing and updating parts you did :-)
