### ISSUE TITLE
Allow querying for ListNodes

### ISSUE THREAD

**Issue by SepidehAlassi** [dhlab-basel/Knora#813]
Followings should be added:
- route for requesting ListNodes
- query for ListNodes (functionality for Knarql)
Since this functionality is necessary for querying topics in BEOL, I would like that we prioritise resolving this issue.

**Comment by tobiasschweizer** [comment]
The following query gets all resources of type `anything:Thing` that have a `anything:hasListItem`:

```sparql
PREFIX knora-api: <http://api.knora.org/ontology/knora-api/simple/v2#>
PREFIX anything: <http://0.0.0.0:3333/ontology/anything/simple/v2#>

    CONSTRUCT {
        ?thing knora-api:isMainResource true .

        ?thing anything:hasListItem ?listItem .

    } WHERE {
        ?thing a knora-api:Resource .

        ?thing anything:hasListItem ?listItem .

        anything:hasListItem knora-api:objectType xsd:string .

        ?listItem a xsd:string .

    } OFFSET 0
```

If we want to restrict this query to a specific list item, we have to decide whether this should be an `xsd:string` or an Iri. We could modify the search logic for `xsd:string` in a way so that a value for the list node's`rdfs:label` can be used in the Filter:

```sparql
PREFIX knora-api: <http://api.knora.org/ontology/knora-api/simple/v2#>
PREFIX anything: <http://0.0.0.0:3333/ontology/anything/simple/v2#>

    CONSTRUCT {
        ?thing knora-api:isMainResource true .

        ?thing anything:hasListItem ?listItem .

    } WHERE {
        ?thing a knora-api:Resource .

        ?thing anything:hasListItem ?listItem .

        anything:hasListItem knora-api:objectType xsd:string .

        ?listItem a xsd:string .

        FILTER(?listItem = "Baumlistenknoten 02")

    } OFFSET 0
```  

But an `rdfs:label` is not unique (and it could be also available in several languages). I would rather prefer an Iri to identify a list node. But the reason it is an `xsd:string` is the idea to serve the list item's label in simple schema for a list value.

@benjamingeer Could we think of a list item like a resource that is pointed to? Could we handle properties pointing to list items like resource references?

**Comment by tobiasschweizer** [comment]
How is the use case of a list node different from a resource reference? Couldn't they be handled the same way?

If we want to serve a resource in simple schema and there is a linking property, we would have the same problem (display it as an object, not as a literal), right? The main difference between simple and complex schemas is that we hide the value objects, still the actual value might be an object in both cases (and then a list node cannot be an `xsd:string`).

In short: Could we make the list node `?listItem` an Iri in simple api? We could make a type like we did for date (`http://api.knora.org/ontology/knora-api/simple/v2#Date`)

> The basic issue is that you have a variable like ?listItem (or ?title in the case of a text value), which you often want to treat as a string, but sometimes you want to treat it as an IRI, and maybe get properties from it as in the complex schema.

Hm, I get the idea, but again for list nodes you could have several languages and the labels might not even be unique. 

I think to use a list node in a KnarQL query the user would chose from a selection of available list nodes first and then submit the IRI. We need a v2 route for serving lists.

**Comment by tobiasschweizer** [comment]
> It's different because a list node is not a resource

I just wanted to say that both might be displayed as an object when serving them in simple schema, I did not mean to imply that list items / nodes are resources.

> So to me, these two situations (text value and list node) look very much the same. What we want is to treat them exactly the way they are treated in the complex schema. That's why I suggested just using the complex schema in these cases. It's already there. Why invent something new?

I get it, but didn't you also have the idea of using a custom SPARQL function for standoff search? 

I think your suggestion of using `knora-api` complex schema is reasonable, but mixing both (complex and simple) might confuse the user. 

Maybe we could try to write serving resources and values in simple schema first (meaning now :-))? Or are you already working on it?

**Comment by tobiasschweizer** [comment]
@benjamingeer Can I call you tomorrow (FaceTime)?

**Comment by benjamingeer** [comment]
Sure.

**Comment by tobiasschweizer** [comment]
Great. Have a good evening!

**Comment by benjamingeer** [comment]
> didn't you also have the idea of using a custom SPARQL function for standoff search?

Yes, but today I thought: why make another function when we already have the complex schema? Instead of an extra function, we can just use what we already have:

```
    anything:hasListItem knora-api:objectType knora-api-complex:ListNode .
    ?listItem a knora-api-complex:ListNode .
```

**Comment by SepidehAlassi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [search for listNode properties](https://trello.com/c/pFv1kZKH/89-search-for-listnode-properties)

**Comment by benjamingeer** [comment]
Result of discussion with @tobiasschweizer: in May we'll look together at allowing the complex schema to be used for list values and text values in KnarQL.

**Comment by tobiasschweizer** [comment]
@SepidehAlassi and I will take care of adding a v2 route for list nodes (#850).

@benjamingeer How should we proceed with this issue? I think we need to change the type inspector and the v2 search responder.

**Comment by benjamingeer** [comment]
Shall we do it together next week? I'll be in the office from Tuesday-Thursday. Will that be soon enough?

**Comment by tobiasschweizer** [comment]
> Shall we do it together next week? I'll be in the office from Tuesday-Thursday. Will that be soon enough?

Yes, I think that would make sense.

**Comment by tobiasschweizer** [comment]
Once this is done, the list node's label should not be returned any more when a list value is queried. Given the list node's Iri, the client do a request to the v2 list route.
