### ISSUE TITLE
Ontology Information about XSLTransformation 

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#818]
http://0.0.0.0:3333/v2/ontologies/allentities/http%3A%2F%2Fapi.knora.org%2Fontology%2Fknora-api%2Fv2

does not include `XSLTransformation` which is defined in `knora-base`:

```

### http://www.knora.org/ontology/knora-base#XSLTransformation

:XSLTransformation  rdf:type owl:Class ;

                    rdfs:subClassOf :TextRepresentation ,
                                    [ rdf:type owl:Restriction ;
                                      owl:onProperty :hasTextFileValue ;
                                      owl:cardinality "1"^^xsd:nonNegativeInteger
                                    ] ;

                    rdfs:label "a TextRepresentation representing an XSL transformation that can be applied to an XML created from standoff. The transformation's result is ecptected to be HTML."@en ;

                    rdfs:comment "a TextRepresentation representing an XSL transformation that can be applied to an XML created from standoff.  The transformation's result is ecptected to be HTML."@en .


```

Could the problem be that it is not an immediate subclass of `knora-base:Resource` and the current implementation only returns direct children?

**Comment by benjamingeer** [comment]
This isn't a bug. `XSLTransformation` is excluded from `knora-api` by `KnoraApiV2WithValueObjects.KnoraBaseClassesToRemove`. I did that because there were no API operations that would allow the client to use it. If you're adding such an operation, you can undo the exclusion.

> the current implementation only returns direct children?

That's not how it works. The implementation returns everything in `knora-base` that isn't explicitly excluded by `KnoraApiV2WithValueObjects`.

**Comment by tobiasschweizer** [comment]
Ok, thanks.

In the GUI someone can author an extended search for a `TextRepresentation` which returns `XSLTransformation`. And then the GUI could not find any information about it in the cache.

So I suggest that I simple remove the exclusion.

**Comment by benjamingeer** [comment]
OK, and then maybe you could also add an API v2 operation for creating an `XSLTransformation`. :)

**Comment by tobiasschweizer** [comment]
It is simply a subclass of  `TextRepresentation` which is a resource. So the resources route can be used.  Otherwise BEOl wouldn't work at all ;-)

**Comment by benjamingeer** [comment]
Just kidding. I hope to add the API v2 resource creation route before I retire. :)

**Comment by tobiasschweizer** [comment]
aha, you tried to trick me :-)
