### ISSUE TITLE
Import Knora Ontologies

### ISSUE THREAD

**Issue by janCstoffregen** [dhlab-basel/Knora#825]
Dear dhlab,
when I import data to graphdb with the script graphdb-free-init-knora-test.sh I get the message 
```
Invalid rule set: /graphdb/KnoraRules.pie
```

When I import it again, I get the message 
```
Multiple ID-statements for repository ID knora-test500
```
The second issue was already solved by @loicjaouen here: https://stackoverflow.com/questions/38503102/error-multiple-id-statements-for-repository-id-on-repository-drop-create/38504966?noredirect=1#comment86715981_38504966
Thank you ver much for your help @loicjaouen!

The first error remains unsolved, I can't solve it right now, do you have an idea what it could be?
Thank you and have a good start into the week,
Jan

**Comment by janCstoffregen** [comment]
it's not running in docker, ok, so I just have to change the path of this file, do you know where it is located?

**Comment by janCstoffregen** [comment]
or should I run another script?

**Comment by subotic** [comment]
take a look at `graphdb-se-local-init-knora-test.sh` vs `graphdb-se-docker-init-knora-test.sh`

**Comment by subotic** [comment]
> or should I run another script?

if you are using `graphdb-free` then you would need to have those two kinds of scripts.

**Comment by janCstoffregen** [comment]
ok, sorry, I did not realise the graphdb-free refers to the docker image..

**Comment by janCstoffregen** [comment]
I'll try the other script now

**Comment by subotic** [comment]
they only difference is in the path to `KnoraRules.pie`.

**Comment by subotic** [comment]
the `local` one: `"$PWD/KnoraRules.pie"`
the `docker` one: `"/graphdb/KnoraRules.pie"`

**Comment by janCstoffregen** [comment]
thank you so much, it works now!

**Comment by subotic** [comment]
you're welcome :-)
