### ISSUE TITLE
Documentation about how to run SALSAH1 tests

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#829]
Where can I find the documentation about how to tun the browser tests for salsah1?

- Sipi needs to be started with `--config config/sipi.knora-test-config.lua`
- Knora webapi needs to be started with `-r`
- Salsah1 needs to be running and then the tests can be executed with `test` in sbt

**Comment by subotic** [comment]
You created those tests. Didn't you write a documentation? ;-)

**Comment by tobiasschweizer** [comment]
> You created those tests. Didn't you write a documentation? ;-)

Good point. But didn't you add the flag `-r `;-)

**Comment by tobiasschweizer** [comment]
Joking, let's do it when we are back from holiday.

**Comment by tobiasschweizer** [comment]
If I find some time, I will do it this week :-)

**Comment by subotic** [comment]
This would be the steps. I took it from `.travis.yml` and cleaned it up a little:


1. start and initialize graphdb-se
    - ./graphdb-se-docker-init-knora-test.sh
1. start the sipi container (with test config)
    - docker run -d --add-host webapihost:[local IP address] -v /tmp:/tmp -v $HOME:$HOME -p 1024:1024 dhlabbasel/sipi:develop /sipi/local/bin/sipi --config=/sipi/config/sipi.knora-test-docker-config.lua
1. start the webapi and salsah1 server
   - cd knora/webapi/ && sbt "run allowReloadOverHTTP" &
    - cd knora/salsah1/ && sbt run &
1. wait for the webapi server to start before we proceed with running the salsah tests
1. unzip chromedriver
    - cd knora/salsah1/lib/chromedriver/ && unzip chromedriver_linux64.zip
1. start built-in salsah1 browser tests
    - cd knora/salsah1/ && sbt headless:test
