### ISSUE TITLE
Link to Knora-Base PDF not working

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#834]
On http://docs.knora.org, there is a link to http://docs.knora.org/assets/pdf/knora-base.pdf which does not work.

**Comment by subotic** [comment]
@benjamingeer is this PDF still needed? Somehow I thought that you converted everything to RST? Do we need to regenerate the PDF, since changes were made to `knora-base`?

**Comment by benjamingeer** [comment]
IIRC we stopped generating that PDF when I converted the `knora-base` doc from LaTeX to RST, so the link should just be a link to the HTML that's generated from that RST.

**Comment by subotic** [comment]
Thanks. Yes, that was also what I was thinking. I will correct it.
