### ISSUE TITLE
Create a V2 route for list nodes

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#850]
Create a V2 route that serves list nodes (similar to `org/knora/webapi/routing/v1/ListsRouteV1.scala`).

**Comment by tobiasschweizer** [comment]
@benjamingeer Shall we use `SparqlExtendedConstructResponse` to support multiple languages?

**Comment by benjamingeer** [comment]
Yes, actually I think we should use `SparqlExtendedConstructResponse` for everything, and get rid of `SparqlConstructResponse`, because with `SparqlExtendedConstructResponse` we get type information from the triplestore. But that would require some refactoring.

**Comment by tobiasschweizer** [comment]
> But that would require some refactoring.

Yes, exactly. See #763.

**Comment by subotic** [comment]
`ListsResponderADM` returns the list with type information. You would “only” need to transform the case classes to JSON-LD.

**Comment by tobiasschweizer** [comment]
> ListsResponderADM returns the list with type information. You would “only” need to transform the case classes to JSON-LD.

Great, we will look at it! Thanks a lot.

**Comment by tobiasschweizer** [comment]
I guess you added this for the admin data.
