### ISSUE TITLE
KnarQL and IRI constraint ?

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#856]
Hi all,
I didn't find a way to get a resource knowing its IRI ? did I miss something ? 
Of course I could use the "v2/resources" endpoint but my deal is to construct the result I need with only my required properties and possibly neighbor's resources (with their properties)  : 

```
PREFIX knora-api: <http://api.knora.org/ontology/knora-api/simple/v2#>
PREFIX ll: <http://0.0.0.0:3333/ontology/0113/lumieres-lausanne/simple/v2#>
CONSTRUCT {
  ?s knora-api:isMainResource true .
} WHERE {
  ?s a knora-api:Resource .
  ?s a ll:BibliographicNotice .
  FILTER(?s = <http://rdfh.ch/0113/jDHMBl7SQGCdgvg2bOl3Dg>)
}
```
_error : "org.knora.webapi.NotImplementedException: Value type http://api.knora.org/ontology/knora-api/simple/v2#Resource not supported in FilterExpression"_

In SPARQL  : 
```
prefix ll: <http://www.knora.org/ontology/0113/lumieres-lausanne#>
CONSTRUCT {
  ?s ?p ?v
}
where {
    ?s ?p ?v .
    # ?s a ll:BibliographicNotice .
    FILTER(?s = <http://rdfh.ch/0113/jDHMBl7SQGCdgvg2bOl3Dg>)
}

```

**Comment by tobiasschweizer** [comment]
When you do a KnarQL query, it is assumed that you do not know the Iri of the thing you are looking for. 

Instead you should make a resource request.

**Comment by gfoo** [comment]
oups, I didn't notice this (new) way :)  

`http://host/v2/resourcespreview/resourceIRI(/anotherResourceIri)*`

thanks

**Comment by tobiasschweizer** [comment]
no problem ;-)
