### ISSUE TITLE
Deleting a project does not work

### ISSUE THREAD

**Issue by lrosenth** [dhlab-basel/Knora#864]
Using the admin-API  ".../admin/projects/url-encoded-project-iri in a DELETE request does not delete the project (which is empty otherwise), but just returns the project data like a GET request.
I testes the feature both from PHP and postman – same result

**Comment by subotic** [comment]
This property should change `knora-base:status` to `false`.

Someday, we can check if the project IRI is used anywhere. If not, then we could really delete it.

**Comment by lrosenth** [comment]
Ok, I got it. Thanks!!

Lukas

Von meinem iPhone gesendet

Am 26.05.2018 um 13:24 schrieb Ivan Subotic <notifications@github.com<mailto:notifications@github.com>>:


We don’t actually delete anything. The project should be deactivated though, i.e. status=false
