### ISSUE TITLE
Add API operations for building and changing lists

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#866]
This could be done like the ontology editing API: you could add or edit only one node at a time, and you wouldn't be able to remove a node if it was used in data (this would have to look at the values of `guiAttribute`).

Should it be in the admin API or in API v2?

@lrosenth

**Comment by lrosenth** [comment]
@subotic: This could be something we're doing together. This would be great to have!



Am 29.05.2018 um 18:36 schrieb Benjamin Geer <notifications@github.com<mailto:notifications@github.com>>:


This could be done like the ontology editing API: you could add or edit only one node at a time, and you wouldn't be able to remove a node if it was used in data (this would have to look at the values of guiAttribute).

Should it be in the admin API or in API v2?

@lrosenth<https://github.com/lrosenth>

**Comment by subotic** [comment]
There is already an issue for this #511 and It is on my todo list.

**Comment by subotic** [comment]
The plan was to have it in the admin API.
