### ISSUE TITLE
Check docs for errors on Travis

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#868]
Could Travis run this during tests?

`typedoc --out target/site/api-v2 --readme none --name "Knora API V2 JSON-LD Format Documentation" --module commonjs src/api-v2`

@tobiasschweizer

**Comment by benjamingeer** [comment]
If it prints an error, that means there's a syntax error in the docs.

**Comment by subotic** [comment]
Is this the same thing as in `jsonformattest` in `docs/Makefile`? Would it be enough to just add running of `jsonformattest`?

**Comment by benjamingeer** [comment]
Yes, that's it.

**Comment by subotic** [comment]
Should `jsonformattest` run first or last?

**Comment by benjamingeer** [comment]
> Should jsonformattest run first or last?

Don't know. @tobiasschweizer ?

**Comment by tobiasschweizer** [comment]
@subotic I am not sure if `jsonformattest`includes both versions of the API (v1 and v2). However, the command is very similar.

**Comment by tobiasschweizer** [comment]
> Should jsonformattest run first or last?

I think it should run first.

**Comment by benjamingeer** [comment]
It includes both.

**Comment by tobiasschweizer** [comment]
> It includes both.

great!

**Comment by subotic** [comment]
jup:

```
jsonformattest:
	$(TYPEDOC) --out $(FORMATDOCDIRV1) --readme none --name "Knora API V1 Format Documentation" --module commonjs $(FORMATSRCDIRV1)
	$(TYPEDOC) --out $(FORMATDOCDIRV2) --readme none --name "Knora API V2 JSON-LD Format Documentation" --module commonjs $(FORMATSRCDIRV2)
	@echo "Sample requests test finished."
```

**Comment by subotic** [comment]
so, any particular order needed? Current order:

1. jsonformat
1. graphvizfigures

Should `jsonformattest` run before or after those two?

**Comment by benjamingeer** [comment]
`jsonformat` and `graphvizfigures` are independent.

@tobiasschweizer Do we actually need to run `jsonformat` if we run `jsonformattest`?

**Comment by tobiasschweizer** [comment]
`jsonformattest ` includes the sample data in the documentation which you actually do not want when you build the docs for knora.org. It just makes sure that the sample data is valid (or the docs actually correctly describe the data).

So I think when you just want to test, you just need  `jsonformattest`. If you want to build the docs for the knora webseite, you can do both to be sure, but `jsonformattest` has to come first so it is overwritten.
