### ISSUE TITLE
Use project shortcode instead of knora as the Sipi IIIF prefix

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#874]
Currently, `knora` is used as the prefix, so that under the `images` folder a `knora` folder holds all images. The goal is to have a folder per project, and for this, we can use the project shortcode.

I suppose the SipiResponder will need to be changed and the lua scripts.

The corresponding issue in Sipi: https://github.com/dhlab-basel/Sipi/issues/233

**Comment by loicjaouen** [comment]
That would be great, it is not always obvious right now to do some maintenance tasks because of that.

But I thought it would be against Sipi nature -a neutral media server-, and thus prone to future problems, to increase it with more of Knora knowledge.

**Comment by benjamingeer** [comment]
This needs to be done for both API v1 and API v2.
