### ISSUE TITLE
SSL Deployment issues

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#877]
There are some issues now that HTTPS is enforced. See https://github.com/orgs/dhlab-basel/teams/dasch/discussions/15

**Comment by subotic** [comment]
Maybe in `Salsah2` the app uses the environment variable, which now includes `https`, in creating the requests? Maybe @tobiasschweizer has an idea?

Or at least, describe the steps to reproduce the issue?

I should be in the office around 14:30, then we could talk over Skype.

**Comment by tobiasschweizer** [comment]
I think the http service has to know how to connect to Knora

**Comment by subotic** [comment]
I have found the problem, at least for this error. The configuration variable which is used in the Gravsearch template needs to be `http://api.01.unibas.dasch.swiss` and not `https://api.01.unibas.dasch.swiss` (always `http`).

I'm redeploying with the new config and will let you know how it goes.

**Comment by tobiasschweizer** [comment]
@subotic That's great!

I think we just need to distinguish between requests to Knora and IRIs we need inside the queries.

**Comment by subotic** [comment]
ok, this seems to have fixed the issue. @tobiasschweizer could you maybe take a look at http://beol-test.dasch.swiss?

**Comment by subotic** [comment]
This is fixed. It was a configuration error.
