### ISSUE TITLE
Gravsearch incomings filtering

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#878]
Hi,
in our ontology we have two classes (Bilbio & Person) linked to the same class (Project) using the same link (isInProject). The Gravsearch reponse is quite strange : 
```
{
  "@id": "http://rdfh.ch/permissions/forbiddenResource",
  "@type": "knora-api:ForbiddenResource",
  "rdfs:label": "This resource is a proxy for a resource you are not allowed to see (may depend on the context: query path)",
  "@context": {
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "knora-api": "http://api.knora.org/ontology/knora-api/v2#"
  }
}
```
when I try to get the incoming resources (1 biblio and 1 person in my data set) of a Project having ones : 
```
PREFIX knora-api: <http://api.knora.org/ontology/knora-api/simple/v2#>
PREFIX test: <http://0.0.0.0:3333/ontology/0666/test/simple/v2#>
CONSTRUCT {
  ?Project knora-api:isMainResource true .
  ?isInProject test:isInProject ?Project .
} WHERE {
  ?Project a knora-api:Resource .
  ?Project a test:Project . 
    ?isInProject test:isInProject ?Project .
    test:isInProject knora-api:objectType knora-api:Resource .
    ?isInProject a knora-api:Resource .
#    ?isInProject a test:BibliographicNotice .
#    ?isInProject a test:Person .
 {
    ?isInProject a test:BibliographicNotice .
  } UNION {
    ?isInProject a test:Person .
  }
}  
```
There is no problem with permission because I can get the incoming Bilbio or Person linked to the project  (uncomment each line), but not together using an UNION. Onto and data set: [Archive.zip](https://github.com/dhlab-basel/Knora/files/2068141/Archive.zip)
thx

**Comment by tobiasschweizer** [comment]
Tomorrow I can have a look at it.

**Comment by tobiasschweizer** [comment]
I have an idea: could you try to run your query on this branch: wip/gravsearch-standoff

We fixed a bug there for optional dependent resources, maybe this solves your problem

**Comment by gfoo** [comment]
well done, it works. No hurry for me, I will work with this branch till you merge.
Anyway, I have to found a way to let this union optional ... yes I know, no nested blocks :)
thx a lot.
