### ISSUE TITLE
Implement type inference for Gravsearch

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#881]
* Change `TypeInspector.inspectTypes` so it takes additional parameters enabling it to send Akka messages, and returns `Future[TypeInspectionResult]`.
* Add an `InferringTypeInspector` class that asks `OntologyResponderV2` for information about ontology entities.
  * The algorithm could be iterative: try to infer some types, then see if the result allows you to infer more types, and keep going until an iteration doesn't add any new information.
  * If a variable is given with an `rdf:type` that's a Knora entity, assume it refers to a class, and ask the ontology responder about that class. If it's a resource class, give the variable a type of `knora-api:Resource`. Otherwise, use the specified type.
  * If a property is given as an IRI, ask the ontology responder about it to get its subject type (if specified) and object type.
  * If a variable or IRI is used as the subject or object of a property, and you have the subject or object type of the property, you can infer the type of the variable or IRI.
  * If a property is given as a variable and the type of its object is known, you can infer the property's object type.
  * If a property is given as a variable and is compared with property IRIs in a `FILTER`, you can ask the ontology responder for the object types of those properties (and check whether they're compatible), then infer the object type of the variable.
  * After the iterations have completed, if there's still missing type information, throw an exception.

**Comment by tobiasschweizer** [comment]
Would the old type annotations still work?

**Comment by benjamingeer** [comment]
Yes, we can run the two type inspectors one after another: first the one that looks for type annotations, then the one that does inference. The second one would build on the results of the first one.

**Comment by tobiasschweizer** [comment]
So we would have to throw an error if the type annotations are inconsistent with what the inference delivers, e.g. if the client provides wrong type annotations. 

But actually we want to get rid of explicit type annotations, we mainly have to care about backwards compatibility.
