### ISSUE TITLE
Make a better knora.org web site

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#888]
It should:

* Clearly say what Knora is
* Briefly describe Knora's main features (one sentence each), in not-too-technical language, with links to somewhat longer explanations (one paragraph each)
* Provide links to:
  * "Quick start", "Try Knora", "Install Knora", or some such thing
  * Code on GitHub
  * Documentation
  * News (e.g. new releases)

It should not:

* Have an outdated academic conference video on the front page

Some decent web sites for inspiration:

* [The Scala Programming Language](https://www.scala-lang.org)
* [The Haskell Programming Language](https://www.haskell.org)
* [CouchDB](http://couchdb.apache.org/)
* [Recogito](https://recogito.pelagios.org/)
* [Jekyll](https://jekyllrb.com/)

**Comment by kilchenmann** [comment]
Where is the page currently running? On which server? Or is it already a github page?

**Comment by benjamingeer** [comment]
> Where is the page currently running?

Don’t know. @subotic?

**Comment by kilchenmann** [comment]
Ah I remember: theres an own repository for knora.org
https://github.com/dhlab-basel/knora.org

**Comment by subotic** [comment]
> Where is the page currently running? 

yes, it's a Github page and can be found here: https://github.com/dhlab-basel/knora.org

**Comment by kilchenmann** [comment]
I already found a nice template. But what I need is content. I took some information from the README and from knora.org. But it's not so much yet 😉
I can commit it on a separate branch in https://github.com/dhlab-basel/knora.org

**Comment by benjamingeer** [comment]
@kilchenmann Great, if you make a branch and a PR, and put TODOs in it so I know where the text should go, I'll replace the TODOs with text.

**Comment by kilchenmann** [comment]
Btw I chose the template from here: https://github.com/CloudCannon/cause-jekyll-template. 
I changed the style (color) and added some content from README and from the documentation. 

@benjamingeer I added TODOs to the places in the code, where you can replace the content with better texts. Please use the this branch: [wip/reDesign](https://github.com/dhlab-basel/knora.org/tree/wip/reDesign)

I will find better pictures for the page and add newer updates. Right now the most content is in the index.html. I tried to include markdown files for each section. But it didn't worked (yet),

**Comment by kilchenmann** [comment]
Can we discuss further stuff about knora.org in the correct repository? I opened a new [issue (#5)](https://github.com/dhlab-basel/knora.org/issues/5) there.

**Comment by benjamingeer** [comment]
@kilchenmann Great, thank you. Will write some text.
