### ISSUE TITLE
Gravsearch response content and type support 

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#889]
I summarize here all what I would (finally) need in my project to fully use Gravsearch : 
- Resource default response content (like "rdfs:label"):
  - creationDate (+ order by)
  - lastModificationDate (+ order by)
  - attachedToUser
- ~~knora-base:UriValue type support~~ (not relevant, see next answer)

related to #802 #793

Thanks a lot !

n.b. : now, I only use Gravsearch to retrieve and search for data in my project (oh yeah !), works like a charm as we say today 👍

**Comment by benjamingeer** [comment]
Support for `creationDate`, `lastModificationDate`, and `attachedToUser` should be easy to add. But I would like to do this after #813 and #630.

**Comment by gfoo** [comment]
`xsd:anyURI` works for me, many thanks.  (May be update the doc as well: https://docs.knora.org/paradox/03-apis/api-v2/query-language.html)

**Comment by tobiasschweizer** [comment]
@gfoo Don't be afraid, I am just playing around with the emojis :-)

**Comment by benjamingeer** [comment]
@gfoo Do you still need this functionality, or can I close this issue like #793?

**Comment by gfoo** [comment]
You can close, thx.
