### ISSUE TITLE
Knora-Service should wait for GraphDB on startup and provide information about current state

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#891]
Currently, `KnoraService` requires a running GraphDB instance. In production, this is difficult to guaranty with container orchestration since the GraphDB docker container is started first, but there is no way to know how long GraphDB will take to actually start.

I suppose that also the bigger the GraphDB triplestore gets, the longer it will take.

I propose to start ontology initialization only after GraphDB is started, which needs to be detected somehow. Further, I would like to see that the HTTP server is started immediately so that monitoring and health endpoints could be queried. They can provide information about the state of the `Knora-Service`, e.g., `Waiting for GraphDB`, `Initializing Ontologies`, `Ready`. Only when the startup procedure is finished, the `/admin`, `/v1`, and `/v2` routes should be activated.

The startup workflow:

1. start HTTP server
1. only `/health` and `/monitor` routes should be active, all other routes should return `503 Service Unavailable` with a description of the state, e.g., waiting for GraphDB
1. start periodic checking if GraphDB is up
1. run `LoadOntologiesRequestV2`
1. enable `/admin`, `/v1`, and `/v2`

**Comment by benjamingeer** [comment]
Sounds good to me. I guess Knora should just try to connect to the triplestore every 500 ms or so, and keep trying until it gets a response.
