### ISSUE TITLE
Use  owlim:MonitorRepository as repository type

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#898]
It seems that we initialize our repositories in the wrong way. We have `rep:repositoryType "openrdf:SailRepository" ;` but according to Ontotext we should have `rep:repositoryType "owlim:MonitorRepository"`.  At least, this was the explanation given by them for a ticket that I opened regarding backup restore.

- http://graphdb.ontotext.com/documentation/standard/configuring-a-repository.html#configure-a-repository-programmatically

**Comment by benjamingeer** [comment]
We just have to remember to put in the release notes that everyone has to dump their repositories and restore them with the new config.

**Comment by subotic** [comment]
Yes, I will also add a check to see if the config is correct, to inform the user to update. I'm working on getting information about the configured repositories in #896 so this information should be already available at startup.
