### ISSUE TITLE
Sideband has no Resource Icon in Ontology

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#90]
The resource class `incunabula:Sideband` has no resource icon which makes resources responder crash.

Do we have a restriction that a resource class requires an icon? Or do we have to handle that in Scala using options?

**Comment by tobiasschweizer** [comment]
this foxes the problem in scala: https://github.com/dhlab-basel/Knora/commit/ab2ea6df1c763789bb54bbe0ed2c73a38bf1ae16

**Comment by benjamingeer** [comment]
Good fix. :)

**Comment by benjamingeer** [comment]
Much easier than trying to imagine an icon for a sideband. :)

**Comment by tobiasschweizer** [comment]
oh sidebands ...
