### ISSUE TITLE
No value found for SPARQL query variable 'ontologyObj' in query result row

### ISSUE THREAD

**Issue by hanscools** [dhlab-basel/Knora#904]
Hello,
I did not find any more specific information on this error and could not derive a possible solution from the 3 SPARQL queries or 2 methods where 'ontologyObj' is mentioned in Knora.
It is produced with the current constellation of ontologies/knora-files/knora on resp.:
https://github.com/nie-ine/Ontologies/tree/master/nie-ontologies
https://github.com/nie-ine/Ontologies/tree/master/NIE_Knora_ontology-dependency
https://github.com/nie-ine/Quick-Installation-Guide---Knora-Salsah-Sipi-GraphDB/tree/master/PrebuiltImages/20180619
Tx in advance for help.

**Comment by benjamingeer** [comment]
When does it happen? When you start Knora? Or when you make a specific API request?

**Comment by benjamingeer** [comment]
I can't reproduce this issue with the `develop` branch of Knora. I loaded all the NIE-INE ontologies using `webapi/scripts/graphdb-se-local-init-knora-test.sh` and this `expect` script:

https://github.com/nie-ine/Ontologies/blob/master/NIE_Knora_ontology-dependency/graphdb-knora-test-data.expect

Then I started Knora and got no errors.

I think that error would have to come from here:

https://github.com/dhlab-basel/Knora/blob/develop/webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala#L469

Are you running the `develop` branch of Knora?

Can you run this query in the GraphDB workbench?

```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX knora-base: <http://www.knora.org/ontology/knora-base#>

SELECT ?ontologyGraph ?ontologyIri ?ontologyPred ?ontologyObj
    FROM <http://www.ontotext.com/explicit>
WHERE {
    GRAPH ?ontologyGraph {
        ?ontologyIri rdf:type owl:Ontology ;
            ?ontologyPred ?ontologyObj .
    }
}
```

Are there any result rows that don't have a value for `ontologyObj`? (I think `rdf:type owl:Ontology` should guarantee that there is always a value.)

**Comment by benjamingeer** [comment]
Is it possible that you have an ontology with a predicate whose object is an empty string ("")?

**Comment by hanscools** [comment]
It was 1 empty string ...
Tx for the hint.
