### ISSUE TITLE
Error Message '...is not a subclass of that property's knora-api:subjectType...'

### ISSUE THREAD

**Issue by sacha-alex** [dhlab-basel/Knora#911]
I am currently running into the following kind of error after I imported our ontologies and restart knora:

ERROR - Dispatcher - Class http://www.knora.org/ontology/005B/text-structure#ReadabilityStructure would inherit a cardinality for property http://www.knora.org/ontology/005B/text-structure#hasWordValue, but is not a subclass of that property's knora-api:subjectType, http://www.knora.org/ontology/0059/text#Expression

I am not really sure about its meaning (especially '... but is not a subclass of that property's knora-api:subjectType ...') and how to fix it. 
For a first quick fix, I added the http://www.knora.org/ontology/0059/text#Expression in the classes' subClassOff-part where the problem happened. Unfortunately I ended up with: 

ERROR - Dispatcher - Class http://www.knora.org/ontology/0059/text#Text has a cardinality for property http://www.knora.org/ontology/005B/text-structure#hasWordValue, but is not a subclass of that property's knora-api:subjectType, http://www.knora.org/ontology/0059/text#Expression

which I interpreted that text:Text should be subclassed of one of its own subclassed decendents.

I added my current ontologies at this issues. Maybe it can be useful.
Any help is welcome. Many thanks in advance.

[nie-ontologies.zip](https://github.com/dhlab-basel/Knora/files/2145146/nie-ontologies.zip)

**Comment by benjamingeer** [comment]
It means:

* The definition of `hasWordValue` states that the subject of that property must be an `Expression`. You have made this constraint using `knora-base:subjectClassConstraint` in the property definition.
* `ReadabilityStructure` inherits a cardinality for `hasWordValue`.
* But `ReadabilityStructure` is not a subclass of `Expression`, so it can't be a subject of that property.

This is a requirement for logical consistency. It's documented here:

https://docs.knora.org/paradox/02-knora-ontologies/knora-base.html#restrictions-on-classes

> Each class must be a subclass of all the classes that are subject class constraints of the properties in its cardinalities.

**Comment by sacha-alex** [comment]
Super, many thanks for the explanation. It helps me a lot to fix the problem!
