### ISSUE TITLE
Refactor DateUtilV2

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#928]
`DateUtilV2` should:

* Not depend on API v1 code
* Be able to convert in both directions between `DateValueContentV2` and Julian day numbers

**Comment by benjamingeer** [comment]
[ICU - International Components for Unicode](http://site.icu-project.org/) supports lots of calendars, with conversions based on Julian day numbers:

http://icu-project.org/apiref/icu4j/com/ibm/icu/util/Calendar.html

**Comment by lrosenth** [comment]
Wow - thats sounds very interesting!!

Thanks,

Lukas

P.S. It seem sthe the DaSCH-SNSF case is making waves _ I think thats positive....

Am 19.09.2018 um 17:33 schrieb Benjamin Geer <notifications@github.com<mailto:notifications@github.com>>:


ICU - International Components for Unicode<http://site.icu-project.org/> supports lots of calendars, with conversions based on Julian day numbers:

http://icu-project.org/apiref/icu4j/com/ibm/icu/util/Calendar.html
