### ISSUE TITLE
Use Knora-Base resources and properties in extended search

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#93]
Make the named graph `knora-base` behave like the salsah-voc. in the old SALSAH, so that the user can do generic searches. This means that only resource classes and property types should be returned that the user shall be allowed to search for (no system-required resources and property types or things that are totally generic and not use as such).

In `application.conf`, set flag `visibleInGUI` to `true` for knora-base.

**Comment by benjamingeer** [comment]
Please try this with the SOARQL query I sent you, I think it might work.

**Comment by tobiasschweizer** [comment]
I already did :-) 

But I think there are resource classes returned the user would not directly search for.

Enjoy your holiday!
