### ISSUE TITLE
Travis build fails because GraphDB runs out of heap space

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#935]
https://travis-ci.org/dhlab-basel/Knora/jobs/403155085

![screen shot 2018-07-12 at 17 43 30](https://user-images.githubusercontent.com/558389/42644139-1e58399e-85fb-11e8-9c97-72922852b620.png)

This is from https://github.com/dhlab-basel/Knora/pull/927

**Comment by subotic** [comment]
try to restart the build. it doesn’t fail every time. I’m trying out GraphDB 8.5 again on Travis to see if it is GraphDB or Knora.

**Comment by benjamingeer** [comment]
I restarted it, it's still failing with the same error.

**Comment by subotic** [comment]
I’ve had better success with GraphDB 8.5.0. Could you please try to change `- GRAPHDB_VERSION="8.6.0-se"` to `- GRAPHDB_VERSION="8.5.0-se"` in `.travis.yml`

**Comment by benjamingeer** [comment]
Thanks, that fixed the build!

**Comment by subotic** [comment]
great :-) I had also no problems since I downgraded.
