### ISSUE TITLE
ClassCastException when starting via sbt reStart on branch develop

### ISSUE THREAD

**Issue by mattssp** [dhlab-basel/Knora#936]
As of today, when I try to start knora via sbt reStart, I get an Exception on startup:

webapi Starting org.knora.webapi.Main.main()
[success] Total time: 6 s, completed 13.07.2018 12:15:57
sbt:webapi> webapi[ERROR] [AppClassLoader@14dad5dc] error The specified aspect 'akka.kamon.instrumentation.DispatcherMetricCollectionInfoIntoDispatcherMixin' cannot be found
webapi[ERROR] Exception in thread "main" java.lang.ExceptionInInitializerError
webapi[ERROR]   at org.knora.webapi.Main.main(Main.scala)
webapi[ERROR] Caused by: java.lang.ClassCastException: akka.dispatch.Dispatchers cannot be cast to akka.kamon.instrumentation.ActorSystemAware
webapi[ERROR]   at akka.kamon.instrumentation.DispatcherInstrumentation.afterActorSystemInitialization(DispatcherInstrumentation.scala:75)
webapi[ERROR]   at akka.actor.ActorSystemImpl.start(ActorSystem.scala:842)
webapi[ERROR]   at akka.actor.ActorSystem$.apply(ActorSystem.scala:246)
webapi[ERROR]   at akka.actor.ActorSystem$.apply(ActorSystem.scala:289)
webapi[ERROR]   at akka.actor.ActorSystem$.apply(ActorSystem.scala:234)
webapi[ERROR]   at org.knora.webapi.LiveCore.system(KnoraService.scala:78)
webapi[ERROR]   at org.knora.webapi.LiveCore.system$(KnoraService.scala:78)
webapi[ERROR]   at org.knora.webapi.Main$.system$lzycompute(Main.scala:29)
webapi[ERROR]   at org.knora.webapi.Main$.system(Main.scala:29)
webapi[ERROR]   at org.knora.webapi.LiveCore.$init$(KnoraService.scala:93)
webapi[ERROR]   at org.knora.webapi.Main$.<init>(Main.scala:29)
webapi[ERROR]   at org.knora.webapi.Main$.<clinit>(Main.scala)
webapi[ERROR]   ... 1 more

**Comment by subotic** [comment]
@mattssp do you still have this problem? Which version of Knora are you using?
