### ISSUE TITLE
timeout or java.lang.OutOfMemoryError when using  /v1/resources/xmlimportschemas/ for some ontologies

### ISSUE THREAD

**Issue by sacha-alex** [dhlab-basel/Knora#944]
Sometimes I'm running into a problem when I'm using /v1/resources/xmlimportschemas/ for the bulk-import. It seems to occur with 'more complex' ontologies only, i.e. that are highly connected with other ontologies. Until now I tried to things:
 - to avoid a timeout error, I increased knora's timeout in 'application.conf'
 - I also increased the memory to avoid a java.lang.OutOfMemoryError ([ERROR] Uncaught error from thread [webapi-akka.actor.default-dispatcher-39]: GC overhead limit exceeded, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[webapi])

Like said before, I have no problems with some of our ontologies (e.g. agent, text, text-structure)
but with others (e.g. delille, drcs, kuno-raeber) I run into problems. It might be to do with knora and its memory usage, since I noticed, that the (graphdb-)queries run just fine (for delille this was done in one minute), but afterwards java/knora uses all CPU resources and drops out after some time (for delille after another 20 minutes).

I would be glad, if you can take a look at this problem. The used ontologies are attached to the issue.
Thank you very much in advance. 

[Ontologies.zip](https://github.com/dhlab-basel/Knora/files/2201891/Ontologies.zip)

**Comment by benjamingeer** [comment]
Related to #937?

**Comment by subotic** [comment]
@benjamingeer Maybe?

@sacha-alex which Knora version are you using?

**Comment by benjamingeer** [comment]
@sacha-alex Could you please test the branch in #948?
