### ISSUE TITLE
Not able to run latest Knora Version

### ISSUE THREAD

**Issue by janCstoffregen** [dhlab-basel/Knora#955]
Dear dhlab,
when I start and compile Knora as described on the README, it gives me the following error ( I only imported ontologies from your repository )

````
reStart
[info] Application webapi not yet started
[info] Starting application webapi in the background ...
webapi Starting org.knora.webapi.Main.main()
webapi[ERROR] objc[87402]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/bin/java (0x10f0db4c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x1101454e0). One of the two will be used. Which one is undefined.
[success] Total time: 13 s, completed Jul 30, 2018 2:30:13 PM
sbt:webapi> webapi [2018-07-30 14:30:21,904] INFO  - KnoraService(akka://webapi) - KnoraService - applicationStateActorReady
webapi KnoraService - startupTaskRunner starting
webapi [2018-07-30 14:30:24,214] INFO  - KnoraService(akka://webapi) - KnoraService - Startup State: StartingUp
webapi [2018-07-30 14:30:25,022] INFO  - KnoraService(akka://webapi) - KnoraService - Startup State: WaitingForRepository
webapi [2018-07-30 14:30:26,044] INFO  - KnoraService(akka://webapi) - KnoraService - checkRepository - status: NotInitialized: None of the available repositories meet our requirements of id: knora-test, sesameType: owlim:MonitorRepository.
webapi [2018-07-30 14:30:26,045] INFO  - KnoraService(akka://webapi) - Please initialize repository. Will exit now.
webapi[ERROR] Exception in thread "main" akka.pattern.AskTimeoutException: Recipient[Actor[akka://webapi/user/applicationState#-117355951]] had already been terminated. Sender[null] sent the message of type "org.knora.webapi.messages.app.appmessages.GetAppState".
webapi[ERROR] 	at akka.pattern.AskableActorRef$.internalAsk$extension(AskSupport.scala:291)
webapi[ERROR] 	at akka.pattern.AskableActorRef$.$qmark$extension1(AskSupport.scala:283)
webapi[ERROR] 	at org.knora.webapi.KnoraService.startupTaskRunner(KnoraService.scala:225)
webapi[ERROR] 	at org.knora.webapi.KnoraService.startService(KnoraService.scala:185)
webapi[ERROR] 	at org.knora.webapi.KnoraService.startService$(KnoraService.scala:177)
webapi[ERROR] 	at org.knora.webapi.Main$.startService(Main.scala:29)
webapi[ERROR] 	at org.knora.webapi.Main$.delayedEndpoint$org$knora$webapi$Main$1(Main.scala:82)
webapi[ERROR] 	at org.knora.webapi.Main$delayedInit$body.apply(Main.scala:29)
webapi[ERROR] 	at scala.Function0.apply$mcV$sp(Function0.scala:34)
webapi[ERROR] 	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
webapi[ERROR] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
webapi[ERROR] 	at scala.App.$anonfun$main$1$adapted(App.scala:76)
webapi[ERROR] 	at scala.collection.immutable.List.foreach(List.scala:389)
webapi[ERROR] 	at scala.App.main(App.scala:76)
webapi[ERROR] 	at scala.App.main$(App.scala:74)
webapi[ERROR] 	at org.knora.webapi.Main$.main(Main.scala:29)
webapi[ERROR] 	at org.knora.webapi.Main.main(Main.scala)
webapi ... finished with exit code 1
````

This happens on Mac and Ubuntu.

Thank you so much for your help.

Best regards,
Jan

**Comment by benjamingeer** [comment]
The error message says:

> None of the available repositories meet our requirements of id: knora-test, sesameType: owlim:MonitorRepository

Since #921, a GraphDB repository has to be of type `owlim:MonitorRepository`. This is set in the repository configuration file when the repository is created. Perhaps the Docker image `dhlabbasel/graphdb-free` hasn't been updated since then. @subotic ?

**Comment by janCstoffregen** [comment]
Dear dhlab,
Sascha found the fix.

In ```graphdb-free-knora-test-repository-config.ttl``` 

```rep:repositoryType "owlim:MonitorRepository" ;``` and  
```sail:sailType "owlim:Sail" ;```

It works now and I would like to do a pull request, but I'd like to ask if this has to be included then in the following file as well: ```graphdb-free-knora-test-repository-config.ttl```

**Comment by subotic** [comment]
I forgot about this use case. When `graphdb-free` is used, then according to the GraphDB documentation, the following settings should be used:

```
...
rep:repositoryType "graphdb:FreeSailRepository" ;
        sr:sailImpl [
            sail:sailType "graphdb:FreeSail" ;
...
```

To be able to know which setting to expect, we would need to have a distinction in `application.conf`.

I would thus suggest, to add `graphdb-free` and `graphdb-se` as separate values for `dbtype` (instead of `graphdb`).

**Comment by janCstoffregen** [comment]
sorry, I meant should it be included in this file as well: ```graphdb-free-knora-test-unit-repository-config.ttl```

**Comment by janCstoffregen** [comment]
I can't estimate what your proposal implies, it would be nice to only set the variable for the db once though, in application.conf and the import scripts for example read this file and check which database you chose so that there is online one "init-knora-test-unit.sh" - file and not one for each database.

**Comment by subotic** [comment]
Yes, the init scripts are not very user-friendly. I'm working on a more user-friendly version [here](https://github.com/dhlab-basel/knoractl), but his will take some time though as this is a side project of mine with a low priority.

I'm refactoring the `graphdb-free` scripts so that they behave the same as the `graphdb-se` scripts. You would need to use the correct one, depending on which GraphDB version you are using.

**Comment by janCstoffregen** [comment]
I agree, it's not so important, just a little bit more convenient.

**Comment by subotic** [comment]
wip in #959

@janCstoffregen could you maybe try out the branch from #959 and see if it works for you?

**Comment by janCstoffregen** [comment]
When using the webapi docker image with the environment variable set to graphdb, this error occurs again.. I know how to change it, just for your information.

**Comment by subotic** [comment]
The supported graphdb types are `graphdb-free` or `graphdb-se`.

**Comment by janCstoffregen** [comment]
So I thought if you use the docker webapi, you still have to declare the graphdb variable so that this message does not occur...

but I get this message again, after executing 

```
 ./graphdb-free-docker-init-knora-test.sh
```

and using the docker webapi

**Comment by janCstoffregen** [comment]
I set the variable in application.conf to graphdb-free, I meant the environment variable in the docker-compose file.
