### ISSUE TITLE
Correct header for the utf8 encoding of JSON responses

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#97]
Currently, the HTTP response header of a Knora API request does not contain an encoding header. It should say `content-type: application/json; charset=utf-8`

**Comment by tobiasschweizer** [comment]
```scala
 HttpResponse(
                        status = StatusCodes.OK,
                        entity = HttpEntity(
                            ContentTypes.`text/plain(UTF-8)`,
                            jsonResponseWithStatus.compactPrint
                        )
```

**Comment by tobiasschweizer** [comment]
https://github.com/spray/spray/blob/master/spray-http/src/main/scala/spray/http/HttpEntity.scala

**Comment by tobiasschweizer** [comment]
ok, there does not seem to be apllication/json with UTF-8

**Comment by tobiasschweizer** [comment]
fixed in https://github.com/dhlab-basel/Knora/commit/ccc1bfd8eaa9aef6e7cac557b32d4e05bce88261

**Comment by subotic** [comment]
Can you please only close an issue when it is merged into develop? This commit is in your private branch. You can write in the commit message ``resolves #issueNr`` (see https://help.github.com/articles/closing-issues-via-commit-messages/) then when this commit is merged, the issue will be closed automatically.
