### ISSUE TITLE
Knora freezes during BEOL import-test

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#980]
The BEOL import test fails on `develop` (https://github.com/dhlab-basel/Knora/commit/7d379187a74f24eb260c62e6c785f440b93bfcac) after around 700 letters with status `500`:

```
{"status":4,"error":"org.knora.webapi.TriplestoreConnectionException: Connection to triplestore timed out after 10 seconds"}
```

For whatever reason, GraphDB is having a hiccup. Maybe this can be easily solved by raising the timeout.

**Comment by subotic** [comment]
This is the same problem which was apparently not solved in #945.

**Comment by subotic** [comment]
wip in #979

**Comment by benjamingeer** [comment]
My `wip/apache-http-client` branch is still there, if it would help.

**Comment by subotic** [comment]
yes, thanks. @tobiasschweizer is using it to run his import.

**Comment by benjamingeer** [comment]
If I try to merge `wip/apache-http-client` into `wip/977-remove-actor-pools`, there are some merge conflicts, but those shouldn't be too difficult to resolve. Shall I do that and push to `wip/977-remove-actor-pools`?

**Comment by tobiasschweizer** [comment]
Thanks, on `wip/import-bebb-apache` the import worked. Now we can get the new data on the beol test server! 👍

**Comment by benjamingeer** [comment]
@subotic just want to confirm, should I merge `wip/apache-http-client` into `wip/977-remove-actor-pools` now? Or not yet?

**Comment by subotic** [comment]
No, please don't. We need to find a real fix. The Apache HTTP client works for the import, but I don't think that it solves the underlying problem.

**Comment by subotic** [comment]
Looking at the source code of the `ask` pattern, I found this warning:

```
When using future callbacks, inside actors you need to carefully avoid closing over
the containing actor’s object, i.e. do not call methods or access mutable state
on the enclosing actor from within the callback. This would break the actor
encapsulation and may introduce synchronization bugs and race conditions because
the callback will be scheduled concurrently to the enclosing actor. Unfortunately
there is not yet a way to detect these illegal accesses at compile time.
```

Do I understand this correctly, that we actually shouldn't use this to make a request from actor A to actor B and then use this result in methods defined in the actor A?

**Comment by subotic** [comment]
Here is the link to the warning: https://github.com/akka/akka/blob/4456d7752b1b9badc201728382efa9562bc1348c/akka-actor/src/main/scala/akka/pattern/AskSupport.scala#L50-L76

Now I understand, why in some examples they use `pipeTo self`. Basically then we could've also used `tell` in the first place.

I think that we need to get rid of some actors. I will try to do that in the `PermissionsResponderADM` and the `UsersResponderADM`. They are used in every request. Maybe this will alleviate the problem so that we are not under pressure to refactor everything at once.

**Comment by benjamingeer** [comment]
> Do I understand this correctly, that we actually shouldn't use this to make a request from actor A to actor B and then use this result in methods defined in actor A?

I always thought this warning only applied if you actually have mutable state in your actor. Otherwise can’t see why it would be a problem to call a method on the enclosing actor from the callback. I’ve always assumed that it’s not an issue for us because our actors don’t have mutable state.

**Comment by benjamingeer** [comment]
i’m tempted to refactor all of Knora, replacing the actors with ordinary Scala objects and the `?` (ask) method with a simple method that just calls `receive` on the appropriate object, in the same thread.

**Comment by subotic** [comment]
I’m going to do that tomorrow on 1 actor an see if it makes a difference. Then you are more than welcome to join in the fun 😉

**Comment by subotic** [comment]
we have more than enough actors and ask methods to rewrite.

**Comment by subotic** [comment]
I've written up a small plan in https://github.com/dhlab-basel/Knora/issues/977#issuecomment-417214162

**Comment by subotic** [comment]
So here is an interesting observation.

Because I was tired of rebooting my computer after each freeze, I'm now running `webapi`, `graphdb` and `sipi` inside Docker containers. When `webapi` is running inside a Docker container, then the freeze doesn't happen. Just to be sure that I've not gone crazy, I've run `webapi` again outside of docker. And it froze again.

So much for "write once, run anywhere". More like "write once, run anywhere, except where and when you need it."

![images](https://user-images.githubusercontent.com/400790/44925795-a9f18700-ad4f-11e8-9eb3-8219da71235a.jpeg)

**Comment by benjamingeer** [comment]
Could be something to do with macOS vs Linux? What if you run it outside Docker on a physical Linux server?

**Comment by subotic** [comment]
Will try that next week. I first need to install my Linux box. But I suspect that it is macOS vs Linux, or at least the difference in base configuration. Maybe some tweaking under macOS is necessary. Like the things, we need to do for running the `ab` tests maybe?

**Comment by benjamingeer** [comment]
> Maybe some tweaking under macOS is necessary. Like the things, we need to do for running the ab tests maybe?

I was thinking the same thing.

**Comment by subotic** [comment]
This seems to be a bug in macOS. When the import is run under Linux, it works. I've opened an issue: https://github.com/akka/akka-http/issues/2201
