### ISSUE TITLE
Ontology API error with link values

### ISSUE THREAD

**Issue by lrosenth** [dhlab-basel/Knora#988]
If adding the cardinality of a resource pointer link value, I get an error that either the link or the link property of the link value oproperty to not have a valid cardinality.

I think the reason is "improved" consistency checking. Using the Ontology API I have to add for links 2 cardinality one after the other: for the link propery and for the linkValue property. If I add the first, the second has not yet the right cardinality (that is none at all) or vice versa. So I can at the moment not add any link property because of this bug...

Suggestion: The linkValue cardinality is automatically added if the link gets a cardinality (in one transaction). I beleive that both cardinalities must always be the same.

Error example (if adding linkValue cardinality:

org.knora.webapi.BadRequestException: Resource class http://0.0.0.0:3333/ontology/1010/postcards/v2#postcard has cardinalities for one or more link value properties without corresponding link properties. The missing (or incorrectly defined) property or properties: http://0.0.0.0:3333/ontology/1010/postcards/v2#externalreference
stdClass Object

**Comment by benjamingeer** [comment]
>  Using the Ontology API I have to add for links 2 cardinality one after the other: for the link propery and for the linkValue property.

You don’t have to add them one after the other, you can add them at the same time, in a single request.

> Suggestion: The linkValue cardinality is automatically added if the link gets a cardinality

I was trying to keep the input and output consistent, but actually I think you’re right.

**Comment by lrosenth** [comment]
Hey Ben, still up??


Am 05.09.2018 um 00:12 schrieb Benjamin Geer <notifications@github.com<mailto:notifications@github.com>>:


Using the Ontology API I have to add for links 2 cardinality one after the other: for the link propery and for the linkValue property.

You don’t have to add them one after the other, you can add them at the same time, in a single request.

Suggestion: The linkValue cardinality is automatically added if the link gets a cardinality

I was trying to keep the input and output consistent, but actually I think you’re right.

**Comment by lrosenth** [comment]
Am 05.09.2018 um 00:12 schrieb Benjamin Geer <notifications@github.com<mailto:notifications@github.com>>:


Using the Ontology API I have to add for links 2 cardinality one after the other: for the link propery and for the linkValue property.

You don’t have to add them one after the other, you can add them at the same time, in a single request.

Didn't know this – will try..

Suggestion: The linkValue cardinality is automatically added if the link gets a cardinality

I was trying to keep the input and output consistent, but actually I think you’re right.

may be...
