### ISSUE TITLE
docker compose / sipi container config

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#994]
Hello,
I have an issue when I use the docker-compose.yml for developer. Sipi try to connect to Knora with a wrong host (when Sipi want to get the authorization infos of an Image):
`sipi       | Sipi: Server.http() failed: Error #1185: HTTP GET request to http://webapihost:3333/v1/files/9kRQGJnRF2V-CNBfsULnUDy.jpx failed: Failed to connect to webapihost port 3333: Connection refused`

My fix is to replace: 
```yml
extra_hosts:
    - webapihost:0.0.0.0
```
with:
```yml
links:
      - "webapi:webapihost"
```

Gilles

**Comment by subotic** [comment]
Thanks for reporting the bug. There are a lot of ways to go about this.

Extending the `webapi` service like this should also work.

```
networks:
    knora-net:
        aliases:
             - webapihost
```

Maybe changing `webapihost` permanently to `webapi` inside the sipi config would be the easiest. Then we could get rid of any `aliases` or `extra_hosts`.
